### ISSUE TITLE
Improve middleware to fully abort a navigation when the server-side auth check failed

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#100]
### Describe the feature

Browbeat on discord reported that components still shortly flash to the end-user even iof the auth middleware detected that the user is not logged in. It's the expectation that we should be able to navigate away on the server side, so that the content is not visible to the end-user.

- [ ] create a reporduction
- [ ] look into the behavior

**Comment by BracketJohn** [comment]
This is actually a Nuxt 3 problem and not a `nuxt-auth` problem. Here's the issue to follow: https://github.com/nuxt/framework/issues/8816

As soon as Nuxt 3.1.0 is released (appearently this december), this issue should be fixed. Leaving it open until then.

**Comment by BracketJohn** [comment]
Hey @endorfin! Thanks for the headsup, will look into this ASAP and release a fix if possible (:

**Comment by BracketJohn** [comment]
> It is not a Nuxt 3 problem! The problem occurs when you use your own custom login page. The current middleware does not cover this case. I solved the problem with my own middleware

Heya @endorfin 👋 

I think you may be describing a different issue: You talk about re-directs to custom login pages, but the issue is about short visibility of protected pages.

AFAIU your issue could be resolved via a new condfiguration option that allows you to specify custom login pages that the global auth middleware knows of. Do you want to open a new issue for that?

**Comment by endorfin** [comment]
No, I had exactly that problem. 

I created a custom login page, specified it in the NuxtAuthHandler and enabled GlobalAppMiddleware in nuxt.config. 

If you are not logged in, all content of the protected pages are visible for a short time before redirecting to the login page. But as I said, the problem only occurs with a custom login page. I suspect that the method "signIn" does not return the correct value and the RouteMiddleware does not stop and display the page. Later the "signIn" method redirects to the login page.

**Comment by endorfin** [comment]
> **nothing** - does not block navigation and will move to the next middleware function, if any, or complete the route navigation

https://nuxt.com/docs/guide/directory-structure/middleware

<img width="806" alt="image" src="https://user-images.githubusercontent.com/101636/209353859-a7ae02db-d197-47b2-8909-67e3820a479b.png">

**Comment by BracketJohn** [comment]
> But as I said, the problem only occurs with a custom login page.

I'm actually able to reproduce it with both our playground and our demo-app that do not have custom login pages. Test it out here: https://nuxt-auth-example.sidebase.io/

Clicking "globally protected" there you will shortly see the page content before going to the _standard_ log in page of the module.

Plus: browbeat did not report having a custom login page, you first brought this up.

Not saying that there's not an improvement to be made for the cust-page redirect, but just saying that this is two different problems:
1. page content is briefly visible although it shouldn't be,
2. middleware does not redirect to custom login page if one exists

**Comment by endorfin** [comment]
It's all about the return value in the defineNuxtRouteMiddleware ;) 

```
return signIn(undefined, { callbackUrl: to.path, replace: true }, { error: 'SessionRequired' })
```
is not valid and blocks not the navigation

**Comment by BracketJohn** [comment]
Hm, under the hood `signIn` will return a `navigateTo`: https://github.com/sidebase/nuxt-auth/blob/42a7a5808fb43b1192340cf189d800f8f5fec185/src/runtime/composables/useSession.ts#L107

This however gives me a lead to look into: See if problem is resolved by returning `navigateTo`

**Comment by BracketJohn** [comment]
Investigated: We can resolve this by `await`ing `signIn` PLUS faking a `navigateTo`.

This issue was resolved via https://github.com/sidebase/nuxt-auth/commit/05682549d3c80df9924a0c8f7f08793a07e631d7 🎊 

Release will happen soon (:
