### ISSUE TITLE
Session is not refreshed and always valid

### ISSUE THREAD

**Issue by Prutheus** [sidebase/nuxt-auth#102]
### Ask your question

I use `nuxt-auth` to authenticate my users agains my ID provider.
However, after a user signed in, he is always able to access the system. If I terminate his session via my ID provider or if I revoke a role which is required for the authentication, this data is not getting updated in my Nuxt application, the user is still authenticated there ...

How to work with this issue correctly?

**Comment by BracketJohn** [comment]
Hey @Prutheus! 👋 

Thanks for the question - what `NuxtAuthHandler` configuration do you use? credentials and then a `$fetch` to your own auth-system in the `authorize` hook or something different?

**Comment by Prutheus** [comment]
Hey @BracketJohn , I use the Keycloak Provider against my Keycloak instance

**Comment by Prutheus** [comment]
I think the cookie expiration timeout needs to be set to a low value instead of 1 month (default) to reload the session, right?

**Comment by BracketJohn** [comment]
So, `nuxt-auth` uses NextAuth.js under the hood rotates the expiry to keep the session from ending, see https://next-auth.js.org/getting-started/client.

If you want to have a quicker client-session expiry, you can set `maxAge` of `session` to some very low value -> this way unless the user is (quite) active and refreshes the session often, the session will expire: https://next-auth.js.org/configuration/options#session

If you want to expire the session as soon as `keycloak` expires the session, you'll need to:
1. add a session expiry check into the `session` or `jwt` callback
2. if the session expiry check returns `true` (i.e.: keycloak says the session was invalidated), you set a custom attribute in the session data / jwt that you return from these hooks, e.g.: `error: 'session-expired'`
3. in the frontend add a middleware that checks for `error === 'session-expiored'` and calls the `signOut` function

Does this help? (:

**Comment by BracketJohn** [comment]
Closing this now as no further response from questioner. Feel free to comment again here / open a new issue in the future!
