### ISSUE TITLE
Static generated pages `nuxi generate`

### ISSUE THREAD

**Issue by sadeghbarati** [sidebase/nuxt-auth#103]
### Ask your question

Silly question :sweat:

Does `nuxt-auth` work `nuxi generate`?

---

Off-topic question:

I'm new to using Auth Providers
How to handle sign-up with Credentials way or redirect after login with Google Provider (for example)

**Comment by BracketJohn** [comment]
Hey @sadeghbarati!

nuxt-auth does not work on fully static pages -> instead you can use server-side generated pages to get the benefits of both. Sorry to say that, but the library needs a server to administer the session lifecycle.

Thnaks for the question (and not silly at all!)
