### ISSUE TITLE
DiscordProvider always leads to having to authorize the page when signing in

### ISSUE THREAD

**Issue by NullBrowbeat** [sidebase/nuxt-auth#104]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.1.3`
- Builder:          `vite`
- User Config:      `modules`, `auth`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `nuxt-icon@0.1.8`, `@sidebase/nuxt-auth@0.3.0-alpha.3`
- Build Modules:    `-`

### Describe the bug

As the title says, the DiscordProvider always leads to having to authorize the page when signing in a user.
That's not the normal Discord login-flow, as far as I know.

**Comment by BracketJohn** [comment]
Heya @NullBrowbeat!

Can you:
1. try again with the latest stable release `@sidebase/nuxt-auth@0.3.0`?
2. provide a reproduction for the issue so that I can debug? (: 

See here for a quick guide on reproductions: https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction

Thanks!

**Comment by BracketJohn** [comment]
Closing this now as there was no further response from questioner. Feel free to ping in this issue again / open a new one (:
