### ISSUE TITLE
Login with cypress

### ISSUE THREAD

**Issue by DenFin** [sidebase/nuxt-auth#106]
### Ask your question

I have a project with a custom OAuth provider. The login works fine. Now I want to introduce e2e tests. Unfortunately I got stuck directly with the second test step, which reads as follows:

```
Scenario Outline: Anonymous user starts login process
    Given Anonymous user is on the landing page
    When Anonymous user triggers the login via "<action>"
    Then the page redirects to provider login page
    And login form is visible on provider login page

    Examples:
      | action |
      | click  |
      | touch  |
```

When cypress executes this line (we have a custom getByTestId command to get elements)

`cy.getByTestId('btn-login-header').click({force: true})`

 the browser calls `/api/auth/providers`, `/api/auth/csrf` and `/api/auth/session`

![Bildschirm­foto 2022-12-12 um 15 18 15](https://user-images.githubusercontent.com/11504119/207069082-0423aa20-695e-4aa7-85dc-31cae95cb895.png)

But when I click the button myself in the Cypress window, I can see that `/api/auth/providers`, `/api/auth/csrf`  and a POST to` /api/auth/signin/providername `gets fired.

After spending almost 2 days of troubleshooting and research I am pretty clueless. 

So my question is: **Does anyone have experience with setting up cypress tests with nuxt-auth?**

While I'm hoping for an answer, I will do some more digging [here](https://next-auth.js.org/tutorials/testing-with-cypress) and [here](https://community.auth0.com/t/next-auth-auth0-e2e-with-cypress-test-not-working-on-host-but-redirecting-to-universal-flow/86683/1)

**Comment by BracketJohn** [comment]
Hey @DenFin 👋 

Thanks for the question, I'm unsure: What's the problem / question exactly? The 3 requests being fired is expected: To login we need to get the providers, then we need to get a CSRF and then a session is fetched. The only thing I'm missing here is the login call itself.

**Comment by DenFin** [comment]
@BracketJohn Thanks for your reply!

Yes, that's exactly the problem. Somehow when the click event is executed via cypress `/api/auth/signin/providername` is not called. Strangely enough when I click the login button manually the signin route gets called

**Comment by BracketJohn** [comment]
are there any error logs that appear in your terminal / can you add any logging statements somewhere to see how far the `signIn` method gets / what causes it to abort?

**Comment by DenFin** [comment]
@BracketJohn  we ultimately decided to take another route. Instead of mocking the click on our login button, we extended Cypress with a custom login command. Simply put this login command sets a cookie, so we can visit our authenticated routes and be logged in. 

[This thread](https://github.com/nextauthjs/next-auth/discussions/2053) helped us getting to this solution

**Comment by BracketJohn** [comment]
Hey @DenFin,

very interesting + good solution, thanks for sharing it here! I'll close this issue then as resolved -> glad that you worked it out ❤️

**Comment by th1nkgr33n** [comment]
For everyone that comes along this thread.

We migrated today the project @DenFin metioned to the latest sidebase/nuxt-auth v0.7.x and since then the cookie setup no longer works.

I haven't looked deeper into the modules sourcecode, but I guess that they changed something that if the 
"/api/auth/session"-Route returns an empty object, the user is treated as not logged in although there are those cookies "nuxt-auth.session-token". 
In devtools you see that the cookies set by cypress gets deleted after the "/api/auth/session"-Route was called

For now we are using the solution to intercept this route with cypress and return data.
```
  cy.intercept('GET', '/api/auth/session*', {
    statusCode: 200,
    body: {
      user: {
        name: 'E2E Testuser',
        email: 'e2e@company.com',
      },
      expires: '2024-04-30T09:39:54.745Z',
      error: '',
    },
  })
```

This pretend a logged in user and works for us.
