### ISSUE TITLE
Credential login: How to perform custom error handling?

### ISSUE THREAD

**Issue by noprobz09** [sidebase/nuxt-auth#108]
### Ask your question

Im using custom signin page and trying to implement or display error message on the same page.

I've tried the setting 

`const { data, status, signIn } = useSession({redirect: false})`

and also this one,

@click="signIn('credentials', { redirect: false, email: form.email, password: form.password })"

but the return response is always

`url: "http://localhost:3000/api/auth/error?error=CredentialsSignin&provider=credentials"`

Anyone able to implement custom signin with error message display on the same page? Thanks in advance!

**Comment by Lucas-Gruber** [comment]
I have the same Problem! I didn't figured out how to do this. i tried this:

```javascript
signIn("credentials", {username: loginData.username, password: loginData.password, redirect: false }).then(
    ({ ok, error }) => {
      if (ok) {
        console.log("ok");
      } else {
        console.log("hallo");
        // console.log(error)
      }
    }
  );
```

But it only work without Errors.

When i have a Error the Code doesn't return to the "then" Statement.

**Comment by BracketJohn** [comment]
Heya!

To get a custom error page you can use the `pages` configuration of the nuxt-auth hanbdler, see https://next-auth.js.org/configuration/pages for all options.

Basically you can tell `nuxt-auth` to direct to your custom page on error by doing:
```ts
pages: {
  error: '/my-cool-error-page'
}
```

There you can do whatever you want. Does that help? (:

**Comment by BracketJohn** [comment]
Ah, got it! Sorry that it took some time to get back to you - had a lot pre-christmas / end-of-year stuff going on at our company

So, then you and @noprobz09 should be able to work with the response of:
```ts
const result  = await signIn('credentials', { redirect: false, email: form.email, password: form.password })
```

As @noprobz09 pointed out, the result of this is:
```
url: "http://localhost:3000/api/auth/error?error=CredentialsSignin&provider=credentials"
```

You can see the `error` query parameter here. These are standardized for nuxt auth (: Documentation for them is:
- here in code: https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/core/pages/signin.tsx
- here in docs (partial): https://next-auth.js.org/errors


For example, in the response shared by @noprobz09 the error is `CredentialsSignin`, which next auth would translate to the following on its default login page: "Sign in failed. Check the details you provided are correct." (source: https://github.com/nextauthjs/next-auth/blob/aad0b8db0e8a163b3c3ae7dec3e9158e20d368f4/packages/next-auth/src/core/pages/signin.tsx#L69-L70)

That should be what you @Lucas-Gruber and you @noprobz09 are looking for, correct?

**Comment by BracketJohn** [comment]
I checked this topic out further and identified a bug in the process of doing so 🎊 Thanks to you two for persuing this (: 

The fix is in #122. There I've also added documentation + a code playground example. That PR will close this issue and I'll do a release shortly after.

Let me know if you have any other concerns AND also let me know if your issue was actually resolve, that would mean a lot to me ❤️ 

Other than that: Happy Holidays 🎊

**Comment by noprobz09** [comment]
Thank you @BracketJohn. Happy Holidays! :)

**Comment by BracketJohn** [comment]
Thanks 💯

**Comment by noprobz09** [comment]
Hi @BracketJohn 

I followed the documentation page for custom signin and tried to copy the sample code in it.

`const { signIn } = useSession()
const mySignInHandler = async ({ username, password }: { username: string, password: string }) => {
  const { error, url } = await signIn('credentials', { username, password, redirect: false })

console.log(error)

  if (error) {
    // Do your custom error handling here
    alert('You have made a terrible mistake while entering your credentials')
  } else {
    // No error, continue with the sign in, e.g., by following the returned redirect:
    return navigateTo(url, { external: true })
  }
}`

and call the `mySignInHandler` from the button `@click="mySignInHandler"`. 
The return error is always `null`

and this is my sample NuxtAuthHandler

`
import CredentialsProvider from 'next-auth/providers/credentials'
import { NuxtAuthHandler } from '#auth'


export default NuxtAuthHandler({
  // A secret string you define, to ensure correct encryption
  secret: 'your-secret-here',
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    CredentialsProvider.default({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: 'Credentials',
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
     
      authorize (credentials) {
        // You need to provide your own logic here that takes the credentials
        // submitted and returns either a object representing a user or value
        // that is false/null if the credentials are invalid.
        // NOTE: THE BELOW LOGIC IS NOT SAFE OR PROPER FOR AUTHENTICATION!
        
        throw new Error('Exception message');   // expecting to throw an error
        // return null;
        
      }
    })
  ]
})

`

**Comment by FrankoFM** [comment]
Hey, im pretty late to the party but I want to bump this because I think @noprobz09 has a valid point.
Is there no way for custom errors when using the credentials provider?

For example:
```ts
CredentialsProvider.default({
    async authorize(data: {
        username: string;
        password: string;
    }) {
        // Auth Logic

        return new Error("Username or password is incorrect");
        // return new Error("To many login attempts");
        // return new Error("Your account has been disabled");
    },
}),
```
