### ISSUE TITLE
Module doesn't install correctly

### ISSUE THREAD

**Issue by tmlmt** [sidebase/nuxt-auth#110]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`, `content`, `runtimeConfig`
- Runtime Modules:  `@nuxt/content@2.2.2`, `@sidebase/nuxt-auth@0.3.0`
- Build Modules:    `-`

### Reproduction

Simply followed the Installation (`npm i -D @sidebase/nuxt-auth`) and the Quick Start guide from the documentation on my existing project.

### Describe the bug

Hello, I get the same as in #19. `npx nuxi prepare`, reloading or rebooting doesn't make a difference. I get the message: 
```
 WARN  Could not resolve import "#auth" in /home/tmlmt/myproject/server/api/auth/[...].ts using imports defined in /home/tmlmt/myproject/package.json.

 WARN  Could not resolve import "#auth" in /home/tmlmt/myproject/server/api/auth/[...].ts using imports defined in /home/tmlmt/myproject/package.json.

 WARN  '#auth' is imported by server/api/auth/[...].ts, but could not be resolved – treating it as an external dependency
```
In my `nuxt.config.ts`, I have the following: 
```
export default defineNuxtConfig({
// ...
modules: ["@nuxt/content", "@sidebase/nuxt-auth"],
//...
```
And when I try to add a new property `auth` into it, Volar complains with `Object literal may only specify known properties, and 'auth' does not exist in type 'NuxtConfig'.ts(2345)`

**Comment by BracketJohn** [comment]
Heya @tmlmt 👋 

Unsure what's happening here, can you please provide a reproduction repo?  I don't think that:

> Simply followed the Installation (npm i -D @sidebase/nuxt-auth) and the Quick Start guide from the documentation on my existing project.

will work, as that is done by many people and works for them.

**Comment by tmlmt** [comment]
Hey @BracketJohn, so I was preparing a Stackblitz with a fresh install and when I installed nuxt-auth, I saw that npm was then running nuxi prepare as postinstall ... so I tried on my own project, and it worked. Very weird. I'll close this for the moment and will reopen if I figure out a reproducible situation.

**Comment by BracketJohn** [comment]
Hey @tmlmt - no worries -> I think this is a known and unfortunate factor of the way that `nuxt` works. Once you have it setup correctly (by adding it to the `postinstall` hook) it's way less confusing. Glad that the issue could be resolved (:
