### ISSUE TITLE
Streamline typing across next auth session data and `useSession` data type

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#112]
### Describe the feature

Raised by @noook in [#61:](https://github.com/sidebase/nuxt-auth/issues/61#issuecomment-1356826150)

> The signature for `useSession` does not go alone this answer :(

![image](https://user-images.githubusercontent.com/19751938/208307447-e871e0f9-c6e4-40b8-8749-ae516d868406.png)

> `useSession().data` does not refer to next-auth types so overriding it does not help much when using the type outside of the NuxtAuth handler

We should:
- [ ] ensure that both have the same data-type, so that it can be overwritten easily.
- [ ] update the recipe on how to add custom session data https://sidebase.io/nuxt-auth/recipes/custom-session-data
  - source is here: https://github.com/sidebase/nuxt-auth/blob/main/docs/content/5.recipes/4.custom-session-data.md

**Comment by noook** [comment]
That's weird because before submitting the comment in the code I checked the code and it directly references Next-auth 🤔

**Comment by BracketJohn** [comment]
@noook we just released a fix / improvement of this behavior, see #115 -> thanks to @JoaoPedroAS51 ❤️  Will do a release at some point today (:
