### ISSUE TITLE
RFC: Switch core to `auth.js` and coordinate collaboration / transition of this module into `auth.js`

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#117]
### Describe the feature

We want to:
- [ ] switch to an `auth.js` core to be fully react independent
- [ ] coodinate a merge / collab with auth.js with @balazsorban44
- [ ] Switch to using h3 sessions and not `nuxt-session`

**Comment by BracketJohn** [comment]
Tasks / issues related / resolved by auth.js move:
- [ ] #119 `.default` does not exist: With auth.js this problem was resolved
- [ ] #97 add `@auth/core` as an explicit dependency to avoid problems related to hoisting

Will expand this as issues come up.

**Comment by austins** [comment]
The icons/logos were fixed in [next-auth@4.18.8](https://github.com/nextauthjs/next-auth/releases/tag/next-auth%404.18.8) as well, would upgrading to that version be an appropriate fix for #131 in the meantime until the switch to `@auth/core`?

**Comment by kilakewe** [comment]
+ 1 issue with cloudflare based deployment.

**Comment by BracketJohn** [comment]
Hey @austins 👋 

We downstreamed the fix in `0.4.0` - use the latest alpha to see it working. In general, `next-auth` is now a peer dependency, hence you have a choice of which version you want to install (: 

> +1 issue with cloudflare based deployment.

Thanks (:

**Comment by BracketJohn** [comment]
Current blockers before fully migrating
- [ ] AFAIK `auth.js` only allows `trustHost: true` - which seriously lowers security, see [1]


[1] assert check that forces us to set `trustHost: true`
https://github.com/nextauthjs/next-auth/blob/6c07331cc53abe45c644308af6b6f2de29fdae2e/packages/core/src/lib/assert.ts#L74-L76

**Comment by tmlmt** [comment]
What are the news on this?

**Comment by BracketJohn** [comment]
closed as part of cleanup (:

note that this does not mean that it is unplanned, but there will be a new/separate issue later on
