### ISSUE TITLE
Custom oAuth Provider with oidc?

### ISSUE THREAD

**Issue by GionRubitschung** [sidebase/nuxt-auth#118]
### Ask your question

Hello everyone

I am currently implementing an oauth2 authorization_code auth flow. For this I have created a custom oauth2 provider. Here is my catch all auth route:
`File: ~~/server/api/auth/[...].ts`
```ts
import { NuxtAuthHandler } from '#auth';

const config = useRuntimeConfig();

export default NuxtAuthHandler({
  secret: config.smapAuth.clientSecret,
  providers: [
    {
      id: 'cf',
      name: 'CloudFoundry',
      type: 'oauth',
      wellKnown: `${config.smapAuth.issuer}/.well-known/openid-configuration`,
      jwks_endpoint: `${config.smapAuth.issuer}/token_keys`,
      clientId: config.smapAuth.clientId,
      authorization: {
        params: {
          scope: 'openid profile email phone roles user_attributes',
          grant_type: 'authorization_code',
          response_type: 'token id_token',
          redirect_uri: 'http://localhost:3000/',
        },
      },
      idToken: true,
      checks: ['pkce', 'state'],
      profile(profile) {
        // TODO: map to db user profile
        return profile;
      },
    },
  ],
});
```

I have enabled the global middleware.
When looking in the browser, an authorization request gets send to the issuer: `GET https://AUTH_ISSUER/oauth/authorize?client_id=CLIENT_ID&scope=openid+profile+email+phone+roles+user_attributes&response_type=token+id_token&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&grant_type=authorization_code&state=STATE&code_challenge=CODE_CHALLENGE&code_challenge_method=S256`. The request receives the correct 302 status for redirection. I get redirected the right way, can sign in on our sso. After the redirect to my app, I get an error: `http://localhost:3000/api/auth/signin?callbackUrl=%2F#error=invalid_client&error_description=Unauthorized%20grant%20type:%20implicit&state=STATE`.

The client is correct, tested this via postman and there it worked. However, I am kind of confused about the grant type. It says implicit? The implicit flow is marked deprecated in my company, so I don't want to use it and don't quite understand why I am getting this here. The authorization request is built correctly. I also cannot access the state, user etc. after the sign in. I have no idea what is going on, does someone know how to solve this?

### Additional information

Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.12.2`
- Builder:          `vite`
- User Config:      `app`, `css`, `typescript`, `modules`, `formkit`, `runtimeConfig`, `auth`, `vite`
- Runtime Modules:  `@formkit/nuxt@1.0.0-beta.12`, `@nuxtjs/tailwindcss@6.2.0`, `@sidebase/nuxt-auth@0.3.0`, `@pinia/nuxt@0.4.6`, `nuxt-icons@3.0.0`, `./modules/standaloneRoutes`
- Build Modules:    `-`
------------------------------

**Comment by BracketJohn** [comment]
Hey @GionRubitschung 👋 

Sadly I do not have any experience with CloudFoundry -> from looking through different forums, stackoverflow, ... this could be related to a `clientSecret` missing or some other configuration of open id connect being incorrect. Can you look into that and verify that your configuration is correct? Maybe one lead is that it's working with postman: Something has to be different there for it to work out, right? If the URL were exactly the same and the rest of the environment as well, it should work in the same way otherwise.

**Comment by BracketJohn** [comment]
Closing this now due to inactivity, feel free to comment again or open a new issue down the road ✋

**Comment by GionRubitschung** [comment]
Hey @BracketJohn 
Sorry, I didn't got the notification. It was a misconfiguration on the auth provider site. The problem was laying within our corporate network. My App is running in a container so the forwarding to the auth provider worked without problems but the rerouting back to the app didn't work because of the network restrictions from our auth provider. Did some reconfiguration and now it works :) The only thing I still don't understand is the error message, which is really confusing to me
