### ISSUE TITLE
Property default does not exist (CredentialsProvider.default)

### ISSUE THREAD

**Issue by tmlmt** [sidebase/nuxt-auth#119]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `build`, `modules`, `content`, `runtimeConfig`, `auth`
- Runtime Modules:  `@nuxt/content@2.2.2`, `@sidebase/nuxt-auth@0.3.0`
- Build Modules:    `-`

### Reproduction

```server/api/auth/[...].ts
import { NuxtAuthHandler } from "#auth";
import CredentialsProvider from "next-auth/providers/credentials";

const config = useRuntimeConfig();

export default NuxtAuthHandler({
  secret: config.secret,
  providers: [
    CredentialsProvider.default({
      id: "credentials",
      name: "Credentials",
      credentials: {
        email: { label: "E-mail", type: "text" },
        password: { label: "Password", type: "password" },
      },
//...
```

### Describe the bug

TypeScript complains when I use CredentialsProviders with .default
![image](https://user-images.githubusercontent.com/10244927/209261648-76c76a0c-cf22-45b5-942d-ca68a18b8966.png)

### Additional context

TypeScript complains, but the app runs
If I remove `default`, the app crashes, saying CredentialsProvider is not a function

**Comment by BracketJohn** [comment]
Hey! This is actually a problem with Vite + SSR and not with our module. 

NextAuth is now becoming `@authjs` which fixes this issue. We'll also switch to authjs under the hood soon, this issue will then be closed by that PR (:

**Comment by tmlmt** [comment]
Hi @BracketJohn, thanks a lot for your reply. OK. Sounds great with the move to @authjs, looking forward to it.

**Comment by BracketJohn** [comment]
Sure thing (: Follow this issue -> as soon as it closes the move will have happened :D

**Comment by BracketJohn** [comment]
Moved this into https://github.com/sidebase/nuxt-auth/issues/117 and will close this issue to keep the repo clean. Thanks again @tmlmt and do know that this will be resolved - just as part of https://github.com/sidebase/nuxt-auth/issues/117.

**Comment by baboon-king** [comment]
you can do that before switch to auth.js
```typescript
// file: nuxt.config.ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    "@sidebase/nuxt-auth",
  ],
  auth: {
    provider: {
      type: "authjs",
    },
    globalAppMiddleware: true,
  },
  build: {
    // fix CredentialsProvider is not a function
    transpile: ["next-auth/providers/identity-server4"],
  },
});

```
