### ISSUE TITLE
Nuxt Auth does not work with Prisma Adapter

### ISSUE THREAD

**Issue by Q16solver** [sidebase/nuxt-auth#128]
### Environment

Operating System: `MacOs`
Node Version: `v18.9.1`
Nuxt Version: `3.0.0`
Nitro Version: `1.0.0`
Package Manager: `npm@8.19.1`
Builder: `vite`
User Config: `css`, `build`, `modules`, `runtimeConfig`, `auth`
Runtime Modules: `@sidebase/nuxt-auth@0.3.2`

### Describe the bug

If I install the Prisma adapter package, then I believe there's some weird conflict that exists with both `prisma adapter` & `nuxt-auth` package both having `next-auth` as a dependency. Perhaps there could be some way to resolve it from this package side by making next-auth a peer dependency and requiring users to install it or something similar?

![image](https://user-images.githubusercontent.com/50786287/210480366-3947cb36-cee4-4dbc-a3a5-b8fc3ece94c8.png)

**Comment by BracketJohn** [comment]
Hey @Q16solver 👋 

Thanks for the issue - will likely make next auth a peer dep to resolve this soon (: 

Today is off for Christmas though (: Merry christmas to you (:

**Comment by Q16solver** [comment]
Yep, thanks for the fast response even though it’s Christmas! Merry Christmas to to you too haha

**Comment by BracketJohn** [comment]
Thanks ❤️

**Comment by MuhammadKhizar7** [comment]
I am using a Prisma adapter with nuxt-auth, and it works fine for me. I did not yet go to deploy it, and I have example to show. 
I use Windows and use NPM it might be mac issue.
https://github.com/MuhammadKhizar7/nuxt-prisma

**Comment by Q16solver** [comment]
haha well, actually you walked into one of the "workarounds" which is installing nuxt-auth first, so the package-lock.json prioritises `nuxt-auth`'s dependency first for whatever reason, and installing the prisma adapter package next doesn't affect it. You'll find that if you remove your node_modules and package-lock.json and regenerate everything, it won't work

**Comment by BracketJohn** [comment]
Hey you two 🔢 

#179 is now open which makes `next-auth` a peer dependency (:
