### ISSUE TITLE
Local auth middleware not typed

### ISSUE THREAD

**Issue by Q16solver** [sidebase/nuxt-auth#129]
### Describe the bug

Hello!

I wanted to use `definePageMeta({ middleware: "auth" });` for some pages locally in nuxt 3 instead of a global middleware, but it seems like it's not really typed? Getting type error when trying to type in "auth"

**Comment by Q16solver** [comment]
I think probably the best solution to this is just have an extra section in the docs providing the sample auth middleware that's used, and let the user define this, so then it will auto generate the types. The module can just only provide the global middleware option

**Comment by BracketJohn** [comment]
Happy new year @Q16solver 🧇 

Thanks for the issue - will look into whether we can support typing for this.

**Comment by Q16solver** [comment]
@BracketJohn If it doesn't seem like it's possible/an easy way to do it without a lot of hacks, perhaps it would be easier to delegate it to the user and provide a sample auth middleware in the docs for user to copy pasta

**Comment by BracketJohn** [comment]
There was an easy way to do it, checkout #139!

**Comment by Q16solver** [comment]
@BracketJohn I think you forgot to also provide type for the middleware, definePageMeta({ middleware: "auth" }); is still raising a type error, I believe you need a middleware: "auth" | ...rest of the types or something similar, I'll reopen this
