### ISSUE TITLE
On `response_type: 'token'` it should get `access_token` from URI fragment, not query params

### ISSUE THREAD

**Issue by LLCampos** [sidebase/nuxt-auth#130]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `modules`, `css`, `postcss`, `auth`
- Runtime Modules:  `@sidebase/nuxt-auth@0.3.2`
- Build Modules:    `-`

### Describe the bug

My `[...].ts` looks like the following:

```ts
import { NuxtAuthHandler } from '#auth'

// @ts-ignore
export default NuxtAuthHandler({
  providers: [
    {
      id: 'rails',
      name: 'Rails',
      type: 'oauth',
      idToken: false,
      clientId: 'myClientId',
      wellKnown: 'http://localhost:3000/.well-known/openid-configuration',
      authorization: {
        params: { response_type: 'token' },
      },
      checks: [],
      profile(profile) {
        return {
          id: '1234',
          name: 'name',
          email: 'email@email.com',
          image: undefined,
        }
      },
    },
  ],
})
```

Note that `response_type: 'token'` is being used!

After request to the authorization URl, browser is redirected to something like `http://localhost:4005/api/auth/callback/rails#access_token=myAccessToken&token_type=Bearer&expires_in=7200`

Looking [here](https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2), I think this looks like what it should be. But I get an error like the following:

```
https://next-auth.js.org/errors#oauth_callback_error access_token not present in TokenSet {
  error: TypeError: access_token not present in TokenSet
      at Client.requestResource ((...)/node_modules/openid-client/lib/client.js:1117:15)
      at Client.userinfo ((...)/node_modules/openid-client/lib/client.js:1235:33)
      at oAuthCallback ((...)/node_modules/next-auth/core/lib/oauth/callback.js:149:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.callback ((...)/node_modules/next-auth/core/routes/callback.js:52:11)
      at async NextAuthHandler ((...)/node_modules/next-auth/core/index.js:201:28)
      at async file://(...)/.nuxt/dev/index.mjs:628:24
      at async Object.handler (file://(...)/node_modules/h3/dist/index.mjs:723:19)
      at async Server.toNodeHandle (file://(...)/node_modules/h3/dist/index.mjs:798:7) {
    name: 'OAuthCallbackError',
    code: undefined
  },
  providerId: 'rails',
  message: 'access_token not present in TokenSet'
}
```

I can make the flow finish and make the user authenticated if I replace the `#` with `?`, as such:

`http://localhost:4005/api/auth/callback/rails?access_token=myAccessToken&token_type=Bearer&expires_in=7200`

I think this might be a bug because it is looking for the `access_token` in the query params, not in the URI fragment?

**Comment by LLCampos** [comment]
Note that I was able to reproduce this in `next-auth`: https://github.com/nextauthjs/next-auth/issues/6204.

**Comment by BracketJohn** [comment]
Hey @LLCampos 👋 

Happy new years to you -> thanks for opening the issue + also checking it with next-auth, that's majorly helpful! 

Looking at your next-auth investigation it looks like this is rather an upstream `next-auth` bug and not something we can resolve here. So we'll need to wait for a fix of https://github.com/nextauthjs/next-auth/issues/6204. Agreed?

**Comment by LLCampos** [comment]
Yup, agreed. ;)

**Comment by LLCampos** [comment]
It seems that implicit flow [is not supported](https://github.com/nextauthjs/next-auth/issues/6204#issuecomment-1369907788) by `next-auth`. Already [put in a PR](https://github.com/nextauthjs/next-auth/pull/6269) to make that explicit.

**Comment by BracketJohn** [comment]
Gotcha - thanks for following through -> sorry that your desired goal is unsupported! Hope that you can switch to the variant that is currently recommended.

Have a good night 👋

**Comment by LLCampos** [comment]
(Unrelated, but I really like how you communicate with new potential contributors. It makes me feel safe and welcome!)
