### ISSUE TITLE
Global app middleware not working?

### ISSUE THREAD

**Issue by tberk** [sidebase/nuxt-auth#150]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `modules`, `app`, `auth`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@sidebase/nuxt-auth@0.3.3`
- Build Modules:    `-`

### Describe the bug

I have enabled the global app middleware from nuxt options by adding

`auth: {
    enableGlobalAppMiddleware: true
  }`

but its not working. I have tried local middleware with `definePageMeta({ middleware: 'auth' })`  and its working fine.

**Comment by BracketJohn** [comment]
seems like you were signed in the whole time!

Thanks for the report and resolving it yourself (:

**Comment by tberk** [comment]
haha, yeah maybe! but I think I was not authenticated at first while I was trying it and enabling local middleware would redirect me to the login page. However, it works great now <3

**Comment by BracketJohn** [comment]
Glad to hear that ❤️ 🤝
