### ISSUE TITLE
Can anyone share auth0 example with nuxt3?

### ISSUE THREAD

**Issue by rajnish93** [sidebase/nuxt-auth#152]
### Ask your question

My server/api/auth/[...].js file 
```js
import CredentialsProvider from "next-auth/providers/credentials";
import Auth0 from "next-auth/providers/auth0";
import { NuxtAuthHandler } from "#auth";

export default NuxtAuthHandler({
  // secret needed to run nuxt-auth in production mode (used to encrypt data)
  secret: process.env.NUXT_SECRET,
  providers: [
    Auth0.default({
      domain: process.env.AUTH0_DOMAIN,
      clientId: process.env.AUTH0_CLIENT_ID,
      audience: process.env.AUTH0_AUDIENCE,
    }),

    CredentialsProvider.default({
      name: "Credentials",
      credentials: {
        username: { label: "Username", type: "text", placeholder: "(hint: jsmith)" },
        password: { label: "Password", type: "password", placeholder: "(hint: hunter2)" },
      },
      authorize(credentials) {
        const user = {
          id: "1",
          name: "J Smith",
          username: "jsmith",
          password: "hunter2",
          image: "https://avatars.githubusercontent.com/u/25911230?v=4",
        };

        if (credentials?.username === user.username && credentials?.password === user.password) {
          // Any object returned will be saved in `user` property of the JWT
          return user;
        } else {
          // eslint-disable-next-line no-console
          console.error("Warning: Malicious login attempt registered, bad credentials provided");

          // If you return null then an error will be displayed advising the user to check their details.
          return null;

          // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
        }
      },
    }),
  ],
  callbacks: {
    async redirect({ url, baseUrl }) {
      // Allows relative callback URLs
      if (url.startsWith("/")) return `/auth/signed-in`;
      // Allows callback URLs on the same origin
      else if (new URL(url).origin === baseUrl) return url;
      return baseUrl;
    },
  },
});
```

With above setup I am getting following error:--

![image](https://user-images.githubusercontent.com/10815566/211543218-655100d9-52f6-49e8-aa8f-5eee351ca433.png)
Login screen:
![image](https://user-images.githubusercontent.com/10815566/211543375-f465452c-b827-4206-818c-231c96f57fde.png)

How do I use my custom login page and handle calbacks?

**Comment by zoey-kaiser** [comment]
Hi @rajnish93!

From what I understand you are dealing with two separate issue; configuring 0auth and callbacks. I will quickly give some input to both issues!

## 0Auth

```js
Auth0.default({
   domain: process.env.AUTH0_DOMAIN,
   clientId: process.env.AUTH0_CLIENT_ID,
   audience: process.env.AUTH0_AUDIENCE,
}),
```

I think that your Auth0 configuration is not setup correctly. When looking into the `NextAuth` documentation I can see that the Auth0 configuration should be: 

```js
Auth0.default({
   clientId: process.env.AUTH0_CLIENT_ID,
   clientSecret: process.env.AUTH0_CLIENT_SECRET,
   issuer: process.env.AUTH0_ISSUER
}),
```
See https://next-auth.js.org/providers/auth0

Maybe this will already fix your issue? 
The error printed in your console also refers to the following page: https://next-auth.js.org/errors#signin_oauth_error. One of the listed issues is incorrect configuration, which is my assumption right now. If it does not fix the issue you can see some other reasons why the error may be called (you can also reply to the issue and I can look again 🤗)

## Callbacks

```js
async redirect({ url, baseUrl }) {
  // Allows relative callback URLs
  if (url.startsWith("/")) return `/auth/signed-in`;
  // Allows callback URLs on the same origin
  else if (new URL(url).origin === baseUrl) return url;
  return baseUrl;
},
```
> The redirect callback is called anytime the user is redirected to a callback URL (e.g. on signin or signout).

This is the offical explanation of what the redirect callback is used for. It is called every time a user is redirected to a callback url of NuxtAuth. It does not apply to all redirects on the page. If you want to create a global redirect callback, I would recommend looking into Server Middleware: https://nuxt.com/docs/guide/directory-structure/middleware#middleware-directory

If you do need another callback from NuxtAuth feel free to look at the NextAuth documentation to see what is available: https://next-auth.js.org/configuration/callbacks#sign-in-callback

**Comment by rajnish93** [comment]
redirect_uri is not working to custom url.
going back to /api/auth

**Comment by rajnish93** [comment]
@zoey-kaiser 
Thanks
Issue Fixed.
