### ISSUE TITLE
Define Default Provider for GlobalAppMiddleware

### ISSUE THREAD

**Issue by simonsax** [sidebase/nuxt-auth#154]
### Ask your question

In case I enable the enableGlobalAppMiddleware Flag in the nuxt config file, is it somehow possible to automatically try to login with a specific provider? This would allow me to implement a SSO solution. At the moment the default login screen is shown and the user has to chose a provider (but in my case there is only 1 available)
`
// nuxt.config.ts
auth: {
   enableGlobalAppMiddleware: true
}
`

### Additional information

I am using a custom OIDC provider

**Comment by BracketJohn** [comment]
Hey again @simonsax 😄 🐑 

This is not possible at the moment, but could be a good feature! Would you want to contribute it?

I think we could add a setting to the `auth` options object:
```
auth: {
  enableGlobalAppMiddleware: true,
  defaultProvider: 'DEFAULT_PROVIDER_NAME'
  ...  // remaining config
}
```

Then if `defaultProvider` is specified, `signIn()` will use that per default (instead of `undefined`, which it currently uses and leads to the sign-in page).

As a work-around until you or someone contributes this, you can create your own global middleware: https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/middleware/auth.ts

**Comment by JoaoPedroAS51** [comment]
@BracketJohn This would be really helpful. I had the same issue on my project.

I actually worked on this a while ago, but for the eloqjs module. See https://github.com/eloqjs/nuxt-next-auth/commit/0c75d332591b70f4c1bb5f4c2721d0b2a799cacf

Maybe we can use part of the code from there, what do you think?

**Comment by BracketJohn** [comment]
Good idea - to re-use, thanks for the heads-up @JoaoPedroAS51 ❤️ 

I think @IronicUsername is working on this, so he'll be able to look at your code & re-use.

**Comment by Kingside88** [comment]
Unfortunately I can no longer SignOut if "defaultProvider" is set.
SignOut redirect back to my page and do not SignOut. 

Using newest version "0.4.0-alpha.5"
**nuxt.config.ts**
`  auth: {
    enableGlobalAppMiddleware: true,
    defaultProvider: 'keycloak'
  },`
**server\api\auth\[...].ts**
`import KeycloakProvider from 'next-auth/providers/keycloak'
import { NuxtAuthHandler } from '#auth'

export default NuxtAuthHandler({
  debug: true,
  secret: process.env.AUTH_SECRET,

  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    KeycloakProvider.default({
      clientId: process.env.AUTH_CLIENT_ID ?? "",
      clientSecret: process.env.AUTH_SECRET,
      issuer: process.env.AUTH_ISSUER ?? "",
      idToken: true,
      wellKnown: process.env.AUTH_WELLKNOWN ?? "",
    }),
  ],
  callbacks: {
    session: (data : any) => {         
        return data.session
    },
},
})
`
