### ISSUE TITLE
definePageMeta({ middleware: "auth" }) is not typed

### ISSUE THREAD

**Issue by Q16solver** [sidebase/nuxt-auth#157]
### Describe the bug

Related to #129 , definePageMeta({ middleware: "auth" }) is still raising a type error, I believe you need a middleware: "auth" | ...rest of the types or something similar

Example generated types by nuxt:

```ts
import type { NavigationGuard } from 'vue-router'
export type MiddlewareKey = "auth" <-- this is missing | "middleware1" | ...other middlewares
declare module "/node_modules/nuxt/dist/pages/runtime/composables" {
  interface PageMeta {
    middleware?: MiddlewareKey | NavigationGuard | Array<MiddlewareKey | NavigationGuard>
  }
}
```

**Comment by BracketJohn** [comment]
Hey @Q16solver 🧇 

You and your typing of middleware - you are really persistent, I love it! :D 

Anyways: I'm actually unsure if it is possible to expand the middleware interface like that, would you like to give it a shot?

**Comment by manniL** [comment]
It seems like the typed PageMeta is not part of `types.d.ts` eventually.

https://unpkg.com/browse/@sidebase/nuxt-auth@0.4.0-alpha.3/dist/types.d.ts

**Comment by BracketJohn** [comment]
still persists with `nuxt-auth@0.5.0-alpha.0` 😢
