### ISSUE TITLE
User id and provider from Oauth in session by default

### ISSUE THREAD

**Issue by Jericho1060** [sidebase/nuxt-auth#158]
### Describe the feature

It's a small improvement for the future that could be usefull.

By default, in the session, we only have :
- name
- email
- image

When they are provided.

I would love to see the id by default in the session and the provider too.

**Comment by Jericho1060** [comment]
if someone is interrested on how to do it, the solution i'm currently using

```ts
// ~/types/next-auth.d.ts
import {DefaultSession} from "next-auth";

declare module "next-auth" {
    interface Session {
        user?: {
            id?: string;
            provider?: string;
        } & DefaultSession["user"];
    }
}
```

```ts
// ~/server/api/auth/[...].ts
import {NuxtAuthHandler} from "#auth";

export default NuxtAuthHandler({
    // ...
    callbacks: {
        jwt: ({token, user, account}) => {
            if (user) {
                token.provider = account?.provider;
            }
            return token;
        },
        session: ({token, session}) => {
            if (token.sub) {
                session.user.id = token.sub;
            }
            if (token.provider) {
                session.user.provider = token.provider;
            }
            return session;
        }
    }
});


```

**Comment by BracketJohn** [comment]
Hey @Jericho1060 🧇 

Thanks for opening this issue and providing some additional information on how you resolved it - super helpful (: 

I understand the request, but we're not interested in adding this to the library at this time: Returning the `id` and `provider` deviated from the default behvaior of the underlying `next-auth` that we use. In our core we want to stay as close to `next-auth` as possible to:
- make maintanence easier,
- leverage cross-ecosystem ressources such as guides, ...

Thanks for the request anyways (:
