### ISSUE TITLE
UseFetch is not defined

### ISSUE THREAD

**Issue by agracia-foticos** [sidebase/nuxt-auth#159]
### Environment

RootDir: /home/projects/nuxt-starter-ydvvvt
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`, `auth`
- Runtime Modules:  `@sidebase/nuxt-auth@0.3.3`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Reproduction

Press button Login
https://stackblitz.com/edit/nuxt-starter-ydvvvt

### Describe the bug

App raises useFetch is not defined.

useFetch is a composable

**Comment by BracketJohn** [comment]
Hey @agracia-foticos 🧇 

Thanks for the q - this is not a nuxt-auth problem. Within your API routes you need to use `$fetch` and not `useFetch`, see https://nuxt.com/docs/api/utils/dollarfetch#fetch

**Comment by BracketJohn** [comment]
closing as no more response from asker + very likely not a `nuxt-auth` problem
