### ISSUE TITLE
Laravel Sanctum Support

### ISSUE THREAD

**Issue by danpastori** [sidebase/nuxt-auth#166]
### Describe the feature

Add Laravel Sanctum "recipe" to documentation for custom providers.

### Additional information

Before we begin, I know this has been mentioned in #30 , but wanted to offer help and hope I chose the right issue template! Feel free to re-assign if a different template is needed.

Thanks for making this incredible package and your contributions to the Nuxt Community! I'm really looking forward to working with sidebase/nuxt-auth.

Here's what I'm proposing:

## 1. Ensure Laravel Sanctum Auth Works Correctly
I've been working on this within our apps and ran into a few hiccups, but would love to work with other devs on Discord to figure this out. I believe I'm passing a cookie wrong, but I know I'm close to having this working. Having done a lot of work with Laravel Sanctum, I believe this comes from me missing something in the nuxt-auth module.

I would love to join the Discord, however, the link in the readme results in an Invalid Invite Code.
https://github.com/sidebase/nuxt-auth#readme

## 2. Documentation Contribution
Once we have the auth working, I'll open a PR and submit documentation with instructions for other devs. I don't mind getting in depth with step by step instructions and code examples so devs can easily add this functionality. I'd include:
- [ ] Setting up a custom provider
- [ ] Updating useFetch() requests to pass the credentials which contain the cookie
- [ ] When using SSR, ensuring the cookie gets passed to the API.

If someone is already working on this, excellent, I'd love to contribute if needed. Otherwise, if I can get access to Discord, I'd love to have a discussion with other devs and get this added to your project! Let me know if you have any questions or need anything more from me!

**Comment by BracketJohn** [comment]
Hey @danpastori 👋 🌊 

First of all: Sorry for the delay in getting back to you - we're doing a lot of things on the module right now, hopefully now is the time to also facilitate this request (especially seeing that it is so popular)

> Thanks for making this incredible package and your contributions to the Nuxt Community! I'm really looking forward to working with sidebase/nuxt-auth.

❤️  Thank you 


> I would love to join the Discord, however, the link in the readme results in an Invalid Invite Code.

we're on it / fixing it atm! thanks and wow: how did we not notice this for so long?

> Once we have the auth working, I'll open a PR and submit documentation with instructions for other devs. I don't mind getting in depth with step by step instructions and code examples so devs can easily add this functionality. I'd include:

That sounds great, how far along are you? I saw some your notes here: https://twitter.com/danpastori/status/1618662799684812800

We can hop on a call or text via discord (real, working link: https://discord.gg/NDDgQkcv3s) or reach out on twitter to me personally (https://twitter.com/bracket_john_)

---

sorry again for the large delay - this totally slipped through.

**Comment by BracketJohn** [comment]
actually, #200 may be related to some of your troubles with the setup (:

**Comment by vanling** [comment]
@danpastori #200 is fixed in ` "@sidebase/nuxt-auth": "0.4.0-alpha.6",` Could you check if this works for Laravel Sanctum too? =D

**Comment by zoey-kaiser** [comment]
Ill close this issue for now, as it seems to have gone stale. @danpastori if you arise into any new problems please open a new issue and refer to this one! 

Thank you everyone for their help and input ❤️
