### ISSUE TITLE
Change default cookie names

### ISSUE THREAD

**Issue by nathanchase** [sidebase/nuxt-auth#167]
### Describe the feature

The cookie names should be "nuxt-auth" instead of "next-auth".

Better yet, provide a mechanism for changing the names to anything you want.

**Comment by BracketJohn** [comment]
Hey @nathanchase 👋 

Thanks for the issue. The cookie name is actually already configurable by passing cookie options to the `NuxtAuthHandler`:
```ts
    const DEFAULT_NUXT_AUTH_COOKIE_NAME = 'my-cool-prefix'
    // ...

   // inside NuxtAuthHandler options:
    cookies: {
      sessionToken: {
        name: `${DEFAULT_NUXT_AUTH_COOKIE_NAME}.session-token`
      },
      callbackUrl: {
        name: `${DEFAULT_NUXT_AUTH_COOKIE_NAME}.callback-url`
      },
      csrfToken: {
        name: `${DEFAULT_NUXT_AUTH_COOKIE_NAME}.csrf-token`
      },
      pkceCodeVerifier: {
        name: `${DEFAULT_NUXT_AUTH_COOKIE_NAME}.pkce.code_verifier`
      },
      state: {
        name: `${DEFAULT_NUXT_AUTH_COOKIE_NAME}.state`
      },
      nonce: {
        name: `${DEFAULT_NUXT_AUTH_COOKIE_NAME}.nonce`
      }
    }
```

**Comment by BracketJohn** [comment]
Renaming the cookie has some additional impact I'd rather avoid for now (see #180). As pointed out above you can already rename the cookies if you wish to, but note that you will need to re-specify _all_cookie options (see docs linked in #180).

The drawbacks this introduces are not worth it for now for this module, but you are free to choose to do this for your setup if you need it.

**Comment by BracketJohn** [comment]
Bad news for you, sorry: We had to stay with `next` for now, see comment right above yours + linked PR for reasoning: https://github.com/sidebase/nuxt-auth/issues/167#issuecomment-1400430653

I'm as sad as you are, but in the end this change is only cosmetic, so I prioritize usability + security + maintainability. Let me know if any other use-cases come to mind.
