### ISSUE TITLE
Update next-auth package

### ISSUE THREAD

**Issue by KoenCa** [sidebase/nuxt-auth#169]
### Describe the feature

Currently nuxt-auth uses next-auth version 14.18.0, but I encountered the following issue: https://github.com/nextauthjs/next-auth/issues/6040 . It should be fixed in a newer version of next-auth so my request is to update next-auth version to have this fixed in nuxt-auth too.

**Comment by BracketJohn** [comment]
Hey @KoenCa 👋 

Thanks for the issue - PR is open to upgrade next-auth. It will also fix missing icons on the pre-existing sing-in page (:
