### ISSUE TITLE
how to protect the login page after getting authenticated

### ISSUE THREAD

**Issue by cax111** [sidebase/nuxt-auth#172]
### Ask your question

How to protect our login page after we logged in to the web, is there any example like programmatically from this module, or i just create a custom middleware to protect manually and redirect by myself ? 
Because i've tried in the demo web, I can visit login page after getting autheticated.
Thanks in advance.

**Comment by Lyazarus** [comment]
Hello, 

Maybe you could add condition in your login page like this 

```javascript
// ~/pages/login.vue
<template>
your login form
</template>

<script setup lang="ts">
const { signIn, status } = useSession()
if (status.value === "authenticated") {
    navigateTo('/')
}
</script>
```

**Comment by BracketJohn** [comment]
If the global middleware is _not_ enabled, you can also use:
```
definePageMeta({ middleare: 'auth' })
```

to protect the page. No need to do this yourself. Read: https://sidebase.io/nuxt-auth/application-side/protecting-pages#local-middleware

Let us know if you need any more help or hop ontop discord: https://discord.gg/9MUHR8WT9B
