### ISSUE TITLE
Skip loading layout when redirecting to login page

### ISSUE THREAD

**Issue by zoomyboy** [sidebase/nuxt-auth#175]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `app`, `css`, `postcss`, `modules`, `components`, `runtimeConfig`, `auth`
- Runtime Modules:  `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`
------------------------------

### Describe the bug

I have the global auth middleware enabled.

```
  auth: {
    isEnabled: true,
    origin: process.env.NUXT_APP_URL,
    basePath: '/api/auth',
    enableSessionRefreshPeriodically: false,
    enableSessionRefreshOnWindowFocus: true,
    enableGlobalAppMiddleware: true,
    globalMiddlewareOptions: {
      allow404WithoutAuth: true,
    },
  },
```

This is the page I'm trying to visit unauthenticated. So I expect the middleware to redirect me to the login page without loading anything from that edit page.
```vue
// pages/event/[id]/edit.vue
<template>
  <div></div>
</template>

<script setup></script>
```

This is the default layout for the page above (pages/event/[id]/edit.vue):
```vue
// layouts/index.vue
<template>
  <div></div>
</template>

<script setup>
const can = await useCan()
</script>
```

In the useCan composable, the following is happening (which actually requires a logged in user to function properly because it reads the cookie).
```js
export default async function () {
  const headers = useRequestHeaders(['cookie'])
  const { data } = await useFetch('/api/userinfo', { headers })

  return data.value
}
```

The thing is: I don't expect this ``useCan`` composable to be called at all because the middleware should kick in before and redirect me to the login page. But actually, the layout is loaded first and then the redirect occurs. This could lead to some unexpected behaviour (as in this case).

Do you have an idea how to solve this problem?

Cheers 

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'account')                                                                                                                                       11:45:27
  at ./.nuxt/dev/index.mjs:705:36
```

**Comment by BracketJohn** [comment]
Hey @zoomyboy 👋 

Thank you for reporting this bug. I think this may be a nuxt 3 problem rather than a nuxt-auth problem.

Checkout https://github.com/nuxt/nuxt/issues/15407#issuecomment-1397379113 -> "Component setup runs before router middleware is resolved" is the issue, they resolved this 7 hours ago and I'm sure they'll release it as part of Nuxt 3.1.0.

To test this you can try out nuxt edge to see if your issue persists there. Would you be so nice to do this?

**Comment by BracketJohn** [comment]
Hey @zoomyboy 👋 

With the release of Nuxt 3.1.0 this issue was fixed. We also already updated the library to use Nuxt 3.1.0. If you update your project to 3.1.0 this issue should be resolved, so closing this now.

Let me know if you have any further problems (:

**Comment by zoomyboy** [comment]
Thank you. I'll try this out

**Comment by BracketJohn** [comment]
Sure thing - feel free to come back here and report the result. If it worked a confirmation would be nice (:
