### ISSUE TITLE
Sign In With Google 

### ISSUE THREAD

**Issue by kaboume** [sidebase/nuxt-auth#183]
### Ask your question

Hello,
My website allows user login either via email / password or via "Sign in with Google" (https://developers.google.com/identity/gsi/web/guides/overview)
I have successfully configured the CredentialsProvider for authentication with email/password.
For the "Sign in with Google" button, the first part of the flow works well with the front-end retrieving the idToken returned by Google. On the other hand, I still have to validate the idToken on the server side and populate the Nuxt Auth Session.

```ts
// MyLogin Component

onMounted(() => {
  google.accounts.id.initialize({
    client_id: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    callback: handleCredentialResponse,
  })
  google.accounts.id.renderButton(
    document.getElementById('buttonDiv'),
    { theme: 'outline', size: 'large' }, // customization attributes
  )
  google.accounts.id.prompt() // also display the One Tap dialog
},
)

const handleCredentialResponse = (response) => {
  console.log(`Encoded JWT ID token: ${response.credential}`)

  // TODO : CALL THE  CredentialsProvider or ???
   const { error } = await signIn('credentials', { idTokenGoogle:  response.credential, redirect: false })
}
```

For this, I wonder if I should reuse the CredentialsProvider with an additional parameter (ex: idTokenGoogle) and implement the logic that goes well in the CredentialsProvider?

```ts
// [...].ts File
export default NuxtAuthHandler({
  secret: config.authSecret,
  providers: [
   CredentialsProvider.default({
      name: 'Credentials',
      async authorize(credentials: any) {
        try {
            // TODO LIKE THAT ?
            if (credentials.idTokenGoogle....) {
             const response = await $fetch(
            `${config.public.API_BASE_URL}auth/check-idtoken-google/`,
            {
              method: 'POST',
              body: JSON.stringify({
                idTokenGoogle: credentials.idTokenGoogle,
              }),
            },

             }
            else {
          const response = await $fetch(
            `${config.public.API_BASE_URL}auth/login/`,
            {
              method: 'POST',
              body: JSON.stringify({
                email: credentials.username,
                password: credentials.password,
              }),
            },
          )
```

Or should I do otherwise?

**Comment by BracketJohn** [comment]
> On the other hand, I still have to validate the idToken on the server side and populate the Nuxt Auth Session.

I don't quite get the question: When you use "sign in with google" the resulting OAuth flow should lead you to google, then back + sign you in automatically. No need to verify any token inside the credential flow (which is a different one to the google one)?

**Comment by BracketJohn** [comment]
closing this now due to inactivity. Just add another point here if you need further assistance or hop onto discord and text into the questions channel: https://discord.gg/NDDgQkcv3s

**Comment by kaboume** [comment]
Hi @BracketJohn,
Due to security reasons, it's necessary to check the id token server-side : 
https://developers.google.com/identity/gsi/web/guides/verify-google-id-token
