### ISSUE TITLE
`getServerSession()` creates endless loop in middleware files in production build

### ISSUE THREAD

**Issue by frostycoles** [sidebase/nuxt-auth#186]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.2.0`
- Builder:          `vite`
- User Config:      `css`, `modules`, `auth`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.0`, `@sidebase/nuxt-auth@0.3.3`
- Build Modules:    `-`

### Reproduction

Clone [my fork of the example repository](https://github.com/frostycoles/nuxt-auth-example)
Run `npm i`
Run `npm run build`
Run `node .output/server/index.mjs`
Navigate to page and watch the server logs

### Describe the bug

I added a server middleware file `server/middleware/auth.ts` so I can check authentication on server routes [as per the docs](https://sidebase.io/nuxt-auth/server-side/session-access-and-route-protection#server-middleware):
```
import { getServerSession } from '#auth';

export default eventHandler(async (event) => {
  console.log('Hello world');
  const session = await getServerSession(event);
  console.log('Hello world again');
  event.context.user = session?.user;
});
```

With `npm run dev` this works fine, but doing a `npm run build` followed by `node .output/server/index.mjs` I get endless `Hello world` logs in the console and never see `Hello world again`. This is true even with server routes like `api/healthz`.

**Comment by rvmourik** [comment]
I experienced the exact same

**Comment by navanjr** [comment]
I am not sure why this does not happen in development mode. But, just apply your custom server middleware on the routes that are necessary to avoid the many "under-the-hood" routes that were added by the nuxt-auth plugin.

See the playground example here: https://github.com/sidebase/nuxt-auth/blob/main/playground/server/middleware/auth.ts
