### ISSUE TITLE
#auth is not available in imports

### ISSUE THREAD

**Issue by noook** [sidebase/nuxt-auth#19]
### Environment

Nuxi 3.0.0-rc.13
RootDir: /Users/nook/work/tls-interim-front
Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `typescript`, `css`, `modules`, `build`, `googleFonts`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxtjs/svg@0.4.0`, `@pinia/nuxt@0.4.3`, `floating-vue/nuxt`, `@sidebase/nuxt-auth@0.0.1-beta.5`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/framework/issues/new

👉 Suggest an improvement: https://github.com/nuxt/framework/discussions/new

👉 Read documentation: https://v3.nuxtjs.org

### Describe the bug

By following the documentation, I used the external config provider (no config in nuxt.config.ts).

However `#auth` doesn't exist. It is not listed in the `.nuxt/tsconfig.json` paths

**Comment by BracketJohn** [comment]
Hey @noook - thanks for the issue - do you habe a reproduction by any chance / can you invite me to your repo?

**Comment by noook** [comment]
Hello, I have no idea why but after reloading multiple times it was still not taken into account. A full reboot of the computer made it work. I'll just close it as I can't reproduce anymore

**Comment by BracketJohn** [comment]
Okay perfect! Two theories jow this could've happened:
- postinstall step didn't run (manually do it by running nuxi prepare)
- volar takeover mode was not correctly activated, so the eidotr was complaining but it actually worked

Well anyways: Göad that it worked now, have fun with the lib and let me know / open the issue if you need any more support (:

**Comment by tmlmt** [comment]
Hello, I also get the same. And `npx nuxi prepare`, reloading or rebooting doesn't make a difference. I get the message: 
```
 WARN  Could not resolve import "#auth" in /home/tmlmt/myproject/server/api/auth/[...].ts using imports defined in /home/tmlmt/myproject/package.json.

 WARN  Could not resolve import "#auth" in /home/tmlmt/myproject/server/api/auth/[...].ts using imports defined in /home/tmlmt/myproject/package.json.

 WARN  '#auth' is imported by server/api/auth/[...].ts, but could not be resolved – treating it as an external dependency
```
Reproduction: simply followed the Installation and Quick Start guide from the documentation on my existing project (Nuxt 3.0.0)
