### ISSUE TITLE
404 on static deployment

### ISSUE THREAD

**Issue by nicolas-bastien** [sidebase/nuxt-auth#195]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.2`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.1.0`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `extends`, `modules`, `auth`
- Runtime Modules:  `@sidebase/nuxt-auth@0.4.0-alpha.4`
- Build Modules:    `-`
------------------------------

### Reproduction

I have a fresh docus start installation with : npx nuxi@latest init smartbooster-inside -t themes/docus

And I have follow the quickstart doc with Auth0 as a provider and a enableGlobalAppMiddleware = true configuration.

### Describe the bug

Deployement fail and home page show a 404 with 

404 (https://smartbooster-inside.netlify.app/api/auth/session?callbackUrl=https://smartbooster-inside.netlify.app/api/auth/)

This is a static deployment.
Can you explain me what to do, I didn't find spacific configuration for static deployment in the documentation.

Thanks a lot

**Comment by BracketJohn** [comment]
Hey 👋 

Thanks for the question - nuct-auth is for non static deployments only, see the docs: ![image](https://user-images.githubusercontent.com/25911230/215325396-46bcc47b-a027-4ab0-b4a0-c1f327a72a3f.jpeg)

**Comment by nicolas-bastien** [comment]
Hi @BracketJohn,
thanks for your answer.

Do you have any plan to make it work with SSR ?
I use nuxt-auth on nuxt 2 and it's working with static, so I'm wondering.

By the way, I think it can help other like me if you mention this in README file here :+1: 
![image](https://user-images.githubusercontent.com/1446466/215339717-60d63469-c63a-4016-85bd-4e7ed6c1882d.png)

Thanks 
Nicolas

**Comment by zoey-kaiser** [comment]
Hi @nicolas-bastien!

> Do you have any plan to make it work with SSR ?

Do you mean SSG? Sadly it is not planned, as the package we use under the hood ([AuthJs](https://authjs.dev/)) does not support it. 😢 

I would recommend you keep up to date on the progress of the official Nuxt 3 authentication module, as they plan to add support for this AFAIK! https://nuxt.com/vision-2023#key-modules

> By the way, I think it can help other like me if you mention this in README file here 👍

Thanks for the idea 💪 We already have it noted inside of our [docs](https://sidebase.io/nuxt-auth/getting-started), however it may make sense to include it in the README, just in case someone is "scouting" our module and does not want to read the entire docs. Ill bring it up and we can discuss it internally!

**Comment by BracketJohn** [comment]
Hey @nicolas-bastien 👋 

I think @zoey-kaiser and myself could resolve your question right now, as the repro is now working?

Checked it here: https://smartbooster-inside.netlify.app/api/auth/session?callbackUrl=https://smartbooster-inside.netlify.app/api/auth/

Please let us know - for now we'll close the issue as:
- static pages are not supported with `nuxt-auth`
- your repro works now (leads to auth0)

Have a good day and let us know if there's anything else.

**Comment by nicolas-bastien** [comment]
@BracketJohn yes I just removed sidebase/nuxt-auth and implement it with vue-auth0 directly.

Thanks

**Comment by BracketJohn** [comment]
sure! all the best (:
