### ISSUE TITLE
Analysis bundle size

### ISSUE THREAD

**Issue by zoey-kaiser** [sidebase/nuxt-auth#2]
After our first release some users began to raise the concern, that due to the next-auth integration under the hood, the package size for nuxt-auth could become a lot bigger then it needs to be.

Therefore we want to look futhur into the finished bundle sizes to see if and how this impacts the finished size.

Thank you to https://twitter.com/Kapcash/status/1587011603706384385?s=20&t=eSg_YjZeyUN_7eSyeBJzFg for bringing up the issue!

**Comment by BracketJohn** [comment]
@zoey-kaiser / @valiafetisov we could test this with the demo website as soon as it is done (referencing https://github.com/sidebase/nuxt-auth-example)

**Comment by BracketJohn** [comment]
### Naive bundle size test

As a first benchmark, we'll checkout how big `nuxt build` bundle output is for:
1.  a vanilla nuxt-app, 
2. a vanilla nuxt-app + `pages`-dir
3. `nuxt-auth` playground
4. https://github.com/sidebase/nuxt-auth-example

#### 1. vanilla nuxt-app

Rationale: Most basic nuxt-app a regular dev may start with

Result:
```
Σ Total size: 2.93 MB (677 kB gzip)
```

<details><summary>Method:</summary>

```sh
> npx nuxi@latest init nuxt-size-test

> cd nuxt-size-test

> npm i

> npm run build
```

</details>

#### 2. vanilla nuxt-app + `pages`-dir

Rationale: Most basic app but with a "real" page, thus forcing nuxt to include routing. Having sub-pages is very common and routing often contributes noticeably to bundle-size.

Result:
```
Σ Total size: 3.11 MB (724 kB gzip)
```

<details><summary>Method:</summary>

1. setup project
```sh
> npx nuxi@latest init nuxt-size-test

> cd nuxt-size-test

> npm i
```

2. add a bare `pages/index.vue`  page

```vue
<template><div>hi</div></template>
```

3. add the `NuxtPage` component to the `app.vue`

```vue
<template>
  <div>
    <NuxtWelcome />
    <NuxtPage />
  </div>
</template>
```

5. Build

```sh
> npm run build
```

</details>

#### 3. [`nuxt-auth` playground](https://github.com/sidebase/nuxt-auth/tree/main/playground)

Rationale: This is an auth-app that uses _all_ nuxt-auth functions while still having a minimal, no CSS no component apporach.

Result:
```
Σ Total size: 3.93 MB (965 kB gzip)
```

<details><summary>Method:</summary>

```sh
> git clone https://github.com/sidebase/nuxt-auth

> cd nuxt-auth

> npm i

> npm run build:playground
```

</details>

#### 4. [nuxt-auth-example](https://github.com/sidebase/nuxt-auth-example)

Rationale: This is an auth-app that verifiable runs online and that makes use of many `nuxt-auth` functions. The downside of this case is that it includes a lot of styling, components, ... for nice UX that will likely impact bundle size

Result:
```
Σ Total size: 4.04 MB (994 kB gzip)
```

<details><summary>Method:</summary>

1. setup project
```sh
> git clone https://github.com/sidebase/nuxt-auth-example

> cd nuxt-auth-example

> npm i

> npm run build

> npm i
```

</details>

---

Comparison based on above numbers:

|                            	| Bundle size 	| Increase % compared to (1) 	| Bundle size gzip 	| Increase gzip % compared to (1) 	|
|----------------------------	|-------------	|----------------------------	|------------------	|---------------------------------	|
| 1. nuxi init - minimal     	|     2.93 MB 	|                     0.00 % 	|           677 kB 	|                          0.00 % 	|
| 2. nuxi init - with router 	|     3.11 MB 	|                     6.14 % 	|           724 kB 	|                          6.94 % 	|
| 3. nuxt-auth playground    	|     3.93 MB 	|                    34.13 % 	|           965 kB 	|                         42.54 % 	|
| 3. nuxt-auth-example       	|     4.04 MB 	|                    37.88 % 	|           994 kB 	|                         46.82 % 	|

Note that the rounding + precision selection has been done in a non-scientific way - this is a ballpark benchmark to get a good feeling of:
- whether the current impact on bundle size is ok
- get indicators which direction to dig towards for further benchmarking / reduction

**Comment by valiafetisov** [comment]
It's surprising that `nuxt-supabase` takes so much space. But can we maybe compare our package with the official [`@nuxtjs/auth-next`](https://github.com/nuxt-community/auth-module)?

Also, we should still investigate (probably in another issue) if we can remove `preact` sub-dependency and server-side rendering because extra dependencies don't only contribute to the bundle size / build speed and cetera, but also open up new attack vectors.

**Comment by BracketJohn** [comment]
Good idea, I added it to the comparison :+1: It's smaller in comparison to the `nuxt-auth` module.

> Also, we should still investigate (probably in another issue) if we can remove preact sub-dependency and server-side rendering because extra dependencies don't only contribute to the bundle size / build speed and cetera, but also open up new attack vectors.

I agree, already  for just the size-reduction this may bring! I've opened #59 for that and posted a first overview of the components that make up the size!
