### ISSUE TITLE
Accessing the JWT to reach an external API

### ISSUE THREAD

**Issue by noook** [sidebase/nuxt-auth#20]
### Describe the feature

I'm currently working with 2 providers:
- Credentials
  - will return me a JWT with the user info
- Google
  - The JWT callback reaches my API to create an API issued JWT to be used from the client

However, I need the JWT issued by the API to be able to do the requests, how can I achieve this ? The NextAuth issues/conversation say the only way to achieve this is to attach the token to the user session on the jwt creation

**Comment by BracketJohn** [comment]
Hey 👋 

Thanks for the questiln - you can use getToken from next-auth/jwt to achieve what you are trying to do.

Here is an example of it: TBD

**Comment by noook** [comment]
This is only available on server-side, right ?

Feel free to close if this is the currently only way to do that !

**Comment by BracketJohn** [comment]
Yes, it is, but you can use it on the cöient side by:
- creating an endpoint that returns the decoded jwt (as linked above)
- calling that endpoint from the frontend

We may consider adding a helper to make this easier - but for now this should make it work for your use case (:

**Comment by BracketJohn** [comment]
Hey @noook!

We've added the getToken utility AND documentstion on how tonproperly use it. Feel free to check it out and open an issue if it doesn't behave as expected / you need something more!

Cheers 🍻
