### ISSUE TITLE
How to use SessionToken with nuxt/apollo

### ISSUE THREAD

**Issue by reinoldus** [sidebase/nuxt-auth#202]
### Ask your question

I am trying to use the session token, I followed these steps:
https://sidebase.io/nuxt-auth/server-side/jwt-access

Result:
```
// file: ~/server/api/token.get.ts
import { getToken } from '#auth'
export default eventHandler(async (event) => {
  const token = await getToken({ event, raw: true })
  return token || 'no token present'
})

```
BTW: when I set raw to true I get a type error complaining that type "false" can't be true, why isn't that a boolean?

Now I am trying to plug those values into nuxt/apollo, I created an apollo.ts like this:
description: https://apollo.nuxtjs.org/recipes/authentication#auth-hook

```
export default defineNuxtPlugin(async (nuxtApp) => {
  // access cookie for auth
  const headers = useRequestHeaders(['cookie']) as HeadersInit
  const { data } = await useFetch('/api/token', { headers })

  nuxtApp.hook('apollo:auth', async ({ client, token }) => {
    // `client` can be used to differentiate logic on a per client basis.
    // apply apollo client token
    console.log(data.value)

    token.value = data.value
  })
})
```
Here nuxt complains:
```
[Vue warn]: onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.                    19:10:51
```
Not sure what to do about it, but I get the "Authorization" header in my request.

Problem: Authentication doesn't work.

I checked the JWT token with: https://jwt.io/ which tells me that I have an "Invalid Signature".

Therefore I assume that my Apollo-Server can't decode the token.

I don't know what is going wrong exactly, but something doesn't seem right.

### Additional information

I am using Auth0 as a provider like this:

```
import Auth0Provider from 'next-auth/providers/auth0'
import { NuxtAuthHandler } from '#auth'
export default NuxtAuthHandler({
  secret: 'XXXXXXXXXXX', // <--- !!!! THIS IS WHAT'S MISSING
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    Auth0Provider.default({
      clientId: process.env.AUTH0_CLIENT_ID,
      clientSecret: process.env.AUTH0_CLIENT_SECRET,
      issuer: process.env.AUTH0_ISSUER,
    }),
  ],
})
```

**Comment by reinoldus** [comment]
Okay, I had a little bit of a blackout, you don't need raw: true, you have to take the token out like this:

```
export default defineNuxtPlugin(async (nuxtApp) => {
  // access cookie for auth
  const headers = useRequestHeaders(['cookie']) as HeadersInit
  const { data } = await useFetch('/api/token', { headers })

  nuxtApp.hook('apollo:auth', async ({ client, token }) => {
    // `client` can be used to differentiate logic on a per client basis.
    // apply apollo client token
    token.value = data.value.token.account.id_token
  })
})
```

If someone could tell me if this is a good approach working with apollo that would be great and if I should be worried about this warning:

```[Vue warn]: onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.                    19:10:51
```

**Comment by BracketJohn** [comment]
Hey @reinoldus 👋 

Glad that you could resolve this issue by yourself 🎊  Indeed: `raw: true` gets you the raw token :D 

Anyways for the `onServerPrefetch` warning: This is related to how nuxt / vue fetch data and not something that this module can avoid. See: https://github.com/nuxt/nuxt/discussions/16058

Closing this now as question was resolved. Have a good day 🌥️
