### ISSUE TITLE
Unable to "Change the default behavior to use `/login` as the path for the sign-in page" 

### ISSUE THREAD

**Issue by yuvraj339** [sidebase/nuxt-auth#205]
### Ask your question

[...].ts inside api/auth
Unable to "Change the default behavior to use `/login` as the path for the sign-in page" 

```
 secret: useRuntimeConfig().authSecret,
  pages: {
    // Change the default behavior to use `/login` as the path for the sign-in page
    signIn: "/login",
  },
```

when comment  signIn: "signin",

it returns to nuxt/Auth default page, but when I uncomment it, looping like this 

![image](https://user-images.githubusercontent.com/8150078/216543486-04bda25c-2eb8-461d-9193-e9bc6c8e5ff4.png)

![image](https://user-images.githubusercontent.com/8150078/216543627-b0ef1840-61d1-470e-8c91-3268a8cb5957.png)

### Additional information

nuxt.config like this

```
export default defineNuxtConfig({
  nitro: {
    plugins: ["~/server/database/index.ts"],
  },
  css: [
    "~/assets/css/main.css",
    // "~/assets/tailwind.css",
    // "~/assets/animate.css",
  ],
  //   modules: ["@nuxtjs/tailwindcss"],
  modules: ["@sidebase/nuxt-auth"],
  auth: {
    // The module is enabled. Change this to disable the module
    isEnabled: true,
    // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`
    origin: "http://localhost:3000",
    // The base path to the authentication endpoints. Change this if you want to add your auth-endpoints at a non-default location
    basePath: "/api/auth",
    // Whether to periodically refresh the session. Change this to `true` for a refresh every seconds or set this to a number like `5000` for a refresh every 5000 milliseconds (aka: 5 seconds)
    enableSessionRefreshPeriodically: false,
    // Whether to refresh the session whenever a window focus event happens, i.e, when your user refocuses the window. Set this to `false` to turn this off
    enableSessionRefreshOnWindowFocus: true,
    // Whether to add a global authentication middleware that will protect all pages without exclusion
    enableGlobalAppMiddleware: false,
    // Select the default-provider to use when `signIn` is called. Setting this here will also effect the global middleware behavior: E.g., when you set it to `github` and the user is unauthorized, they will be directly forwarded to the Github OAuth page instead of seeing the app-login page
    defaultProvider: undefined,
    // Configuration of the global auth-middleware (only applies if you set `enableGlobalAppMiddleware: true` above!)
    globalMiddlewareOptions: {
      // Whether to allow access to 404 pages without authentication. Set this to `false` to force users to sign-in before seeing `404` pages. Setting this to false may lead to vue-router problems (as the target page does not exist)
      allow404WithoutAuth: true,
    },
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  //   alias: {
  //     "class-validator": "class-validator/cjs/index.js",
  //   },
  runtimeConfig: {
    authSecret: process.env.AUTH_SECRET,
    mongoUrl: process.env.MONGO_URL,

    // The private keys which are only available server-side
    // apiSecret: "123",
    // Keys within public are also exposed client-side
    // public: {
    //   apiBase: "/api",
    // },
  },
});
```

**pages -> login**

```
<template>
  <WebAuthLogin></WebAuthLogin>
</template>
<script setup>
definePageMeta({ auth: false });
</script>
```

**Comment by BracketJohn** [comment]
Hey there, thanks for the issue!

Can you please share more information about the environment? For that, run `npx nuxi info` inside your project and share the output here.

**Comment by BracketJohn** [comment]
One quick idea I just had: Did you forget to add:
```ts
definePageMeta({ auth: false })
```

to your custom signin page? See docs: https://sidebase.io/nuxt-auth/application-side/custom-sign-in-page

This is what would result in an infinite loop like the one you are seeing!

**Comment by yuvraj339** [comment]
Here are some more details

![image](https://user-images.githubusercontent.com/8150078/218666277-4fd6f50e-b7b2-447c-83dd-e3f4b256fa79.png)

![image](https://user-images.githubusercontent.com/8150078/218666385-c2d8977b-e63e-43a2-8e51-fb13d393de1d.png)

login page
![image](https://user-images.githubusercontent.com/8150078/218667609-2e0f50f0-3c0d-4379-869e-cae33753b383.png)


auth.ts and authentication.global.ts  are same as mentioned in doc

nuxt.config.ts
![image](https://user-images.githubusercontent.com/8150078/218668064-51324015-3df2-4d39-b24a-af46f7db70ba.png)

> 
  ```
auth: {
    // The module is enabled. Change this to disable the module
    isEnabled: true,
    // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`
    origin: "http://localhost:3000",
    // The base path to the authentication endpoints. Change this if you want to add your auth-endpoints at a non-default location
    basePath: "/api/auth",
    // Whether to periodically refresh the session. Change this to `true` for a refresh every seconds or set this to a number like `5000` for a refresh every 5000 milliseconds (aka: 5 seconds)
    enableSessionRefreshPeriodically: false,
    // Whether to refresh the session whenever a window focus event happens, i.e, when your user refocuses the window. Set this to `false` to turn this off
    enableSessionRefreshOnWindowFocus: true,
    // Whether to add a global authentication middleware that will protect all pages without exclusion
    enableGlobalAppMiddleware: false,
    // Select the default-provider to use when `signIn` is called. Setting this here will also effect the global middleware behavior: E.g., when you set it to `github` and the user is unauthorized, they will be directly forwarded to the Github OAuth page instead of seeing the app-login page
    defaultProvider: undefined,
    // Configuration of the global auth-middleware (only applies if you set `enableGlobalAppMiddleware: true` above!)
    globalMiddlewareOptions: {
      // Whether to allow access to 404 pages without authentication. Set this to `false` to force users to sign-in before seeing `404` pages. Setting this to false may lead to vue-router problems (as the target page does not exist)
      allow404WithoutAuth: true,
    },
  },
```
});
> 

>

**Comment by yuvraj339** [comment]
![image](https://user-images.githubusercontent.com/8150078/218678610-b0fe0e61-701f-40a8-b31d-881ccc8ca533.png)

**Comment by yuvraj339** [comment]
Its not only looping on web browser its stop VS code, I have to restart VS code some time after add page in side [...].ts file as I mentioned above image

**Comment by phenomenal-hardy** [comment]
did you managed to solve it? having the exact same loop... but i got ERR_HTTP_HEADERS_SENT error

Cannot set headers after they are sent to the client


my custom login page:
`\pages\auth\login.vue`

```
<script setup lang="ts">

definePageMeta({ auth: false })

</script>
<template>
  <div>
    NEW LOGIN PAGE - FORMKIT HERE
  </div>
</template>

```

`nuxt.config.ts`
```
	auth: {
		isEnabled: true,
		origin: 'http://localhost:5000',
		/**  endpoint de autenticacion, va al siguiente catch-all server route */
		/** ~/server/api/auth/[...].ts */
		basePath: '/api/auth',
		enableSessionRefreshOnWindowFocus: true,
		enableGlobalAppMiddleware: true,
		defaultProvider: 'credentials',
	},
```

`~~\middleware\authentication.global.ts`
```
export default defineNuxtRouteMiddleware((to) => {
	const { status, signIn } = useSession();
	// Return immeadiatly if user is already authenticated
	if (status.value === 'authenticated') {
		return;
	}
	/**
	 * We cannot directly call and/or return `signIn` here as `signIn` uses async composables under the hood, leading to "nuxt instance undefined errors", see https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529
	 *
	 * So to avoid calling it, we return it immeadiatly.
	 */
	return signIn(undefined, { callbackUrl: to.path }) as ReturnType<
		typeof navigateTo
	>;
});
```


`~~/server/api/auth/[...].ts`
```
	pages: {
		signIn: '/auth/login',
	},


	providers: [

		CredentialsProvider.default({
			name: 'Credentials',
			credentials: {
				email: {
					label: 'Correo electronico',
					type: 'text',
					placeholder: '(hint: tucorreo@gmail.com)',
				},
				password: {
					label: 'Password',
					type: 'password',
					placeholder: '(hint: mysecretpassword)',
				},
			},
			authorize(credentials: any) {
				console.log('trying to authorize', credentials);
```


Error
```
packages/defy dev:defy: Warning: Malicious login attempt registered, bad credentials provided
packages/defy dev:defy: [Vue Router warn]: uncaught error during route navigation:
packages/defy dev:defy: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
packages/defy dev:defy:     at new NodeError (node:internal/errors:399:5)
packages/defy dev:defy:     at ServerResponse.setHeader (node:_http_outgoing:663:11)


packages/defy dev:defy: Warning: Malicious login attempt registered, bad credentials provided
packages/defy dev:defy: trying to authorize [Object: null prototype] {
packages/defy dev:defy:   callbackUrl: '/',
packages/defy dev:defy:   csrfToken: 'b61c18792933aed7d6f784993521724970fb6277fd2124bb5d87f3902beb63db',
packages/defy dev:defy:   json: 'true'
packages/defy dev:defy: }
packages/defy dev:defy: Warning: Malicious login attempt registered, bad credentials provided
packages/defy dev:defy: trying to authorize [Object: null prototype] {
packages/defy dev:defy:   callbackUrl: '/',
packages/defy dev:defy:   error: 'SessionRequired',
packages/defy dev:defy:   csrfToken: 'b61c18792933aed7d6f784993521724970fb6277fd2124bb5d87f3902beb63db',
packages/defy dev:defy:   json: 'true'
packages/defy dev:defy: }
packages/defy dev:defy: Warning: Malicious login attempt registered, bad credentials provided
packages/defy dev:defy: [nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
packages/defy dev:defy:     at new NodeError (node:internal/errors:399:5)
packages/defy dev:defy:     at ServerResponse.setHeader (node:_http_outgoing:663:11)

```

**Comment by yuvraj339** [comment]
Not yet still looking into it, until I got solution fixing other things, please update here if you found any solution @phenomenal-hardy

**Comment by zoey-kaiser** [comment]
Hello @yuvraj339 and @phenomenal-hardy!

I am not directly seeing any big issues in your code. I would create a new PR on our [nuxt-auth-example](https://github.com/sidebase/nuxt-auth-example/) using a custom signin page (to ensure everything is working and provide a nice example). Once I complete it I will mention both of you in the PR and that may help you find a fix the issues you are facing!

I am trying to get around to it today!

**Comment by phenomenal-hardy** [comment]
Hello @zoey-kaiser  


i think i commented out the `return signIn(undefined` line in the middleware file. so no more redirect loop. 
i dont think it is a final solution, but everything is working 😮‍💨 thanks



 ```typescript


// /middleware/auth.global.ts
export default defineNuxtRouteMiddleware((to, from) => {
	const { status } = useSession();

	// Return immeadiatly if user is already authenticated
	if (status.value === 'authenticated') {
		//console.log(data.value);

		return;
	}
	/**
         * THIS IS COMMENTED
         * 
	 * 
	 * We cannot directly call and/or return `signIn` here as `signIn` uses async composables under the hood, leading to "nuxt instance undefined errors", see https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529
	 *
	 * So to avoid calling it, we return it immeadiatly.
	 */
	/*
	return signIn(undefined, { callbackUrl: to.path }) as ReturnType<
		typeof navigateTo
	>;
	*/
});
 ```

login page, get the form payload and call signIn

 ```typescript

// login.vue


definePageMeta({ layout: 'auth', auth: false })

 const { error, url }  = await signIn('credentials', { 

email: payload.email, 
password: payload.password, redirect: false 

},);
 ```


My catch all api route, get credentials sent from `login.vue` and make a login post request to backend server (a nest js app running on 4000),
 ```typescript
// server/api/auth/[...].ts


async authorize(credentials: any) {
				console.log('trying to authorize', credentials);

				return await $fetch<AuthResponse>(
					`http://localhost:4000/auth/login`,
					{
						method: 'POST',
						headers: {
							Accept: 'application/json',
							'Content-Type': 'application/json',
							'X-Requested-With': 'XMLHttpRequest',
							'Access-Control-Allow-Origin': '*',
						},
						body: {
							email: credentials.email,
							password: credentials.password,
						},
					},
				)
					.then((res: AuthResponse) => {
						console.log(res);

						const defyUser = res.user;

						const nuxtUser = {
							id: defyUser.id,
							email: defyUser.email,
							name: defyUser.name,

							// le añadimos el accessToken al usuario guardado por nuxt-auth
							// ej: const { data } = useSession();
							// https://gist.github.com/vanling/b10ebe14ee90ff249bea28bf94abb745
							accessToken: res.accessToken,
						};

						return nuxtUser;
					})
					.catch(
						(err: {
							data: {
								message: string;
								statusCode: string;
							};
						}) => {
							console.error(
								'Warning: Malicious login attempt registered, bad credentials provided',
							);
							console.log('error desde el server:');
							console.log(err.data.message);

							// If you return null then an error will be displayed advising the user to check their details.
							// You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
							return null;
						},
					);
```

**Comment by yuvraj339** [comment]
> Hello @zoey-kaiser @yuvraj339
> 
> i think i commented out the `return signIn(undefined` line in the middleware file. so no more redirect loop. i dont think it is a final solution, but everything is working 😮‍💨 thanks
> 
> ```ts
> // /middleware/auth.global.ts
> export default defineNuxtRouteMiddleware((to, from) => {
>    const { status } = useSession();
> 
>    // Return immeadiatly if user is already authenticated
>    if (status.value === 'authenticated') {
>    	//console.log(data.value);
> 
>    	return;
>    }
>    /**
>         * THIS IS COMMENTED
>         * 
>     * 
>     * We cannot directly call and/or return `signIn` here as `signIn` uses async composables under the hood, leading to "nuxt instance undefined errors", see https://github.com/nuxt/framework/issues/5740#issuecomment-1229197529
>     *
>     * So to avoid calling it, we return it immeadiatly.
>     */
>    /*
>    return signIn(undefined, { callbackUrl: to.path }) as ReturnType<
>    	typeof navigateTo
>    >;
>    */
> });
> ```
> 
> login page, get the form payload and call signIn
> 
> ```ts
> // login.vue
> 
> 
> definePageMeta({ layout: 'auth', auth: false })
> 
> const { error, url }  = await signIn('credentials', { 
> 
> email: payload.email, 
> password: payload.password, redirect: false 
> 
> },);
> ```
> 
> My catch all api route, get credentials sent from `login.vue` and make a login post request to backend server (a nest js app running on 4000),
> 
> ```ts
> // server/api/auth/[...].ts
> 
> 
> async authorize(credentials: any) {
>    			console.log('trying to authorize', credentials);
> 
>    			return await $fetch<AuthResponse>(
>    				`http://localhost:4000/auth/login`,
>    				{
>    					method: 'POST',
>    					headers: {
>    						Accept: 'application/json',
>    						'Content-Type': 'application/json',
>    						'X-Requested-With': 'XMLHttpRequest',
>    						'Access-Control-Allow-Origin': '*',
>    					},
>    					body: {
>    						email: credentials.email,
>    						password: credentials.password,
>    					},
>    				},
>    			)
>    				.then((res: AuthResponse) => {
>    					console.log(res);
> 
>    					const defyUser = res.user;
> 
>    					const nuxtUser = {
>    						id: defyUser.id,
>    						email: defyUser.email,
>    						name: defyUser.name,
> 
>    						// le añadimos el accessToken al usuario guardado por nuxt-auth
>    						// ej: const { data } = useSession();
>    						// https://gist.github.com/vanling/b10ebe14ee90ff249bea28bf94abb745
>    						accessToken: res.accessToken,
>    					};
> 
>    					return nuxtUser;
>    				})
>    				.catch(
>    					(err: {
>    						data: {
>    							message: string;
>    							statusCode: string;
>    						};
>    					}) => {
>    						console.error(
>    							'Warning: Malicious login attempt registered, bad credentials provided',
>    						);
>    						console.log('error desde el server:');
>    						console.log(err.data.message);
> 
>    						// If you return null then an error will be displayed advising the user to check their details.
>    						// You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
>    						return null;
>    					},
>    				);
> ```

I was tried same, but I am not sure that is final solution lats wait for @zoey-kaiser reply

**Comment by hkrawczyk** [comment]
@zoey-kaiser any update on this?

**Comment by BracketJohn** [comment]
This issue is quite old. Can you:
- provide an up to date reproduction? Please make an actual repo where the error occurs
- ensure to use at least the latest stable version of the module for it

With just screenshots and code snippets it's impossible for us to further debug at this point.

Thanks!

**Comment by BracketJohn** [comment]
Closing it now as nothing new arose - feel free to open a new issue later on or comment here with a reproduction using the latest stable vewrsion of the module.
