### ISSUE TITLE
callbackUrl pointing to http://localhost/ - when origin in nuxt.config.ts is set to a different address from http://localhost:3000

### ISSUE THREAD

**Issue by tsrift** [sidebase/nuxt-auth#209]
### Describe the bug

I have set a Google Oauth Provider and locally (localhost:3000) everything works fine.
But when I set **origin** in **nuxt.config.ts** to some other address for production and when I run:
`npx nuxi generate`

then I get error:
` ERROR  [nuxt] [request error] [unhandled] [403] 403 Forbidden (http://some-address.com/api/auth/session?callbackUrl=http://localhost/)`

Why is this **callbackUrl** pointing to **http://localhost/** and not to the value from origin http://some-address.com?
How can I solve this problem?
I expect to see:
`http://some-address.com/api/auth/session?callbackUrl=http://some-address.com/`
and in that case there would be no error.

This would be the basic functionality not working as expected.

> nuxt.config.ts
> 
> ```
>   auth: {
>     // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`
>     # origin: 'http://localhost:3000'
>     origin: 'http://some-address.com'
> ```

### Logs
```
 ERROR  [nuxt] [request error] [unhandled] [403] 403 Forbidden (http://some-address.com/api/auth/session?callbackUrl=http://localhost/)                                                             22:02:57  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async /.../.nuxt/prerender/chunks/server.mjs:1223:62
  at async Object.callAsync (/.../node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (/.../.nuxt/prerender/chunks/server.mjs:117:33)
  at async applyPlugins (/.../.nuxt/prerender/chunks/server.mjs:126:5)
  at async createNuxtAppServer (/.../.nuxt/prerender/chunks/server.mjs:1522:7)
  at async Object.renderToString (/.../node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
  at async /.../.nuxt/prerender/chunks/renderer.mjs:387:21
  at async /.../.nuxt/prerender/chunks/renderer.mjs:28:22
  at async Object.handler (/.../node_modules/h3/dist/index.mjs:840:19)
```

_No response_

**Comment by tsrift** [comment]
With
`ssr: false`
I am able to generate the site:
`npx nuxi generate`

but then when I visit the site I also get 403 Forbidden error:
`403 Forbidden (http://some-address.com/api/auth/session?callbackUrl=http://some-address.com/)`

**Comment by tsrift** [comment]
By definition:
https://sidebase.io/nuxt-auth/getting-started

> nuxt-auth is an open source Nuxt module that provides authentication for non-static Nuxt 3 applications.

So, for node server application I managed to build it and then run it with DATABASE_URL field in .env (for prisma) in same process when starting node application.

1. First installed: https://www.npmjs.com/package/cross-env
`yarn add cross-env`
2. Then added another script in package.json > scripts:
 `   "withenv": "cross-env DATABASE_URL=file:./db.sqlite node .output/server/index.mjs"`
3. And after building it with `npx nuxi build `
I run it with: `yarn withenv`

**Comment by tsrift** [comment]
I tried to publish on Azure and get the same error because of the callbackUrl=http://localhost:4280/
`https://some-address.com/api/auth/session?callbackUrl=http://localhost:4280/`

**Comment by raducretu** [comment]
I get the same wirh a custom domain with auth0 when deploying to Netlify

**Comment by tsrift** [comment]
I successfully uploaded on Azure static web apps.
 **secret** and **origin** properties should be set directly, not as .env variables (Application settings in Azure).
Links are working now but OAuth is not working, I don't know why. I'm redirected to Google OAuth provider but I'm not authenticated successfully and redirected back at Sign In page.

Also, before that, there is another thing to fix in GoogleProvider, and that's:
https://github.com/nextauthjs/next-auth/issues/4190
> try adding checks: "both" on your provider
```
  providers: [
    GoogleProvider.default({
      checks: 'both',
      clientId: '',
      clientSecret: ''
    }),
```

**Comment by scottwansz** [comment]
according[ the doc](https://sidebase.io/nuxt-auth/configuration/nuxt-config#origin) :

> The AUTH_ORIGIN environment variable takes precendence over the origin configuration key, so you can always overwrite the origin at deploy-time.

when I set the AUTH_ORIGIN some url still use the value of origin origin-config key inside the nuxt.config.ts
below is the [nuxt-auth-example](https://github.com/sidebase/nuxt-auth-example) show the ERROR which set AUTH_ORIGIN as nuxtauth.com, diffrent from the value of origin origin-config key, but providers request still use the vaule of origin origin-config key.

![nuxtauth-provider-url-error](https://user-images.githubusercontent.com/11176084/222665997-c17a5a4c-11ea-4100-9e00-5b60bce9fa71.png)

**Comment by zoey-kaiser** [comment]
We had a similar issue in #228 and someone made a nice overview of how to deploy on Vercel:

https://github.com/sidebase/nuxt-auth/issues/228#issuecomment-1455111997

Maybe this helps for AWS! As for Netlify, we are aware that deploying to it is a bit harder. I will be opening a new issue to investigate this! Lets keep looking into it there to stay a bit more organized. Therefore I will also close this issue, you are welcome to open a new one for AWS so we can keep looking into it!
