### ISSUE TITLE
`getSession`'s status is always unauthenticated on server-side in route middlewares

### ISSUE THREAD

**Issue by noook** [sidebase/nuxt-auth#21]
### Environment

Nuxi 3.0.0-rc.13
RootDir: /Users/nook/work/tls-interim-front
Nuxt project info: (copied to clipboard)

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `typescript`, `css`, `modules`, `auth`, `build`, `googleFonts`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/google-fonts@3.0.0-1`, `@nuxtjs/svg@0.4.0`, `@pinia/nuxt@0.4.3`, `floating-vue/nuxt`, `@sidebase/nuxt-auth@0.0.1-beta.5`
- Build Modules:    `-`
------------------------------

### Describe the bug
**Given I am authenticated:**

When trying to guard a route, the session is **always** null (`unauthenticated`) on server side, but available on client side

```ts
definePageMeta({
  middleware: [async () => {
    const { status } = await useSession();
    console.log(status.value); // 'unauthenticated' on server, 'authenticated' on client
    if (status.value === 'authenticated') {
      return true;
    } else {
      console.log('hmm not ok');
      console.log(status.value); // 'unauthenticated' on server
    }
  }],
});
```

**Comment by BracketJohn** [comment]
Hey @noook!

Thanks for this bug report 🦃 

In the current implementation this is actually intended / a must: `useSession` only fetches from the client side, as this is where the auth-cookie is stored and can then be transmitted. If you want to stop running the full inline middleware on the server you can add:
```
if (process.server) {
  return true
}
```


at the top of your page-meta.

What's the problem you have / the use-case you cannot solve with this behavior? Do you already want to abort navigation on the server-side?

**Comment by noook** [comment]
This app uses an external API that requires authentication with a JWT
That means that even on the server on ssr I should be able to query that API with the session of the user

**Comment by BracketJohn** [comment]
Yeah - it works - I'll try to add a helper for it later. If you want to proceed _now_: Use useFetch to fetch the session from GET /api/auth/sesseion. 

As useFetch is isomorphic, this should work on both server and client.

I'll either add a helper for this or make useSession itself isomorphic.

**Comment by noook** [comment]
I just tried and I still have an empty object server side, and a correct value on the client.

(I remapped the auth endpoint because API is reserved for me it routes to another server)

![image](https://user-images.githubusercontent.com/19751938/201469814-696803d6-3a59-4a1e-b123-bd5ced43aba0.png)

**Comment by BracketJohn** [comment]
Perfect, glad the proposal worked for you (:

We'll publish a new release soon that includes native isomorphic fetching OR a special, isomorphic helper (unsure about the design details atm).

I'll leave this issue open until then (:

**Comment by BracketJohn** [comment]
@noook did you tsckle the onServerPrefetch warning somehow or just ignore it?

**Comment by noook** [comment]
I have the warning indeed. This [conversation](https://github.com/nuxt/framework/discussions/5226) suggests using `$fetch` instead which removes the warning but that's maybe not what we want

**Comment by BracketJohn** [comment]
hm, I briefly tried it and it threw some other error. I'll investigate a bit more (:
