### ISSUE TITLE
how to access encoded jwt token?

### ISSUE THREAD

**Issue by Kingside88** [sidebase/nuxt-auth#217]
### Ask your question

Here you descripe how to get the decoded jwt token:
https://sidebase.io/nuxt-auth/server-side/jwt-access

This works well. 
But to use the jwt token alongside the 'Authorisation' header, you need the token encoded.
Can someone please provide an example?

My composable looks like this:
**composables\useGetFetch.ts**
```
export const useGetFetch = async (url : string, opts = {}) => {
  const config = useRuntimeConfig();

  const headers = useRequestHeaders(['cookie']) as HeadersInit
  const { data: jwtTokenDecoded } = await useFetch('/api/token', { headers })

  return $fetch(url, {
      ...opts,
      method: "GET",
      baseURL: config.API_BASE_URL,
      credentials: 'omit',
      headers: {
        'pragma': 'no-cache',
        'cache': 'no-cache',
        'cache-control': 'no-cache',
        'Expires': '0',
        'Authorization': `Bearer ???`
      },
      
  })
}
```
**server\api\token.get.ts**
```
import { getToken } from '#auth'

export default eventHandler(async (event) => {
  const token = await getToken({ event })
  return token || 'no token present'
})
```
![image](https://user-images.githubusercontent.com/7474465/217380511-7936d102-d397-4e68-b80d-437b50e4c7f3.png)

**Comment by BracketJohn** [comment]
Hey @Kingside88 👋 

This one is easy: Just add `{ raw: true }` to the `getToken` call:
```ts
import { getToken } from '#auth'

export default eventHandler(async (event) => {
  const token = await getToken({ event, raw: true })
  return token || 'no token present'
})

```

That will return the token in raw form. This is also documented at the bottom of the first section here: https://sidebase.io/nuxt-auth/server-side/jwt-access#jwt-access (: 

Let me know if this helped / you have any follow up qs (:

**Comment by Kingside88** [comment]
that was it! Thank you!
