### ISSUE TITLE
Infinite Sign-in loop with Custom Middleware on Firefox only.

### ISSUE THREAD

**Issue by njoswald** [sidebase/nuxt-auth#218]
### Ask your question

I am having an issue where I am getting an infinite sign-in after entering my credentials. I am using global authentication to make my entire app besides a few public pages authenticated. Cognito is the provider I am using, and I am using some custom middleware to switch the callback url from to.path -> to.fullPath. I wanted to make sure that I am getting the query parameters in the url after logging in. 
I have been running into the issue where after entering all my credentials, I will get redirected to 
`http://localhost:3000/api/auth/signin?callbackUrl={full path with parameters}`
This page just has a "Sign in with Cognito" button that will only redirect to the same page, creating an infinite loop. 
I have tested this on Chrome, Edge, and Firefox. Only Firefox gets stuck at an infinite loop. Chrome and Edge go straight to the desired page after signing in. 

Here is the custom middleware:
```
export default defineNuxtRouteMiddleware((to) => {
    console.log("check global off");
    if (to.meta.auth === false) {
        return
    }

    console.log("check auth status");
    const { status, signIn } = useSession()
    if (status.value === 'authenticated') {
        return
    }

    const authConfig = useRuntimeConfig().public.auth

    console.log("check 404 page");
    if (authConfig.globalMiddlewareOptions.allow404WithoutAuth) {
        const matchedRoute = to.matched.length > 0
        if (!matchedRoute) {
        return
        }
    }

    console.log("signin");
    return signIn(undefined, { callbackUrl: to.fullPath }) as ReturnType<typeof navigateTo> })
```

It's basically just a modification of the source code middleware. I added some console.log's to see if there is a difference between browsers. I noticed that chrome and edge run through the middleware once when initially loading the target page, but then run through the middleware again after the sign-in is complete. Firefox, on the otherhand, only goes through the middleware once and gets stuck at the login loop. 

Chrome/Edge Log:
```
check global off                                                                                16:52:33
check auth status                                                                               16:52:33
check 404 page                                                                                  16:52:33  
signin
check global off                                                                                16:52:33
check auth status                                                                               16:52:33
check 404 page                                                                                  16:52:33  
signin
check global off                                                                                16:52:46
check auth status
```

Firefox Log:
```
check global off                                                                                17:00:55
check auth status                                                                               17:00:55
check 404 page                                                                                  17:00:55
signin 
check global off                                                                                17:00:55
check auth status                                                                               17:00:55
check 404 page                                                                                  17:00:55  
signin
```

I have made sure that cookies and site data are enabled. I have also tried to delete all cookies and retry signing in. I have tried using another computer's firefox and had the same issue. 
Is there something else I should add to the middleware that could alleviate this issue, or is it something related to Firefox that is messing with the redirect?

### Additional information

Using:
Nuxt v.3.1.2
nuxt-auth v0.4.0-alpha.5

**Comment by BracketJohn** [comment]
Hey @njoswald 👋 

Thanks for opening this question!


> Here is the custom middleware:

why did you implement a custom middleware for this - AFAIC see there's no changes from the original middleware? 

I think for me to help you here it would be best if you:
1. switch to the native global middleware
2. share a repository where I can reproduce this behavior 

At the moment I sadly don't have an idea based on your initial description.

**Comment by njoswald** [comment]
Hi @BracketJohn 
Thanks for looking at this. 
The reason that I am using custom middleware is to make sure that the full url is being passed to the callback url when signin is initiated. The last line of my middleware is the only thing that is changed. Here is the last line to my middleware:
`return signIn(undefined, { callbackUrl: to.fullPath }) as ReturnType<typeof navigateTo> })`
and here is the last line of the original middleware:
`return signIn(undefined, { callbackUrl: to.path, error: 'SessionRequired' }) as ReturnType<typeof navigateToAuthPages>`

As you can see, it's nearly identical except for the callbackUrl which is now **to.fullPath** instead of **to.path**.
This ensures that the full path including url parameters is sent to the callbackUrl. The page I am attempting to access after signing in needs the url parameter to work correctly, and I have not found a good way to allow url parameters from the official docs. 

As for a repository, I cannot send the original as it is a company private repository. However, I will invite you to another personal repository where I have replicated the issue. 

While attempting to replicate the issue I did find that the problem only occurs with PDFTron Webviewer pages. (https://github.com/PDFTron/webviewer-nuxtjs-sample) Because of that, it may be an issue that is only related to PDFTron. Please let me know if that is the case. 

The bottom text form in replicated app is the problem application while the top text form works correctly. 
And again, this problem only occurs on Firefox. Chrome and Edge both pass the callback url to the Webviewer page correctly.

**Comment by madebyfabian** [comment]
Same thing happens for me, but on all browsers. I need a custom middleware implementation since I want to make sure that when my app is in preview mode (for CMS authors), they don't have to sign in, since the sign in functionality is somehow broken, likely caused by the CMS embedding the app within an iframe.

Is there another way to like "force sign in" without entering credentials when somebody opens the app with, to keep it simple, example.com/page?force_sign_in=true

**Comment by BracketJohn** [comment]
Hey @njoswald, hey @madebyfabian 🏴󠁧󠁢󠁷󠁬󠁳󠁿 

re @njoswald: I will check it out, but as you already observed: If this works as expected for pages that do not use PDFTron, the chance is high that PDFTron is the cause. Nevertheless I'll have a look at the repo you shared later!

re @madebyfabian: Glad to have you here! One idea I have right away: How about you enable the global middleware and then in a central place do something like:
```ts
definePageMeta({ auth: !useRoute().params.forceSignIn })
```

I've never tried this, but would be cool to see it working.

Another idea is to disable the global middleware and instead adding the local middleware to a central page (under which you mount all the other pages) and then turn it on / off depending on some param (same approach as above).

The problem for your casde btw is likely that you are distributing it via an iframe, which has non-intuitive cookie behavior.

**Comment by madebyfabian** [comment]
@BracketJohn Thanks for the suggestion! I have to disable the global middleware anyways, since it's causing an infinite redirect loop as soon as I push to vercel (dev works fine). Wanted to create an issue on that with a minimal reprod, so that's another topic.

The issue here is that due to the iframe, the nuxt router never get's the additional query params. So the CMS (Storyblok) adds a `?_storyblok=` parameter (and a bunch of others), including a key, which I could use to validate that we are really inside the CMS and then disable it.

Next issue is that

```ts
definePageMeta({ auth: !useRoute().params._storyblok })
```

will not work ("nuxt instance unavailable").

**Comment by madebyfabian** [comment]
But regardless if I use the global middleware or try to build my own, I always get infinite redirects. Though doing it like it's pointed out in the docs. Will create a minimal reprod in a seperate issue.

**Comment by kurashina-design** [comment]
On all browsers, `const session = await getSession();` is empty after login whether `enableGlobalAppMiddleware` is true or false.

**Comment by BracketJohn** [comment]
Hey!

Sorry for the long wait here - as it has been quite some time now, I'd ask you to try this with up to date module + nuxt + next-auth peer dep and re-open the issue if it persists. Thanks ❤️
