### ISSUE TITLE
How to translate "Sign in with ..."

### ISSUE THREAD

**Issue by SamG92** [sidebase/nuxt-auth#225]
### Ask your question

Hello,

I'm trying to implement nuxt-auth in my nuxt3 environment.
I succeeded in getting it to work but I would like to translate text in French for my users in the signin page ("Sign in with" , "or" ...):
![image](https://user-images.githubusercontent.com/105436774/217815317-53b55529-59f9-4ecc-a20e-dcea3d6d5965.png)

How I can I do that?

Thanks a lot
Sam

**Comment by Kingside88** [comment]
I guess you have to create you're own login page. Is this a possible solution for you?
https://sidebase.io/nuxt-auth/application-side/custom-sign-in-page

**Comment by SamG92** [comment]
Well, I don't know how I missed that page from the documentation...
Thanks a lot!
