### ISSUE TITLE
I can´t modify user session data

### ISSUE THREAD

**Issue by agracia-foticos** [sidebase/nuxt-auth#229]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.3.1`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.12.0`, `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.9`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`

### Describe the bug

I'm trying modify user session data adding new field accessToken like the demo of https://sidebase.io/nuxt-auth/recipes/custom-session-data but the field doesn't appear.

I'm added callbacks like this:
` callbacks: {
    // Callback when the JWT is created / updated, see https://next-auth.js.org/configuration/callbacks#jwt-callback
    async jwt({ token, account, profile }) {
      // Persist the OAuth access_token and or the user id to the token right after signin
      if (account) {
        token.accessToken = account.access_token
        token.id = profile.id
      }
      return token
    },
    // Callback whenever session is checked, see https://next-auth.js.org/configuration/callbacks#session-callback
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token and user id from a provider.
      session.accessToken = token.accessToken
      session.user.id = token.id
      return session
    }
  },` in /src/server/api/auth/[...].ts

And i'm created a new file : './next-auth.d.ts'
`// file: ~/next-auth.d.ts
import { DefaultSession } from "next-auth"
declare module "next-auth" {
  interface Session {
    // New access token field we added to the session
    accessToken: string
    user: DefaultSession["user"]
  }
}
`

But new field isn't created
![image](https://user-images.githubusercontent.com/77386602/218398583-82aa0624-c16a-4c00-9e3d-13df468d6826.png)

**Comment by BracketJohn** [comment]
Hey @agracia-foticos 👋 

Thanks for the issue - we recently merged #206 which clarified and fixed the instructions on manual data! Can you please checkout and follow the updated https://sidebase.io/nuxt-auth/recipes/custom-session-data again and see if this works for you?

**Comment by agracia-foticos** [comment]
Perfect!!!!!

**Comment by BracketJohn** [comment]
Aweeeesome! You can thank @jorgv for contributing #206 (:

**Comment by agracia-foticos** [comment]
@BracketJohn @jorgv 
![image](https://github.com/user-attachments/assets/81f5545c-b456-4114-8d5c-6670fa00f2f7)

THanks in advance
