### ISSUE TITLE
Utilize native `useSession` from `h3`

### ISSUE THREAD

**Issue by manniL** [sidebase/nuxt-auth#230]
### Describe the feature

Hey!

Since the last `h3` and `nitropack` release, a "native" [`useSession`](https://github.com/unjs/h3/pull/315) composable is provided. Ideally, `nuxt-auth` would utilize it 😋

**Comment by zoey-kaiser** [comment]
Hi @manniL!

I definitely agree with this! We had already discussed renaming our composable to `useAuth` once`h3` added their native composable. 

Depending on the workload it may take a few days for me to get around to it. If you have some extra time and want to contribute, feel free to open a PR and take a crack at it yourself. It would help push this through quickly.

**Comment by zoey-kaiser** [comment]
I added this to the TODO in #117 

Once we get around to the bigger rewrite we can integrate this. I will therefore close this issue 🎈
