### ISSUE TITLE
getServerSession in API endpoint messes up with it

### ISSUE THREAD

**Issue by tmlmt** [sidebase/nuxt-auth#241]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `app`, `css`, `build`, `modules`, `runtimeConfig`, `auth`, `i18n`, `nitro`, `security`, `vite`
- Runtime Modules:  `@sidebase/nuxt-auth@0.4.1`, `@nuxtjs/i18n@8.0.0-beta.9`, `@pinia/nuxt@0.4.6`, `nuxt-security@0.10.2`, `@vueuse/nuxt@9.12.0`
- Build Modules:    `-`

### Reproduction

Create an API endpoint `example.get.ts` which includes `const session = await getServerSession(event);`

### Describe the bug

I get a `Cannot stringify arbitrary non-POJOs Blob` and an empty Blob {} is received from the API endpoint even if the value is valid on the other end.

**Comment by rd-carter** [comment]
@tmlmt I also encountered this problem. I looked at the source code of nuxt-auth and nitro, and found that it should be a problem with nitro. When I put the request in nexttick, it will be fine.
```
nextTick(() => {
    getConversations()
})
```

**Comment by tmlmt** [comment]
@rd-carter thanks for your message! Could you elaborate a bit on what you think the issue may be with nitro?

I found it not really satisfactory  to condition an API request to the state of the DOM (`nextTick`) as a workaround. My own use-case was that I needed to use the userId in  my endpoint to update user settings. I ended up using a [server middleware](https://nuxt.com/docs/guide/directory-structure/server#server-middleware) to augment the context:

```
import { getServerSession } from "#auth";

export default eventHandler(async (event) => {
  const session = await getServerSession(event);

  if (event.path?.startsWith("/api/user/")) {
    if (!session) {
      throw createError({ statusMessage: "unauthenticated", statusCode: 403 });
    }
    event.context.auth = { id: session.user.id };
  }
});
```

**Comment by rd-carter** [comment]
You can try this way, I also encountered this problem in middleware. Then I adjusted the order of the code and the program ran normally. I feel weird too
```
import { getServerSession } from "#auth";

export default eventHandler(async (event) => {


   if (!event.path?.startsWith("/api/user/")) {
      return 
   }


  


  const session = await getServerSession(event);

  if (session) {
      event.context.auth = { id: session.user.id };
      return
    }
    

    throw createError({ statusMessage: "unauthenticated", statusCode: 403 });

  
});
```

Here is my code：
path: ~/server/middleware/auth.ts
```
import { getServerSession } from '#auth'

export default eventHandler(async (event) => {
  
  const path = event.path
  
  if (path === '/' || path?.startsWith('/?callbackUrl=') || path?.startsWith('/api/auth')) {
    return
  }

  const session = await getServerSession(event)
  if (!session) {
    throw createError({ statusMessage: 'What\'s upwassup?', statusCode: 403 })
  }

})

```

**Comment by anPalmer** [comment]
Not ideal, but I was able to write my own replacement function to call using an auto-imported server util that calls to the session end point /api/auth/session, passes in the headers from the request, and gets back the session without causing the same issue.

_/server/utils/getServerSession.ts_
```js
import { H3Event } from "h3";
const getServerSession = async (event:H3Event) => {
    const headers = getHeaders(event) as HeadersInit;
    const session = await $fetch("/api/auth/session", {
        headers,
    });
    return session;
}
export default getServerSession;
```
_/api/randomendpoint.ts_
```js
export default defineEventHandler(async (event) => {
    const session = await getServerSession(event);
    //use session reliably
}
```

I would've assumed this is all the getServerSession would be doing, so I'm surprised it fixed the issue. But it did, at least for me. Still would love to see an actual fix. 🙏

**Comment by zoey-kaiser** [comment]
Hi @anPalmer @tmlmt @rdzhaoxin 👋 

I just released nuxt-auth `0.4.3`. This updates incorporates the wrapper that @anPalmer had made, which means it should now be possible to call `getServerSession()` without any "hacky" workarounds!

Let me know if this did the trick for you!


```sh
npm i -D @sidebase/nuxt-auth@0.4.3
```

**Comment by autorunman22** [comment]
Still getting this very issue at `0.5.0`

**Comment by mubaidr** [comment]
For the latest beta (0.6), await getServerSession(event) returns null sometimes.
