### ISSUE TITLE
use app.baseURL to allow installing application in subfolder

### ISSUE THREAD

**Issue by kvanska** [sidebase/nuxt-auth#242]
### Describe the feature

When setting https://nuxt.com/docs/api/configuration/nuxt-config#baseurl it is not possible to configure nuxt-auth working. 

If trying to configure origin or basePath for nuxt-auth, they just introduce bunch of new problems. 

Easiest would be that nuxt-auth respects the nuxtjs app.baseURL property for the auth paths as well as redirect urls. 

this configuration should work out of the box:
```
export default defineNuxtConfig({
  app: {
    baseURL: '/myapplication/',
  },  
  modules: [
    '@sidebase/nuxt-auth'
  ]
})
```

**Comment by zoey-kaiser** [comment]
Hi @kvanska 👋 

I understand the confusion. We are currently using `basePATH` and `origin` to compose the [`NEXTAUTH_URL`](https://next-auth.js.org/configuration/options#nextauth_url). We therefore pass the values to AuthJS behind the scenes and do not handle it ourselves. 
The `basePath` therefore does not refer to the file structure, but the structure of the application once it is started. 

If you have an idea of how we could handle this (To make it make sense in a Nuxt way and a AuthJS way) feel free to open a PR and I will get around to reviewing it! We always love when our community members help us improve `nuxt-auth`.

I hope my explanation made sense 😊, if you have any other questions for concerns feel free to reach out!

**Comment by zoey-kaiser** [comment]
I will be closing this issue as there has not been any progress here. Please reopen it if the issue still consists!
