### ISSUE TITLE
Set the JWT expiration date after login 

### ISSUE THREAD

**Issue by kaboume** [sidebase/nuxt-auth#260]
### Ask your question

Hi,
I'm using the CredentialsProvider to login the users.
The CredentialsProvider  make a call API to a backend which returns a JWT Token with an expiration date.
My question : how to set the JWT expiration date of the JWT build by Nuxt-auth with the expiration date of the JWT returned by the Back End ?

```
providers: [

    CredentialsProvider.default({
      name: 'Credentials',
      credentials: {
        username: { label: 'Username', type: 'text', placeholder: '(hint: jsmith)' },
        password: { label: 'Password', type: 'password', placeholder: '(hint: hunter2)' },
      },
      async authorize(credentials: any) {
        try {
          const response = await $fetch(
            `${config.public.API_BASE_URL}auth/login/`,
            {
              method: 'POST',
              body: JSON.stringify({
                email: credentials.username,
                password: credentials.password,
              }),
            },
          )
          **console.log('response', response)**
          if (response.user) {
            const u = {
              id: response.user.id,
              name: response.user.name,
              role: response.user.role,
              email: response.user.email,
              accessToken: response.tokens.access.token,
            }
            return u
          }
          else {
            return null
          }
        }
        catch (error) {
          console.warn(error)

          throw createError({
            statusCode: error.status,
            statusMessage: error.data.message,
          })

          return null
        }
      },
    }),
  ],

  session: {
    strategy: 'jwt',
  },

  callbacks: {
    async jwt({ token, user, account }) {
      if (account && user) {
        console.warn('JWT callback', { token, user, account })
        return {
          ...token,
          ...user,
        }
      }
      return token
    },
    async session({ session, token }) {
      session.user = {
        ...session.user,
        ...token,
      }
      return session
    },
  },
```

Here is the result of the console.log('response', response) : 

```
response {
  user: {
    role: 'user',
    isEmailVerified: true,
    name: 'Eric',
    email: 'eric.xxxxxxx@gmail.com',
    createdAt: '2023-01-11T10:44:38.672Z',
    updatedAt: '2023-02-09T08:42:08.710Z',
    id: '63be93164781b246a0a7a2e2'
  },
  tokens: {
    access: {
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JlOTMxNjQ3ODFiMjQ2YTBhN2EyZTIiLCJpYXQiOjE2Nzc1OTc1MjYsImV4cCI6MTY3NzYxNTUyNiwidHlwZSI6ImFjY2VzcyJ9.XtNTtJoXnIXu8wbYNkYW5pjU4kiKI_J4zkcGfum7hiI',
      **expires: '2023-02-28T20:18:46.850Z'**
    },
    refresh: {
      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JlOTMxNjQ3ODFiMjQ2YTBhN2EyZTIiLCJpYXQiOjE2Nzc1OTc1MjYsImV4cCI6MTY4MDE4NTkyNiwidHlwZSI6InJlZnJlc2gifQ.IvVrJeMP7nMMZ_x3APhWDRw2OnzoMRDqFCaic1qRWHY',
      expires: '2023-03-30T14:18:46.852Z'
    }
  }
}
```

And when I display the content of the session in the application side : 

```
{
  "user": {
    "name": "Eric",
    "email": "eric.xxxxx@gmail.com",
    "sub": "63be93164781b246a0a7a2e2",
    "id": "63be93164781b246a0a7a2e2",
    "role": "user",
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2JlOTMxNjQ3ODFiMjQ2YTBhN2EyZTIiLCJpYXQiOjE2Nzc1OTc1MjYsImV4cCI6MTY3NzYxNTUyNiwidHlwZSI6ImFjY2VzcyJ9.XtNTtJoXnIXu8wbYNkYW5pjU4kiKI_J4zkcGfum7hiI",
    "iat": 1677597526,
    "exp": 1680189526,
    "jti": "0f9459c8-c0ec-4f00-b0b8-04f47e24a602"
  },
  **"expires": "2023-03-30T15:18:46.991Z"**
}
```

**Comment by kaboume** [comment]
My goal behind this is to automatically log out the user when the expiration date of the JWT returned by the API backend has expired.
This is currently not the case because the expiration date of Nuxt Auth's JWT is further away than the JWT returned by the backend api

**Comment by zoey-kaiser** [comment]
You could look into setting a default session expiry time in the NuxtAuthHandler: https://next-auth.js.org/configuration/options#session

**Comment by kaboume** [comment]
Hi @zoey-kaiser ,
Thanks for the reply.
With this solution, I have to fill each side (Nuxt AUth & Backend API Auth) with the same session duration. I agree that it works but I would have liked at the time of authentication, when I retrieve the Access Token from the Back end ApI fill in the expiry date of the JWT forged by Nuxt Auth.

**Comment by zoey-kaiser** [comment]
Hi @kaboume

In that case you could have a look at refreshing the JWT token once you receive the answer from the backend. Have a look here for how to implement this: https://authjs.dev/guides/basics/refresh-token-rotation

**Comment by kaboume** [comment]
Hi @zoey-kaiser ,

I tried 

> You could look into setting a default session expiry time in the NuxtAuthHandler: https://next-auth.js.org/configuration/options#session

with this test configuration :

  session: {
    strategy: 'jwt',
    // maxAge: 30 * 24 * 60 * 60, // 30 days
    maxAge: 120, // 2 minutes
  },

But when the session expires after 2 minutes, nothing happens at the application level: the user is not automatically disconnected.
How to ensure that the user is automatically logged out once the session expires?

**Comment by zoey-kaiser** [comment]
Hi @kaboume 👋 

from my understanding the user would need to make another request for the expired session to be noticed. NextAuth supports setting a refetch interval (check session every X seconds) to account for what you are trying to achieve. In order to activate this feature add the following option to your `nuxt.config.ts`:

```ts
auth: {
  enableSessionRefreshPeriodically: true, // checks every 1000ms. Can also be a number in milliseconds.
  enableSessionRefreshOnWindowFocus: true // rechecks session every time the window is focused
}
```

I hope this solves your issue!

**Comment by kaboume** [comment]
Hi @zoey-kaiser ,

I'm still stuck because the expiration date of the JWT token retrieved from my authentication back-end is different than the JWT created by Nuxt-auth.

Where in the application and how can I automate the testing of the expiration date of my JWT from my authentication back-end so that I can trigger a signOut from Nuxt Auth?

And last question: I still don't understand why the expiration date of the JWT created by Nuct AUth is extended automatically when I refresh the page... (while I never refresh the JWT of Nuxt Auth with a refresh token.. .)

**Comment by BracketJohn** [comment]
Hey @kaboume 🧇 

The only way for us to help here will be a reproduction we can use -> can you please provide us one?

**Comment by BracketJohn** [comment]
closing as no reproduction available. We are happy to re-open this but only if a working reproduction is posted, that one of us can actually verify locally, thanks!
