### ISSUE TITLE
How do I interact with Prisma during login?

### ISSUE THREAD

**Issue by CodyBontecou** [sidebase/nuxt-auth#261]
### Ask your question

I'm working with the TwitchProvider and would like to interact with Prisma when a user logs in or registers. What is the best way to do this?

**Comment by zoey-kaiser** [comment]
Hi @CodyBontecou 👋 

You should be able to use the SignInCallback which is triggered whenever a signin attempt is made. Note: It is also called when a failed signin request happens. Therefore it may also be helpful to look into the other callbacks!

https://next-auth.js.org/configuration/callbacks#sign-in-callback

**Comment by CodyBontecou** [comment]
Hey @zoey-kaiser!

Is it appropriate to call an async function within the SignInCallback? I'd like to call a Nuxt server function on account creation, and I am unsure where to place this code.

**Comment by zoey-kaiser** [comment]
> Is it appropriate to call an async function within the SignInCallback? I'd like to call a Nuxt server function on account creation, and I am unsure where to place this code.

I don"t think it would cause any issues!

**Comment by CodyBontecou** [comment]
I ended up doing something like:
```ts
callbacks: {
    async signIn({ user, account, profile, email, credentials }) {
      const isAllowedToSignIn = true
      if (isAllowedToSignIn) {
        await $fetch('/api/create-stripe-customer', {
          method: 'POST',
          query: {
            API_ROUTE_SECRET: '...',
          },
          body: {
            record: {
              email: email,
              id: user.id,
            },
          },
        })
        return true
      } else {
        // Return false to display a default error message
        return false
        // Or you can return a URL to redirect to:
        // return '/unauthorized'
      }
    },
}
```

and it works great. Thank you for the help.

**Comment by oruman** [comment]
I use alternative - add global variable in Server for Prisma.
https://github.com/sidebase/sidebase/pull/103
