### ISSUE TITLE
Can we use our own Auth backend>

### ISSUE THREAD

**Issue by jahidanowar** [sidebase/nuxt-auth#276]
### Ask your question

I have a auth rest API. I need to set the bearer token. Can we get access to the JWT token in the frontend, not in server? I can't route all my requests via nuxt server. 

Apparently, I can set the user data, but I am not able to set or access jwt token given by my rest API from the frontend.

```ts
 async authorize(credentials: any) {
    try {
      // Get JWT token from API endpoint using credentials
      const res = await useFetchApi().post<SignInResponse>(
        apiRoutes.auth.signIn,
        {
          email: credentials.email,
          password: credentials.password,
        }
      );
      if (res.result && res.data.token) {
        const user = {
         // can I store the JWT here??
        };
        return user;
      }
      // Return user data
    } catch (err: any) {
     ...
    }
},
```

Where do I store the `res.data.token` ?? and how can I access it in the frontend?

**Comment by zoey-kaiser** [comment]
Hi @jahidanowar 👋 

You can add your own custom session data. You do this by extending the session object. You will then get your data returned when you call `useSession()`.

Have a look at the documentation [here](https://sidebase.io/nuxt-auth/recipes/custom-session-data), it comes with code snippets which should hopefully help you!

**Comment by jahidanowar** [comment]
What if i delete the user from my external backend? And let's suppose I have the session active in nuxt? Is there any option to check if the user is indeed logged in every time the page is refreshed, like the @nuxtjs/auth? 
So basically, When the session is active, I want to request the `/me` route every time the page is refreshed. It will return the user data and it should be updated in the nuxt-auth session as well.

**Comment by zoey-kaiser** [comment]
By default the session is updated every refresh, however we have two options that minic those of NextAuth that check the session every X milliseconds or everytime the window is focused:

`enableSessionRefreshPeriodically` & `enableSessionRefreshOnWindowFocus`

https://sidebase.io/nuxt-auth/configuration/nuxt-config

**Comment by jahidanowar** [comment]
Ok, But I am asking if it will run the logic inside authorize. I want to call the external rest-api along with the jwt on every session update. If it fails, it should log out.

**Comment by 35grain** [comment]
Yeah good question, what actually happens when the session is refreshed? Is only the frontend nuxt-auth JWT refreshed or also anything within authorize? Or is there anyway to configure it so?
