### ISSUE TITLE
import getToken within Nitro Api results in useCookies is undefined

### ISSUE THREAD

**Issue by darwebdb** [sidebase/nuxt-auth#28]
Heads ups: 
When adding getToken in the nitro server on version, results in an error.

```
// example file: server/api/licenses/retrieve.ts
import { getToken } from '#auth'

export default defineEventHandler(async (event) => {
    const config = useRuntimeConfig();

    const token = await getToken({ event, raw: true })

    const settings = {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + token.value
      },
    }

    const response = await $fetch(
        'http://your.domain.com/api/...';
      return response;
  });
```

After successfully authenticating and hitting the above endpoint the following error output is shown in the terminal when trying to retrieve the token:
`[nuxt] [request error] [unhandled] [500] useCookies is not defined`

"@sidebase/nuxt-auth": "^0.0.1-beta.6",
"nuxt": "3.0.0-rc.12",

**Comment by BracketJohn** [comment]
Thanks @darwebdb - you are the best!

Can you checkout if `@sidebase/nuxt-auth@0.0.1-beta.7` fixes this problem?

**Comment by darwebdb** [comment]
I can confirm the fix, the above code is now outputting the token correctly within the nitro api when using:
`@sidebase/nuxt-auth@0.0.1-beta.7`.
Able to make authenticated calls now including the token!!

You guys are amazing!

**Comment by darwebdb** [comment]
During some cycling between yarn dev. 
I noticed that the JWT got malformed during.

My strapi user/jwt object returned from logging in using a tool like insomnia outputs:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjY4MzY4NzE4LCJleHAiOjE2NjgzNzk1MTh9.oSQHlABXk-UK_JDHKwfRcjwC8z0XaGS7OapbC7sbjsU`

After adding the req.headers to the call,
I do receive either a user model based off the module's user Interface.
If I add raw:true, I receive the raw JWT, but it's malformed compared to the original, it might a be completely new one.
`eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..fDDAqkXdXOIATHLS.qHoDtAVwIBDpeQj8Wdv_ukd1_HALVxxzgCaBJL7XSWlqYPSwcqHdAXrs9JAyHPkRx6cMpRU-I5yKVPqaIGQGZmmsQAzxqeQE65qEdLdU3IVnRah720b762g7vfS1NXIHAaQMj7wHn0mBYdloBU8o1thb67jwfYYCaEGntNTzQ7Ugy_BtOQ.kKxF_uPjxC3Hd1_zmwfZVg`

**Comment by BracketJohn** [comment]
Hey @darwebdb - let's resolve this in a new issue! Ideally, you can add a reproduction there, so that I can look at the code? it's a bit hard to debug this specific problem otherwise,

thanks ❤️
