### ISSUE TITLE
How get accessToken on the cliente to work with external API

### ISSUE THREAD

**Issue by julio-soft** [sidebase/nuxt-auth#280]
### Ask your question

I'm using Auth0 Provider.
however, I need the access token on the client for an auth0 protected external api. In the doc it mentions getToken() but it returns a token that is useless for me to access the external api from the client. some way to get this access token.

**Comment by iliwili** [comment]
I am in the same boat here!

**Comment by CavalcanteLeo** [comment]
same here, i need the raw token, not the decoded one...

Also the one that is on the cookie seems to be encrypted, which is not valid

**Comment by smastrom** [comment]
You can query the raw token like this:

**server/api/token.ts**
```ts
import { getToken } from '#auth'

export default defineEventHandler(async (event) => {
  const token = await getToken({ event, raw: true })
  if (token) {
    return token
  }
  
  setResponseStatus(event, 401)
  return {}
})
```

Then use `$fetch('api/token')` to get the token string from the client.

The problem is (at least for me) that this token is not compact auth0 access token that you can use to access other services.

I ended up doing my own auth0 implementation for this reason. It takes an afternoon but at least works as expected.

https://auth0.com/docs/api/authentication#introduction

**Comment by julio-soft** [comment]
> I ended up doing my own auth0 implementation for this reason. It takes an afternoon but at least works as ex

Hi, thanks for the commnets. Has you said, the token returned from getToken() doesn't work with auth0. Can you share with u your auth0 implementation?

**Comment by jtswm** [comment]
To get the access token for an external API, you can use the `jwt` callback to store the access token in the encrypted JWT (as shown in the example below).

Once you have the access token stored in the encrypted JWT via the `jwt` callback, there are a couple of ways to access it and use it:

**1) Get the access token client side via the session:**

Adapted from:
https://next-auth.js.org/configuration/callbacks#jwt-callback
https://next-auth.js.org/configuration/callbacks#session-callback

```javascript
import { NuxtAuthHandler } from '#auth'

export default NuxtAuthHandler({
  callbacks: {
    jwt({ token, account }) {
      // Persist the access_token in the encrypted JWT.
      if (account) {
        token.access_token = account.access_token
      }
      return token
    },
    session({ session, token }) {
      // Make access token available on the client.
      session.access_token = token.access_token
      return session
    },
  },
  providers: [
    ...
  ],
})
```
You can then get the access token client side by reading the session with `const { data } = useSession()`

**2) Get the access token client side via an endpoint:**
First, access the decrypted and decoded JWT on the client by following the steps here: https://sidebase.io/nuxt-auth/server-side/jwt-access. Then, grab the access token from the JWT.

**3) Proxy client requests through a Nuxt endpoint:**
Set up a protected API endpoint on the Nuxt backend to proxy requests to the external API. The client sends any requests intended for the external API to the Nuxt endpoint first. The Nuxt endpoint decrypts and decodes the JWT (with `getToken`) to access the access token and then makes a call to the external API with the access token attached. Once the Nuxt endpoint receives a response from the external API, it returns a response to the client.

**Comment by BracketJohn** [comment]
Seems to be resolved, thanks @jtswm ❤️ 💯 

See y'all on the other side!
