### ISSUE TITLE
Can trustHost be respected in client-side too? and also in assert plugin

### ISSUE THREAD

**Issue by chenyuncai** [sidebase/nuxt-auth#281]
### Ask your question

I have seen why the origin key need to be set in prod mode in next-auth community and they now add support trustHost mode.

In nuxt-auth, we add trusthost too, but we still check the origin config when app startup. can we add the trusthost checked first?

and in the client side, we still take the runtimeConfig().public.auth.origin when trustHost set.

**Comment by zoey-kaiser** [comment]
Hi @chenyuncai 👋 

AFAIK `trustHost` is being rolled out in AuthJS and is not available in NextAuth. We are planning to upgrade to AuthJS (#117), however are waiting for their full release. 

You can follow the process in this issue linked above. I hope I was able to answer your question!
