### ISSUE TITLE
Using HTTPS during development 

### ISSUE THREAD

**Issue by RHellenes** [sidebase/nuxt-auth#286]
### Ask your question

I have set up HTTPS on localhost but after i initiate the github provider login I get redirected to http://... Is there a way to override the default redirect? — This happens imediately after the inital signIn function that comes with enableGlobalAppMiddleware set to true

**Comment by vanling** [comment]
@RHellenes I currently use https aswell and this did the trick in the nuxt config.

```
auth: {
    ...(process.env.NODE_ENV === 'development'
      ? { origin: 'https://localhost:3000' }
      : { origin: 'https://developling.nl' }),
}
```

**Comment by RHellenes** [comment]
Thank you for your comment @vanling. 
Although your code was a bit smarter than mine, it did not solve the error. 

--------
Here was my error message

```zsh
[nuxt] error caught during app initialization [FetchError: request to https://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/ failed, reason: unable to verify the first certificate (https://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/)]
```
After reading the error message again I noticed this part: "failed, reason: unable to verify the first certificate" instead of only focusing on the callbackUrl being http and not https. Which lead me back to a flag I removed earlier because it printed out a warning that it is bad practice: `NODE_TLS_REJECT_UNAUTHORIZED=0` — Readding it seems to do the trick.



Heres the full command if anyone in the future have use for it. 
```json
"scripts": {
     "dev": "NODE_TLS_REJECT_UNAUTHORIZED=0 nuxt dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem" 
 }
```

(this required you to have installed mkcert) [Check this guide made by Storyblok on how to do it](https://www.storyblok.com/faq/setting-up-https-on-localhost-in-nuxt-3)

**Comment by vanling** [comment]
@RHellenes ah!Sorry. you're right. Did not think about that one. Got that piece also tucked away in my starter
