### ISSUE TITLE
Custom fields for Credentials Provider

### ISSUE THREAD

**Issue by darwebdb** [sidebase/nuxt-auth#29]
### Describe the feature

I would like to suggest a custom/optional field in the user interface object to store additional data. 
F.e when logging in with Strapi using Credential flow, the server will return a JWT. This token needs to stay unaltered otherwise the secret is no longer valid. I would like to propose a extra optional field for users, so that they can add in content that can be then safely stored within the encoded session jwt. By using getToken in Nitro we could then reacquire the original raw JWT token from Strapi.

### Additional information

Within the [...].ts auth catch all endpoint:

`if (user) {

          const u = {
            id: user.id,
            name: user.user.username,
            // Passing the OG JWT through the email field.
            email: user.jwt
          };

          return u;
        } else {
          // If you return null then an error will be displayed advising the user to check their details.
          return null;

          // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
        }`

And then in Nitro Api I hack it out the email field currently with getToken:
`const token = await getToken({ event });

    const settings = {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + token.email,
      },
    };`

_No response_

**Comment by BracketJohn** [comment]
Hey @darwebdb!

Thank you for this issue! Have you looked at https://next-auth.js.org/getting-started/typescript#main-module?

You can use the `session` callback to add additional data into your session. You could also directly do this in the `credentials` workflow (:

**Comment by darwebdb** [comment]
Hey @BracketJohn 

Thanks for coming back so quick. 
I didn't know you could just append more fields to the user.
Initially I stuck the original JWT to a user.jwt field but that didn't come out of the decoded session JWT.

I'll play with it today and update everything.

Will keep you updated.

**Comment by jorgv** [comment]
Also trying to figure out a way to add more fields since the user object is limited. I played with the session and the jwt callbacks but seems that the response from the signin is not available, so I can't add the fields I want.

 @BracketJohn you mention that we can also add more fields in the credentials workflow, do you have a snippet of that, because there I have the response, I just need a way to add it to the session data.

thanks

**Comment by BracketJohn** [comment]
Hey @jorgv!

Thanks for the q -> there are different times / places at which the user / session objects can be altered. E.g., you can alter it every time before it used, or you could try to alter it permanently in the database (if you're using an adapter and not a pure-JWT strategy).

I'm unsure what direction you want to take, so I'll just start with some suggestions. Have you tried:
- using the [JWT callback](https://next-auth.js.org/configuration/callbacks#jwt-callback) to alter what is stored as part of the JWT? This is called every time the JWT is generated, _before_ the session callback happens
- using [session callback](https://next-auth.js.org/configuration/callbacks#session-callback) to alter what is returned for `useSession` and `getSession` requests?

if you are using an adapter and rather want to change the database model of the auth data, checkout the [adapter docs](https://next-auth.js.org/adapters/overview) that go into detail on how to change the db models per supported adapter type.

Does any of this help? If so: Which one is the thing you wanted to do?

**Comment by BracketJohn** [comment]
Hey @jorgv, Hey @darwebdb,

this is a question that has been answered by @JoaoPedroAS51 here: https://github.com/sidebase/nuxt-auth/issues/61#issuecomment-1330946022

It will also be part of our documentation once #90 is merged: https://sidebase.io/nuxt-auth/recipes/custom-session-data

I'm closing this issue for now, please open a new one if there's any further need for clarification (: 

Thanks to both of you (:
