### ISSUE TITLE
How to understand which provider was used

### ISSUE THREAD

**Issue by vazgen** [sidebase/nuxt-auth#292]
### Ask your question

There are google and facebook providers in my application. How to understand which provider was using for login?

thank you

### Additional information

I do not store logged user into the database, I use external API which stores user info. So I want to be able to register the user and add info which provider was used for login.

**Comment by vanling** [comment]
@vazgen 

You could check out the callback section

```
callbacks: {
  async jwt({ token, user, account }) {
    console.log(token, user, account)
    return Promise.resolve(token)
  },
  async session({ session, token, user, profile }) {
    console.log(session, token, user, profile)
    return Promise.resolve(session)
  },
}
```

Not 100% sure, but I think provider is added in account.

**Comment by vazgen** [comment]
thank you, it works fine! `account` has provider and provider token.
