### ISSUE TITLE
Upgrade from next-auth to @authjs

### ISSUE THREAD

**Issue by SaraVieira** [sidebase/nuxt-auth#295]
### Describe the feature

Right now nuxt auth needs next auth to run and one big issue with it is that next auth is not supported on cloudflare workers, something they have fixed in https://authjs.dev/.

I was wondering if there are plans to migrate to use authjs under the hood.

Thank you!

### Additional information

Reference issue on the next auth repo 

https://github.com/nextauthjs/next-auth/issues/725#issuecomment-1419010387

**Comment by zoey-kaiser** [comment]
See #117!

**Comment by SaraVieira** [comment]
Oh sorry, should have seen that
