### ISSUE TITLE
AUTH_ORIGIN overrides

### ISSUE THREAD

**Issue by drusellers** [sidebase/nuxt-auth#296]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `pnpm@7.30.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `experimental`, `app`, `modules`, `css`, `postcss`, `auth`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@sidebase/nuxt-auth@0.4.4`
- Build Modules:    `-`

### Reproduction

```sh
git clone git@github.com:sidebase/nuxt-auth-example.git
cd nuxt-auth-example
echo 'shamefully-hoist=true' > .npmrc
echo 'auto-install-peers=true' >> .npmrc
pnpm install
# edit nuxt.config.ts to point origin to https://a-website.com
pnpm run build
NUXT_SECRET=a-secret AUTH_ORIGIN=https://b-website.com PORT=3003 node .output/server/index.mjs
```

in another terminal run

```
curl -I localhost:3003/protected/globally
```

In the server console you should see

```
Listening http://[::]:3003
[nuxt] [request error] [unhandled] [500] request to https://a-website.com/api/auth/session?callbackUrl=http://localhost:3003/protected/globally failed, reason: getaddrinfo ENOTFOUND a-website.com (https://a-website.com/api/auth/session?callbackUrl=http://localhost:3003/protected/globally)
```

Note that the request to `https://a-website.com` 

### Describe the bug

It looks like the AUTH_ORIGIN env var is not overriding the nuxt.config.ts value.

**Comment by BracketJohn** [comment]
Hey @drusellers!

I just tried this and it didn't reproduce - could you provide a repro repo?

Checkout my logs (or lack thereof):
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/25911230/229522337-b7ab9569-4efb-4b8e-b379-836593e76e80.png">

**Comment by BracketJohn** [comment]
closing this now as no more information arose and no working reproduction exists.

Do comment with a reproduction to re-open it or open a new issue in the future!

**Comment by drusellers** [comment]
Sorry for the delay, I was out on leave.

Here is a loom video (English) - https://www.loom.com/share/c7775352f3c34789b779f834d2d77f2e

And here is the github reproduction repository.
https://github.com/drusellers/nuxt-auth-example
