### ISSUE TITLE
Dynamic root route

### ISSUE THREAD

**Issue by andreasvirkus** [sidebase/nuxt-auth#297]
### Ask your question

Hi team,

I'm a little confused how could I make a dynamic root route (`/`) work in Nuxt 3 based on the session status? I'd like to keep my public and guarded navbar and other components in separate pages and not switch between them with `v-if` in my templates - is there a best practise to achieve this?

**Comment by zoey-kaiser** [comment]
Hi @andreasvirkus 👋 

Is there a specific reason you want to avoid `v-if`?
I would personally split the two "views" into separate components and then have a single `v-if` to keep the page structured nicely. Don't forget to deactivate the global middle ware in case you have it on :)

**Comment by andreasvirkus** [comment]
I guess the biggest reason was code organization - I didn't like having "pages" in my components directory, just a separation of concerns thingy 🤷‍♀️ I'll go with the `v-if` for now then.

**Comment by andreasvirkus** [comment]
Just wanted to update that using [Layouts](https://nuxt.com/docs/guide/directory-structure/layouts#setting-another-layout) in Nuxt seems to be a clean way to achieve what I wanted (& a best-practise, as docs also mention session-based state there)
