### ISSUE TITLE
Session initial state missing from client

### ISSUE THREAD

**Issue by andreasvirkus** [sidebase/nuxt-auth#298]
### Ask your question

Hello, atm after authenticating (via the SlackProvider provided by `next-auth/providers/slack`), every time I reload a page, the initial session state is missing and I'd have to manually call `getSession` - this means when a user reloads on an authenticated route, they get redirected to the login page. But if I go to a public page and visit a `<NuxtLink>`, then I can still access the protected routes 🤔 

Also when I'm on a public route, the `state` from `useSession` is `unauthenticated` on the client side until I call `getSession` and only then it updates.

Here's my auth handler:
```js
// server/api/auth/[...].ts
import { NuxtAuthHandler } from '#auth'
import SlackProvider from 'next-auth/providers/slack'

export default NuxtAuthHandler({
  secret: process.env.AUTH_SECRET,
  pages: {
    signIn: '/login',
  },
  providers: [
    SlackProvider.default({
      clientId: process.env.SLACK_CLIENT_ID,
      clientSecret: process.env.SLACK_CLIENT_SECRET,
    }),
  ],
})
```

**Comment by zoey-kaiser** [comment]
Hi @andreasvirkus 👋 

That should definitely not be the expected behavior! Nothing initially comes to mind and your NuxtAuthHandler looks good! Can you by any chance share more parts of the project? Otherwise it could also be helpful to compare your setup to our https://github.com/sidebase/nuxt-auth-example, as I do know this project setup is working correctly!

**Comment by andreasvirkus** [comment]
Will try to modify the example project to replicate the issue as soon as I have a free moment

**Comment by andreasvirkus** [comment]
When just swapping out the NuxtAuthHandler to use the Slack provider instead, this same issue can be replicated in the `nuxt-auth-example` repo - here's a recording as proof (GitHub onlly allows 10MB sorry)

https://drive.google.com/file/d/1T1VzyHAyyV3VSxhoHn7I6zaqCwtT_aSo/view?usp=sharing

**Comment by andreasvirkus** [comment]
It works now magically. It seems that adding `AUTH_ORIGIN` in local env fixed it? 🤔
