### ISSUE TITLE
How do I style/change the signin page?

### ISSUE THREAD

**Issue by Explosion-Scratch** [sidebase/nuxt-auth#299]
### Ask your question

<img width="751" alt="image" src="https://user-images.githubusercontent.com/61319150/228265979-a9078815-1a0e-48d4-8e62-d967270f9963.png">
This signin page doesn't fit with my project, how can I style it? I don't see layout for this page anywhere, and the only styling possibilities seem to be through adding a style attribute to the `CredentialsProvider.default` call.

**Comment by chenyuncai** [comment]
you can manual write your own login page or component and invoke login action whenever you want.
```
const { signIn } = useSession()

// some button click action
const submitOnClick = async () => {
  await signIn('credentials', {
    username: form.value.email,
    password: form.value.password,
    redirect: true,
    callbackUrl: ’last page location or just home like "/"‘
  })
}

```

**Comment by zoey-kaiser** [comment]
Hi @Explosion-Scratch 👋 

As @chenyuncai mentioned you would need to write a custom signin page. See more information about this here on our docs to help you get started!

https://sidebase.io/nuxt-auth/application-side/custom-sign-in-page

**Comment by Explosion-Scratch** [comment]
Thanks for the help guys! Appreciate it! Sorry for not seeing the docs! I thought I checked 😐

**Comment by Explosion-Scratch** [comment]
I know this is unrelated but these AI tools are getting insane:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/61319150/228562951-d4ebe482-046b-4145-bedd-f102619ef925.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/61319150/228563074-fab70aea-d51e-479c-acd5-a74a0514e017.png">
<img width="821" alt="image" src="https://user-images.githubusercontent.com/61319150/228563196-f1e15b56-d0b8-4936-8346-e20207bb8052.png">
<img width="553" alt="image" src="https://user-images.githubusercontent.com/61319150/228563345-48261d98-b6b9-47dc-98c6-5516f9ff1f4f.png">

(minor tweaks, like 5 mins of styling, padding, <hr> element and github icon)
<img width="431" alt="image" src="https://user-images.githubusercontent.com/61319150/228565987-aa8bc7c0-4e48-4bc1-aff2-d4ab887accb1.png">

**Comment by zoey-kaiser** [comment]
Looking really nice @Explosion-Scratch 😊
