### ISSUE TITLE
How to change path of rest api default ( get sesstion)

### ISSUE THREAD

**Issue by vnphu** [sidebase/nuxt-auth#310]
### Ask your question

How to change path of rest api default ( get sesstion)

### Additional information

<img width="585" alt="image" src="https://user-images.githubusercontent.com/50934312/230247091-d4145922-dc1c-4565-bac3-8587b31c2b99.png">

**Comment by BracketJohn** [comment]
You can change it by modifying the  `basePath` in the nuxt.config.ts + then locating the  `NuxtAuthHandler` at the place you defined as a base url.

See https://sidebase.io/nuxt-auth/configuration/nuxt-config#basepath for more.

Have a good weekend!
