### ISSUE TITLE
fetch failed - nuxt 3 and credentials or strapi auth

### ISSUE THREAD

**Issue by titogarrido** [sidebase/nuxt-auth#312]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `modules`, `image`, `app`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@nuxt/image-edge@1.0.0-27840416.dc1ed65`, `@sidebase/nuxt-auth@0.5.0-rc.0`, `nuxt-swiper@1.1.0`
- Build Modules:    `-`
------------------------------

### Describe the bug

I am trying to implement a credential login using FastAPI as my backend authentication and authorization provider. I was using the strapi example provided [here](https://sidebase.io/nuxt-auth/recipes/strapi) as a implementation sample for me. 

The issue is when I try to run a fetch request to my backend I am receiving a `"http://localhost:3000/api/auth/error?error=fetch%20failed"` and there is no call to my backend.

To understand the process I have also installed strapi on my machine and used the following code:
```
// file: ~/server/api/auth/[...].ts
import { NuxtAuthHandler } from "#auth";
import GoogleProvider from "next-auth/providers/google";
import CredentialsProvider from "next-auth/providers/credentials";

export default NuxtAuthHandler({
  pages: {
    // Change the default behavior to use `/login` as the path for the sign-in page
    signIn: "/user/login",
  },
  secret: "your-secret-key",
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    GoogleProvider.default({
      clientId:
        "xxxx.apps.googleusercontent.com",
      clientSecret: "xxxx",
    }),
    // @ts-ignore Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
    CredentialsProvider.default({
      name: "Credentials",
      credentials: {}, // Object is required but can be left empty.
      async authorize(credentials: any) {
        const response = await $fetch(`http://localhost:1337/api/auth/local/`, {
          method: "POST",
          body: JSON.stringify({
            identifier: credentials.username,
            password: credentials.password,
          }),
        });
        if (response.user) {
          const u = {
            id: response.id,
            name: response.user.username,
            email: response.user.email,
          };
          return u;
        } else {
          return null;
        }
      },
    }),
  ],
});
```

And I have got the same error. I am attaching a print screen.

### Additional context

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/333484/230743534-73f330ec-12e4-429a-aae2-25b18a627159.png">

**Comment by alphaelf** [comment]
hi @titogarrido can you provide your `/user/login` page code?
or is there any error says `InvalidUrl`

**Comment by BracketJohn** [comment]
Hey @titogarrido - as @alphaelf said: Please provide code, ideally a full minimal reproduction (see https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction). Doing this properly is the only way to guarantee that we can help you.

Also: Thanks for already jumping in here @alphaelf ❤️ 💯

**Comment by titogarrido** [comment]
Hi Guys,

I ended up losing my environment. Anyway I was using the default login page from the module.

I will try to create the environment again using StackBlitz.

**Comment by BracketJohn** [comment]
Error could lie in many olaces! One thing you could try (if you are advanterous, its alpha stuff): v0.6 introduces a native, static local-auth provider that should deastically simplify the credentials flow you are trying to implement here!

**Comment by alphaelf** [comment]
error is in h3 server, when you use custom login page, the `signIn` method sends credentials via `application/x-www-form-urlencoded` and in h3 `readBody` method return all values as string or string array so when you send `callbackUrl` as `undefined` the `readBody` return it as string and nuxt-auth recognize it as url and send `undefined` string to `createUrl` method and it makes error `Invalid Url`.
i report this [issue](https://github.com/unjs/h3/issues/275#issuecomment-1509556375) in h3 repo but i think that i reported it badly

**Comment by BracketJohn** [comment]
Alright, thanks!

Let us know here or in a new issue if something nuxt-auth specific comes up again (:
