### ISSUE TITLE
Using Nuxt Auth to SSO into Auth0, but JWT is not usable to call backend (remote) api

### ISSUE THREAD

**Issue by dstrickland67** [sidebase/nuxt-auth#314]
### Ask your question

I feel like I must be missing something. ( In a former life, I used nuxt 2 / nuxt auth similarly).

We are using Auth0 to provide SSO security to google.  (https://admin.test.com)

We hope to grab the JWT from the SSO and then re-use the same JWT when call out backend API which can validate Auth0 JWTs.  ( https://api.test.com )

As described in the documentation, I can grab the with getToken({event}).

```
// file: ~/server/api/token.get.ts
import { getToken, getServerSession } from '#auth'
export default eventHandler(async (event) => {
  const session = await getServerSession(event)
  const token = await getToken({ event })
  console.log('SESSION: ')
  console.dir(session)
  console.log('END SESSION')
  console.log('token: ')
  console.dir(token)
  console.log('END token')
  // console.log(token)
  return token
})
```

I am expecting to see some base64 string when I get a token, but I get a parsed JSON object.  

Next I followed the docs on NextJS to provide a call back for JWT

` callbacks: {
    async jwt ({ token, account, profile }) {
      // Persist the OAuth access_token and or the user id to the token right after signin

      if (account) {
        console.log('FULL_TOKEN: ' + token)
        console.dir(token)
        // eslint-disable-next-line no-console
        console.log('FROM SERVER JWT_TOKEN: ' + account.access_token)
        // eslint-disable-next-line no-console
        console.log('FROM SERVER profile: ', profile)
        token.accessToken = account.access_token
        // token.id = //profile?.id
      }
      return token
    }

  },`

The server JWT_token looks promising 

`eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYtdGR1dWdsZ3lxaHBqbXpkay51cy5hdXRoMC5jb20vIn0..EjTju0JhfGLAvvXm.eQjJcxc7W-RNwQXm4Qp-FaBB-rPDKN4yFy1YkFF_Ram_k45XymWhmmVl2r6WDzan691X9TFx3E4pHcNqF6vxkqyo1n9R6EdSjsjT2G4dq1D_Vxlqj2xuqwMDUUlhzXf48PDQqKcZPCpSOU0x8KdA6ApMsXgGi8wZdLWEcDsVetqCLR1gBsSP8UG3eH6OAnJYw8ADu9TM-hjuUATPRa7A0DgQyaRMLOlTIuYez03lSkoyZEMZsDirAQYOi2XLdICTH4WQ8gUJbG4lRR45tnfV1mgJILOm5IB22B4tSCZXkmLNWMw4sHfdfSCRtLpEz7IZpJkK7imWUJmC5JiXpxlGvcox7XqKCUQ.zpXBCSaEv4xpHASv4q53qQ`

When I use the jwt.io decoder, it says there is no encoded json.
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/3538674/230905022-d40a840e-cb6c-43d8-b4c3-9eea3e67f2e4.png">

The parsed JWT is interesting from a UI perspective, but I also need the AUTH0 jwt unchanged to pass it along to our backend services.

Many thanks for any help.

**Comment by dstrickland67** [comment]
Just one additional comment here.   We have an admin site that is currently based on remix.  It gets the JWT (same Auth0 APP endpoint).  We are moving to nuxt because it is way simpler to turn out apps, but have to resolve this before we can move ahead.   Thanks.

**Comment by miestassimon** [comment]
Hi. Check this link. You can set up a callback in `NuxtAuthHandler` and pass your JWT token to the `token` or `session` object. I don't know where would be better to store it. I've faced with the same problem and solved it by that approach. 

https://sidebase.io/nuxt-auth/recipes/custom-session-data#add-callbacks-to-the-nuxtauthprovider-to-alter-the-session-data

**Comment by BracketJohn** [comment]
This is the right approach, thanks @miestassimon 

Closing as it was answerred!
