### ISSUE TITLE
How to redirect with a custom page

### ISSUE THREAD

**Issue by krxdow** [sidebase/nuxt-auth#315]
### Ask your question

Hi everyone

I try to custom my login page with adaptive callback, by default without a custom page it's work

for example when I add this in a vue pages  **/pages/example.vue**
``` javascript
<template>
    <h1>Example Test</h1>
</template>
<script lang="ts" setup>

definePageMeta({
    middleware: "auth",
});

</script>

```

I have my default login vue 
![authDefault](https://user-images.githubusercontent.com/10833493/231197046-6d8457d0-c615-443a-af7d-783775c65c10.png)

After sign in , I'm automatically redirected to /pages/example.vue
![authDefault2](https://user-images.githubusercontent.com/10833493/231201059-f2d5a2b6-ae93-4771-8b13-c09936582d4f.png)

I try to have the same behavior  with a custom login 
So To customize the login page, in server/api/auth/[...].ts file, I add this 

```javascript
export default NuxtAuthHandler({
    pages: {
        signIn: '/login',
    },
)}
```

Also, I add pages/login.vue 

```javascript
<template>
    <div>
        <button @click="signIn('github',{callbackUrl:'/example'})">
            Sign in with github
        </button>
        <br>
        <input v-model="username" type="text" placeholder="username (jsmith)">
        <input v-model="password" type="password" placeholder="password (hunter2)">
        <br>
        <button @click="signIn('credentials', {username, password, callbackUrl: '/exemple' })">
            Sign in with username and password
        </button>
        <br>
        <button @click="mySignInHandler({ username, password, callbackUrl: '/exemple' })">
            Sign in with username and password using a custom sign in handler
        </button>
    </div>
</template>

<script setup lang="ts">


import { ref } from 'vue'
import { definePageMeta, useAuth, navigateTo } from '#imports'

definePageMeta({ auth: false })

const username = ref('')
const password = ref('')

const { signIn } = useAuth()

const mySignInHandler = async ({ username, password, callbackUrl }: { username: string, password: string, callbackUrl: string }) => {
    const { error, url } = await signIn('credentials', { username, password, callbackUrl, redirect: false })

    if (error) {
        // Do your custom error handling here
        alert('You have made a terrible mistake while entering your credentials')
    } else {
        // No error, continue with the sign in, e.g., by following the returned redirect:
        return navigateTo(url, { external: true })
    }
}
</script>

```
I try to make something more generic with my custom login page
Does anyone have a suggestion?

**Comment by BracketJohn** [comment]
What are you trying to achieve? Does the callbackURL not work as expected? If that's the case: Please provide a reproduction.

if it's something different: Please ask a more specific question or elaborate, I don't quite get what you mean with "elegant" here

**Comment by krxdow** [comment]
Sorry, it is true that my question is not clear
In fact, I simply go through a personalized login page
and have the right redirection without having to specify the callback option in the signIn function.
So that you can reuse the login.vue page

When I don't use a custom page login, and when I click to sign with a provider or credential, I have a good redirection

I try to make the same behavior with a custom login page

**Comment by BracketJohn** [comment]
Thanks for elaborating - can you please probide a reproduction?

**Comment by krxdow** [comment]
## reproduction
### without a custom login page

/pages/example.vue file
```html
<template>
    <h1>Example Test</h1>
</template>
<script lang="ts" setup>

definePageMeta({
    middleware: "auth",
});

</script>
```

server/api/auth/[...].ts

```javascript
import CredentialsProvider from 'next-auth/providers/credentials'
import GithubProvider from 'next-auth/providers/github'


import {NuxtAuthHandler} from '#auth'
import PrismaAdapter from '@next-auth/prisma-adapter'
import * as Prisma from "@prisma/client"

const prisma = new Prisma.PrismaClient()

export default NuxtAuthHandler({
    // A secret string you define, to ensure correct encryption
  //  adapter: PrismaAdapter(prisma),
    
    secret: process.env.AUTH_SECRET ?? 'test-123',
    providers: [
        // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
        GithubProvider.default({
            clientId: process.env.GITHUB_CLIENT_ID,
            clientSecret: process.env.GITHUB_CLIENT_SECRET

        }),

        // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
        CredentialsProvider.default({
            // The name to display on the sign in form (e.g. 'Sign in with...')
            name: 'Credentials',
            // The credentials is used to generate a suitable form on the sign in page.
            // You can specify whatever fields you are expecting to be submitted.
            // e.g. domain, username, password, 2FA token, etc.
            // You can pass any HTML attribute to the <input> tag through the object.
            credentials: {
                username: {label: 'Username', type: 'text', placeholder: '(hint: jsmith)'},
                password: {label: 'Password', type: 'password', placeholder: '(hint: hunter2)'}
            },
            authorize(credentials: any) {
                // You need to provide your own logic here that takes the credentials
                // submitted and returns either a object representing a user or value
                // that is false/null if the credentials are invalid.
                // NOTE: THE BELOW LOGIC IS NOT SAFE OR PROPER FOR AUTHENTICATION!

                const user = {id: '1', name: 'J Smith', username: 'jsmith', password: 'hunter2'}

                if (credentials?.username === user.username && credentials?.password === user.password) {
                    // Any object returned will be saved in `user` property of the JWT
                    return user
                } else {
                    // eslint-disable-next-line no-console
                    console.error('Warning: Malicious login attempt registered, bad credentials provided')

                    // If you return null then an error will be displayed advising the user to check their details.
                    return null

                    // You can also Reject this callback with an Error thus the user will be sent to the error page with the error message as a query parameter
                }
            }
        })
    ],
})
```
When to navigate to **http://localhost:3000/example**
![authDefault](https://user-images.githubusercontent.com/10833493/231310745-c999b6fe-f216-44ed-9010-02060772a17c.png)

And after sign in with GitHub provider or credential , I come back in /pages/example.vue
![authDefault2](https://user-images.githubusercontent.com/10833493/231311197-8c172e4e-e048-44a4-aa11-8e9839d88b64.png)

---
## With a custom login page
I try to have the same thing with a custom login page

/pages/login.vue

```html
<template>
    <div>
        <button @click="signIn('github')">
            Sign in with github
        </button>
        <br>
        <input v-model="username" type="text" placeholder="username (jsmith)">
        <input v-model="password" type="password" placeholder="password (hunter2)">
        <br>
        <button @click="signIn('credentials', {username, password })">
            Sign in with username and password
        </button>
        <br>
        <button @click="mySignInHandler({ username, password, callbackUrl:'' })">
            Sign in with username and password using a custom sign in handler
        </button>
    </div>
</template>

<script setup lang="ts">


import { ref } from 'vue'
const route = useRoute();

definePageMeta({ auth: false })

const username = ref('')
const password = ref('')

const { signIn } = useAuth()
const mySignInHandler = async ({ username, password, callbackUrl }: { username: string, password: string, callbackUrl: string }) => {
    const { error, url } = await signIn('credentials', { username, password, callbackUrl, redirect: false })

    if (error) {
        // Do your custom error handling here
        alert('You have made a terrible mistake while entering your credentials')
    } else {
        // No error, continue with the sign in, e.g., by following the returned redirect:
        return navigateTo(url, { external: true })
    }
}
</script>
```

And in a server/api/auth/[...].ts file i add

export default NuxtAuthHandler({
    ...
    pages: {
        signIn: '/login',
    },
...
})

So when I navigate to http://localhost:3000/example
![authDefault4](https://user-images.githubusercontent.com/10833493/231312160-086bcbd4-7847-4e97-89cc-8d8b737af0b6.png)

**Comment by BracketJohn** [comment]
Hey @krxdow  👋 

thanks for the really thourough steps. However, a reproduction needs a repo and a small amount of commands to actually reach the error. Read here for more: https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction

Sorry for being so pedantic about this, but if we would reproduce every 10 step guide that is given to us by hand, we wouldn't be able to fix any issues anymore.

**Comment by krxdow** [comment]
hi @BracketJohn 

Minimal Reproduction  StackBlitz or CodeSandbox doesn't work with auth system, 
 it seems to have confusion with the address of origin, in the variables of the environment

So i pushed in a github repository  a Minimal Reproduction
https://github.com/krxdow/TestRedirection/tree/a2b82c8103966c587522765bddc9fe9a00d72fec

and below if you need, I have attached the zipper project
[TestRedirection-master.zip](https://github.com/sidebase/nuxt-auth/files/11217391/TestRedirection-master.zip)

**Comment by krxdow** [comment]
hi @BracketJohn @PersistentFK 
It's not perfect but I found a patch that allows my custom login page to have [default](https://next-auth.js.org/getting-started/client#specifying-a-callbackurl) behavior.
that's to say
By default, redirected to the URL of the page from which the connection is initiated, specifying a callbackUrl with useRouter() function; **_route.getRoutes().at(0).path_**

```html 
<template>
 <button @click="signIn('credentials',
             {username, password , redirect:true,callbackUrl:route.getRoutes().at(0).path })">
            Sign in with username and password
        </button>
</template>

<script setup lang="ts">
...
const route = useRouter();
...
</script>
```

this way i can reuse my custom login page to access the protected page

**Comment by tcarterBAMF** [comment]
I'm still using `0.4.4`, and what is working for me to have my custom login page redirect to the original protected page is to thread the `?callbackUrl=...` query param (since that is being set correctly) to the login page to the `signin()` function.

Would it be possible for `signin()` to automatically pick up a `?callbackUrl=...` query param?  Maybe it's best to keep it explicit and document it this requirement for custom login pages.


```vue
<template>
 <button @click="signIn('azure-ad',
             { callbackUrl: route.query.callbackUrl })">
            Sign in
        </button>
</template>

<script setup lang="ts">
...
const route = useRouter();
...
</script>
```

**Comment by krxdow** [comment]
Thank you @tcarterBAMF for the tip, 
I agree that is the best way to have my custom login page redirect to the original protected page

**Comment by crunchwrap89** [comment]
Hi,
I also have the same issue.
Using a custom login page will break the redirect.

**Comment by guesant** [comment]
@PersistentFK 

> I am having the same problem as the topic starter. Auth login works with the default one, but when I try to create custom one according to the docs, I fail with the form just clearing itself out with no errors.

I'd think you forgot to preventDefault the event

```
@submit.prevent="handler"
```

or

```
handler(e) {
  e.preventDefault();
}
```

---

For people using v0.6, there is some hints:

https://github.com/academic-tasks/academic-tasks-frontend/blob/nuxt/nuxt.config.ts#L51-L63

https://github.com/academic-tasks/academic-tasks-frontend/blob/nuxt/composables/useAuthSignInCallbackUrl.ts#L1-L13
