### ISSUE TITLE
Example of using it with Laravel JWT

### ISSUE THREAD

**Issue by IsidroMar95** [sidebase/nuxt-auth#32]
### Describe the feature

Any idea or any example of how can be implemented with Laravel JWT? I was using [Laravel JWT](https://auth.nuxtjs.org/providers/laravel-jwt) provider of Nuxt Auth, and was super easy to implement, but now i do not know how to implement with this awesome module.

**Comment by BracketJohn** [comment]
Hey @IsidroMar95!

First: Thanks @zoey-kaiser for the research here (: I think the stsckoverflow approach you found looks promising!

Can you make it work @IsidroMar95 / have you already tried? If you succeed we could add it to our docs as an example (: I know that there's others that are very interested in this. 

Do let us know here if you need more help OR please share code snippets if you've got something that works.

**Comment by BracketJohn** [comment]
To use Laravel JWT you'll need to:
1. Use the credentials provider and then do an API-call to Laravel JWT using `$fetch`
2. Alter the callback hook `jwt` to add the Laravel JWT into the `nuxt-auth` JWT

These steps are similar to the ones required for strapi and for directus to work.

Checkout our recipes for them here: https://sidebase.io/nuxt-auth/recipes/strapi. You should be able to follow + adapt them for your use-case.

I've added your documentation request to #30 to track it there and am closing this issue now. Thanks for opening it + feel free to reach out on discord or maybe even open a PR to contribute a laravel JWT recipe if you've figured it out.
