### ISSUE TITLE
App without any login page: Cannot remove auto-generated login page by nuxt-auth

### ISSUE THREAD

**Issue by mkierdev** [sidebase/nuxt-auth#320]
### Describe the bug

Even ff we do not use build-in login page, it is always generated by nuxt-auth and cannot remove it. 

Moreover, if we use custom login-page or just use signIn function, URL to the generated page is returned in providers call (when users signs in). Then user can inspect its URL and enter that page (which for obvious reasons I would not like to show it).

There should be an option to enable "custom mode" where we are making use of composables to signIn / signOut without worrying about built-in pages.

**Comment by TutorFx** [comment]
Did  you tryed this?
```js 
//server/api/auth/[...].ts
export default NuxtAuthHandler({
  pages: {
    signIn: '/login',  // Route of your log in page
  },
})
```

**Comment by mkierdev** [comment]
I did now but it has to be a route, it cannot be null or false.
My use case is that I do not have any login page (it's not that rare after all)

Not ideal, but I ended up with this solution: create /auth/signin/[...].ts file in which 404 error is returned.

**Comment by BracketJohn** [comment]
>  My use case is that I do not have any login page (it's not that rare after all)

very rare indeed!

> Not ideal, but I ended up with this solution: create /auth/signin/[...].ts file in which 404 error is returned.

smart! 

As this is quite a rare use-case I'd close this issue with this workaround being present. People should be able to find this issue (I've updated it's title). If you want, you could add this to the docs somewhere (: Closing the issue for now!
