### ISSUE TITLE
Provide nuxt-based auth-pages to avoid wrongful xss detection (e.g. with nuxt-security) 

### ISSUE THREAD

**Issue by tmlmt** [sidebase/nuxt-auth#324]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `app`, `extends`, `appConfig`, `css`, `postcss`, `build`, `modules`, `runtimeConfig`, `auth`, `content`, `i18n`, `image`, `nitro`, `routeRules`, `robots`, `security`, `vite`
- Runtime Modules:  `@sidebase/nuxt-auth@0.4.4`, `@nuxtjs/i18n@8.0.0-beta.11`, `@pinia/nuxt@0.4.8`, `@vueuse/nuxt@9.13.0`, `@nuxt/image-edge@1.0.0-28020728.5df24eb`, `@nuxt/content@2.5.2`, `nuxt-simple-sitemap@2.4.11`, `nuxt-simple-robots@2.1.1`, `nuxt-og-image@2.0.0-beta.15`, `nuxt-security@0.13.0`
- Build Modules:    `-`

### Reproduction

Will prioritize making one if you can't point out to the cause straight away

### Describe the bug

Both sign in and out, which used to work a unknown amount of commits / deps bumps (should implement some more testing 🙈), do not work with nuxt-auth@0.4.4 and next-auth@4.22.0. 

1. Sign-in doesn't work, the call to signIn fails with a 500 error:

![image](https://user-images.githubusercontent.com/10244927/231992829-50e356af-e63a-42b9-8fd9-b48cc3e1bc66.png)

2. On a signed-in state (which I was in before I cleared my browser's cache to try out), after confirming that I want to sign-out on the splash page, I get a 500 error, and my session stays connected.

![image](https://user-images.githubusercontent.com/10244927/231990263-15ae83d8-0434-4259-8bfb-83ad73abcaa0.png)

```
[nuxt] [request error] [unhandled] [500] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Promise
  at new NodeError (node:internal/errors:387:5)  
  at Function.from (node:buffer:328:9)  
  at readRawBody (./node_modules/h3/dist/index.mjs:280:53)  
  at readBody (./node_modules/h3/dist/index.mjs:306:22)  
  at readBodyForNext (./.nuxt/dev/index.mjs:501:18)  
  at getInternalNextAuthRequestData (./.nuxt/dev/index.mjs:584:24)  
  at ./.nuxt/dev/index.mjs:596:31  
  at ./node_modules/h3/dist/index.mjs:1189:14  
  at Object.handler (./node_modules/h3/dist/index.mjs:1432:12)  
  at Object.handler (./node_modules/h3/dist/index.mjs:1247:31)
```

### Additional context

My `/api/auth/[...].ts` contains a NuxtAuthHandler with a CredentialsProvider
The call to sign out is very basic: 
```
await signOut()
``` 
and the signIn() call consists in sending those credentials:
```
  const { error, status } = await signIn("credentials", {
    email: email.value,
    password: password.value,
    redirect: false,
  });
```

**Comment by BracketJohn** [comment]
> Both sign in and out, which used to work a unknown amount of commits / deps bumps (should implement some more testing 🙈), do not work with nuxt-auth@0.4.4 and next-auth@4.22.0.

to quickly fix this for you: have you looked at whether your deps in the lock-file were (accidentaly) updated in the commit(s) that broke this?

Other than that: sadly no immeadiate idea, so please go ahead and provide a minimal repro. You can find a guide + nuixt starters for this here: https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction

**Comment by halindraprakoso** [comment]
I hav the same issue.

repro: https://stackblitz.com/edit/github-xp4wje

**Comment by tmlmt** [comment]
@BracketJohn thanks for your message. Let's try to make a repro then !

@halindraprakoso could you describe your issue? Not sure these are the same. When I run your repro on Stackblitz with Chromium, when I sign in I get error, at it seems like we're being redirected to `http://localhost:3000/api/auth/callback/credentials` which obviously is not right, as we should be redirected relative to the repo's base url. 
@BracketJohn by the way, that's the same behavior I have when I just open and run your own example repo: https://stackblitz.com/github/sidebase/nuxt-auth-example/tree/main/

**Comment by BracketJohn** [comment]
Thank you fore the repo ❤️ 

Steps I took:
1. opened it on stackbliz
2. click "download project"
3. npm i
4. npm run dev
5. open `localhost:3000`, click sign in
6. enter `jsmith` and `hunter2` as username and password
7. click sign in -> it works

Screenshot of cookies:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25911230/232208941-d47a8b67-898a-45f5-8f05-3fb7495bbc87.png">

@halindraprakoso I think the problem here rather lies with stackblitz -> it has wonky / bad support for cookies. See e.g., @danielroe's comment here: https://github.com/nuxt/nuxt/issues/20030#issuecomment-1493346372

so, I agree with @tmlmt -> this is likely something else. @tmlmt have you gotten around to provide a repro of your issue? Due to the cookie issues with stackblitz it's best if you also check that the problem occurs in your local development

**Comment by tmlmt** [comment]
Thanks for the follow up @BracketJohn! Note taken about having to test locally instead of Stackblitz.
I will most likely have little time this weekend, but I'll report here as soon as I've investigated further.

**Comment by BracketJohn** [comment]
Sure thing - no worries! I'll wait around a bit to get the reproduction from you (: 

Yeah - the stackblitz cookie thing is quite unfortunate and an easy trap to fall into.

**Comment by halindraprakoso** [comment]
@tmlmt @BracketJohn 
oh, I see! The reason I used stackblitz was 'cause' I was able to reproduce the exact error message right away, not realizing that cookie support can be rather wonky

I actually managed to figure out that my issue is that something seems to be conflicting with nuxt-security,  https://github.com/baroshem/nuxt-security.

**Comment by tmlmt** [comment]
Hey guys, so I've taken some time to investigate, and also narrowed down to see that the change happened after the commit where I introduced `nuxt-security`. Indeed, disabling `xssValidator` with the following ...
```
security: {
  xssValidator: false,
  // ... rest of your nuxt-security config
}
```
... authentication (sign in/out) works again.

[XSS Validator](https://nuxt-security.vercel.app/security/xss-validator) filter things out when the body or query params of a request contains script tags, to prevent cross-scripting-attacks. In the case of nuxt-auth (next-auth), if I take the example of signing out for instance, what happens is that the call to `/api/auth/signout` returns the HTML code of a "sign-out confirmation" page. I guess that HTML code cause xssValidator to block the sign-out process. See below screenshot, where the bottom part shows the response (that HTML code) of the first GET call to the API, and the top part shows the error encountered during the POST call to the API. 

![image](https://user-images.githubusercontent.com/10244927/232324652-83df9560-f8d1-442f-b60d-4609b1c7682d.png)

@BracketJohn : 
1- I had never seen that sign-out confirmation page before (and it's the same on your [example implementation](https://nuxt-auth-example.sidebase.io/): clicking on logout immediately logs out without the confirmation step), is that something you're implemented in nuxt-auth to bypass that step which is present in next-auth? 
2- Any way we could arrange things and still enable xss protection on our apps? 

I will rename the title of this issue accordingly.

**Comment by BracketJohn** [comment]
Thanks!

I think as a workaround you can exclude the nuxt-auth specific routes from XSS checking.

Going further to actually resolve this, we'd need to provide nuxt-based pages for login, logout, ... out of the box -> this may besomething we take on in the future. This should avoid wrong detection of XSS.

**Comment by tmlmt** [comment]
Hey @zoey-kaiser, I assume you meant `Closed as not planned` and not `Closed as completed` as the issue is still valid, in the sense that you haven't provided nuxt-based pages for login, logout as mentioned in the previous message in this thread. If you confirm closing this with no further work on it, I will leave here in case it can be useful to other users, the workaround that enables `nuxt-auth` to work with `nuxt-security`: one needs to disable xss validation on the auth routes, i.e., in `nuxt.config.ts` like this:
```
  routeRules: {
    "/api/auth/**": {
      security: {
        xssValidator: false,
      },
    },
  }
```

**Comment by zoey-kaiser** [comment]
@tmlmt indeed, sorry about that! 

I am currently trying to minimize the scope of the new updates, as the amount of issues has gotten a bit out of control 😵.
Thanks for leaving the snipped on how to add `nuxt-security` to work with NuxtAuth! I will add it to the docs and credit you.
