### ISSUE TITLE
vite error: unresolved import specifier

### ISSUE THREAD

**Issue by Ferdidurke** [sidebase/nuxt-auth#333]
### Environment

@sidebase/nuxt-auth v.0.6.0-alpha.1

- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, css, runtimeConfig, vite, nitro, devtools, pwa
- Runtime Modules:  @pinia/nuxt@0.4.8, @nuxt/devtools@0.4.0, @vite-pwa/nuxt@0.0.7, @element-plus/nuxt@1.0.4, @nuxtjs/eslint-module@4.0.2
- Build Modules:    -

### Reproduction

install sidebase and import useAuth from /local/ folder

### Describe the bug

![image](https://user-images.githubusercontent.com/91009429/232714741-8ae0d074-9b05-41f3-ab7d-f7e0cb8df7c4.png)

**Comment by BracketJohn** [comment]
Hey @Ferdidurke 👋 

Thanks for the issue -> what resolved it / was the problem?

**Comment by BracketJohn** [comment]
> and import useAuth from /local/ folder

you should not import it -> you should just use the module and then `useAuth` is (magically) going to be available.

Please share more of your code or a full repo so tyhaty I can have a further look!

**Comment by Ferdidurke** [comment]
@BracketJohn yes bro, i use import from node_modules
i remove import and it works
thanks for your time
I spend a some time on trying integrate code from example folder in repo with local strategy, but after find another example in docs
if you can, i think need update examples
thanks
