### ISSUE TITLE
get provider name that logged in the user

### ISSUE THREAD

**Issue by ckouder** [sidebase/nuxt-auth#336]
### Ask your question

I need to obtain the provider name and sso-token that sign in the user to validate the user for a backend service. It seems that the `useAuth().data` does not provide any useful information. Is there any workaround?

**Comment by zoey-kaiser** [comment]
This information is inside the `account` parameter. You can access them in the callbacks and assign them as custom session data:

Callbacks docs: https://next-auth.js.org/configuration/callbacks
Typing for Account: https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/types.ts#L106
Adding custom session data: https://sidebase.io/nuxt-auth/recipes/custom-session-data

I hope this helps you!
