### ISSUE TITLE
update types annotation for useAuth hook

### ISSUE THREAD

**Issue by Ferdidurke** [sidebase/nuxt-auth#337]
### Environment

Nuxt project info:                                                                                                                                                13:49:05

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      modules, css, runtimeConfig, typescript, vite, nitro, devtools, pwa, auth, eslint
- Runtime Modules:  @pinia/nuxt@0.4.8, @nuxt/devtools@0.4.1, @vite-pwa/nuxt@0.0.7, @element-plus/nuxt@1.0.4, @nuxtjs/eslint-module@4.0.2, @sidebase/nuxt-auth@0.6.0-alpha.1
- Build Modules:    -
------------------------------

### Reproduction

set typecheck: true in nuxt.config.ts, and run build

### Describe the bug

![image](https://user-images.githubusercontent.com/91009429/233006220-2f9ec5d1-f0d6-4db6-9fd6-d84ea5b57982.png)

### Additional context

my nuxt config
`export default defineNuxtConfig({
	modules: [
		'@pinia/nuxt',
		'@nuxt/devtools',
		'@vite-pwa/nuxt',
		'@element-plus/nuxt',
		'@nuxtjs/eslint-module',
		'@sidebase/nuxt-auth',
	],
	css: ['@/assets/styles/global.scss', '@/assets/styles/normalize.css'],
	runtimeConfig: {
		mongoDbUrl: process.env.MONGO_DB_URL,
		jwtSecret: process.env.JWT_SECRET,
		publicRoutes: ['/api/auth/login', '/api/auth/register'],
	},
	typescript: {
		strict: true,
		typeCheck: true,
	},
	vite: {
		optimizeDeps: {
			include: ['jsonwebtoken'],
		},

		css: {
			preprocessorOptions: {
				scss: {
					additionalData: '@import "@/assets/styles/variables.scss";',
				},
			},
		},
		ssr: {},
		build: {
			reportCompressedSize: true,
			watch: {},
			commonjsOptions: {
				include: [/jsonwebtoken/, /node_modules/],
			},
		},
	},
	nitro: {
		plugins: ['~/server/index.ts'],
	},
	devtools: {},
	pwa: {
		registerType: 'autoUpdate',
		devOptions: {
			enabled: false,
		},
		includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.png'],
		manifest: {
			name: 'Nuxt 3 starter app',
			short_name: 'NUXT APP',
			description: 'Awesome fullstack application built with Nuxt3 + MongoDB',
			theme_color: '#ffffff',
			icons: [
				{
					src: 'icon-192x192.png',
					sizes: '192x192',
					type: 'image/png',
				},
				{
					src: 'icon-512x512.png',
					sizes: '512x512',
					type: 'image/png',
				},
				{
					src: 'icon-512x512.png',
					sizes: '512x512',
					type: 'image/png',
					purpose: 'any maskable',
				},
			],
		},
	},
	auth: {
		// @ts-ignore This layer will show a runtime-error when the other layer is loaded, as then type === 'local' is selected
		origin: 'http://localhost:3000',
		provider: {
			type: 'local',
			pages: {
				login: '/auth/login',
			},
			token: {
				signInResponseTokenPointer: '/token/accessToken',
			},
		},
		globalAppMiddleware: {
			isEnabled: true,
		},
	},
	eslint: {
		failOnError: true,
	},
});`

my header for example

`export default defineComponent({
	name: 'TheHeader',
	setup() {
		const { data: userData, signOut } = useAuth();

		const logout = (): void => {
			signOut({ callbackUrl: '/auth/login' });
		};

		return {
			userData,
			logout,
		};
	},
});`

at now i see only this params in interface useAuth:
![image](https://user-images.githubusercontent.com/91009429/233006930-29adc182-9a5f-400a-a82a-115a03073d01.png)

types in core library
![image](https://user-images.githubusercontent.com/91009429/233007253-c817c178-e278-42d1-8185-31872d062c57.png)

**Comment by BracketJohn** [comment]
Hey, thanks for the report! Should be fixed via #347, try out the `alpha.2`-version of the module to confirm (:

**Comment by Ferdidurke** [comment]
@BracketJohn it's ok, thanks!
