### ISSUE TITLE
How can I run a function after the user creates their account using oauth?

### ISSUE THREAD

**Issue by CodyBontecou** [sidebase/nuxt-auth#342]
### Ask your question

I'd like to run an HTTP request immediately after users create their accounts using an Oauth Provider alongside Prisma (using the PrismaAdapter). Is there a convenient hook or place I can do this?

**Comment by BracketJohn** [comment]
Yeah, just use one of the next auth callbacks: https://next-auth.js.org/configuration/callbacks

Thanks!
