### ISSUE TITLE
Not working well with Laravel sanctum

### ISSUE THREAD

**Issue by DarkHiito** [sidebase/nuxt-auth#345]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.20.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@8.19.4`
- Builder:          `vite`
- User Config:      `css`, `vite`, `ssr`, `modules`, `build`, `i18n`, `googleFonts`, `auth`
- Runtime Modules:  `@nuxtjs/google-fonts@3.0.0`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.6.0-alpha.1`
- Build Modules:    `-`

### Reproduction

Config the local provider on a Laravel API using Sanctum (SPA config).
```
auth: {
      baseURL: 'http://api.local.test/',
      provider: {
          type: 'local',
          endpoints: {
              signIn: { path: '/login', method: 'post' },
              signOut: { path: '/logout', method: 'post' },
              signUp: { path: '/register', method: 'post' },
              getSession: { path: '/user', method: 'get' }
          }
      }
  }
```
Using `signIn` to connect to the api
```
await signIn({
    email: email.value,
    password: password.value,
});
```
Refresh the page and see that the `/user` call returns an empty response.
And finally test the package method vs `$fetch(.., {credentials: 'include'])`
```
// Empty response
getSession().then((res) => {
    console.log(res);
});

// Returns the user object
$fetch('http://api.local.test/user', {credentials: 'include'}).then((res) => {
    console.log(res);
});
```
It's the same for the logout route, wich does not log out the user without `{credentials: 'include'}`

### Describe the bug

Hi guys, i don't know if i'm doing the right way, but i got an issue.
I'm trying to use nuxt-auth on an existing Laravel app using Sanctum from a new Nuxt 3 app.

I'm using the `local` provider, but when i use the methods `signIn`, `signOut` or `getSession`, Laravel does not retrieve the user because the credentials are not added in the request header.

When i call the same endpoints with `$fetch(..., {credentials: 'include'})`, it works well.

I assume a solution could be to add headers into `nuxt.config.ts` endpoints.

Thanks for your time !

**Comment by BracketJohn** [comment]
Hey @DarkHiito 👋 

Can you please provide basicinformation + a reproduction>?

E.g., what nuxt version, what module version, ... -> without it it is impossible for us to debug this!

**Comment by DarkHiito** [comment]
Hey @BracketJohn, I updated the issue with my env and the reproduction steps 👍

**Comment by BracketJohn** [comment]
One thing I spotted right away: the local provider expects username and password in the sign in call, not email and password (:

Other than that: Feel free to upgrade to alpha.2 released yesterday bight which already includes some fixes (see release notes)

ither than that: I'll check it out, but an actual repository with a reproduction I can run would be 100x easier to debug - if you can provide one that would be great. Otherwise I may still directly ask for one later on

**Comment by BracketJohn** [comment]
Closing as repro is missing. Feel free to re-open this with an full, working reproduction, thanks!
