### ISSUE TITLE
Avoiding getSession() function call when token is absent

### ISSUE THREAD

**Issue by tnt-freskim-veliu** [sidebase/nuxt-auth#349]
### Describe the bug

The getSession() function should not be called if the bearer token is missing, as it will result in an error. Please ensure that the bearer token is present before calling getSession() to avoid any issues. 

Also please make sure that in each request you send a header "Accept: application/json" (or maybe you can add it as an option to endpoints config).

Currently, I'm using Nuxt v3.4.2 and @sidebase/nuxt-auth  v0.6.0-alpha.2

**Comment by BracketJohn** [comment]
Good one - should be almost a one-line fix, do you want to contribute it?

I assume this is about the local provider? In that case: just add an if to the getSession func that chrcks for token existance (:

**Comment by BracketJohn** [comment]
closed via #355, thanks @tnt-freskim-veliu 🎊
