### ISSUE TITLE
More logging or debug mode that you can toggle with an environment variable

### ISSUE THREAD

**Issue by sduduzog** [sidebase/nuxt-auth#352]
### Describe the feature

After some time investigating why my nuxt app was taking long to load and finaly displays an error 500 I discovered that my docker service blocked outbound requests.

This caused the `getSession` call to hang then fail with just _fetch failed_ with no other context of the error.

**Comment by nikkorejz** [comment]
Any solution?

**Comment by sduduzog** [comment]
If you're facing any issues similar to mine, ensure that your nuxt app can connect to the database. If on docker, check how you configured your networking. That ended up being the issue for me.

**Comment by nikkorejz** [comment]
I haven't any database, I tried to impement local authentification (login/pass). In dev environment all works fine, but in docker's container I got 500 error. Could you tell more about docker network configuration, please?

**Comment by sduduzog** [comment]
@zoey-kaiser Thanks for the reply. I think I should have closed this a long time ago. The issues I needed logged at the time turned out to be coming from an upstream dependency, next-auth. So with that in context, its fair to not action this issue.
