### ISSUE TITLE
The nuxt-auth@0.6.0-alpha.2 is not awaiting for the joinPathToApiURLWN on signinUrl of authjs (auth middleware / useAuth / signIn).

### ISSUE THREAD

**Issue by guesant** [sidebase/nuxt-auth#359]
### Environment

Nuxi 3.4.2                                                                                               17:46:15
                                                                                                         17:46:15
RootDir: /mnt/tiedot/projetos/academic-tasks/academic-tasks-frontend                                     17:46:15
Nuxt project info:                                                                                       17:46:15

------------------------------
- Operating System: Linux
- Node Version:     v18.12.1
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@8.19.2
- Builder:          vite
- User Config:      runtimeConfig, modules, vite, css, build, auth, graphql-client
- Runtime Modules:  @vueuse/nuxt@10.1.0, nuxt-graphql-client@0.2.27, @sidebase/nuxt-auth@0.6.0-alpha.2, @nuxtjs/color-mode@3.2.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-tkpaqv?file=pages/protected.vue

### Describe the bug

The auth middleware tries to redirect to the login pages, but the user is sent to `/[object%20Promise]?callbackUrl=/protected`. 

![image](https://user-images.githubusercontent.com/43099880/235325856-b9a372db-ae97-4274-9685-0bcffe1b71db.png)

I think the bug comes from here:

https://github.com/sidebase/nuxt-auth/blob/5cf59750a9f3539f58061da5ef24f9b9e2dd371a/src/runtime/composables/authjs/useAuth.ts#L87

As long in the same file the `await` keyword is used for the same function:

https://github.com/sidebase/nuxt-auth/blob/5cf59750a9f3539f58061da5ef24f9b9e2dd371a/src/runtime/composables/authjs/useAuth.ts#L66

### Additional context

I'm available to make an PR.

**Comment by BracketJohn** [comment]
Ah, good catch? Want to open a PR? Otherwiese Ill do it (:

**Comment by guesant** [comment]
> Ah, good catch? Want to open a PR? Otherwiese Ill do it (:

Thanks! I'll do.

**Comment by guesant** [comment]
PR: #360.

**Comment by BracketJohn** [comment]
Thanks! Tests are running now, will do a release shortly (:
