### ISSUE TITLE
local provider and csrf request before login

### ISSUE THREAD

**Issue by timmaier** [sidebase/nuxt-auth#366]
### Ask your question

Hey I'm trying to have a csrf get request run before the login route request. This [https://sidebase.io/nuxt-auth/v0.6/getting-started#local-remarks](url) indicates that this is still a WIP and does not support the csrf endpoint option mentioned here https://auth.nuxtjs.org/schemes/cookie/ yet.

**Comment by BracketJohn** [comment]
Yes, this is exactly right! You'll need to implement CSRF for local yourself as it will be out of scope for the `local`provider initially. Reason for this is that we want to keep the `local` provider compatible with fully static apps, for CSRF you need a server-side.

In the future we may add optional server-side capabilities to static providers that are opt-in, but it is not planned for now.

If you absolutely need CSRF and don't want to implement it yourself you can go with the `authjs` provider and then in the `NuxtAuthHandler` use the credential provider.

Hope that helps, have a good sunday 🌤️

**Comment by Buffalom** [comment]
@BracketJohn I don't quite understand why this is out of scope for the `local` provider. Fetching a CSRF token before doing the login-request and setting a header for the login-request would be just as possible in a fully static app, or am I missing something?

I don't currently see how I can set a header for the login-request. This means, I am not even sure how I can implement the CSRF myself with the current implementation.

**Comment by mishu-** [comment]
I second @Buffalom 's question. I am trying to set the csrf header.. no clue how.

**Comment by timmaier** [comment]
My usecase was for laravel sanctum and I followed [this](https://manchenkoff.medium.com/laravel-10-and-nuxt-3-setup-ssr-with-authentication-from-scratch-497ab1a3fc56) great medium article by @manchenkoff. 

It works perfectly for my usecase where I needed all api requests to be authenticated after auth.
