### ISSUE TITLE
v0.6 beta.2: Protection not being applied & not redirecting

### ISSUE THREAD

**Issue by kogratte** [sidebase/nuxt-auth#369]
### Ask your question

Hello!
I'm starting a new nuxt project where I need auth, so, according to their website, I installed this one just like the documentation says.
I'm running two issues, but it may be me (I just do not know what to look after):
- When registering global middleware using those instructions:
```typescript - nuxt.config.ts
export default defineNuxtConfig({
   modules: [
       [...],
       '@sidebase/nuxt-auth'
   ],
    auth: {
        globalAppMiddleware: true
    },
   [...]
});
```
the middleware does not seems to be registers. The nuxt inspector list only nuxt.validate, nothing else.

The second issue is with guest mode.

In my login page, I've got this config:
``` vue - pages/login/index.vue

definePageMeta({
    auth: {
        unauthenticatedOnly: true,
        navigateAuthenticatedTo: '/user',
    }
});
```

Despite that, even being logged in, I'm never redirected. Maybe it is a consequence of the first one.

Any idea?

**Comment by raducretu** [comment]
had the same issue, apprently the needs to be 
```
globalAppMiddleware: {
    isEnabled: true //or is_enabled
}
```

**Comment by willjosefi** [comment]
I'm having issues too

I enabled the `globalAppMiddleware` using boolean and the object `{isEnabled: true}`
Created a simple route `/dashboard/protected`, and the protection is not being applied

**Comment by kogratte** [comment]
Also, there is no JWT available, why? It doesn't seems to be mentioned
elsewhere in the doc, but I may have missed something...

From what I understand, JWT or session are two distinct modes, but I can't
see how or why I should use one or the other.

**Comment by BracketJohn** [comment]
Hey there 👋 

Will have a look into this - please be aware that v0.6 is still a beta, use v0.5 for a smooth, tested experience if this is what you are looking for (:

**Comment by BracketJohn** [comment]
Okay, lookedat this issue again - would one of you please provide:
- a specific problem,
- a reproduction for said problem?

Then I can actually help (: Other than that: Please keep in mind that v0.6 is still in beta, if you are looking for a stable experience use v0.5 please, thanks!

**Comment by imduchy** [comment]
Instead of opening a new issue, this is a repo with a newly generated nuxt3 project and nuxt-auth v0.5.0.

https://github.com/imduchy/nuxt3-auth

I'm running into same problems. I registered the Auth0 provider and after clicking on sign in button, I'm able to complete the auth flow. However, protected pages are available even without an active session.

I tried to follow the example with a custom log in page but after logging-in, I was never redirected.

```javascript
auth: {
  unauthenticatedOnly: true,
  navigateAuthenticatedTo: '/protected',
}
```

Nuxt version: 3.5.2
Node version: 16

**Comment by imduchy** [comment]
@BracketJohn any updates on this, please?

**Comment by BracketJohn** [comment]
> https://github.com/sidebase/nuxt-auth/issues/369#issuecomment-1536242756

This was (another?) problem, but resolved + released via https://github.com/sidebase/nuxt-auth/pull/423

I'll still look into the other report about `/protected` not being protected :+1:

**Comment by imduchy** [comment]
@BracketJohn I was curious if you had a chance look at it

**Comment by MuhammadM1998** [comment]
Hi, I'm experiencing the same issue with `0.6.0-beta.5`. I've checked the middlewared in `node_modules/@sidebase/nuxt-auth/dist/runtime/middleware/auth.mjs/` and the logic seems correct to me. I tried using `console.log` to check if values such as `status` and `metaAuth` is correctly passed but it doesn't show up in the console.

**Comment by zoey-kaiser** [comment]
@MuhammadM1998 Thanks for the investigation 💪 

I updated the docs, to be more inline with what you described. This should make it more clear how to use the middleware.

**Comment by MuhammadM1998** [comment]
@zoey-kaiser Glad to help 🙏  Thanks for the module!
