### ISSUE TITLE
Extending a bit more documentation about provider flow

### ISSUE THREAD

**Issue by darwebdb** [sidebase/nuxt-auth#39]
### Describe the feature

Default session middleware provider will return you to /api/auth/signin while in my case I want this to be to the custom sign in page at /auth/signin in the pages folder.

When trying to create custom login/signin pages, I came to the following settings that enable the module to redirect to the proper custom route.

My suggestion is to add these parameters to the current proper documentation.
```
// ./server/api/auth/[...].ts 
// Custom redirect paths when using custom sign in pages.
{
...
  pages: {
    signIn: '/auth/signin',
  },
...
}
  ```
  
  This would be interesting too.
  A better commented object that represents the most commonly used args
  ```
signIn("Credentials", { redirect: false, ...})
```

**Comment by BracketJohn** [comment]
Hey @darwebdb 👋 

I've expanded the custom-sign-in-page docs dramatically in #47 and showed how to configure the `NuxtAuthHandler` with the `pages` config -> feel free to check it out and open an issue if you see further need for extension: https://github.com/sidebase/nuxt-auth#custom-sign-in-page

**Comment by darwebdb** [comment]
Hey @BracketJohn  👋, 

I've figured it out going through the NextAuth docs, thats how I got to the suggestion.
It fixed the redirect url.

**Comment by BracketJohn** [comment]
Nice - thanks for that (:
