### ISSUE TITLE
baseURL is ignored in redirect_uri query parameter

### ISSUE THREAD

**Issue by terion-name** [sidebase/nuxt-auth#395]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.0.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.4.0
- Builder:          vite
- User Config:      modules, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.6.0-beta.1
- Build Modules:    -
------------------------------

### Reproduction

```ts
export default defineNuxtConfig({
    modules: ["@sidebase/nuxt-auth"],
    auth: {
        baseURL: '/sso',
    }
})
```

/routes/sso/[...].ts:
```ts
export default NuxtAuthHandler({
    secret: process.env.AUTH_SECRET,
    providers: [
        // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
        AuthentikProvider.default({
            clientId: process.env.AUTHENTIK_ID,
            clientSecret: process.env.AUTHENTIK_SECRET,
            issuer: process.env.AUTHENTIK_ISSUER,
        }),
    ],
});
```

redirect page:
```vue
<template></template>
<script setup lang="ts">
onMounted(() => {
  useAuth().signIn('authentik', {callbackUrl: '/login'})
})
</script>
```

redirects to:
```
https://myauthserver.dev/application/o/authorize/?client_id=1&scope=openid%20email%20profile&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fauthentik&state=foo&code_challenge=bar&code_challenge_method=S256
```

`redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fauthentik` — not `/sso/callback/authentik`

### Describe the bug

redirect_uri should respect baseURL config

**Comment by Koaieus** [comment]
Do you mean
```ts
    app: {
        baseURL: '/sso',
    }
```
instead of 
```ts
    auth: {
        baseURL: '/sso',
    }
``` ?

If yes: I'm running into similar problems!
If no: `auth` doesn't provide a `baseURL` key as far as I can see in the docs

**Comment by Koaieus** [comment]
Do you mean
```ts
app: {
    baseURL: '/sso',
}```
instead of
```ts
auth: {
    baseURL: '/sso',
}
```
by the way?

**Comment by hnccox** [comment]
I can't seem to get nuxt-auth to hit my laravel backend endpoints.

`auth: {
		baseURL: 'http://localhost:8000/',
		provider: {
			type: 'local',
			endpoints: {
				getSession: { path: '/session' }
			},	
			pages: {
				login: '/auth/login'
			},
			token: {
				signInResponseTokenPointer: '/token/accessToken',
				// type: 'Bearer',
				// headerName: 'Authorization',
				// maxAgeInSeconds: 3600
			},
			sessionDataType: { id: 'string', email: 'string', name: 'string', role: 'admin | guest | account', subscriptions: "{ id: number, status: 'ACTIVE' | 'INACTIVE' }[]" }
		},
		session: {
      // Whether to refresh the session every time the browser window is refocused.
      enableRefreshOnWindowFocus: true,

      // Whether to refresh the session every `X` milliseconds. Set this to `false` to turn it off. The session will only be refreshed if a session already exists.
      enableRefreshPeriodically: 5000
    },
		globalAppMiddleware: {
			isEnabled: true,
			allow404WithoutAuth: true,
			addDefaultCallbackUrl: true,
		},
	},`

Anytime I press the SignIn button, it creates a "New request: /api/auth/login"
and my backend isn't being hit...

**Comment by zoey-kaiser** [comment]
Ill look into this. From what I understand this happens when:

- using <0.6.0
- using the local providor
- `baseUrl` is set to be `localhost:8000`
- Requests are not sent to this baseUrl.

Is this correct?

**Comment by zoey-kaiser** [comment]
This looks to be the same issue as #368. I will continue my investigation there! Feel free to follow along and ensure your issues are also resolved!

**Comment by zoey-kaiser** [comment]
> redirect_uri should respect baseURL config

`baseURL` needs to be a full URL, not just a path! Try it with `http://localhost:300/sso/callback/authentik` 🤗
