### ISSUE TITLE
With beta.2 AUTH_NO_ORIGIN error appears

### ISSUE THREAD

**Issue by peterbud** [sidebase/nuxt-auth#396]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  pnpm@8.5.0
- Builder:          vite
- User Config:      ssr, components, modules, auth, runtimeConfig, vite, sourcemap, css, devtools
- Runtime Modules:  @sidebase/nuxt-auth@0.6.0-beta.2, @unocss/nuxt@0.51.13, @vueuse/nuxt@10.1.2
- Build Modules:    -

### Reproduction

Upgrade nuxt-auth from beta.1 to beta.2

### Describe the bug

With beta.1 I had no problem and nuxt-auth was working fine. With beta.2 I experience `AUTH_NO_ORIGIN: No origin` errors in development, and the only way to get rid of this is to define AUTH_ORIGIN in `.env`.

I looked into the source, and maybe the issue is here:
https://github.com/sidebase/nuxt-auth/blob/2f80e95fa0072f55b8ea35c347d2df9d11a3d557/src/runtime/server/services/utils.ts#LL18C2-L21C6

It seems to me that there is no more `useRuntimeConfig().auth.computed.origin`, only `useRuntimeConfig().public.auth.computed.origin`

**Comment by peterbud** [comment]
Thanks!

**Comment by zoey-kaiser** [comment]
Hi @peterbud, I wanted to quickly give you some more context to this!

Thank you for your own investigation 🥳 I saw this problem in some other issues as well and managed to pinpoint, the change in 0.6, that broke this. I will hopefully push a fix soon, but in the meantime, I decided to close some issues that overlap with one another!
