### ISSUE TITLE
auth option of definePageMeta is not typed

### ISSUE THREAD

**Issue by mlutsiuk** [sidebase/nuxt-auth#397]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.18.0
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.2
- Package Manager:  pnpm@8.5.0
- Builder:          vite
- User Config:      modules, build, auth
- Runtime Modules:  ../src/module.ts
- Build Modules:    -

### Describe the bug

`definePageMeta({ auth })` in not typed
<img width="275" alt="image" src="https://github.com/sidebase/nuxt-auth/assets/63050099/ba459eee-a4d2-45d6-99ca-04583ffa0047">

There is some type declarations in `src/runtime/middleware/auth.ts`, but it has no impact
```ts
type MiddlewareMeta = boolean | {
  unauthenticatedOnly: true,
  navigateAuthenticatedTo?: string,
}

declare module '#app' {
  interface PageMeta {
    auth?: MiddlewareMeta
  }
}
```

**Comment by Danielwinkelmann** [comment]
I was thinking you fixed it yourself in #379 ?

**Comment by mlutsiuk** [comment]
Nope, in #379 i fixed `auth` middleware registration, this issue about auth param in definePageMeta

https://sidebase.io/nuxt-auth/v0.6/application-side/guest-mode

**Comment by mlutsiuk** [comment]
What I've noticed: if I add this field to `PageMeta` in one of Nuxt generated files(e.g. `.nuxt/types/middleware.d.ts`), it works fine

```ts
import type { NavigationGuard } from 'vue-router'
export type MiddlewareKey = "auth"
declare module "D:/Dev/packages/nuxt-auth/node_modules/.pnpm/nuxt@3.4.2_@types+node@18.15.11_eslint@8.37.0_rollup@3.21.8_typescript@5.0.3_vue-tsc@1.2.0/node_modules/nuxt/dist/pages/runtime/composables" {
  interface PageMeta {
    middleware?: MiddlewareKey | NavigationGuard | Array<MiddlewareKey | NavigationGuard>
    auth: 'some type' | 'to test'
  }
}
```

<img width="509" alt="image" src="https://github.com/sidebase/nuxt-auth/assets/63050099/16de4089-242c-4d79-a820-a44cc0a0bcfd">

Later I made some changes and found the solution - change the namespace from `#app` to `#app/../pages/runtime/composables`

```ts
type MiddlewareMeta = boolean | {
  unauthenticatedOnly: true,
  navigateAuthenticatedTo?: string,
}

declare module '#app/../pages/runtime/composables' {
  interface PageMeta {
    auth?: MiddlewareMeta
  }
}
```


It looks weird, and I think it must be a Nuxt issue.

**Comment by BracketJohn** [comment]
Lets also open an upstream issue in the nuxt repo to see if this is a potential upstream bug. 

I volunteer to do it, unless you want to?

**Comment by mlutsiuk** [comment]
@BracketJohn ok, it's on you

**Comment by DavidShield** [comment]
Hi, I find the same issue, however neither change .nuxt/types/middleware.d.ts or change the namespace from #app to #app/../pages/runtime/composables works for me. I also download the latest code from github and run it locally. I find whenever I refresh the login page after login, it will automatically logout. I am not sure whether there are something wrong with the example so I cannot test that feature there.
