### ISSUE TITLE
Nuxt app baseURL not taken into account

### ISSUE THREAD

**Issue by Koaieus** [sidebase/nuxt-auth#404]
### Environment

Nuxi 3.2.3                                                                                                                                                                                                     
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@4.0.0-rc.22`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

If using a nondefault `baseURL` setting in Nuxt config's `app` key (not `auth`!), this URL is not respected for e.g. server routes, login/logout redirects

E.g. if using this config:
> `nuxt.config.ts`
```ts
export default defineNuxtConfig({
  app: {
    baseURL: '/something',
  },
```
... these expectations I have are not met:
- default auth endpoints to be at `/something/api/auth`
  - this could be overridden by setting `auth/baseURL` but imo the `app/baseURL` modification should be applied first during resolution, allowing `auth/baseURL` setting to remain at default
- callback URL to have a path at least starting with `/something/...`
  - currently, callbackURL is detected as e.g. `localhost:xxx` instead of `localhost:xxx/something`
  - hard redirecting to '/' (≈`origin`) will not actually point to this Nuxt app's root i.e. lead to 404 or some other app 
  - composing callbackURL as `origin` joined with `baseURL` set in Nuxt's `app` settings might fix this?

Are my expectations wrong? Is my approach wrong? Or is this a bug?

Cheers,
  Koaieus

### Additional context

Might be related to [this issue (#395)](https://github.com/sidebase/nuxt-auth/issues/395), but I'm not sure because this issue mentions setting baseURL under `auth` key in Nuxt setting.
So I'm not sure if that issue applies here; as both `baseURL` settings seem to do entirely different things!

**Comment by kaboume** [comment]
Same issue : https://github.com/sidebase/nuxt-auth/issues/368

**Comment by redanefzi** [comment]
I had the same issue but i was able to fix it by adding:

```js
computed: {
      origin: true,
      fullBaseUrl: process.env.AUTH_URL,
   },
```

to
 ```js
 auth:{} 
```

**Comment by zoey-kaiser** [comment]
Closing this in favor of https://github.com/sidebase/nuxt-auth/issues/368
