### ISSUE TITLE
Nuxt Auth in Cheviot stack making fetch requests return type `unknown`

### ISSUE THREAD

**Issue by KyleSmith0905** [sidebase/nuxt-auth#426]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.15.0
- Nuxt Version:     3.0.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@7.29.0
- Builder:          vite
- User Config:      runtimeConfig, modules, extends, typescript
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0, nuxt-svgo@1.2.1, @sidebase/nuxt-auth@0.6.0-beta.2, @huntersofbook/naive-ui-nuxt@0.5.1
- Build Modules:    -

### Reproduction

https://github.com/KyleSmith0905/mre--sidebase-fetch-autocomplete

Steps to get there:
1. Run `pnpm create sidebase@latest`
a) What will your project be called - `mre--sidebase-fetch-autocomplete-app`
b) What stack would you like to use for your new project? - `Cheviot`
c) Initialize a new git repository? - `no`
d) Would you like to run `pnpm install` after finishing up? - `yes`
2. Run `pnpm i @sidebase/nuxt-auth`
3. Add `@sidebase/nuxt-auth` to the nuxt config by adding it to the modules array.
4. Write a $fetch function.
5. Observe lack of type-support.

### Describe the bug

When using the Cheviot Sidebase stack while also using _@sidebase/nuxt-auth_ there seems to be no type support for `$fetch` (probably other types of fetch as well) statements. The `$fetch` statements would not autocomplete the path to the server, and when url is correct, the autocomplete types the return as `unknown`.

### Additional context

I assume the problem lies with me due to how important of an issue this seems to me. But it was pretty easy to recreate that I assume others have ran into that problem.

**Comment by zoey-kaiser** [comment]
Hi @KyleSmith0905, this is likely due to the Cheviot being slightly outdated. I will aim to upgrade it ASAP! Thanks for letting us know and sorry for the inconvenience!
