### ISSUE TITLE
Vercel issue with email provider and nodemailer

### ISSUE THREAD

**Issue by jnarowski** [sidebase/nuxt-auth#428]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v16.17.1
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      auth, app, runtimeConfig, modules, formkit, content, devtools
- Runtime Modules:  nuxt-icon@0.4.1, @pinia/nuxt@0.4.11, @formkit/nuxt@0.17.2, @sidebase/nuxt-auth@0.6.0-beta.2, @nuxtjs/tailwindcss@6.7.0, @nuxt/content@2.6.0, @formkit/nuxt@0.17.2
- Build Modules:    -
```

### Describe the bug

They are discussing it partially here:
https://stackoverflow.com/questions/65631481/nodemailer-in-vercel-not-sending-email-in-production

I am using nuxt-auth with nodemailer and deploying to Vercel. It works locally, but does not work in production. There I get an error=EmailSignin

I see someone mentioned this to solve the issue:
```
export default defineEventHandler(async (event) => {
  await mailTransport.sendMail(mailOptions);

  return {}
}
```

**And the reasoning:**
_You need to remove the callback from the nodemailer sendEmail function otherwise it does not return a promise... this cause the script in vercel to be terminated earlier hence not email being sent!_

I am just not sure where to add this and how to apply it. Might be nice to update your docs with specific instructions for nodemailer and vercel if it is in fact a nuxt-auth issue?

**Comment by zoey-kaiser** [comment]
Hi @jnarowski, this seems to be an issue that has to do with Vercel more then NuxtAuth. I sadly don't know what the best approch would be to properly configure this on your end.
