### ISSUE TITLE
 Error: Navigating to external URL is not allowed by default. Use `navigateTo (url, { external: true })`

### ISSUE THREAD

**Issue by Jeroen-Cox** [sidebase/nuxt-auth#429]
### Environment

- Operating System: `Darwin`
- Node Version:     `v19.8.1`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `ssr`, `typescript`, `runtimeConfig`, `modules`, `auth`, `components`, `app`
- Runtime Modules:  `@sidebase/nuxt-auth@0.6.0-beta.2`
- Build Modules:    `-`

### Describe the bug

I setup a basic 'local' authentication using @sidebase/nuxt-auth@0.6.0-beta.2. I can successfully login/logout etc. But everytime nuxt-auth wants to do a redirect I see two errors:

`[Vue warn]: Unhandled error during execution of native event handler`

`Uncaught (in promise) Error: Navigating to external URL is not allowed by default. Use navigateTo (url, { external: true })`

So these errors happen after using signIn() and signOut()

### Additional context

My nuxt.config.ts:

export default defineNuxtConfig({
  // Client side rendering only
  ssr: false,
  // Typescript settings
  typescript: {
    typeCheck: false,
    strict: true,
  },
  runtimeConfig: {
    public: {
      baseURL: process.env.API_BUILDER_URL,
      flowBuilderUrl: process.env.FLOW_BUILDER_URL,
      downloadCloseHost:
        process.env.DOWNLOAD_CLOSE_URL || "https://downloadclose.com",
    },
  },
  modules: ["@sidebase/nuxt-auth"],
  // Auth setup, see https://sidebase.io/nuxt-auth/configuration/nuxt-config
  // TODO: set auth origin for production
  auth: {
    provider: {
      type: "local",
      endpoints: {
        signIn: { path: "/login", method: "post" },
        signOut: { path: "/logout", method: "post" },
        getSession: { path: "/user", method: "get" },
      },
      token: {
        type: "Bearer",
      },
      pages: { login: "/login" },
    },
    baseURL: `${process.env.API_BUILDER_URL}/api`,
    globalAppMiddleware: {
      isEnabled: true,
    },
  },
  components: [
    {
      path: "~/components",
      pathPrefix: false,
    },
  ],
  app: {
    // Page header settings
    head: {
      title: "Close Builder",
      titleTemplate: "%s – Close",
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
        { hid: "description", name: "description", content: description },
        { hid: "og:description", name: "og:description", content: description },
      ],
      link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }],
    },
  },
});

**Comment by tjeneis** [comment]
This seems to be because the useAuth composable of the package passed a full url with protocol by default to the navigateTo router helper function without supplying the required `{ external: true }`. What you can do for now to prevent this is to manually supply a valid path in the signInOptions of your signIn and signOut actions where you want to redirect to after the action has finised.

Example:
`signIn({ username, password }, { callbackUrl: '/' })`

**Comment by Jeroen-Cox** [comment]
@tjeneis thanks, that was indeed the problem!

**Comment by zoey-kaiser** [comment]
@omnichronous does your commit https://github.com/omnichronous/nuxt-auth/commit/30da88c899eef8183bc1bd292468c21ca24ed39b solve the issue? 

If so, you are welcome to open a PR, or I can look into doing this myself!

**Comment by omnichronous** [comment]
@zoey-kaiser I didn't get around to testing it properly and I see that you already opened a PR with a fix, much appreciated ❤️

**Comment by CarterSnich** [comment]
> signIn({ username, password }, { callbackUrl: '/' })

`signIn` worked, but not for `signOut`. I'm still getting the error.
