### ISSUE TITLE
define refresh endpoint for local provider

### ISSUE THREAD

**Issue by andr-ec** [sidebase/nuxt-auth#431]
### Describe the feature

include a configuration for the refresh endpoint.
```
endpoints: {
        signIn: { path: "/api/users/login", method: "post" },
        signOut: { path: "/api/users/logout", method: "post" },
        signUp: { path: "/api/users/register", method: "post" },
        getSession: { path: "/api/users/me", method: "get" },
        refresh: { path: "/api/users/refresh", method: "get" },
      },
```

The refresh path should automatically be called when the token is set to expire or when it will expire.

**Comment by zoey-kaiser** [comment]
Hi @andr-ec,

The way I understand this would be:
- A session fetch is executed
- This fetch fails as the token expired (we cannot call a route the moment the session is set to expire, as we don't have cron jobs etc, running)
- If a refresh endpoint is defined, a call to this refresh endpoint is made, with what data? (The previous token?)

Is this what you were thinking of? Or did I misunderstand your request?

**Comment by zoey-kaiser** [comment]
Addressed in https://github.com/sidebase/nuxt-auth/pull/581
