### ISSUE TITLE
Static site with Azure authentication

### ISSUE THREAD

**Issue by hieuluong** [sidebase/nuxt-auth#433]
### Describe the feature

Hi, I am building a static Nuxt 3 site with Azure authentication feature.
I am using sidebase/nuxt-auth 0.6.0-beta.2, and implemented following this document https://sidebase.io/nuxt-auth/recipes/azure-ad-example 
It runs ok with `npm run dev`, but when I generate static site with `npm run generate` then `npm run start`, it show errors
![image](https://github.com/sidebase/nuxt-auth/assets/19338865/f4b6a1a2-8971-4b41-87ce-4a8494228c5d)

I know the **server** do not work with static site, how can I implement in this case ?

**Comment by zoey-kaiser** [comment]
Sadly, using authjs, does not work with static deplopyments. The only static solution we currently support is a credentials based one. Any OAuth solution, will not work with a static deployment.
