### ISSUE TITLE
Adding Nuxt Auth slows web load times, even when unused.

### ISSUE THREAD

**Issue by KyleSmith0905** [sidebase/nuxt-auth#449]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.15.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@7.29.0
- Builder:          vite
- User Config:      devtools, runtimeConfig, routeRules, modules
- Runtime Modules:  @sidebase/nuxt-auth@0.6.0-beta.2
- Build Modules:    -

### Reproduction

https://github.com/KyleSmith0905/mre--nuxt-cold-start

You will need to provide a Postgres database (preferably serverless with long cold starts, could be free plan, for this test I was using _Neon Postgres_) and deploy it on a server (I used _Vercel_).

### Describe the bug

When adding Sidebase Nuxt Auth as a module the page speed becomes slower on cold and warm starts. This effect is present despite Nuxt Auth remaining unused for the routes. On a serverless database, this change is highly noticeable on cold starts, as it can take up to 2 seconds extra to warm.

I infer the wait is due to Nuxt Auth asynchronously making a request to the database and stalling the code on the server. I have not checked this repository for the issue.

The page I tested was marked as prerendered; meaning, the page being rendered shouldn't depend on authentication? And if it wasn't prerendered, auth is not being used anywhere.

**Comment by KyleSmith0905** [comment]
After starting another project, I've realized this might be due to Nuxt using serverless architecture.

It doesn't 100% make sense to me since I was using a server route someone else on the page.

Maybe @sidebase/nuxt-auth forces the page to be server rendered? idk.

I'm currently trying to work this out right now, so I'll come back when I have this figured out.

**Comment by zoey-kaiser** [comment]
Hi @KyleSmith0905! 

Thanks for the investigation! Here is the code for our current middleware: https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/middleware/auth.ts

If you have any ideas on how to futhur optimize it, feel free to let me know or open a PR! What I underatand from your last message is that the slow load times are related to the middleware and it forcing the page to be pre-rendered, correct? So therefore disabling the middleware (or writing your own) reduces the cold and warm startup times.

**Comment by KyleSmith0905** [comment]
Yeah, I've been taking a look occasionally at my free time. To clarify, when I add pre-render to the page, it does not pre-render on Vercel (or not that I think). I'm not sure how it works.

**Comment by KyleSmith0905** [comment]
It might be fixed (with @sidebase/nuxt-auth@0.6.0 or the latest minor version of Nuxt?). I took the authjs playground and deployed it to Vercel:
https://nuxtauth-experiments-git-prerender-experiment-kylesmith0905.vercel.app/

It prerendered nicely.

My other sites are now also prerendering nicely now (with no changes).

I'm closing this issue.
