### ISSUE TITLE
signIn credentials missing SignInOptions prop

### ISSUE THREAD

**Issue by frasza** [sidebase/nuxt-auth#45]
### Describe the bug

I am trying to use the module with credentials signIn method passing username and password on the frontend. Issue occurs when I am trying to pass username and password as SignInOptions.

```
signIn("credentials", {
    username: username.value,
    password: password.value,
})
```

Editor says `Argument of type '{ username: string; password: string; }' is not assignable to parameter of type 'SignInOptions'.` and when I checked modules source code, it is not there indeed, only callbackUrl and redirect are.
Am I missing something?

**Comment by BracketJohn** [comment]
Ohhhh, thanks @frasza, good catch - this indeed is a bug and needs to be fixed. Would you like to try your hand? Otherwise we'll come around to it shortly.

In the meantime you should be able to ts-ignore it as a worksround.

Thanks 🙏

**Comment by frasza** [comment]
Great, thank you! Was looking to fix this, but glad to see fast response.

**Comment by BracketJohn** [comment]
Sure thing 🚀 

The release it out now. Use it as `npm i -D @sidebase/nuxt-auth@0.1.3` (:

Let me know if there's any further problems here 🎊
