### ISSUE TITLE
Google Auth provider - No refresh_token returned

### ISSUE THREAD

**Issue by tiwence** [sidebase/nuxt-auth#451]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.1.0`
- Builder:          `vite`
- User Config:      `app`, `ssr`, `runtimeConfig`, `components`, `routeRules`, `css`, `modules`, `auth`, `plugins`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.12`, `@pinia/nuxt@0.4.7`, `@sidebase/nuxt-auth@0.6.0-beta.2`
- Build Modules:    `-`
------------------------------

### Describe the bug

Hello there, 

I encounter an issue by using sidebase/nuxt-auth over the GoogleAuth provider. I set-up the NuxtAuthHandler like this : 

```
const config = useRuntimeConfig()

GoogleProvider.default({
            clientId: config.oauthClientId,
            clientSecret: config.oauthClientSecret,
            authorization: { params: { scope: "openid email profile https://www.googleapis.com/auth/cloud-platform" } },
})]
```

And I customize the jwt and session storage like this, to get the google auth accessToken to verify it on a remote API:

```
async jwt({ token, account }) {
    const isSignin = account ? true : false
    if (isSignin) {
        token.accessToken = account?.access_token
        token.idToken = account?.id_token
        token.accessTokenExpires = account?.expires_at! * 1000
        token.refreshToken = account?.refresh_token
    }

    if (Date.now() < token.accessTokenExpires) {
        return Promise.resolve(token)
    }

    return Promise.resolve(token)
},
async session({ session, token, user }) {
    ; (session.user as any).accessToken = (token as any).accessToken
        ; (session.user as any).idToken = (token as any).idToken
        ; (session.user as any).refreshToken = (token as any).refreshToken
    return Promise.resolve(session)
}
```

In the jwt function, I wanted to recover the **refresh_token** from the google auth workflow. But it remains still **undefined** (even during the first login)... I got the other credentials such as the id_token or the access_token.
But I need it to refresh google auth credentials on my server.

Could you help me if I missed something in the documentation to get this refresh_token ? 

Thank you in advance !

**Comment by JonathanGildevall** [comment]
For anyone encountering the same issue:
https://developers.google.com/identity/openid-connect/openid-connect#refresh-tokens

Seems like you need to ask for it explicitly, by setting the access_type

**Comment by tiwence** [comment]
Thank you for your help. OK I figured it out by add the access_type parameters into the Google OAuth Provider, like the following implementation: 

```
GoogleProvider.default({
    clientId: config.oauthClientId,
    clientSecret: config.oauthClientSecret,
    authorization: { params: { scope: "openid email profile https://www.googleapis.com/auth/cloud-platform", access_type: "offline" } },
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth?prompt=consent&response_type=code',
    accessTokenUrl: 'https://oauth2.googleapis.com/token'
})
```
