### ISSUE TITLE
When i sign out, we redirect to localhost:3000, not to origin url

### ISSUE THREAD

**Issue by agracia-foticos** [sidebase/nuxt-auth#453]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

We are using this code for signout:

`export async function signOut() {
    const { signOut } = useAuth()
    const { reset } = await useSession()
    await reset()
    await signOut({ callbackUrl: `/${LOGIN_SLUG}` })
}`

nuxt.config.ts

```
auth: {        
        // @ts-ignore (isEnabled boolean type)
        isEnabled                         : process.env.NUXT_AUTH_ENABLED=="true", //all environment variables are strings
        origin                            : process.env.NUXT_BASE_URL, // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`                  
        basePath                          : '/api/auth', // The base path to the authentication endpoints. Change this if you want to add your auth-endpoints at a non-default location                  
        enableSessionRefreshPeriodically  : false, // Whether to periodically refresh the session. Change this to `true` for a refresh every seconds or set this to a number like `5000` for a refresh every 5000 milliseconds (aka: 5 seconds)                  
        enableSessionRefreshOnWindowFocus : true,  // Whether to refresh the session whenever a window focus event happens, i.e, when your user refocuses the window. Set this to `false` to turn this off                  
        enableGlobalAppMiddleware         : false, // Whether to add a global authentication middleware that will protect all pages without exclusion                  
        globalMiddlewareOptions           : { // Configuration of the global auth-middleware (only applies if you set `enableGlobalAppMiddleware: true` above!)                      
            allow404WithoutAuth : true  // Whether to allow access to 404 pages without authentication. Set this to `false` to force users to sign-in before seeing `404` pages. Setting this to false may lead to vue-router problems (as the target page does not exist)
        }
    },
```

.env
`NUXT_BASE_URL="http://localhost:3001"`

but in the redirection, signout redirect me to localhost:3000, not to localhost:3001

### Describe the bug

We are using this code for signout:

`export async function signOut() {
    const { signOut } = useAuth()
    const { reset } = await useSession()
    await reset()
    await signOut({ callbackUrl: `/${LOGIN_SLUG}` })
}`

nuxt.config.ts

`auth: {        
        // @ts-ignore (isEnabled boolean type)
        isEnabled                         : process.env.NUXT_AUTH_ENABLED=="true", //all environment variables are strings
        origin                            : process.env.NUXT_BASE_URL, // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`                  
        basePath                          : '/api/auth', // The base path to the authentication endpoints. Change this if you want to add your auth-endpoints at a non-default location                  
        enableSessionRefreshPeriodically  : false, // Whether to periodically refresh the session. Change this to `true` for a refresh every seconds or set this to a number like `5000` for a refresh every 5000 milliseconds (aka: 5 seconds)                  
        enableSessionRefreshOnWindowFocus : true,  // Whether to refresh the session whenever a window focus event happens, i.e, when your user refocuses the window. Set this to `false` to turn this off                  
        enableGlobalAppMiddleware         : false, // Whether to add a global authentication middleware that will protect all pages without exclusion                  
        globalMiddlewareOptions           : { // Configuration of the global auth-middleware (only applies if you set `enableGlobalAppMiddleware: true` above!)                      
            allow404WithoutAuth : true  // Whether to allow access to 404 pages without authentication. Set this to `false` to force users to sign-in before seeing `404` pages. Setting this to false may lead to vue-router problems (as the target page does not exist)
        }
    },`

.env
`NUXT_BASE_URL="http://localhost:3001"`

but in the redirection, signout redirect me to localhost:3000, not to localhost:3001

**Comment by agracia-foticos** [comment]
```
 const { error } = await signOut({redirect: false })

    if (error){
      console.error(`ERROR SIGNOUT:${JSON.stringify(error)}`)
      throw createError({
        statusCode: 500,
        statusMessage: error,
      });
    }else{
      window.location.href=`/${LOGIN_SLUG}`
    }
```

This code runs Ok for me, but
`await signOut({ callbackUrl: /${LOGIN_SLUG} }) }`
fails yet

**Comment by victj99** [comment]
Hi, i have the same problem with signIn and signOut. In production or dev with a different port redirects to localhost:3000, setting the baseUrl  or callbackUrl doesn't work.

Package Version: 0.6.beta2
Nuxt Version: 3.6
Node Version: 16.20.0
Npm Version: 9.6.7

**Comment by TomasSestak** [comment]
Having this issue aswell

**Comment by paulvonber** [comment]
Same here login/logout always redirect back to localhost

**Comment by SaphirePI** [comment]
> Same here login/logout always redirect back to localhost
Same for me

**Comment by Az-r-ow** [comment]
Same here

**Comment by janrudowski** [comment]
same here. everything works in dev, breaks in production redirects to localhost:3000

**Comment by paulvonber** [comment]
After some hours I got it working, in general this solution is buried in the documentation but it's very blurry. 
Anyway it works for me so I would suggest to try it out.

<img width="691" alt="image" src="https://github.com/sidebase/nuxt-auth/assets/37245111/c1eb7571-27a3-4ef8-b1ba-cc64ff3ba37d">

<img width="437" alt="image" src="https://github.com/sidebase/nuxt-auth/assets/37245111/7185c4fc-e7fe-4512-90db-b41750972c76">

**Comment by Az-r-ow** [comment]
I mean yeah this is a good workaround, but it would be cooler if the native thing of nuxt-auth could work.

**Comment by agracia-foticos** [comment]
any advance?

**Comment by scotthansonde** [comment]
I was having this problem in production as well, with these packages installed:
```
"@sidebase/nuxt-auth": "^0.5.0",
"next-auth": "4.22.1",
```
I then double-checked the [installation instructions](https://sidebase.io/nuxt-auth/getting-started/installation), and saw that the peer dependency is `next-auth@4.21.1`, not 4.22.1. I downgraded next-auth to 4.21.1, and that solved it for me

**Comment by oyasuyuki** [comment]
same...

**Comment by christohill** [comment]
I may have found a potential fix for this. I was having the same issue when starting the nuxt app and port 3000 was not available, so it was auto assigning a different port (ie: 3002). It seems to have sorted itself out once I assigned a port to the dev server in package.json

```
scripts: {
  ...
  "dev": "nuxt dev --port=3010"
}
```
Sign in seems to be redirecting properly now, though I haven't made it to testing with signOut, I'd assume it works the same.

**Comment by christine927t** [comment]
> I was having this problem in production as well, with these packages installed:
> 
> ```
> "@sidebase/nuxt-auth": "^0.5.0",
> "next-auth": "4.22.1",
> ```
> 
> I then double-checked the [installation instructions](https://sidebase.io/nuxt-auth/getting-started/installation), and saw that the peer dependency is `next-auth@4.21.1`, not 4.22.1. I downgraded next-auth to 4.21.1, and that solved it for me

Thank you, this just solved the issue for my team as well.

**Comment by kaboume** [comment]
Hi, 
Same issue.
In production, signout redirects to localhost:3000
Any fix please by the Nuxt Auth Team  ?

**Comment by rogue-ninja-creative** [comment]
> Hi, Same issue. In production, signout redirects to localhost:3000 Any fix please by the Nuxt Auth Team ?
> 
> "@sidebase/nuxt-auth": "^0.5.0",

await signOut({ redirect: false })

works for me.

**Comment by zoey-kaiser** [comment]
Hi @agracia-foticos!

I looked into this issue and can report the following. In Version 0.6, we reworked how the redirect after logging out works.
If you are using the latest version of the 0.6 beta (0.6.0-beta.7), you can define the signout redirect like so:

```ts
signOut({ callbackUrl: '/signout' })
```

You will not need to also include `redirect: false` and do your own navigation afterwards. 

As 0.5.0 has ended its lifecycle and we are close to releasing 0.6.0, we currently don't plan to update 0.5.0 to resolve this issue, retrospectively. I hope this is understandable!
