### ISSUE TITLE
Nuxi generate throws 500 error

### ISSUE THREAD

**Issue by agracia-foticos** [sidebase/nuxt-auth#455]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.5.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

when we lauch nuxi generate, there is a lot of callings to "locales" sites that not exists :(

`ERROR  [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:3000/api/auth/session?callbackUrl=http://localhost/pt/unsubscribe) 
 ERROR  [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:3000/api/auth/session?callbackUrl=http://localhost/pl/unsubscribe) `

we have an url http://localhost:3000/unsuscribe but without lang 

### Describe the bug

when we lauch nuxi generate, there is a lot of callings to "locales" sites that not exists :(

`ERROR  [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:3000/api/auth/session?callbackUrl=http://localhost/pt/unsubscribe) 
 ERROR  [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:3000/api/auth/session?callbackUrl=http://localhost/pl/unsubscribe) `

we have an url http://localhost:3000/unsuscribe but without lang

**Comment by agracia-foticos** [comment]
the fail its for strategy: 'no_prefix', of the module i18n...

But there is another error now

` ERROR  [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:3000/api/auth/session?callbackUrl=http://localhost/test)   `

The callbackUrl is not correct, must be the same that api/auth

**Comment by BracketJohn** [comment]
Hey @agracia-foticos!

Thanks for the issue - sounds like it couild be related to other parts of your setup. Can you please provide a full reproduction? So, a repo + some simple commands that will result in the error?

It's hard to debug this, as you yourself noticed: part of the error was related tio i18n!

**Comment by agracia-foticos** [comment]
It is also difficult for me to provide you with a functional environment.

Here you are an environment with a copy of our code related with auth and i18n

https://stackblitz.com/edit/nuxt-starter-wyfi9k

I hope I can help you

**Comment by agracia-foticos** [comment]
any advance?

**Comment by prabodhana** [comment]
I have the same issue is there any solution? after getting this error i tried with "ssr:false" then it complied but after run the complied files it given same error.

**Comment by rod2ik** [comment]
Hi,
I am having the same problem than both of you : everything was working perfectly, but I  received the following error after trying to activate https on dev server :

[16:18:33] [nuxt] [request error] [unhandled] [500] fetch failed (http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/)

I have set in an env file:

AUTH_ORIGIN = 'https://localhost:3000'
NEXTAUTH_URL = 'https://localhost:3000'
as wel AUTH_SECRET and AUTH_NO_SECRET

I followed the exact config detailled in the Official Nuxt 3 page for https (https://nuxt.com/docs/api/configuration/nuxt-config#https) :

```
export default defineNuxtConfig({
  modules: ['@sidebase/nuxt-auth''],
  devServer: {
    https: {
      key: './myserver+3-key.pem',
      cert: './myserver+3.pem',
    },
  },
})
```

**Comment by rod2ik** [comment]
I will try to propose you a fresh install reproducible error (with typescript, as I am using this as well), and note all error and how I fixed them until this blocking error.

Gitlab repo will be found at this url : 

1°)  fresh install : `npx nuxi@latest init auth-localhost`
2°) `cd auth-localhost`, and `yarn install`
3°) install `nuxt-auth` module : `yarn add @sidebase/nuxt-auth`

In `nuxt.config.ts`, I am already having this (typescript error) with this configuration : 

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@sidebase/nuxt-auth',
  ],
  auth: {
    provider: {
      type: 'authjs',
    },
    globalAppMiddleware: true,
})
```

Error (auth keyword not recognised, sorry in french)
``L`'argument de type '{ devtools: { enabled: boolean; }; modules: string[]; auth: { provider: { type: string; }; globalAppMiddleware: boolean; }; }' n'est pas attribuable au paramètre de type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.
  Un littéral d'objet peut uniquement spécifier des propriétés connues, et 'auth' n'existe pas dans le type 'InputConfig<NuxtConfig, ConfigLayerMeta>'.ts(2345)
(property) auth: {
    provider: {
        type: string;
    };
    globalAppMiddleware: boolean;
}
```

I solved this inserting an `auth.d.ts` file inside my `types` folder : 

```ts
// Hack : copied from @/.nuxt/types/auth.d.ts

declare module '#auth' {
  const getServerSession: typeof import('./../node_modules/@sidebase/nuxt-auth/dist/runtime/server/services').getServerSession
  const getToken: typeof import('./../node_modules/@sidebase/nuxt-auth/dist/runtime/server/services').getToken
  const NuxtAuthHandler: typeof import('./../node_modules/@sidebase/nuxt-auth/dist/runtime/server/services').NuxtAuthHandler
  interface SessionData {
    id: string | number
  }
}
```

**Comment by jd-solanki** [comment]
Try adding `callbackUrl` in your `signIn` like this: `await signIn('google', { callbackUrl: '/' })`

**Comment by radonyizsolt** [comment]
Hi, is there any workaround for this already? Can't put my application to production using reverse proxy in apache.

**Comment by ekun69** [comment]
hi,, is any solution for this issue?, i have simillar issue while running npx nuxi generate

**Comment by Bryceed** [comment]
Same problem

**Comment by zoey-kaiser** [comment]
Hi everyone, 

Sorry this issue went under. So there are a few different issues going on here. From the original issue, I can say that `nuxi generate` does not work with the `authjs` provider as SSR is required for it to work properly. 
if you are using the `local` provider from `0.6.0` you can render it statically. 

I hope this may already answer some question. 

I also see that some people were having issues with running a SSL certificate on dev servers, this is something unrelated to the original issue, AFAIK. I would recommend we open a new issue for this, as it became a little hard for me to properly follow along/get the current projects and reproduction links from the people still active in this thread!
