### ISSUE TITLE
providers page not found 

### ISSUE THREAD

**Issue by mahanteshaCloudMPower** [sidebase/nuxt-auth#463]
### Environment

node  20 
nuxt 3.6

### Describe the bug

providers

https://ws.spocapp.in/api/auth/providers
404 Not Found
 am getting 404 error in production 
![Screenshot from 2023-06-27 15-54-45](https://github.com/sidebase/nuxt-auth/assets/80378935/6469e5d3-01f7-4dcf-9906-0245ae0d5466)

same thing working in development  
https://dev.spocapp.in/api/auth/providers

![Screenshot from 2023-06-27 16-10-30](https://github.com/sidebase/nuxt-auth/assets/80378935/19071617-0cdf-461b-9eba-388a55dc91e1)

**Comment by zoey-kaiser** [comment]
Hi @mahanteshaCloudMPower,

Sadly I will need some more context to help you out. However, as it has been a while, I will close this issue. If you want to start a new investigation, feel free to 

1. Upgrade to the newest version of NuxtAuth
2. If the issue still persists, please provide a reproduction for me!
