### ISSUE TITLE
State reset too early when use PageTransition/LayoutTransition

### ISSUE THREAD

**Issue by mrleblanc101** [sidebase/nuxt-auth#465]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.19.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, srcDir, imports, runtimeConfig, app, modules, pinia, auth, postcss, build, svgo, eslint
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vueuse/nuxt@10.2.0, @sidebase/nuxt-auth@0.6.0-beta.3, nuxt-svgo@3.1.0, nuxt-swiper@1.1.1, nuxt-lodash@2.5.0
- Build Modules:    -
------------------------------

### Reproduction

![2023-06-28 06 33 42](https://github.com/sidebase/nuxt-auth/assets/17392251/5cad1633-d2dc-41a4-a562-b965983167ff)

### Describe the bug

The User data should be reset after the page is unmounted and the transition-out completed, not immediately.

### Additional context

This could cause issue if I use sub-key on the User object leading to `Cannot read X of undefined` errors.

**Comment by zoey-kaiser** [comment]
I personally believe that the current behavior is correct. The session gets expired as soon as the URL changes. The transition afterwards is only visual, but delaying the expiration of the session is not smart IMO. 

I would handle this in your fronted, to ensure it looks good. However functionality wise, I would not change anything.
