### ISSUE TITLE
Not working on generate command

### ISSUE THREAD

**Issue by prabodhana** [sidebase/nuxt-auth#478]
### Environment

- Operating System: Linux
- Node Version:     v16.20.1
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  npm@8.19.4
- Builder:          vite
- User Config:      devtools, ssr, css, typescript, build, vite, runtimeConfig, modules, googleFonts, app, auth
- Runtime Modules:  @nuxtjs/google-fonts@3.0.1, @sidebase/nuxt-auth@0.5.0, @pinia/nuxt@0.4.11, ()
- Build Modules:    -

### Describe the bug

I tried to run generate command after finished the project but given me this error.
![Screenshot from 2023-07-11 23-06-32](https://github.com/sidebase/nuxt-auth/assets/39000060/04bb2d48-f1c6-427b-90d1-a3a433374c5d)

After again I tried generate with ssr:false its successfully execute the command but after add to hosting it gives this error
![Screenshot from 2023-07-11 23-14-07](https://github.com/sidebase/nuxt-auth/assets/39000060/9d03eeb6-bc0c-4f2d-9064-db8ac6fd4837)

**Comment by selemondev** [comment]
Hey there @prabodhana : 

1. As for nuxt-sidebase-auth v0.5 to v0.6, if you chose the provider `authjs`, the `nuxi generate` command won't work.

2. Did you change the baseUrl in your nuxt.config.ts file when deploying your application? Example from : `http:localhost:3000` to `https://my-application.com`.

**Comment by prabodhana** [comment]
@selemondev I'm used  CredentialsProvider. And yes I'm already tried it change base url if i change it it given 404 error

**Comment by babalugats76** [comment]
I am experiencing the same issue with a nearly identical config.  The `generate` command fails both locally and in the Cloud (Netlify).  All development testing works perfectly.

```
12:48:53 PM: [info] [nitro] Initializing prerenderer
12:48:54 PM: [info] [nitro] Prerendering 3 initial routes with crawler
12:48:55 PM: [error] [nuxt] [request error] [unhandled] [404]  (404 Not Found (https://tres-rios.colestock.com/api/auth/session?callbackUrl=http://localhost/))
```
It is like the server routes are not being created?

**Comment by ekun69** [comment]
i have similar issue, it always callback url to localhost instead of localhost:3000

**Comment by zoey-kaiser** [comment]
Using the `authjs` provider does not work on staticly generated sites. If you are using a static site please refer to the new [local provider](https://sidebase.io/nuxt-auth/v0.6/getting-started/quick-start#provider-local).
