### ISSUE TITLE
Custom Errors

### ISSUE THREAD

**Issue by FrankoFM** [sidebase/nuxt-auth#497]
### Describe the feature

I noticed that there is currently no way of providing more information about an error, especially for the `CredentialsProvider`.
You can return `null` as an error, but that's it.
I think that would provide so much value, since you can then handle the errors on the client side or just display the message, so the user knows why it's failing.

For example:
```js
CredentialsProvider.default({
    async authorize(data) {
        // Auth Logic

        return new Error("Username or password is incorrect");
        // return new Error("To many login attempts");
        // return new Error("Your account has been disabled");
    },
}),
```

**Comment by FrankoFM** [comment]
Okey, so it can be done, but it's kinda weird.

```js
CredentialsProvider.default({
    async authorize(data) {
        // Auth Logic

        throw createError("Custom Error");
    },
}),
```

This will result in:
`{error: 'Custom Error', status: 200, ok: true, url: null}`

Why is `status: 200`? Why is `ok: true`.


```js
CredentialsProvider.default({
    async authorize(data) {
        // Auth Logic

        // This is not chaning the status
        throw createError({ status: 401, message: "Unauthorized" });
        // So is this
        throw createError({ statusCode: 401, message: "Unauthorized" });
    },
}),
```

Am I missing something?

**Comment by zoey-kaiser** [comment]
Hi @FrankoFM, I will look into, why status code 200 is always sent! I will also look into adding more documention on how to throw these errors!

- [ ] Make `createError` take custom status code into account
- [ ] Add more documentation on how to throw custom errors with the `local` provider.

**Comment by zoey-kaiser** [comment]
@FrankoFM, 

AFAIK, the issue with the status codes not being displayed correctly, is due to the errors being created on the client side and not the server side. In this case, `createError` will always return 200, as it wants to avoid the entire webapp "crashing". You can override this behaviour by passing `{ fatal: true }` inside the error object.

https://nuxt.com/docs/api/utils/create-error#throwing-errors-in-your-vue-app

**Comment by andre-silva9975** [comment]
Greetings!

I still have this issue. When I create an error inside the authorize function like presented below, the error I get from the console is 401 (Unauthorized) instead of 403. Does this problem still persist?

`async authorize(credentials: {email: string, password: string}) {
        const user = await prisma.users.findUnique({where: { email: credentials.email }})
        if(!user){
          throw createError({
            statusCode: 403,
            statusMessage: "Credentials not working",
            fatal: true
          })
        }
        return user
}`
