### ISSUE TITLE
jwt rotation not working properly after browser close and open

### ISSUE THREAD

**Issue by quroom** [sidebase/nuxt-auth#498]
### Environment

Windows 10
Nuxi 3.6.5
Nuxt 3.6.5 with Nitro 2.4.1 
@sidebase/nuxt-auth 0.4.4
next-auth 4.22.3

### Describe the bug

This is own my jwt refresh code.
This code works well until browser close.

```
import { NuxtAuthHandler } from "#auth";
import GoogleProvider from "next-auth/providers/google";
import NaverProvider from "next-auth/providers/naver";
import { JwtUtils } from "@/constants/utils";
const config = useRuntimeConfig();
export default NuxtAuthHandler({
  secret: process.env.NUXT_SECRET,
  pages: {
    // Change the default behavior to use `/login` as the path for the sign-in page
    signIn: "/login",
  },
  providers: [
    GoogleProvider.default({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    }),
    NaverProvider.default({
      clientId: process.env.NAVER_CLIENT_ID,
      clientSecret: process.env.NAVER_CLIENT_SECRET,
    }),
  ],
  callbacks: {
    async jwt({ token, user, account, profile }) {
      console.log(
        `[current] access: ${token.accessToken}, refresh: ${token.refreshToken}`
      );
      try {
        if (user && account) {
          if (account.provider === "google" || account.provider === "naver") {
            const response = await $fetch(
              `${config.public.apiBase}/dj-rest-auth/${account.provider}/`,
              {
                method: "POST",
                body: {
                  access_token: `${
                    account.provider === "google"
                      ? account.id_token
                      : account.access_token
                  }`,
                },
              }
            );
            const { access, refresh } = response;
            token = {
              ...token,
              accessToken: access,
              refreshToken: refresh,
            };
          }
        } else if (!token.accessToken || !token.refreshToken) {
          return {};
        } else if (JwtUtils.isJwtExpired(token.accessToken)) {
          const response = await $fetch(
            `${config.public.apiBase}/dj-rest-auth/token/refresh/`,
            {
              method: "POST",
              body: {
                refresh: token.refreshToken,
              },
            }
          );
          const { access, refresh } = response;
          console.log(`[new] access: ${access}, refresh: ${refresh}`);
          token = {
            ...token,
            accessToken: access,
            refreshToken: refresh,
          };
          return token;
        }
      } catch (error) {
        if (error.data) {
          console.debug(token.email, error.data);
        } else {
          console.debug(token.email, error);
        }
        return {};
      }
      return token;
    },
    async session({ session, token }) {
      if (token.accessToken) {
        session.accessToken = token.accessToken;
      } else {
        session = {};
      }
      return session;
    },
  },
  events: {
    async signOut({ token }) {
      await $fetch(`${config.public.apiBase}/dj-rest-auth/logout/`, {
        method: "POST",
        body: {
          refresh: token.refreshToken,
        },
      });
    },
  },
});

```

But in some scenario, user can close browser and after 12 hours like enough expiration access token,
user can open browser again. Then the code refresh access_token and refresh_token automatically.
And then in jwt callback function, returns new access token and refresh token.
But somehow, the token is not updated correctly.
I don't know how I can fix it correctly but I can only figure the cookie is not updated.

[frontend\node_modules\@sidebase\nuxt-auth\dist\runtime\server\services\nuxtAuthHandler.mjs#125](https://github.com/sidebase/nuxt-auth/blob/45d7e349ee0bb8791afdba69c7c35f39c9fe5a75/src/runtime/server/services/authjs/nuxtAuthHandler.ts#L152)

This code is always runned when jwt callback run like refresh tab , open browser.
So it works well with refreshed tab while browser running.
But it's not working with two conditions.
1. browser closed
2. token expired

Then as soon as browser open, the token is updated. And session-token cookie should be updated too matched new token. But somehow even if setCookie code was run, but cookie is still same as previous session-token cookie.
Maybe.. there might be bug with nuxt initialize code with cookie and update cookie after jwt callback logic.

### Additional context
![업데이트되야할 쿠키토큰](https://github.com/sidebase/nuxt-auth/assets/39736691/12a81b9b-314d-4312-acf7-ff5eb26a1ff0)
This cookie should be updated to browser cookie

![실제 쿠키토큰](https://github.com/sidebase/nuxt-auth/assets/39736691/644bf16b-2e96-4187-9fbf-6c6c65ee19ee)
But after code run, cookie is still same as before.

**Comment by quroom** [comment]
I am not sure what the problem is.. but I modified directus code.
now it works properly what I am expecting.

**Comment by quroom** [comment]
It's not solved..
It sometimes occurs , it makes me crazy..
I guess I need to give up using nuxt-auth based on next-auth.
It's not frome nuxt-auth, it's more related to next-auth.
And it's an old issue discussed many times in next-auth repo.
https://github.com/nextauthjs/next-auth/discussions/1455
https://github.com/nextauthjs/next-auth/issues/2071
https://github.com/nextauthjs/next-auth/issues/2129
https://github.com/nextauthjs/next-auth/discussions/3941
All of them are related issue. but there isn't realy solution.
Maybe some comments can be workaround but not real solution.

I hope someday it will be solved. Then auth package can be more valuable

**Comment by itsmeny** [comment]
I also face this issue....

**Comment by KhaledAlMana** [comment]
same problem

**Comment by zoey-kaiser** [comment]
Hmm, interesting issue. As you pointed out it seems to be more related to authjs, then our module. 

I have used refresh tokens inside the JWT countless times before. I would follow these steps to continue with this issue:

- Add a refresh provider example for authjs
- See if applying our refresh logic fixes your issue
- continue investing 

However, as you already pointed our numerous issues in the nextauth repo, it may not be the fix. However, we are also now beginning the migration to authjs, which may fix this issue. Keep an eye on #673 for updates on this!

**Comment by zoey-kaiser** [comment]
Closed due to inactivity.
