### ISSUE TITLE
useAuth() not defined when using custom login page

### ISSUE THREAD

**Issue by baseerx** [sidebase/nuxt-auth#499]
### Environment

<template>
  <div
    class="container-fluid bg-gradient-to-b from-green-600 to-green-400 h-screen w-full flex items-center justify-center"
  >
    <div class="bg-white p-20 w-1/3 rounded-md">
      <form
        @submit="mySignInHandler"
        class="flex flex-col items-center justify-center gap-6 w-full"
      >
        <input
          type="text"
          placeholder="Username"
          class="text-black rounded-md w-full py-2 px-2"
          v-model="username"
        />
        <input
          type="password"
          placeholder="password"
          class="text-black rounded-md w-full py-2 px-2"
          v-model="password"
        />
        <button
          type="submit"
          class="rounded-md px-8 py-2 bg-green-500 text-white"
        >
          Login
        </button>
      </form>
    </div>
  </div>
</template>
<script setup>
import {ref} from "vue";
definePageMeta({
    auth: {
        unauthenticatedOnly: true,
        navigateAuthenticatedTo: '/',
    }
})

const { signIn } = useAuth()

const username = ref("");
const password = ref("");
const mySignInHandler = async () => {
  const { error, url } = await signIn('credentials', {
    username: username.value, // Use username.value to get the actual value from the ref
    password: password.value, // Use password.value to get the actual value from the ref
    redirect: false
  });

  if (error) {
    // Do your custom error handling here
    alert('You have made a terrible mistake while entering your credentials');
  } else {
    // No error, continue with the sign in, e.g., by following the returned redirect:
    return navigateTo(url, { external: true });
  }
};

</script>
<style scoped></style>

### Reproduction

<template>
  <div
    class="container-fluid bg-gradient-to-b from-green-600 to-green-400 h-screen w-full flex items-center justify-center"
  >
    <div class="bg-white p-20 w-1/3 rounded-md">
      <form
        @submit="mySignInHandler"
        class="flex flex-col items-center justify-center gap-6 w-full"
      >
        <input
          type="text"
          placeholder="Username"
          class="text-black rounded-md w-full py-2 px-2"
          v-model="username"
        />
        <input
          type="password"
          placeholder="password"
          class="text-black rounded-md w-full py-2 px-2"
          v-model="password"
        />
        <button
          type="submit"
          class="rounded-md px-8 py-2 bg-green-500 text-white"
        >
          Login
        </button>
      </form>
    </div>
  </div>
</template>
<script setup>
import {ref} from "vue";
definePageMeta({
    auth: {
        unauthenticatedOnly: true,
        navigateAuthenticatedTo: '/',
    }
})

const { signIn } = useAuth()

const username = ref("");
const password = ref("");
const mySignInHandler = async () => {
  const { error, url } = await signIn('credentials', {
    username: username.value, // Use username.value to get the actual value from the ref
    password: password.value, // Use password.value to get the actual value from the ref
    redirect: false
  });

  if (error) {
    // Do your custom error handling here
    alert('You have made a terrible mistake while entering your credentials');
  } else {
    // No error, continue with the sign in, e.g., by following the returned redirect:
    return navigateTo(url, { external: true });
  }
};

</script>
<style scoped></style>

### Describe the bug

mentioned code shows useAuth() not defined. there is no way mentioned in docs which guides regarding its import.

**Comment by quroom** [comment]
Which version of nuxt-auth are you using?
If it's prior to v0.5, you should call useSession() instead of ustAuth()

https://sidebase.io/nuxt-auth/application-side#overview

**Comment by andreasvirkus** [comment]
> Which version of nuxt-auth are you using? If it's prior to v0.5, you should call useSession() instead of useAuth()

...as he's using `useAuth()`, isn't that just an indication that he's using 0.5?

**Comment by zoey-kaiser** [comment]
As there has not been a response by @baseerx for a while, I will close this issue. @baseerx if the issue still presists, please provide a reproduction to the issue on StackBlitz, so I can investigate futhur!
