### ISSUE TITLE
Use nuxt nitro config to set host and port in local development

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#50]
### Describe the feature

Currently in dev-mode we set the origin for the user unless they set their own `origin` using the module config:
https://github.com/sidebase/nuxt-auth/blob/44a159c5d936869c3c9d5e41d337a1578174bec1/src/module.ts#L61-L62

This leads to problems when users have their app running during development on a non-standard port (or host) during development. It does not lead to a production problem as we enforce a manually set `origin` during production for security reasons.

On discord:
- a diuscord user  @ThatTonybo actually faces this problem [1]
- @danielroe provided a solution that (at the moment) works to determine host and port during development: https://discord.com/channels/473401852243869706/473406398005248011/1044975921033130088

Let's apply the solution as discussed on discord. We should ensure a fallback to `3000` in case nothing is set:
```
nuxt.options.server.port || process.env.PORT || process.env.NITRO_PORT || 3000
```

Let's: 
- [ ] make port-detection dynamic
- [ ] make host-detection dynamic

[1]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/25911230/203579807-9b1756fc-82d2-440f-afd7-df28221e3a2f.png">

**Comment by JoaoPedroAS51** [comment]
Hi! I'm pretty sure you can achieve this using [requrl](https://github.com/unjs/requrl). I tested it my self and seems to work.

You can also create a wrapper for the function, so it gets the request event automatically:
```js
import _getURL from 'requrl'

export const getURL = (includePath?: boolean) => _getURL(useRequestEvent()?.node.req, includePath)
```

Then pass the `basePath` option to public runtimeConfig and change the `_getBasePath` in your composable to:
```js
const _getBasePath = () => joinURL(getURL(), useRuntimeConfig().public.auth.basePath)
```

In server handler, use without the wrapper and pass the event:
```js
import getURL from 'requrl'

const getInternalNextAuthRequestData = async (event: H3Event): Promise<RequestInternal> => {
   const nextRequest: Omit<RequestInternal, 'action'> = {
     host: getURL(event.node.req),
   }
}
```

By the way, your package is really awesome, nice work! :)

**Comment by BracketJohn** [comment]
Thanks for the proposal + the praise ❤️ 

I think that the proposal would actually work, we can try it out @ironicusername (#51)
