### ISSUE TITLE
can't save google users to my strapi backend

### ISSUE THREAD

**Issue by thejacer87** [sidebase/nuxt-auth#508]
### Environment

```
$ npx nuxi info
Nuxi 3.6.3                                                            11:21:25 p.m.
                                                                      11:21:25 p.m.
RootDir: /home/jbennest/Development/Lyrext                            11:21:25 p.m.
Nuxt project info:                                                    11:21:25 p.m.

------------------------------
- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Describe the bug

I think I might be doing something wrong, or misunderstanding something. But I will lay out what I want, what is happening now, and what i think might be going wrong.

**What I want:**

Nuxt 3 frontend, strapi backend. I want users of my site to be able to make accounts with email and google auth (more later).

When they sign in/up via email or google, a user is created in strapi.

**What is happening:**

Using nuxt-auth, I setup the credentials provider. Using email and pwd, it worked and I can see the user that was generated in strapi.

But when I used the google auth, it authenticates just fine, but no data was saved to strapi.

**What I think is happening**
Because the redirect url and all settings with nuxt-auth just use the nuxt frontend url: localhost:3000, nothing ever gets sent to the strapi backend.

I assume the nuxt-auth module is setup to only send the oauth request to: http://localhost:3000/auth/connect/callback/google

I can see no way to set it to, what i assume to be correct, http://localhost:1337/api/connect/google/callback.

but even if I go to that url manually in the browser, or via a button click it redirects to  http://localhost:1337/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider

even though the url is set in my google console

any help is appreciated

i know there's probably just some little setting i messed up
![image](https://github.com/sidebase/nuxt-auth/assets/6412919/3c092d3f-e1be-4736-8e79-a15d062f8ad0)

**Comment by zoey-kaiser** [comment]
Hi @thejacer87,

You will have to setup and handle the user creation logic differently for each provider. I assume that for the credentials provider you are using the authorize function, to create the user. Sadly this won't work for the OAuth providers then. 

I would recommend you look into the callbacks of NextAuth: https://next-auth.js.org/configuration/callbacks and hook into the Session callback, to create or update the user in your database. 

I hope this response helps you. I will close this issue for now, if you still run into issues feel free to respond and ill reopen the issue!
