### ISSUE TITLE
useFetch() server-side defaults to http://localhost - ignoring AUTH_ORIGIN

### ISSUE THREAD

**Issue by ilanc** [sidebase/nuxt-auth#509]
### Environment

RootDir: /code/web/nuxt/auth/nuxt-auth-bug-useFetch                                                                                                                                11:40:23
Nuxt project info:                                                                                                                                                                 11:40:23

------------------------------
- Operating System: Linux
- Node Version:     v18.12.1
- Nuxt Version:     3.4.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      typescript, modules, auth
- Runtime Modules:  @nuxtjs/tailwindcss@6.6.7, @sidebase/nuxt-auth@0.6.0-beta.2
- Build Modules:    -
------------------------------

### Reproduction

There's a public repo [here](https://github.com/ilanc/nuxt-auth-bug-useFetch) with repro instructions in the readme.

```sh
git clone https://github.com/ilanc/nuxt-auth-bug-useFetch
cd nuxt-auth-bug-useFetch
yarn
cp .env.example .env
yarn dev --open
# see below
```

- browse to http://localhost:4001/example
- login with
  - username: jsmith
  - password: hunter2

Notice the `<pre>` tag which `useFetch()`s `/public/example.json` is showing `null`. Check the log message in the server console:
- `[nuxt] [request error] [unhandled] [500] fetch failed (http://localhost/api/auth/session?callbackUrl=http://localhost/example.json)`
- nb `http://localhost/` should be `http://localhost:4001/`

Now browse to another page and then return to `/example` - the `<pre>` tag is now working as expected.

### Describe the bug

`useFetch` server-side is not taking `PORT`,`AUTH_ORIGIN` into account.

`useFetch` client-side seems to work.

### Additional context

There are a couple other bug reports in the same vein:
- https://github.com/sidebase/nuxt-auth/issues/453
- https://github.com/sidebase/nuxt-auth/issues/503
- https://github.com/sidebase/nuxt-auth/issues/296

**Comment by septatrix** [comment]
I have a similar error though for me the URL is actually correct. Also I am not able to somehow circumvent this by using client side navigation as seems to be possible in your case...

`[nuxt] [request error] [unhandled] [500] [GET] "http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/": <no response> fetch failed`

**Comment by septatrix** [comment]
Downgrading to 0.5 is the only thing which works for me sadly

**Comment by ilanc** [comment]
There is a related nuxt issue here with /public static file routing (eg which affects the /public/example.json url I used here)

[here](https://github.com/nuxt/nuxt/issues/23589)

**Comment by zoey-kaiser** [comment]
Closed due to an old version. If anyone is still experiencing this issue, please check if it still exists in 0.8.0 and that the module has been setup using the new docs: https://auth.sidebase.io
