### ISSUE TITLE
Add Adapter Example: DynamoDB

### ISSUE THREAD

**Issue by JulienQNN** [sidebase/nuxt-auth#512]
### Describe the feature

Made an example of using nuxt-auth with [`@auth/dynamodb-adapter`](https://authjs.dev/reference/adapter/dynamodb) from authjs.dev.

I think it would be a good additional to show some examples of others Auth.js database Adapters. For this one i used Discord as provider.

Caveat : One bug related to dynamo was the `crypto` library not defined in the dynamodb Adapter, i managed to replace it by the [uuid](https://www.npmjs.com/package/uuid) package in : 

`nuxt-auth/playground-authjs/node_modules/@auth/dynamodb-adapter/index.js` 

import { v4 as uuidv4 } from 'uuid';

`crypto.randomUUID()` replaced by `uuidv4()`

Any idea of how to deal with this more properly ?

### Additional information

The dynamoDB table can be generated here [`https://authjs.dev/reference/adapter/dynamodb#default-schema`](dynamoDB-default-schema)

**Comment by guylil** [comment]
For anyone who came here from google 

I encountered in the error :
[next-auth][error][adapter_error_createUser] 
https://next-auth.js.org/errors#adapter_error_createuser crypto is not defined {
  message: 'crypto is not defined',
  stack: 'ReferenceError: crypto is not defined\n' +


I solved the issue by setting the Node.js version to 20 in the deployment
