### ISSUE TITLE
NextAuth >= v4.23.0 Breaking change: - Package subpath './core' is not defined by "exports"

### ISSUE THREAD

**Issue by sduduzog** [sidebase/nuxt-auth#514]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      experimental, postcss, build, vite, typescript, vue, nitro, modules, googleFonts, ui, htmlValidator, apollo, graphqlServer, content, runtimeConfig, app, devtools
- Runtime Modules:  @nuxtjs/google-fonts@3.0.2, @sidebase/nuxt-auth@0.6.0-beta.4, nuxt-icon@0.5.0, @nuxtjs/html-validator@1.5.2, @nuxthq/ui@2.7.0, @nuxt/content@2.7.2
- Build Modules:    -
------------------------------

### Reproduction

n/a

### Describe the bug

When doing a clean install with no package-lock.json, the next-auth package installed along with nuxt-auth module seem to have breaking changes in import namespaces used by the nuxtAuthHandler file.

### Additional context

A current workaround is pinning next-auth to v4.22.5

### Logs

```shell
ℹ Vite client warmed up in 8934ms                                                                                                                       01:51:59

[01:52:01]  WARN  (node-resolve plugin) Could not resolve import "next-auth/core" in C:\dev\monorepo\web\node_modules\@sidebase\nuxt-auth\dist\runtime\server\services\authjs\nuxtAuthHandler.mjs using exports defined in C:\dev\monorepo\web\node_modules\next-auth\package.json.


[01:52:01]  WARN  (node-resolve plugin) Could not resolve import "next-auth/core" in C:\dev\monorepo\web\node_modules\@sidebase\nuxt-auth\dist\runtime\server\services\authjs\nuxtAuthHandler.mjs using exports defined in C:\dev\monorepo\web\node_modules\next-auth\package.json.


[01:52:01]  WARN  (node-resolve plugin) Could not resolve import "next-auth/core" in C:\dev\monorepo\web\node_modules\@sidebase\nuxt-auth\dist\runtime\server\services\authjs\nuxtAuthHandler.mjs using exports defined in C:\dev\monorepo\web\node_modules\next-auth\package.json.


[01:52:01]  WARN  (node-resolve plugin) Could not resolve import "next-auth/core" in C:\dev\monorepo\web\node_modules\@sidebase\nuxt-auth\dist\runtime\server\services\authjs\nuxtAuthHandler.mjs using exports defined in C:\dev\monorepo\web\node_modules\next-auth\package.json.


[01:52:01]  WARN  (node-resolve plugin) Could not resolve import "next-auth/core" in C:\dev\monorepo\web\node_modules\@sidebase\nuxt-auth\dist\runtime\server\services\authjs\nuxtAuthHandler.mjs using exports defined in C:\dev\monorepo\web\node_modules\next-auth\package.json.


[01:52:01]  WARN  "next-auth/core" is imported by "node_modules/@sidebase/nuxt-auth/dist/runtime/server/services/authjs/nuxtAuthHandler.mjs", but could not be resolved – treating it as an external dependency.

✔ Nitro built in 5761 ms                                                                                                                          nitro 01:52:03

[01:52:03]  ERROR  [worker reload] [worker init] Package subpath './core' is not defined by "exports" in C:\dev\monorepo\web\node_modules\next-auth\package.json imported from C:\dev\monorepo\web\.nuxt\dev\index.mjs

  at new NodeError (node:internal/errors:399:5)
  at exportsNotFound (node:internal/modules/esm/resolve:361:10)
  at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
  at packageResolve (node:internal/modules/esm/resolve:872:14)
  at moduleResolve (node:internal/modules/esm/resolve:938:20)
  at defaultResolve (node:internal/modules/esm/resolve:1153:11)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
```

**Comment by Sparo** [comment]
Exact same problem here. My workaround also was to pin `next-auth`, but the version I have used is from the `nuxt-auth` docs: `next-auth@4.21.1`.

So `nuxt-auth` docs said that we should use `next-auth@4.21.1` I did that... but your solution sounds better.

**Comment by sduduzog** [comment]
> Exact same problem here. My workaround also was to pin `next-auth`, but the version I have used is from the `nuxt-auth` docs: `next-auth@4.21.1`.
> 
> So `nuxt-auth` docs said that we should use `next-auth@4.21.1` I did that... but your solution sounds better.

I think you can as far as up to v4.23.5. That's the last I'm on

**Comment by Salotronic** [comment]
same problem here...

**Comment by SherifAugustus** [comment]
faced the same problem, reverting to `next-auth@4.21.1` fixed it.

**Comment by bjornol** [comment]
same problem here...

**Comment by sduduzog** [comment]
@kennedyngigi4 just install the specific `next-auth` version to your project, then `nuxt-auth` will use that one

**Comment by AliBahadori41** [comment]
> next-auth@4.21.1

I had same issue and `next-auth@4.21.1` fixed it.

**Comment by RicLzPt** [comment]
Same problem

**Comment by RicLzPt** [comment]
4.23.2 same issue.

**Comment by TakiMoysha** [comment]
Had the same error when using `yarn`. I switched to `npm` and the problems went away.

**Comment by dingkai031** [comment]
Hello,I'm also having this problem. What does pinning mean and how to do that?

Thanks

**Comment by sduduzog** [comment]
@dingkai031 in the `package.json file` make sure that the `next-auth` version number does not have a tilde (`^`) so it should look like `"next-auth": "4.21.1"`

After removing it, make sure to run an install command again so that the pinned version is the one installed

**Comment by zoey-kaiser** [comment]
Hi @sduduzog and everyone else!

I just tested the newest version of NextAuth (4.23.2) and it seems to have resolved the issue! You should be able to use the newest version again, as they undid their change with the exports! Therefore I will be closing this issue!

**Comment by greenacresfoundation** [comment]
#Hi @sduduzog and everyone else!

I just tested the newest version of NextAuth (4.23.2) and it seems to have resolved the issue! You should be able to use the newest version again, as they undid their change with the exports! Therefore I will be closing this issue!

Hey just tested this with 4.23.2 and the bug is still there. This shouldn't be closed yet.

**Comment by RicLzPt** [comment]
> #Hi @sduduzog and everyone else!
> 
> I just tested the newest version of NextAuth (4.23.2) and it seems to have resolved the issue! You should be able to use the newest version again, as they undid their change with the exports! Therefore I will be closing this issue!
> 
> Hey just tested this with 4.23.2 and the bug is still there. This shouldn't be closed yet.

Yes. The erro remains

**Comment by zoey-kaiser** [comment]
Too bad, Ill keep this open. Maybe someone wants to open a PR on the offical NextAuth repo or pressure them more into reverting this change! I had mentioned it before in the commit comments, but received no answer...

**Comment by RomainMazB** [comment]
I confirm that 4.32.2 doesn't fix the issue, I rollback to 4.21.1 as mention previously.

**Comment by RicLzPt** [comment]
I upgraded to 4.24.3 and de issue continue

**Comment by ize-302** [comment]
For anyone else wondering how to go about this

Just run this 

`npm install next-auth@4.21.1 --save-exact=true`

**Comment by ReaganM02** [comment]
@RicLzPt  I am not sure if this will help you, but I have the same issue and it looks like it is fixed by adding `npm install next-auth@4.21.1 --save-exact=true`

https://stackblitz.com/edit/nuxt-starter-77eysh?file=package.json

**Comment by RicLzPt** [comment]
> @RicLzPt I am not sure if this will help you, but I have the same issue and it looks like it is fixed by adding `npm install next-auth@4.21.1 --save-exact=true`
> 
> https://stackblitz.com/edit/nuxt-starter-77eysh?file=package.json

Thanks for your answer. I did this anteriorly and resolved. My intention is give a feedback that the error continue.

**Comment by GoudekettingRM** [comment]
@zoey-kaiser is there a timeline for the upgrade? Would the upgrade cause major backwards incompatible changes In the way Nuxt Auth is used?

I.e. I want to implement Nuxt Auth in a new app, but if the fixed version is soon to come out and works mainly differently, I might focus my time elsewhere for the time being

**Comment by andreasvirkus** [comment]
I think `next-auth@4.22.5` is the latest working version, see if you still have the vulnerability warning with that version?

**Comment by zoey-kaiser** [comment]
> @zoey-kaiser is there a timeline for the upgrade? Would the upgrade cause major backwards incompatible changes In the way Nuxt Auth is used?

Sadly we are kind of stuck between two (non optional) solutions here.

1.) NextAuth was updated to partially use the new authjs infrastructure, which is why the breaking change happened. Rewriting our module to use their new architecture, would be a good amount of work and would need to be repeated once authjs is completely out (as we can then remove NextAuth completely)
2.) Switch to authjs under the hood, removing NextAuth completely. The issue with this, is that authjs, is still in "experimental" and is missing some features, we are still waiting for (see #117)

> Also, as a sidenote, when having next-auth@4.21.1 installed, I'm getting the following vulnerability warning:

The good news about this: It does not matter for NuxtAuth. The vulnerability has to do with the middleware provided by NextAuth. As we provide our own middleware and do not use theirs, this vulnerability does not apply to NuxtAuth!

See https://github.com/advisories/GHSA-v64w-49xw-qq89

**Comment by razbakov** [comment]
4.21.1 works only in dev mode, but breaks in build:

```
(node-resolve plugin) Could not resolve import "next-auth/core" in node_modules/@sidebase/nuxt-auth/dist/runtime/server/services/nuxtAuthHandler.mjs using exports defined in node_modules/@sidebase/nuxt-auth/node_modules/next-auth/package.json.
```

**Comment by yuelongh** [comment]
just to say I used next-auth@4.22.5 and the baseURL set in auth object inside nuxt.config.ts I still get "http://127.0.0.1:3000/api/auth/signin/credentials" for signinUrl  and callbackURL rather then the baseURL set by myself.

next-auth@4.21.1 works okay!

**Comment by davidlemaitre** [comment]
@yuelongh Same config here. I resolved by setting `NEXTAUTH_URL` environment variable.

**Comment by agracia-foticos** [comment]
Same issue

**Comment by SiamGamerAlbion** [comment]
same issue

**Comment by tukutela** [comment]
yep same, what a bummer! thanks nuxt-auth team for your work!

**Comment by marwenbk** [comment]
this broke our site

**Comment by Fexxix** [comment]
Hi there, I added these two lines in the `next-auth`'s `package.json` and it fixed the development version at least.
```json
"./core": {
      "types": "./core/index.d.ts",
      "default": "./core/index.js"
    },
```
I know this won't work in production and even in development it's only a temporary fix. I'm on `next-auth`'s `4.24.5` version, should I revert to an older version?

**Comment by AdytZZa22** [comment]
Same issue. `4.22.5` works fine, but there is still a warning: `Could not resolve import "next-auth/core"`

**Comment by dandonovan78** [comment]
> For anyone else wondering how to go about this
> Just run this
> `npm install next-auth@4.21.1 --save-exact=true`

It felt a bit weird to have to install next-auth when @sidebase/nuxt-auth includes it, adding the following to my package.json seems to work to pin the version (using npm):
 "overrides": {
    "@sidebase/nuxt-auth": {
      "next-auth": "4.21.1"
    }
  },

**Comment by phaberest** [comment]
Do we have any possible update on this matter?

Locking version to `4.21.1` makes it work but exposes to a security issue reported on https://github.com/advisories/GHSA-v64w-49xw-qq89

**Comment by zoey-kaiser** [comment]
Hi everyone!

We are now beginning this migration, for more information please keep an eye on [#673](https://github.com/sidebase/nuxt-auth/issues/673). As this issue will be fixed through this migration, I will now close this issue.

Thank you for all the hard work investigating!

**Comment by v0id-4lpz** [comment]
Tested today and `@sidebase/nuxt-auth@0.7.2` + `next-auth@4.22.5` don't work as the doc says.

Working with `@sidebase/nuxt-auth@0.7.2` + `next-auth@4.21.1`

**Comment by zoey-kaiser** [comment]
> ❌ Tested today and @sidebase/nuxt-auth@0.7.2 + next-auth@4.22.5 don't work as the doc says.

Thanks for checking this. We also use `next-auth@4.21.1` in our apps, so I will adjust the docs to recommend that version ❤️

**Comment by itsalfredakku** [comment]
Here’s a compatible solution that works after extensive research:

`@sidebase/nuxt-auth@0.7.2` with `next-auth@4.21.1` resolved the issue.

**Comment by razbakov** [comment]
@zoey-kaiser 
Pinning version is not a solution.

Next.js@13.5.11 is no longer receiving security updates since 2024-12-21.
It's a critical security issue.
