### ISSUE TITLE
Issue with adding origin 

### ISSUE THREAD

**Issue by SherifAugustus** [sidebase/nuxt-auth#515]
### Environment

- Operating System: Windows_NT
- Node Version:     v16.19.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      modules, auth, i18n, googleFonts, googleSignIn, headlessui
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/google-fonts@3.0.1, @nuxtjs/i18n@8.0.0-beta.13, nuxt-headlessui@1.1.4, nuxt-swiper@1.1.1, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/device@3.1.0, nuxt-vue3-google-signin@0.0.9, @sidebase/nuxt-auth@0.6.0-beta.4
- Build Modules:    -

### Reproduction

n/a

### Describe the bug

I still get the AUTH_NO_ORIGIN production error whenever I try to deploy my application even when I add my `origin` to the `auth` object in the `nuxt.config.ts` file  

### Additional context

The documentation I followed: https://sidebase.io/nuxt-auth/configuration/nuxt-config

### Logs

```shell
AUTH_NO_ORIGIN: No origin - this is an error in production, see https://sidebase.io/nuxt-auth/resources/errors. You can ignore this during development
```

**Comment by andrei-hudovich** [comment]
Yeah, `auth` settings in the `nuxt.config.ts` are not honored.

**Comment by Saganic** [comment]
Any news on this?

**Comment by andrei-hudovich** [comment]
`auth.origin` must be `auth.baseURL`, seems like the docs haven't been updated...

**Comment by zoey-kaiser** [comment]
> auth.origin must be auth.baseURL, seems like the docs haven't been updated...

This is a change done in `v0.6` and upwards. You can find the correct documentation for this when selecting the correct version from the module headers.

https://sidebase.io/nuxt-auth/v0.6/configuration/nuxt-config

As this seems to be a misunderstanding, I will close this issue and refer you to the documentation or to #368 if there are any issues with deploying to another baseUrl.

**Comment by FerhatCengz** [comment]
To resolve the AUTH_NO_ORIGIN error in your Nuxt.js project, you need to ensure that your environment variable is correctly set and properly used in your Nuxt configuration. Here are the steps to fix this issue:

First, set the AUTH_ORIGIN environment variable in your .env file. For example:

.env
```bash
AUTH_ORIGIN=http://localhost:3000
```


2.Configure Nuxt to Use the Environment Variable:

In your nuxt.config.ts file, ensure that the auth module uses the AUTH_ORIGIN environment variable. Here is how you can do it:

```javascript
    auth: {
    baseURL: process.env.AUTH_ORIGIN
   }
```

**Comment by fyyyyy** [comment]
As of 0.6.7 it needs to be 
   auth: {
    baseURL: process.env.AUTH_ORIGIN + "/api/auth"
   }

otherwise it will thrown an error  _No match found for location with path "/session"_
