### ISSUE TITLE
Production redirect_uri is always localhost - [next-auth][warn][NEXTAUTH_URL] 

### ISSUE THREAD

**Issue by WilliamFalci** [sidebase/nuxt-auth#516]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.15.1
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, app, plugins, runtimeConfig, build, modules, auth, sitemap, css, googleFonts, elementPlus, vite, routeRules
- Runtime Modules:  @funken-studio/sitemap-nuxt-3@4.0.4, @nuxtjs/google-fonts@3.0.1, @vueuse/nuxt@10.1.2, @pinia/nuxt@0.4.9, @sidebase/nuxt-auth@0.6.0-beta.4, @element-plus/nuxt@1.0.4, @nuxt/image-edge@1.0.0-28020728.5df24eb
- Build Modules:    -
------------------------------

### Reproduction

https://discord.com/oauth2/authorize?client_id=981994406955581492&scope=identify%20email&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fdiscord&state=bWw3hxRDJHeVVrgTkXh8hRZXI3U1KygkfNT6M1OgaN8

### Describe the bug

PM2 configuration
`module.exports = {
    apps: [
      {
        name: 'Website',
        exec_mode: 'cluster',
        instances: 'max',
        port: '8800',
        script: './.output/server/index.mjs',
        log_date_format: "YYYY-MM-DD HH:mm Z",
        combine_logs: true,
        log_file: '/home/ubuntu/xxx/_LOGS/WEBSITE/logs.log'
      }
    ]
  }`
  
  Nuxt config auth conf:
  `auth: {
        computed: {
            origin:'https://xxxxx.tv'
        },
        provider: {
            type: 'authjs',
        }
    },`

### Additional context

Im using ^0.6.0-beta.4

Before open this issue I read everything I found on every git/stackoverflow ect I tried everything but nothing.

The only way I found to not receive the error "AUTH_NO_ORIGIN" has been place the "origin" under the "computed" section, but still the redirect_uri is on localhost.

I tried to set the env variables like docs, then I tried with the "NUXT_" prefix, then I tried to inject by pm2, then I tried to add the env variable to the runtimeConfig but nothing... everything I do the redirect_uri is on localhost and I receive always the warn:

`[next-auth][warn][NEXTAUTH_URL] `

I spent more then 5 hours on this error, someone can help me please?

**Comment by asokr** [comment]
Try to use env conf in your pm2 config
 `    {
      name: 'example',
      port: '3001',
      exec_mode: 'cluster',
      instances: 'max',
      script: './lk/server/index.mjs',
      env: {
        "NEXTAUTH_URL": "https://example.com/api/auth",
        "AUTH_ORIGIN": "https://example.com/"
      }
    } `

**Comment by dhondtlaurens** [comment]
I've come across a similar issue that stemmed from not configuring the `NEXTAUTH_URL`. While going through the documentation ([link](https://sidebase.io/nuxt-auth/configuration/nuxt-config#module-nuxtconfigts)), it wasn't immediately apparent that setting this variable was necessary. I had assumed that defining the origin and the default basePath ('/api/auth') would suffice.

It's worth noting that this behavior might be disrupted due to the error detailed in this GitHub issue: [sidebase/nuxt-auth#515](https://github.com/sidebase/nuxt-auth/issues/515).

After some troubleshooting, I found that the only reliable setup for now is to establish both the `NEXTAUTH_URL` and `AUTH_ORIGIN` environment variables in a production environment.

**Comment by mohdrasbi** [comment]
> I've come across a similar issue that stemmed from not configuring the `NEXTAUTH_URL`. While going through the documentation ([link](https://sidebase.io/nuxt-auth/configuration/nuxt-config#module-nuxtconfigts)), it wasn't immediately apparent that setting this variable was necessary. I had assumed that defining the origin and the default basePath ('/api/auth') would suffice.
> 
> It's worth noting that this behavior might be disrupted due to the error detailed in this GitHub issue: [sidebase/nuxt-auth#515](https://github.com/sidebase/nuxt-auth/issues/515).
> 
> After some troubleshooting, I found that the only reliable setup for now is to establish both the `NEXTAUTH_URL` and `AUTH_ORIGIN` environment variables in a production environment.

I've faced the same issue and setting `NEXTAUTH_URL` alongside `AUTH_ORIGIN` worked. Thanks @dhondtlaurens!

**Comment by zoey-kaiser** [comment]
Yes, setting both is currently only the way to properly make this work. Does someone want to update the docs to make this more clear, otherwise ill put it on my TODO!
