### ISSUE TITLE
ReferenceError: useAuth is not defined

### ISSUE THREAD

**Issue by glennovische** [sidebase/nuxt-auth#517]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `app`, `build`, `runtimeConfig`, `modules`, `css`, `plugins`, `postcss`, `vite`, `auth`, `experimental`
- Runtime Modules:  `@sidebase/nuxt-auth@0.5.0`, `nuxt-vitest@0.6.12`, `nuxt-lodash@2.5.0`, `@formkit/nuxt@1.0.0-beta.9-f64c966`, `@vueuse/nuxt@10.3.0`, `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

### Describe the bug

In a component i use `const { data } = useAuth();` everything works as expected but when writing tests with vitest for this component I get the following error while running the test

```
ReferenceError: useAuth is not defined
 ❯ setup components/Navigation.vue:43:18
```

Eventually this seem to be a problem with imports or something.

In my test I mock useAuth like this:
```
mocks: {
        useAuth: () => ({
          isAuthenticated: true,
          user: {
            name: 'John Doe',
          },
        }),
      },
```

but I just can't get pass this ReferenceError because the error is not in the test but in the component

anyone any idea on how to fix this?

**Comment by dschreij** [comment]
Mocking composables in nuxt is a big pain. In any case, you cannot mock useAuth like this. mocks in vue-test-utils is to mock entities in the vue component instance. For imported functions you will need to use `vi.mock` or `jest.mock`. If you are using vitest, you could also have a look at https://github.com/danielroe/nuxt-vitest#mocknuxtimport. However, I have had little success with this, probably due to https://github.com/danielroe/nuxt-vitest/issues/169, so even though have put some more info on this problem here, I haven't solved it myself yet either.

**Comment by TTtigers** [comment]
Here is a document about useAuth, you can try, if it helps you！！！
[https://useauth.dev/docs/getting-started/](url)

**Comment by zoey-kaiser** [comment]
Hi @glennovische Did the response by @dschreij help you? I don't have much to add to what was said, so I will close this issue for now. If you need furthur help, feel free to respond and we can continue the conversation!

**Comment by glennovische** [comment]
@dschreij Thanks for responding. In the other thread did you test `mockNuxtImport`?? If so I will give it a try aswell.

**Comment by dschreij** [comment]
Hi @glennovische I did use `mockNuxtImport` which did the trick for me. I didn't have much success with `vi.mock` in a Nuxt environment so can't really tell if it is possible to get things to work with that too. I think mockNuxtImport does some 'magic' stuff with hoisting and auto imports, so it may be preferable to use it in any case if it is all the same to you.
