### ISSUE TITLE
Unable to use getServerSession in server api route that starts with /api/auth

### ISSUE THREAD

**Issue by chriscdn** [sidebase/nuxt-auth#535]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      sourcemap, app, components, css, build, vite, modules, auth, proxy, runtimeConfig
- Runtime Modules:  @nuxt/image-edge@1.0.0-rc.2-28257829.3628546, @sidebase/nuxt-auth@0.6.0-beta.5, @nuxt-alt/proxy@2.3.2
- Build Modules:    -
------------------------------

### Describe the bug

I created a `/server/api/` set of endpoints for connecting and disconnecting existing social accounts. I placed these files in a directory named `/server/api/auth-connect`. In these files, the `getServerSession` returns `undefined` since the api route (`/api/auth-connect/`) starts with the string `/api/auth`.

I traced the problem to the [getServerSession](https://github.com/sidebase/nuxt-auth/blob/92f44bcc1550497ce1ee2a18809047c631796eba/src/runtime/server/services/authjs/nuxtAuthHandler.ts#L185) method:

```js
export const getServerSession = async (event) => {
  const authBasePath = useRuntimeConfig().public.auth.computed.pathname;
  if (event.path && event.path.startsWith(authBasePath)) {
    return null;
  }

  // .....
};
```

In my instance, `authBasePath` resolves to `/api/auth`.  Since `event.path` resolves to `/api/auth-connect/`, the check passes and therefore returns null.

I can't comment on why this check is necessary, but doubt all routes that start with `auth` should be excluded from using this method.

**Comment by adesousa** [comment]
Same here ... 
2 days, I'm raging against the version trying to find something ! And here is @chriscdn finding the exact same problem !

In my case I changed the base url to baseURL: '/api/admin/auth' and got same problem.

The try catch gave me this information: 

`  statusCode: 500,
  fatal: false,
  unhandled: false,
  statusMessage: 'Tried to get server session without setting up an endpoint to handle authentication (see https://github.com/sidebase/nuxt-auth#quick-start)',
  data: undefined
}`

**Comment by adesousa** [comment]
As a workaround I decided to change getServerSession by : 
`
const authBasePath = useRuntimeConfig().public.auth.computed.pathname
const session = await $fetch(authBasePath + '/session', {
    method: 'GET',
    headers: event.headers
  })
`
It's working fine so far. 🚀

**Comment by zoey-kaiser** [comment]
Closed due to an old version. If anyone is still experiencing this issue, please check if it still exists in 0.8.0 and that the module has been setup using the new docs: https://auth.sidebase.io
