### ISSUE TITLE
failed, reason: certificate is not yet valid

### ISSUE THREAD

**Issue by kennedyngigi4** [sidebase/nuxt-auth#538]
### Describe the bug

While running nuxt app in production I get next-auth error stating;

callbackUrl=<website_url> failed, reason: certificate is not yet valid 

How can I solve the issue? It only occurs on server(VPS)

Here is my package.json
`
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.2",
    "@sidebase/nuxt-auth": "0.5.0",
    "nuxt": "^3.7.4",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "next-auth": "^4.22.5",
    "nuxt-snackbar": "^1.0.3",
    "pinia": "^2.1.6",
    "pinia-plugin-persistedstate": "^3.2.0"
  }
}
`

**Comment by zoey-kaiser** [comment]
Hi @kennedyngigi4, from just the error message, I assume this may be related to SSL certificates. Could you please provide more context for when and how this happens?

- Full error message
- Nuxt Config
- Any files relating to NuxtAuth
- Deployment information (where + how)
- Maybe a reproduction?
