### ISSUE TITLE
After sign out, can access protected page with browser back key.

### ISSUE THREAD

**Issue by quroom** [sidebase/nuxt-auth#548]
### Reproduction

1. Go nuxt-auth example site
https://nuxt-auth-example.sidebase.io/
2. Login
3. Go globally protected page
4. Press back key in browser

### Describe the bug

I don't think it's predictable result.
I guess it's related to browser behavior too.
But I would like to ask, Is there workaround to prevent this behavior?
It can be unsafe for security.

**Comment by quroom** [comment]
I left #544 But there is no answer.. So I posted this in issue section.
I will close one of them when I get answer.

**Comment by zoey-kaiser** [comment]
Hi @quroom! 

`nuxt-auth-example` is running on a pretty old version of NuxtAuth (0.4.3). I am currently working on upgrading it to the new version 0.6.0. 

We have a couple of apps running on v0.5.0 and above, where I was not able to replicate this issue. Therefore, this issue has already been resolved and we just need to upgrade the example! Thanks for the heads up!

**Comment by quroom** [comment]
@zoey-kaiser 
Could you give me small example in stackbliz or codesandbox?
I was trying to set that env in codesandbox. but I got lots of errors because of package version problem.
And I am also using nuxtauth v0.5 but in my env it still happens.

**Comment by quroom** [comment]
You made a branch "add-local-provider"
https://github.com/sidebase/nuxt-auth-example/tree/add-local-provider
It works well.
Thanks for made it.

**Comment by quroom** [comment]
In my guess, It's more related to browser behavior.
I am using jwt token for backend authentication after oauth login.
After logout, the browser has previous data with back key.
It's common behavior in browser I guess.
So I need to check user really login or not. like with logout timestamp something in backend.

It should also fixed in nuxt-auth side.. but before that, I also need to check the user is really logged in or just api called by temporary status with back key.

**Comment by quroom** [comment]
Anyway, I implement logic in backend response 401 error to frontend.
I made logic write logout time in backend by logout in frontend.
Then even though client send api with live access token to backend, backend compares the user login time and logout time.
So if logout time > login time, it returns 401 error.
That makes redirect to login page in my custom error.vue page :)

That's the my logic.

But it still remains why it has access_token after logout.

**Comment by zoey-kaiser** [comment]
Hi @quroom,

I am currently working on setting up the final changes for the release of 0.6.0. Therefore the NuxtAuth Example is currently using the local provider, as I wanted to test it thoroughly in a production environment. Once i have concluded my testing I will be reverting it back to the Authjs provider.

I was testing your issues on a couple of other production apps we are using and I was not able to replicate it. Which providers are you using?

> I have spent few hours to set up nuxt-auth v0.6.0 But I was just getting errors, when I tried to signin.

I would recommend you use [`create-sidebase`](https://sidebase.io/sidebase/welcome/quick-start) to create a new Nuxt3 application. It automatically sets up NuxtAuth for you. 

`create-sidebase` still uses 0.5, but you can follow the following migration steps:

- Upgrade the devDependency `@sidebase/nuxt-auth` to version `0.6.0-rc.1`
- Remove the NextAuth dependecy
- Add a new `peerDependency` of NextAuth (version < 0.23)
- Adjust your `nuxt.config` to match the [new config style](https://sidebase.io/nuxt-auth/v0.6/configuration/nuxt-config)

**Comment by quroom** [comment]
@zoey-kaiser 
Thanks for your kindness.
I am using google and naver provider.

I will try samething when you are done with 0.6.0 release.

**Comment by phoenix-ru** [comment]
@quroom Is this still reproducible on your end?

**Comment by quroom** [comment]
@phoenix-ru I will reponse when I am done test.
Today is holiday in south korea :)

**Comment by phoenix-ru** [comment]
bump @quroom

**Comment by quroom** [comment]
> bump @quroom

Sorry for late response.
It isn't issue anymore.
So I close this.
