### ISSUE TITLE
Add possibility to disable signOut endpoint

### ISSUE THREAD

**Issue by anjarupnik** [sidebase/nuxt-auth#555]
### Describe the feature

It would be nice if it would be possible to disable signOut endpoint for local provider. In our application it is enough to do sign out on the frontend part without making a backend call. Currently this is not possible as it throws error if no proper endpoint provided. In @nuxtjs/auth-next that was done by setting endpoint to false:
![Screenshot 2023-10-23 at 14 14 16](https://github.com/sidebase/nuxt-auth/assets/31987405/ccf02f8e-4238-44bc-9a52-04aab217b92a)

Would it be possible to add this?

**Comment by IsraelOrtuno** [comment]
I think this is a really nice feature.

What I actually do is to create my own composable as wrapper for `useAuth`. Here's an example of what you could do for now:

```ts
export const useAppAuth = () => {
  const { signOut, getSession } = useAuth()

  const logout = async () => {
    rawToken.value = null
    await getSession()
  }

  return { logout }
}

// ... Then use logout instead of signOut

const { logout } = useAppAuth()

await logout()
```

**Comment by zoey-kaiser** [comment]
Hi @anjarupnik 👋 

Just to make sure I understand you correctly, this would be required when you don't want to sign a user out, while making a backend call?

Could you not in theory define the backend logout logic inside the `logout` endpoint? I am sorry if I do not fully understand how you would want to use this feature. 😄

**Comment by anjarupnik** [comment]
Hi @zoey-kaiser,

No, the case is opposite. This would be used in case you don't have any logout endpoint and want to sign out user in your application. So signing out without making a backend call. It would do what @IsraelOrtuno workaround is doing: clearing token and reseting session data. Does this make it more clear? 😄

**Comment by anjarupnik** [comment]
Hi @zoey-kaiser, sure I will try this week to implement it if I get the time. Yes, indeed it is less secure but since token in our application is not valid for a long time we decided not to build the sign out endpoint. Previous auth library for Nuxt 2 had this options for disabling certain endpoints and I think it is nice to give that flexibility, even though, I agree that is better practice to have endpoint that will invalidate/delete the token.

**Comment by anjarupnik** [comment]
I've created a proposition for disabling signOut endpoint if you think it is good to add it. Otherwise above proposed workaround also works well.

**Comment by zoey-kaiser** [comment]
Released in https://github.com/sidebase/nuxt-auth/releases/tag/0.6.1
