### ISSUE TITLE
Authentication work on development but not on production

### ISSUE THREAD

**Issue by Johongirmirzo** [sidebase/nuxt-auth#563]
### Describe the bug

Sorry I don't understand where the bug is but I can provide it only code. Basically, everything working well in dev mode but when deployed, server is timing out, we've used fetch, axios, node-fetch but all return the same error. We've also hosted our app on netlify for test purposes if we made nginx config errors. And in that time it's returning error but when api request is successfull it's returning "can't read properties of undefined". But server is returning response. Here's code
```js
import CredentialsProvider from 'next-auth/providers/credentials'
import { NuxtAuthHandler } from '#auth';
import { NOT_HACKABLE } from '@/utils/constants';
import { loginUser } from '@/api/auth'
import { ENDPOINTS, BASE_URL } from '@/config/endpoints';
import axios from "axios";
import fetch from "node-fetch"

 
export default NuxtAuthHandler({
  pages: {
    signIn: "/authentication/login"
  },
  secret: 'my-billing-secret',
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    CredentialsProvider.default({
      name: 'Credentials',
      credentials: {
         email: { label: 'Email', type: 'text', placeholder: '(hint: jsmith)' },
         password: { label: 'Password', type: 'password', placeholder: '(hint: hunter2)' }
      },
      async authorize (credentials: any) {
        console.log("Env vars", process.env);
        console.log("Credentails data ", credentials);
        console.log("Credentails url ", `${BASE_URL}${ENDPOINTS.USER}/`);
        try {
          if(NOT_HACKABLE !== credentials.password) {
            const userLoginData = {
              username: credentials.pnfl,
              password: credentials.password
            }
           const loginResp = await loginUser(userLoginData)
           
           const userResp = await axios.get(`${BASE_URL}${ENDPOINTS.USER}/${loginResp.data.id}/`, {
               headers: {
               "Content-Type": "application/json",
               "Authorization": `Bearer ${loginResp.data.access}`
             }
            }) 
          
          if(loginResp.data?.access){
            return {
              ...userResp.data.user,
              access: loginResp.access,
              refresh: loginResp.refresh
            }
          } else {
            return null;
          }
        }catch(err: any){
          console.log("Login error", err)
          throw createError({statusCode: 400, statusMessage: err.response.data?.detail ? err.response.data?.detail : err.message})
        }
      },
    })
  ]
})
```

**Comment by kaboume** [comment]
Hello,
Could you share your nuxt.config.js file ?
Thanks

**Comment by nktll** [comment]
Same issue here. Deploying on Vercel, it worked just 3-4 days ago and now all server/api calls return 204 error. And it's hard to debug what went wrong on remote server.

**Comment by karis** [comment]
hi @Johongirmirzo and @nktll 

im using vercel too, its working 

using authjs provider
```
 auth: {
    isEnabled: true,
    baseURL: process.env.AUTH_ORIGIN,
    provider: {
      type: 'authjs',
    },
```

my package.json
"@sidebase/nuxt-auth": "0.6.0-rc.1"

**Comment by Timothy16** [comment]
@karis Please i delopy to vercel all server/api sometimes returns 500 when you refresh or revisit the page it returns 200

**Comment by karis** [comment]
> ```js
> loginUser
> ```

hi @Timothy16 

can you create reproduction on stackblitz?

did you use .env?

have you set properly on your vercel account.

**Comment by Timothy16** [comment]
@karis yes i use env and it is properly set on vercel.

As i said, every API that need auth token return error  500 sometimes and when refresh the page it return 200.

**Comment by Johongirmirzo** [comment]
HI to all! I'm sorry for coming late, Problem is fixed! Our devops team could not correctly configure  .env file on the server. That was the root of the problem. Thanx for all for trying to help me

**Comment by zoey-kaiser** [comment]
Hi @Johongirmirzo 👋 

Glad to hear that everyone else was able to help you and you resolved your issue. Before closing this issue up, I wanted to link the docs one more time, that refer to the needed environment variable or config files to properly handle redirect URLs:

https://sidebase.io/nuxt-auth/configuration/nuxt-config#provider-authjs-baseurl

Good luck with your further work!
