### ISSUE TITLE
Parameter "basePath" does not work

### ISSUE THREAD

**Issue by ftrsoft** [sidebase/nuxt-auth#571]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, modules, auth, runtimeConfig
- Runtime Modules:  @sidebase/nuxt-auth@0.6.0
- Build Modules:    -
------------------------------

### Describe the bug

When set in nuxt.config.ts these values

`  auth: {
    globalAppMiddleware: true,
    basePath: '/ws/auth',
    provider: {
      type: 'authjs'
    }
  },`

and use file as API: /server/ws/auth/[...].js  it is not work. 

Infinite error in console:

```
3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?ca
llbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localho
st:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session
?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://localhost:3000/api/auth/session?callbackUrl=http://loca

```

**Comment by ftrsoft** [comment]
I try 
```
  auth: {
    globalAppMiddleware: true,
    basePath: '/_auth',
    provider: {
      type: 'authjs'
    }
  },
```

and use ~/server/routes/_auth/[....].js too 
It is same error

**Comment by karis** [comment]
hi @ftrsoft 
thanks for inspiring me

last night, i was update to 6.0
and  got infinite loop too

then i try to fix, here is my folder setup

~ /server / api / [...]ts
~ /server / api / token.get.ts

on nuxt.config.ts :
`auth: {
    isEnabled: true,
    baseURL: process.env.AUTH_ORIGIN,
    provider: {
      type: 'authjs'
    },
    globalAppMiddleware: {
      isEnabled: true,
      allow404WithoutAuth: true,
      addDefaultCallbackUrl: true,
    }
  },`

.env
AUTH_SECRET=your-secret
AUTH_ORIGIN=http://localhost:3000/api/auth/


hope can help you too..

**Comment by ftrsoft** [comment]
I want to change default url 'api/auth' to another. How I can do it?

**Comment by karis** [comment]
i just try your setup. it works. no loop
 
i create `~/server/routes/_auth` contain same as  `~/server/api/auth`

then i edit my .env:
AUTH_ORIGIN=http://localhost:3000/_auth/

i use package.json: 
`"@sidebase/nuxt-auth": "0.6.0-rc.1"`


![Screenshot 2023-11-15 at 10 31 04](https://github.com/sidebase/nuxt-auth/assets/1776951/6015f093-f18d-416f-9cd2-3e3a218ef4eb)

**Comment by karis** [comment]
hi @ftrsoft 
we have the different version

i am using baseURL params not basePath. i am asuming you are using version 5.0

**Comment by ftrsoft** [comment]
That's work. Thanks!
