### ISSUE TITLE
fix package.json exports

### ISSUE THREAD

**Issue by patroza** [sidebase/nuxt-auth#575]
the package.json exports are missing a types entry:
```json
  "exports": {
    ".": {
      "import": "./dist/module.mjs",
      "require": "./dist/module.cjs",
      "types": "./dist/module.d.ts" // missing
    }
  },
```
this causes no types to load for people using tsconfig moduleResolution set to Node16, NodeNext or bundler.

**Comment by phoenix-ru** [comment]
Hi @patroza.
I couldn't replicate the Typescript errors you are having when consuming the module with `moduleResolution` set to `Node16`, `NodeNext` or `Bundler`.

`package.json` already provides `types`:
https://github.com/sidebase/nuxt-auth/blob/0bc80f7ecd52e5fac856104249ea98f45fddf974/package.json#L13

Could you please provide further details?
