### ISSUE TITLE
Invalid Url upgrading to 0.6.2

### ISSUE THREAD

**Issue by agracia-foticos** [sidebase/nuxt-auth#591]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.0`
- Package Manager:  `npm@9.5.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

I'm upgrading from 0.5.0 to 0.6.2

this is my nuxt.config.ts
`    auth: {        
        // @ts-ignore (isEnabled boolean type)
        //BE CAREFULL, With visual studio debugger isEnabled can't be false, fails... issue opened
        isEnabled                         : process.env.NUXT_AUTH_ENABLED=="true", //all environment variables are strings
        baseURL                           : `http://localhost:3000/api/auth`, // The origin is set to the development origin. Change this when deploying to production by setting `origin` in this config before build-time or by exporting `AUTH_ORIGIN` by running `export AUTH_ORIGIN=...`                  
        // Whether to add a global authentication middleware that will protect all pages without exclusion
        globalAppMiddleware               : false,
        provider                          : { type: 'authjs' }
    },`

My NuxtAuthHandler are in :
![image](https://github.com/sidebase/nuxt-auth/assets/77386602/c4fd15c8-6f7b-481a-b624-9648182a1cc3)

The error is: 
`{
  "url": "/api/auth/callback/credentials",
  "statusCode": 500,
  "statusMessage": "",
  "message": "Invalid URL",
  "stack": "<pre><span class=\"stack internal\">at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)</span>\n<span class=\"stack internal\">at new NodeError (node:internal/errors:399:5)</span>\n<span class=\"stack internal\">at URL.onParseError (node:internal/url:566:9)</span>\n<span class=\"stack internal\">at new URL (node:internal/url:646:5)</span>\n<span class=\"stack internal\">at Object.redirect (./node_modules/next-auth/core/lib/default-callbacks.js:16:65)</span>\n<span class=\"stack internal\">at createCallbackUrl (./node_modules/next-auth/core/lib/callback-url.js:20:35)</span>\n<span class=\"stack internal\">at init (./node_modules/next-auth/core/init.js:131:48)</span>\n<span class=\"stack internal\">at AuthHandler (./node_modules/next-auth/core/index.js:131:28)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at <anonymous> (./node_modules/@sidebase/nuxt-auth/dist/runtime/server/services/authjs/nuxtAuthHandler.mjs:88:24)</span>\n<span class=\"stack internal\">at async Object.handler (./node_modules/h3/dist/index.mjs:1675:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1885:7)</span></pre>"
}`

Any idea that whats happend?

**Comment by agracia-foticos** [comment]
Any solution??

**Comment by agracia-foticos** [comment]
Any notice?

**Comment by agracia-foticos** [comment]
![image](https://github.com/sidebase/nuxt-auth/assets/77386602/a88452d3-932f-455c-91bc-b6f226f02345)
i try a lot of diferent code, but in all versions of my code raises "invalid url", please i need help!!!

**Comment by davidlemaitre** [comment]
I faced a similar issue after upgrading nuxt-auth from 0.6.2 to 0.6.3 and next-auth from 4.21.1 to 4.22.5. I'm using a custom provider in my case, I had to set `NEXTAUTH_URL` environment variable, same value than `AUTH_ORIGIN` one.

**Comment by agracia-foticos** [comment]
I add NEXTAUTH_URL="http://localhost:3000/api/auth" to my .env but i have the same error: "invalid url"

**Comment by davidlemaitre** [comment]
Try `NEXTAUTH_URL=http://localhost:3000` and `AUTH_ORIGIN=http://localhost:3000`
And my NuxtAuthHandler is located to `<project-root>/server/api/auth/[...].ts`

**Comment by davidlemaitre** [comment]
Remove the space after equals sign for the `NUXT_BASE_URL` environment variable in your .env file

**Comment by agracia-foticos** [comment]
> Remove the space after equals sign for the `NUXT_BASE_URL` environment variable in your .env file

![image](https://github.com/sidebase/nuxt-auth/assets/77386602/12c9e554-f8b0-4976-8b2c-0bc5a0431ef6)

There isnt spaces in NUXT_BASE_URL :(

**Comment by davidlemaitre** [comment]
Try  `baseURL: process.env.NUXT_BASE_URL ` in the nuxt.config.ts

**Comment by agracia-foticos** [comment]
> Try `baseURL: process.env.NUXT_BASE_URL ` in the nuxt.config.ts

It's the same!
![image](https://github.com/sidebase/nuxt-auth/assets/77386602/aaea02f2-14cc-487a-be6a-e31866d90121)

Not works! :(

**Comment by davidlemaitre** [comment]
Maybe the environment variables are not available in your setup. Try to use hardcoded values for both isEnabled and baseURL settings. Or remove baseURL config from nuxt.config.ts file, the default is http://localhost:3000/api/auth like you want in development.

**Comment by zoey-kaiser** [comment]
Hi @agracia-foticos,

As @davidlemaitre suspects, I think that somewhere a url is not being set correctly. Therefore I would recommend the following to try and debug this problem:

- remove all environment variables relating to auth
- Remove `baseURL` from the `nuxt.config` (in development, NuxtAuth can automatically determine your origin)
- If this does not work, please hard code `baseURL` in your `nuxt.config` to `localhost:3000`. 

I also wanted to remind you that setting `baseURL` in the nuxt config is for injecting the environment variable at build time and setting it via `AUTH_ORIGIN` is for injecting it runtime. You do not need to set both, one is enough!

**Comment by agracia-foticos** [comment]
> Hi @agracia-foticos,
> 
> As @davidlemaitre suspects, I think that somewhere a url is not being set correctly. Therefore I would recommend the following to try and debug this problem:
> 
> * remove all environment variables relating to auth
> * Remove `baseURL` from the `nuxt.config` (in development, NuxtAuth can automatically determine your origin)
> * If this does not work, please hard code `baseURL` in your `nuxt.config` to `localhost:3000`.
> 
> I also wanted to remind you that setting `baseURL` in the nuxt config is for injecting the environment variable at build time and setting it via `AUTH_ORIGIN` is for injecting it runtime. You do not need to set both, one is enough!

The error now:
![image](https://github.com/sidebase/nuxt-auth/assets/77386602/130f9a8a-b998-411e-8c49-da8952da5809)

nuxt.config.ts
![image](https://github.com/sidebase/nuxt-auth/assets/77386602/3f7f6ac8-c4d7-4d65-8d7b-528fef2fde70)

The only key that we have in .env its NUXT_AUTH_SECRET, the another are deleted

**Comment by agracia-foticos** [comment]
> Hi @agracia-foticos,
> 
> As @davidlemaitre suspects, I think that somewhere a url is not being set correctly. Therefore I would recommend the following to try and debug this problem:
> 
> * remove all environment variables relating to auth
> * Remove `baseURL` from the `nuxt.config` (in development, NuxtAuth can automatically determine your origin)
> * If this does not work, please hard code `baseURL` in your `nuxt.config` to `localhost:3000`.
> 
> I also wanted to remind you that setting `baseURL` in the nuxt config is for injecting the environment variable at build time and setting it via `AUTH_ORIGIN` is for injecting it runtime. You do not need to set both, one is enough!

nuxt.config.ts
![image](https://github.com/sidebase/nuxt-auth/assets/77386602/161aec06-fcda-4d77-be3c-4fa8cd0df278)

the only key in .env its NUXT_AUTH_SECRET

![image](https://github.com/sidebase/nuxt-auth/assets/77386602/fe77d197-8201-45af-8518-306db0a8e278)


same issue
`[nuxt] [request error] [unhandled] [500] Invalid URL
  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)  
  at new NodeError (node:internal/errors:405:5)  
  at new URL (node:internal/url:778:13)  
  at Object.redirect (./node_modules/next-auth/core/lib/default-callbacks.js:16:65)  
  at createCallbackUrl (./node_modules/next-auth/core/lib/callback-url.js:20:35)  
  at init (./node_modules/next-auth/core/init.js:131:48)  
  at AuthHandler (./node_modules/next-auth/core/index.js:131:28)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at <anonymous> (./node_modules/@sidebase/nuxt-auth/dist/runtime/server/services/authjs/nuxtAuthHandler.mjs:88:24)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1675:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1885:7)`

**Comment by zoey-kaiser** [comment]
Could you please show me your `NuxtAuthHandler` (the file inside `/api/auth/[...].ts`). 
I feel like there may be an issue in there 😄 

Otherwise, could you create a small reproduction of the issue? I think this would greatly help me, find the issue and expatiate the process!

**Comment by agracia-foticos** [comment]
> @agracia-foticos Could you please show me your `NuxtAuthHandler` (the file inside `/api/auth/[...].ts`). I feel like there may be an issue in there 😄
> 
> Otherwise, could you create a small reproduction of the issue? I think this would greatly help me, find the issue and expatiate the process!

The `NuxtAuthHandler` runs in 0.5.2 version... i think there isnt the problem here.

i try to give you a small reproduction, but it's going to be complicated

**Comment by zoey-kaiser** [comment]
> The NuxtAuthHandler runs in 0.5.2 version... i think there isnt the problem here.

I saw that the error originated from the section in nuxt-auth concering itself with the NuxtAuthHandler, which is why I wanted to verify, that the problem would not occur from there!

**Comment by agracia-foticos** [comment]
NuxtAuthHandler
`export default NuxtAuthHandler({
  // A secret string you define, to ensure correct encryption
  pages: {
    // Change the default behavior to use `/login` as the path for the sign-in page
    signIn: `/login`, //`/${LOGIN_SLUG}` fails on windows (Salo 2/8/23)
  },
  secret: <string>useRuntimeConfig().authSecret,
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    CredentialsProvider.default({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: 'Credentials',
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
      async authorize (credentials: WebUser) {
        // You need to provide your own logic here that takes the credentials
        // submitted and returns either a object representing a user or value
        // that is false/null if the credentials are invalid.
        // NOTE: THE BELOW LOGIC IS NOT SAFE OR PROPER FOR AUTHENTICATION!

                 
      }
    }),
  ],
  callbacks: {
    // Callback when the JWT is created / updated, see https://next-auth.js.org/configuration/callbacks#jwt-callback
    jwt: async ({token, user}) => {
      const isSignIn = user ? true : false;
      if (isSignIn) {
        (token as any) = user
      }
      return Promise.resolve(token);
    },
    // Callback whenever session is checked, see https://next-auth.js.org/configuration/callbacks#session-callback
    session: async ({session, token}) => {
      (session as any) = token;
      return Promise.resolve(session);
    },
  },
})`

> > The NuxtAuthHandler runs in 0.5.2 version... i think there isnt the problem here.
> 
> I saw that the error originated from the section in nuxt-auth concering itself with the NuxtAuthHandler, which is why I wanted to verify, that the problem would not occur from there!

NuxtAuthHandler
`export default NuxtAuthHandler({
  // A secret string you define, to ensure correct encryption
  pages: {
    // Change the default behavior to use `/login` as the path for the sign-in page
    signIn: `/login`, //`/${LOGIN_SLUG}` fails on windows (Salo 2/8/23)
  },
  secret: <string>useRuntimeConfig().authSecret,
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    CredentialsProvider.default({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: 'Credentials',
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
      async authorize (credentials: WebUser) {
        // You need to provide your own logic here that takes the credentials
        // submitted and returns either a object representing a user or value
        // that is false/null if the credentials are invalid.
        // NOTE: THE BELOW LOGIC IS NOT SAFE OR PROPER FOR AUTHENTICATION!

                 
      }
    }),
  ],
  callbacks: {
    // Callback when the JWT is created / updated, see https://next-auth.js.org/configuration/callbacks#jwt-callback
    jwt: async ({token, user}) => {
      const isSignIn = user ? true : false;
      if (isSignIn) {
        (token as any) = user
      }
      return Promise.resolve(token);
    },
    // Callback whenever session is checked, see https://next-auth.js.org/configuration/callbacks#session-callback
    session: async ({session, token}) => {
      (session as any) = token;
      return Promise.resolve(session);
    },
  },
})`

**Comment by agracia-foticos** [comment]
> > The NuxtAuthHandler runs in 0.5.2 version... i think there isnt the problem here.
> 
> I saw that the error originated from the section in nuxt-auth concering itself with the NuxtAuthHandler, which is why I wanted to verify, that the problem would not occur from there!

NuxtAuthHandler
`// file: ~/server/api/auth/[...].ts
import CredentialsProvider from 'next-auth/providers/credentials'
import { NuxtAuthHandler } from '#auth'
import { GOOGLE_LOGIN, USER_PASSWORD_LOGIN } from '@/constants/wanapix'
import type { WebUser } from '@/types/fapi/WebUser'

export default NuxtAuthHandler({
  // A secret string you define, to ensure correct encryption
  pages: {
    // Change the default behavior to use `/login` as the path for the sign-in page
    signIn: `/login`, //`/${LOGIN_SLUG}` fails on windows (Salo 2/8/23)
  },
  secret: <string>useRuntimeConfig().authSecret,
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    CredentialsProvider.default({
      // The name to display on the sign in form (e.g. 'Sign in with...')
      name: 'Credentials',
      // The credentials is used to generate a suitable form on the sign in page.
      // You can specify whatever fields you are expecting to be submitted.
      // e.g. domain, username, password, 2FA token, etc.
      // You can pass any HTML attribute to the <input> tag through the object.
      async authorize (credentials: WebUser) {
        // You need to provide your own logic here that takes the credentials
        // submitted and returns either a object representing a user or value
        // that is false/null if the credentials are invalid.
        // NOTE: THE BELOW LOGIC IS NOT SAFE OR PROPER FOR AUTHENTICATION!

                 
      }
    }),
  ],
  callbacks: {
    // Callback when the JWT is created / updated, see https://next-auth.js.org/configuration/callbacks#jwt-callback
    jwt: async ({token, user}) => {
      const isSignIn = user ? true : false;
      if (isSignIn) {
        (token as any) = user
      }
      return Promise.resolve(token);
    },
    // Callback whenever session is checked, see https://next-auth.js.org/configuration/callbacks#session-callback
    session: async ({session, token}) => {
      (session as any) = token;
      return Promise.resolve(session);
    },
  },
})`

**Comment by agracia-foticos** [comment]
Any idea?

**Comment by agracia-foticos** [comment]
I have upgraded the version to 0.6.3 but we have the same error :(

**Comment by zoey-kaiser** [comment]
Amazing! Seems to be an issue in the redirecting. Ill look into this and see why its caused!

**Comment by magnetic5355** [comment]
Same issue on 0.6.7

[nuxt] [request error] [unhandled] [500] Invalid URL
  at new URL (node:internal/url:787:36)  
  at ./node_modules/.pnpm/next-auth@4.22.5_next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/providers.js:55:19  
  at Array.reduce (<anonymous>)  
  at normalizeOAuthOptions (./node_modules/.pnpm/next-auth@4.22.5_next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/providers.js:51:51)  
  at ./node_modules/.pnpm/next-auth@4.22.5_next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/providers.js:25:37  
  at Array.map (<anonymous>)  
  at parseProviders (./node_modules/.pnpm/next-auth@4.22.5_next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/providers.js:15:38)  
  at init (./node_modules/.pnpm/next-auth@4.22.5_next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/init.js:56:30)  
  at AuthHandler (./node_modules/.pnpm/next-auth@4.22.5_next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:138:28)

**Comment by zoey-kaiser** [comment]
Closed due to an old version. If anyone is still experiencing this issue, please check if it still exists in 0.8.0 and that the module has been setup using the new docs: https://auth.sidebase.io

**Comment by jerryfromearth** [comment]
> Closed due to an old version. If anyone is still experiencing this issue, please check if it still exists in 0.8.0 and that the module has been setup using the new docs: https://auth.sidebase.io

I'm afraid it's still an issue in @sidebase/nuxt-auth:0.9.3 + next-auth:4.21.1.

I got "[500] Invalid URL" while calling signIn function. 
Removing `globalAppMiddleware: false,` from `nuxt.config.ts` solved the issue.
Setting it to `true` also solves the issue (but it's not what I wanted).
