### ISSUE TITLE
Callback url doesn't include query params

### ISSUE THREAD

**Issue by AbdallahAlhaddad** [sidebase/nuxt-auth#597]
### Environment

```bash
------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.10.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Describe the bug

The `?callbackUrl=<url>` to which the user should be redirected after login doesn't include the original url `query` parameters.

**Comment by nojiritakeshi** [comment]
@AbdallahAlhaddad 
Does this bug still exist?
With the latest version, I don't encounter this bug, at least in my development environment.

**Comment by AbdallahAlhaddad** [comment]
it still doesn't work, what happens is that the original url query params gets replaced by module specific param: `&error=undefined`
### Environment

```bash
------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.13.1
- "@sidebase/nuxt-auth":  0.6.3
- "next-auth": 4.22.5
------------------------------
```

### auth module configuration
```ts
// nuxt.config.ts
  auth: {
    isEnabled: true,
    provider: 'authjs',

    session: {
      enableRefreshPeriodically: false,
      enableRefreshOnWindowFocus: true,
    },

    globalAppMiddleware: {
      isEnabled: true,
      allow404WithoutAuth: false,
    },
  },
```

**Comment by fotyG** [comment]
@AbdallahAlhaddad try modifying this part of your nuxt.config.ts as follows:
```
  auth: {
    globalAppMiddleware: {
      isEnabled: true,
      allow404WithoutAuth: false,
      addDefaultCallbackUrl: false,
    },
  },
  ```
  I was able to maintain all query parameters this way - hope this helps you as well!

**Comment by nojiritakeshi** [comment]
Hi @AbdallahAlhaddad , @fotyG 
The problem always appears to occur when both of the following conditions are met.
```ts
auth: {
addDefaultCallbackUrl: true
}
```
```ts
// server/api/auth/[...].ts
// Indicates that you are setting `pages`.
pages: {
    signIn: '/login',
  },
```
I don't think this problem would occur if `addDefaultCallbackUrl: true` is used but `pages` is not set?

In any case, it appears to be a glitch, so I'm going to look into it some more and try to create a PR.

**Comment by nojiritakeshi** [comment]
@AbdallahAlhaddad , @fotyG
This problem is not caused by the nuxt-auth code base, but seems to be an issue with the dependency next-auth.
Specifically, the issue is in the AuthHandler function in next-auth/src/core.
```ts
case "signin":
        if (pages.signIn) {
          let signinUrl = `${pages.signIn}${
            pages.signIn.includes("?") ? "&" : "?"
          }callbackUrl=${encodeURIComponent(options.callbackUrl)}`
          if (error)
            signinUrl = `${signinUrl}&error=${encodeURIComponent(error)}`
          return { redirect: signinUrl, cookies }
        }
```

**Comment by zoey-kaiser** [comment]
>  Specifically, the issue is in the AuthHandler function in next-auth/src/core.

Always upsetting when this happens.... However, I am also unsure how this would work on a technical level, as I am unsure if you can include query parameters in a query parameter 😵.
Therefore my main question would be, is it absolutely necessary that it includes the query parameters on the callback or is there some way to circumvent this, as a fix is tricky to implement (maybe even impossible if we cannot change NextAuth)

**Comment by AbdallahAlhaddad** [comment]
@zoey-kaiser 

Yes, you are right. There are some limitations to adding query parameters in the `callbackURL`, as it is up to the browser to parse the URL. I think it can be tricky to make it work in all cases and across all browsers.

However, technically, we can work around this by encoding the callback URL using [Base 64 URL Encoding](https://www.base64url.com).

**Comment by AbdallahAlhaddad** [comment]
> ```ts
> case "signin":
>         if (pages.signIn) {
>           let signinUrl = `${pages.signIn}${
>             pages.signIn.includes("?") ? "&" : "?"
>           }callbackUrl=${encodeURIComponent(options.callbackUrl)}`
>           if (error)
>             signinUrl = `${signinUrl}&error=${encodeURIComponent(error)}`
>           return { redirect: signinUrl, cookies }
>         }
> ```

@nojiritakeshi 
This code snippet seems fine to me, I think the issue is with passing wrong/incomplete callback URL in `options.callbackUrl`

**Comment by AbdallahAlhaddad** [comment]
The issue is with the nuxt middleware [callback url determination](https://github.com/sidebase/nuxt-auth/blob/0eea47a51e9b46650e921d8e5d5b10384fb9282c/src/runtime/middleware/auth.ts#L88C140-L88C144), it uses `to.path` instead of `to.fullPath`

**Comment by zoey-kaiser** [comment]
Resolved in https://github.com/sidebase/nuxt-auth/releases/tag/0.6.6

**Comment by quroom** [comment]
@zoey-kaiser 
Thanks for quick update.
In my case, I only add in nuxt.config
```
    globalAppMiddleware: {
      addDefaultCallbackUrl: false,
    },
```
And now I can see query params in callback url.
