### ISSUE TITLE
Custom login body

### ISSUE THREAD

**Issue by MuhammadM1998** [sidebase/nuxt-auth#606]
### Describe the feature

The documentation states that the `login` endpoint for local & refresh providers must match a `username` & `password` schema
![Screenshot 2023-12-13 150111](https://github.com/sidebase/nuxt-auth/assets/86230182/82d37392-abb7-4c55-a956-f600f2368390)

We're using the same auth endpoint for Android and iOS apps. Enforcing the backend, Android, and iOS implementation to match the one described above is a bit of a hassle (It's merely rewording but they'll be doing that across the codebases). We're also using phone number instead of a username, so sending that value in a username field is a bit counter-intuitive.

It would be great if we can customize the path of the credentials. Maybe with the same approach as https://github.com/sidebase/nuxt-auth/pull/592?

Thanks a lot for your work and the great module 🙏

**Comment by valh1996** [comment]
Hi @MuhammadM1998 
Thanks for the repor!
Feel free to suggest a PR if you want to speed things up. I also need to finish mine ^^

**Comment by MuhammadM1998** [comment]
@valh1996 I'd love to help but I'm not sure where to start, how to test, etc... That being said I'll give it a try and hope things work out

**Comment by dennismwas** [comment]
You can use useAuthState() hook call your login using normal fetch to the login route on server then use useAuthState().setToken() function to set the token and useAuth().data.value to set the user of the session.
The useAuthState() provides mutable refs that you can manipulate the auth state.

**Comment by MuhammadM1998** [comment]
lol I digged into the code and found that the `credentials` is extracted and sent as a whole. No `user` or `password` is specified.
https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/composables/local/useAuth.ts#L22C1-L22C1

I tried and it does work! This is my code
```vue
<script>
const { signIn } = useAuth()

async function login() {
  const body = {
    phone: '115499818',
    password: '115499818',
    login_type: '1',
    // Whatever you pass here will be sent to the `signIn` endpoint you defined in `nuxt.config`
  }

  await signIn(body, { redirect: false })
}
</script>

@zoey-kaiser Maybe this is worth updating the docs?

**Comment by zoey-kaiser** [comment]
> @zoey-kaiser Sorry for the ping but maybe this is worth updating the docs?

For sure! I assume we forgot to add this. Do you mind opening a PR and adding it?

**Comment by MuhammadM1998** [comment]
Sure thing, I'll add it to my weekend list
