### ISSUE TITLE
bridge: nuxt.options.runtimeConfig is undefined

### ISSUE THREAD

**Issue by AndreyYolkin** [sidebase/nuxt-auth#62]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `2.16.0-27720022.54e852f`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Install nuxt-auth in a project with nuxt bridge, but without runtimeConfig section in `nuxt.config.js`

### Describe the bug

Nuxt 2 bridge does not create empty runtimeConfig if none was specified in `nuxt.config.js`. It leads to fail during module installing process

**Comment by BracketJohn** [comment]
Merged, thanks for the issue and resolution - nuxt 2 compat would be great (:
