### ISSUE TITLE
addDefaultCallbackUrl for local auth not working

### ISSUE THREAD

**Issue by blaaat** [sidebase/nuxt-auth#622]
### Environment

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      runtimeConfig, devtools, modules, i18n, auth, vuetify, vite
- Runtime Modules:  @invictus.codes/nuxt-vuetify@0.3.0, @sidebase/nuxt-auth@0.6.3, @pinia/nuxt@0.5.1, @nuxtjs/i18n@8.0.0
- Build Modules:    -

### Reproduction

I'm using the following config: 
```   
 globalAppMiddleware: {
      isEnabled: true,
      addDefaultCallbackUrl: true
    },
    baseURL: '/',
    provider: {
      type: 'local',
      endpoints: {
        signIn: { path: '/api/admin/login.php', method: 'post' },
        signOut: { path: '/api/admin/logout.php', method: 'post' },
        signUp: { path: '/api/admin/register.php', method: 'post' },
        getSession: { path: '/api/admin/user.php', method: 'get' }
      },
      token: {
        signInResponseTokenPointer: '/token'
      },
    },
```

### Describe the bug

I'm not being redirected back to the page I initially visited. 
If I don't set a callbackUrl manually in the signIn request I get an alert with the following: 

`Error: Navigating to an external URL is not allowed by default. Use `navigateTo(url, { external: true })`.

**Comment by nojiritakeshi** [comment]
Hi @zoey-kaiser .
I too am curious about this issue.
Is it intended to make sure that the callback URL is set manually for local providers?
Personally, I believe that there are use cases, even for local providers, where you want to be taken to a certain page after login, such as `addDefaultCallbackUrl: '/loggedIn'`.

If you agree with my idea, I would like to investigate and create a PR.

**Comment by bitfactory-frank-spee** [comment]
This looks like this is related to https://github.com/sidebase/nuxt-auth/issues/656
