### ISSUE TITLE
Refresh token does not refresh the token

### ISSUE THREAD

**Issue by azuryel** [sidebase/nuxt-auth#623]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.3.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19

### Describe the bug

When my token is expiring  there isn't any call to my refresh token api endpoint that are made.  and i'm considered as "unauthentication" 
it's unclear from the documentation if it need to be manually called and how to do that. 

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/490965bf-0ca0-443f-9292-8523fd579105)
![image](https://github.com/sidebase/nuxt-auth/assets/9035821/95b86a96-c9df-4bfa-99d2-7c29827b14b8)
![image](https://github.com/sidebase/nuxt-auth/assets/9035821/92914623-9577-40d3-81d6-28e8ee1d1a98)

on my node server log:

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/1b96a272-580f-423b-8dc6-304edec721c3)
We can see that after the 401 unauthorized there isn't any call made to the refresh token api endpoint

which lead me then to my frontend considering me unauthenticated and clear all my data / status etc.. 

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/8c8fea9d-8220-46e9-ae50-64aa4fa1b57a)

Here is my code in nuxt.config.ts: 

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/78287ccb-c2a1-4a42-8854-867e5d6be11c)

and my login form 

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/a2c040c3-92a5-4d78-b9d6-2924a7311fc3)

**Comment by azuryel** [comment]
actually work.

**Comment by anegelya** [comment]
@azuryel I have the same issue. How did you fix this?

**Comment by azuryel** [comment]
> @azuryel I have the same issue. How did you fix this?

@anegelya hi sorry for the late reply i was kind of busy these week, but i have answered to that question on this issue 
https://github.com/sidebase/nuxt-auth/issues/480#issuecomment-1872145353

I've been using it for nearly a month now  it work perfectly fine 

in addition of the linked post here is my current auth config in 

nuxt.config.ts

```
 auth: {
    baseURL: process.env.API_BASE_URL,
    globalAppMiddleware: false,
    provider: {
      type: "refresh",
      endpoints: {
        signIn: { path: "/user/login", method: "post" },
        signOut: false,
        signUp: { path: "/user/register", method: "post" },
        getSession: { path: "/user/me", method: "get" },
        refresh: { path: "/user/refreshToken", method: "post" },
      },
      token: {
        signInResponseTokenPointer: "/accessToken",
        maxAgeInSeconds: 259200,
        sameSiteAttribute: "lax",
      },
    },
  },
```

how to use the middleware ( because doc is a bit confuse on it )

```
definePageMeta({
  layout: "full-page",
  middleware: "auth",
  auth: {
    unauthenticatedOnly: true,
    navigateAuthenticatedTo: "/",
  },
});
```

**Comment by anegelya** [comment]
@azuryel Thank you a lot!
