### ISSUE TITLE
auth state lost after a page redirection and return back on website 

### ISSUE THREAD

**Issue by azuryel** [sidebase/nuxt-auth#626]
### Environment

- Operating System: Linux
- Node Version:     v20.3.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19

### Reproduction

My nuxt.config.ts

```

 auth: {
    baseURL: process.env.API_BASE_URL,
    provider: {
      type: "refresh",
      endpoints: {
        signIn: { path: "/user/login", method: "post" },
        signOut: false,
        signUp: { path: "/user/register", method: "post" },
        getSession: { path: "/user/me", method: "get" },
        refresh: { path: "/user/refreshToken", method: "post" },
      },
      token: {
        signInResponseTokenPointer: "/accessToken",
        maxAgeInSeconds: 1800,
        sameSiteAttribute: "strict",
      },
    },
  },
```

### Describe the bug

**Login to your account using refresh provider, when click on an external redirection link, ( stripe redirectToCheckout in this example) and then come back to my website all my state are null and im considered as unauthenticated , but my both my token and refresh are here **

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/2de83940-0f4c-4684-baff-821b2ef3089a)

**Click on a link that redirect you to an external website ( for my case i'm working with stripe redirectToCheckout function)** 

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/c863a347-b0f3-4b6c-9f57-9bba213a293f)
 

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/15ac2bee-fcd6-4e16-95e6-eaec1d563e10)

![image](https://github.com/sidebase/nuxt-auth/assets/9035821/94714282-71cd-4b16-a3c5-1e41dcec8d73)

**Comment by flrnt** [comment]
@azuryel did u try to reload your page ? I guess the behavior is the same. Moreover the same thing for me.

**Comment by zoey-kaiser** [comment]
Hi @azuryel has the fixed worked for you? If so I think we can close this issue 🤗

**Comment by azuryel** [comment]
Hi yes it worked perfectly after nearly a month of testing. very happy with the plugin. 
for reference if someone come back here 

my nuxt.config.js

```
  auth: {
    baseURL: process.env.API_BASE_URL,
    globalAppMiddleware: false,
    provider: {
      type: "refresh",
      endpoints: {
        signIn: { path: "/user/login", method: "post" },
        signOut: false,
        signUp: { path: "/user/register", method: "post" },
        getSession: { path: "/user/me", method: "get" },
        refresh: { path: "/user/refreshToken", method: "post" },
      },
      token: {
        signInResponseTokenPointer: "/accessToken",
        maxAgeInSeconds: 259200,
        sameSiteAttribute: "lax",
      },
    },
  },
```
