### ISSUE TITLE
Custom refresh token name.

### ISSUE THREAD

**Issue by N1K1TAS95** [sidebase/nuxt-auth#635]
### Describe the feature

Hi there! 
I'm using nuxt-auth and refresh mode to manage JWT.
Obtaining new access and refresh token works fine, but not refreshing a token.
Nuxt-auth sends this JSON: 
```
{
  "refreshToken":"eyJhbGc..."
}
```
My back-end expects a JSON with field "refresh", so an 400 error is returned.
I wish to customize the name like so:
```
refreshToken: {
  signInResponseRefreshTokenPointer: '/refresh',
  maxAgeInSeconds: 86400,
  fieldName: 'refresh'
}
```
Thanks!

**Comment by bodgerbarnett** [comment]
This is also a problem for me. I feel like the refresh provider is very nearly there now but for this one thing.

**Comment by simon-ccoms** [comment]
I'm using djangorestframework-simplejwt (https://github.com/jazzband/djangorestframework-simplejwt/) and the token name that's returned from there isn't configurable either so I'm a bit stuck.

I can obviously try and get that changes one way or the other but I was hoping that this library would act like the original nuxt-auth and allow it to be changed in here.

**Comment by bodgerbarnett** [comment]
I'm using djangorestframework-simplejwt (https://github.com/jazzband/djangorestframework-simplejwt/) and the token name that's returned from there isn't configurable either so I'm a bit stuck.

I can obviously try and get that changes one way or the other but I was hoping that this library would act like the original nuxt-auth and allow it to be changed in here.

**Comment by N1K1TAS95** [comment]
@bodgerbarnett same here. I'm little bit stuck with DRF and JWT. Cannot change the name in both, front and back end. Now I'm using only Token Authentication.

**Comment by phoenix-ru** [comment]
> Nuxt-auth sends this JSON

Could you please clarify, whether you mean a request going out from this call
```ts
const auth = useAuth()
auth.refresh()
```

Or a response from `POST /api/auth/refresh`?

If I understand you correctly, you have a django server which handles the JWTs and you only use `nuxt-auth` to talk with it? Meaning you don't have a custom Nuxt server route?

If this is the case, for now I could only suggest you to proxy requests from `~/server`. I will further think how we can support your usecase without over-complicating our own codebase.

**Comment by N1K1TAS95** [comment]
@phoenix-ru I mean the call that is made by nuxt-auth to referesh the token. Both manually via `auth.refresh()` and automatically after a timeout.
The call is made to my API endpoint defined in `nuxt.config.ts` via:
```
endpoints: {
  ...
  refresh: {path: '/token/refresh/', method: 'post'},
  ...
},
```
and contains the refresh token in the body defined by field `refreshToken`, but my backend expects a field called `refresh`.

For now, I'm using the local provider from nuxt-auth.

**Comment by N1K1TAS95** [comment]
@phoenix-ru I'm using Django for backend alongside to Django Rest Framework and djangorestframework-simplejwt to handle API authentication and authorization.

> Therefore your sign in endpoint /api/auth/login (or the name you gave it) is handled by PHP and interpreted by nuxt-auth correctly.
But your token refresh endpoint /api/auth/token/refresh is also handled by PHP, which can only accept body in format { refresh: string }.

Yes, exatly.

Thank you for the temporary solution, I'll try it while I wait for the new release of nuxt-auth.
