### ISSUE TITLE
Refresh provider not working

### ISSUE THREAD

**Issue by bodgerbarnett** [sidebase/nuxt-auth#640]
### Environment

- Operating System: Darwin
- Node Version:     v18.10.0
- Nuxt Version:     3.9.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.6.4
- Build Modules:    -

### Describe the bug

I've got the setup of the local provider right - and it's working, like this:-

```
export default defineNuxtConfig({
  devtools: {enabled: true},
  modules: ["@sidebase/nuxt-auth"],
  auth: {
    provider: {
      type: "local",
    },
  },
});
```

but if I try and use the refresh provider:-

```
export default defineNuxtConfig({
  devtools: {enabled: true},
  modules: ["@sidebase/nuxt-auth"],
  auth: {
    provider: {
      type: "refresh",
    },
  },
});
```

I get the following error:-

```
[4:22:18 PM]  ERROR  Importing from server is not allowed in the Vue part of your app. [importing node_modules/@sidebase/nuxt-auth/dist/runtime/server/plugins/refresh-token.server.mjs
```

**Comment by gottafixthat** [comment]
I'm experiencing the exact same issue, slightly different setup:
* Operating System: Ubuntu 22.04
* Node Version: v18.19.0
* Nuxt Version: 3.9.3
* Vue Version: 3.4.14
* Nitro Version: 2.8.1
Package Manager: pnpm 8.14.1
Runtime Modules: @sidebase/nuxt-auth@0.6.4, @nuxtjs/tailwindcss, nuxt-primevue, daisyui

**Comment by flrnt** [comment]
@bodgerbarnett @gottafixthat it has been fixed by @danielroe yesterday https://github.com/sidebase/nuxt-auth/pull/639
we wait for @zoey-kaiser to release it. For now, you can patch it (`yarn patch @sidebase/nuxt-auth`, `pnpm patch ...` or whatever package manager you use).
Works fine ! 👌🏻

**Comment by zohaibshahzad1990** [comment]
![image](https://github.com/sidebase/nuxt-auth/assets/61659296/23164783-2755-4497-a76c-f70a4cddb773)
I have tried to patch but there is no patch

**Comment by flrnt** [comment]
yes because it's up to you to update the package in the node modules folder, then apply your command : `npx patch-package @sidebase/nuxt-auth`. It will create things for you automatically. See patch-package docs

**Comment by zoey-kaiser** [comment]
Released in https://github.com/sidebase/nuxt-auth/releases/tag/0.6.5! Sorry for the wait, I was coming home from a trip ❤️

**Comment by zohaibshahzad1990** [comment]
Thank you so much
