### ISSUE TITLE
Proposal to improve the experience of `useSession`

### ISSUE THREAD

**Issue by JoaoPedroAS51** [sidebase/nuxt-auth#65]
### Describe the feature

Hi! I'm João Pedro. I'm one of the maintainers of the nuxt 2 auth module :)

So, currently, each time `useSession` is used it makes a request to the api to get the session, which means we have to `await` for the request and this makes the component asynchronous. And if it's used in more than one component, it will make unnecessary requests.

My proposal is to use `useSession` only to get the data stored with `useState`, and fetch the session on load the page through a plugin.

This follows the same approach of the auth module, which fetches the user on load the auth plugin.

**Comment by BracketJohn** [comment]
Hey @JoaoPedroAS51!

Thank you for taking the time to propose this + great to get input from one of the nuxt 2 auth maintainers! (: 

As for your suggestion: If I understand correctly, the plugin will do something like:
```ts
const { signIn } = useSession()  // no await as not async any longer

await signIn()
```

How would a user define that some route is unprotected? Did you also allow configuring specific routes? Because at the moment our users are able to do:
```
const { data } = await useSession({ required: false })
```
to not force a login for certain pages.

**Comment by JoaoPedroAS51** [comment]
@BracketJohn If you are interested, you can take a look at [@eloqjs/nuxt-next-auth](https://github.com/eloqjs/nuxt-next-auth). I created this lib to fit the needs of the project I'm currently working on. So all theses things I'm suggesting, like this proposal and the fix of host/port with `requrl` , it's all there.

**Comment by BracketJohn** [comment]
Thanks @JoaoPedroAS51 really helpful. I think we'll take over some of the stuff from your module then, I like the approach and it makes it more "nuxt-ish" (:

**Comment by BracketJohn** [comment]
As discussed: Let's go ahead with this and make `useSession` sync (:

**Comment by BracketJohn** [comment]
I've gotten started (and already quite far) in #69. #69 will:
- use a plugin for session init,
- add a module-middleware that people can use,
- adds refresh options:
  - periodically,
  - on window focus

for another PR / issue:
- broadcasting
