### ISSUE TITLE
signIn with callbackUrl: undefined returns an error instead of navigating to the previous page 

### ISSUE THREAD

**Issue by clcoco** [sidebase/nuxt-auth#656]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      app, vite, css, postcss, runtimeConfig, imports, modules, auth, i18n
- Runtime Modules:  @sidebase/nuxt-auth@0.6.7, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.2
- Build Modules:    -
------------------------------

### Describe the bug

I'm using the local provider.
I expect the signIn function to take the user back to the pages they were trying to access while not being logged (or the index page if none was provided) but instead it returns the following error: `Navigating to an external URL is not allowed by default. Use navigateTo(url, { external: true })`

The code I'm using:
```
await signIn({
      username: user.value.email,
      password: user.value.password
    }, { callbackUrl: undefined })
```

More so, even if I pass `external: true` it returns the same error anyway

**Comment by bitfactory-frank-spee** [comment]
I ran into this problem also. First, I have a simple workaround implemented for now:
```
const { signIn } = useAuth();
const { redirectedFrom } = useRoute();

signIn(
    {
        password,
        username,
    },
    {
        callbackUrl: redirectedFrom ? redirectedFrom.fullPath : '/',
    },
);
```

Second, I tried to debug this error, but I could not get to the bottom of the problem in this package.

1. I tried to use 'refresh' instead of 'local', it did not matter, although the code is different between the two!
	- https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/composables/local/useAuth.ts#L64 (has external as option)
	- https://github.com/sidebase/nuxt-auth/blob/main/src/runtime/composables/refresh/useAuth.ts#L71 (no external as option)
2. That the code is different does not matter, because they have the same default callback URL: `getRequestURLWN(nuxt)`
3. If you look for that method you get this: https://github.com/sidebase/nuxt-auth/blob/0bc80f7ecd52e5fac856104249ea98f45fddf974/src/runtime/utils/callWithNuxt.ts#L6 It calls the `getRequestURL` inside Nuxt. This apparantly returns an absolute URL.
4. Vue Router gets an absolute URL to navigateTo, so it thinks it should be external, and so you need to set `external: true`. That is not the behaviour you want in a SPA. 
	- A second workaround is to use `external: true` flag in the signInOptions. Important: this does not work for `refresh`. Because that is missing in the code there. Downside of this workaround is that the page will do a full refresh. Not so nice.

**Comment by clcoco** [comment]
> I ran into this problem also. First, I have a simple workaround implemented for now:
> 
> ```
> const { signIn } = useAuth();
> const { redirectedFrom } = useRoute();
> 
> signIn(
>     {
>         password,
>         username,
>     },
>     {
>         callbackUrl: redirectedFrom ? redirectedFrom.fullPath : '/',
>     },
> );
> ```
It works only for internal navigation though, doesn't it? If I arrive from an external route (ie: a page refresh) it doesn't work. The redirect to the login page from the protected routes, if i'm not mistaken, is handled as external so it won't work.


>        * A second workaround is to use `external: true` flag in the signInOptions. Important: this does not work for `refresh`. Because that is missing in the code there. Downside of this workaround is that the page will do a full refresh. Not so nice.

Second this, the `external` bool is ignored for some reason

**Comment by bitfactory-frank-spee** [comment]
> @clcoco It works only for internal navigation though, doesn't it? If I arrive from an external route (ie: a page refresh) it doesn't work. The redirect to the login page from the protected routes, if i'm not mistaken, is handled as external so it won't work.

I am not sure I fully understand. The auth middleware (logged in guard) is working as intended for me. When you set this:
```
    globalAppMiddleware: {
        isEnabled: true,
    },
```

So if you come from an external route and you are not logged in you will be redirected to the login page. If you are already logged in (session in local storage / cookie / etc.) then there is no need to use `signIn`, the module will call `getSession`.

If you come from an external page directly to (or refresh on) the login page then the `redirectedFrom` is undefined or null. So in my workaround there is a check if it is available, if not then default the callback to the root page `/`.

**Comment by bitfactory-frank-spee** [comment]
@Vitalii-Kh95 Why can't you adjust your code to this?
```
async function userRegister() {
    const { redirectedFrom } = useRoute();
    
    try {
        await signUp(
            { ...register}
        );
        await signIn(
            { 
                username: register.username, 
                password: register.password,
            },
            {
                callbackUrl: redirectedFrom ? redirectedFrom.fullPath : '/',
            },
        );
    } catch (error) {
        console.log("error", error);
    }
}
```
So you add the second options parameter to the signIn call with the callbackUrl?

**Comment by bitfactory-frank-spee** [comment]
@Vitalii-Kh95 Hmm, if it works it works 🙂. Make sure to check the documentation on local provider here: https://sidebase.io/nuxt-auth/configuration/nuxt-config and here: https://sidebase.io/nuxt-auth/application-side/session-access-and-management
