### ISSUE TITLE
Custom Session Data for CredentialsProvider is broken

### ISSUE THREAD

**Issue by FrankoFM** [sidebase/nuxt-auth#661]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.8.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- User Config:      devtools, builder, site, modules, runtimeConfig, tailwindcss, sitemap, gtag, image, nitro, auth
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.3, @nuxt/content@2.12.0, @nuxt/image@1.3.0, @nuxtjs/robots@3.0.0, nuxt3-leaflet@1.0.12, nuxt-simple-sitemap@3.4.1, nuxt-gtag@1.2.0, @sidebase/nuxt-auth@0.6.7     
- Build Modules:    -

### Reproduction

https://github.com/sidebase/nuxt-auth-example

### Describe the bug

When login is a success, it return the user object to store it in the session data, however that is only working for the "default" fields like "name", "email" and "image"

Not working in my env, also tested in on the example repo, looks broken there too.

This is the User object that is returned on success:
`const user = { id: '1', name: 'J Smith', username: 'jsmith', password: 'hunter2' }`

However this is the session data:
![image](https://github.com/sidebase/nuxt-auth/assets/49619925/157eb31d-0ad0-4ba6-9dbc-d182bd196ba5)

As you can see it only has the 'name' value

**Comment by FrankoFM** [comment]
Fixed it by using the `jwt` and `session` [callback](https://sidebase.io/nuxt-auth/recipes/custom-session-data#add-callbacks-to-the-nuxtauthprovider-to-alter-the-session-data), so this should be added to the example i guess.

**Comment by zoey-kaiser** [comment]
Hi @FrankoFM 👋 

We have this features in our docs: https://sidebase.io/nuxt-auth/recipes/custom-session-data. We can look to update the example in the future to feature this too!
