### ISSUE TITLE
Cannot set redirect_uri for Google authentication provider

### ISSUE THREAD

**Issue by matthewairalo** [sidebase/nuxt-auth#664]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Describe the bug

I cannot set a custom redirect uri for the Google provider. It always seems to just send the default /api/auth/providers/google instead, which results in an error from Google authenticator due to redirect_uri mismatch.

Here's my configuration:

**nuxt.config.js**
```
auth: {
    provider: {
      type: 'authjs',
      token: '',
      addDefaultCallbackUrl: false,
      globalAppMiddleware: false,
    },
    addDefaultCallbackUrl: false,
    baseURL: '/nuxt-api/auth',
  },
```

**server/routes/nuxt-api/auth/[...].ts** (yes, I am trying every option that came to my mind)
```
  providers: [
    // @ts-ignore Import is exported on .default during SSR, so we need to call it this way. May be fixed via Vite at some point
    GoogleProvider.default({
      clientId: process.env.GOOGLE_APPID,
      options: {
        callbackUrl: `${process.env.APP_URL}/auth/callback`,
        callback_url: `${process.env.APP_URL}/auth/callback`,
        redirect_uri: `${process.env.APP_URL}/auth/callback`,
        redirectUri: `${process.env.APP_URL}/auth/callback`,
        redirect_url: `${process.env.APP_URL}/auth/callback`,
        redirectUrl: `${process.env.APP_URL}/auth/callback`,
        user: false,
      },
      callbackUrl: `${process.env.APP_URL}/auth/callback`,
      callback_url: `${process.env.APP_URL}/auth/callback`,
      redirect_uri: `${process.env.APP_URL}/auth/callback`,
      redirectUri: `${process.env.APP_URL}/auth/callback`,
      redirect_url: `${process.env.APP_URL}/auth/callback`,
      redirectUrl: `${process.env.APP_URL}/auth/callback`,
    }),
  ],
```

**Comment by matthewairalo** [comment]
Similar issues with any provider. All seem to be using the default /api/auth/callback/:provider: route.

**Comment by ElizeoRocha** [comment]
@matthewairalo the redirect_uri worked with this approach for me, I hope it helps you

![image](https://github.com/sidebase/nuxt-auth/assets/48933133/6125972d-e145-4300-88a9-3f05d083f3db)

**Comment by zoey-kaiser** [comment]
Please follow the configuration provided above 😊
