### ISSUE TITLE
Add refresh token body key to refresh request in refresh  provider

### ISSUE THREAD

**Issue by hdood** [sidebase/nuxt-auth#689]
### Describe the feature

Add a key in configuration file that allow us to  to customize the refresh token body key in refresh request. 

### How would you implement this?

I will add a key in `types.ts` file and name it `requestbodyKey` with the default value `refreshToken` and then update `refresh` method in `useAuth.ts` to reflect those changes.

### Additional information

- [X] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [ ] Local
- [X] Refresh
- [ ] New Provider

**Comment by phoenix-ru** [comment]
Duplicates #635
