### ISSUE TITLE
RFC: Add session broadcasting to share the nuxt auth session between tabs

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#70]
### Describe the feature

Proposed by @JoaoPedroAS51.

We should support broadcasting of session data to share the session state between different tabs. This was originally suggested by @JoaoPedroAS51 and a first implementation of this exists here: https://github.com/eloqjs/nuxt-next-auth

**Comment by tcrold** [comment]
i think this is a solution to a problem wherein a user opens 2 tabs of the app's Login Page. The moment he logs in to the first tab, Nuxt Auth cannot detect that the user already logged in to the app in the 2nd tab. So, the user can still login to it using other credentials and thus beating the purpose of ensuring integrity across tabs.
