### ISSUE TITLE
feat: ✨ add flag to disable getSession after signIn on local / refresh provider

### ISSUE THREAD

**Issue by bitfactory-frank-spee** [sidebase/nuxt-auth#701]
### Describe the feature

With the `signIn` method it should be possible to optionally do a `getSession` so you can manually call for session data and manually handle the errors coming from the `getSession` endpoint.

### How would you implement this?

I created a PR: https://github.com/sidebase/nuxt-auth/pull/702

### Additional information

- [X] Would you be willing to help implement this feature?

Some extra information why we need this:

Our 2FA/OTP middleware on the Laravel API returns a `428` error on `user/me` (or any other endpoint if 2FA is needed). The `signIn` method always calls `getSession`, and the error from the `user/me` API endpoint [dies in `getSession`](https://github.com/sidebase/nuxt-auth/blob/a3538f129d30962ffafd3ac4f5497e1f89372607/src/runtime/composables/local/useAuth.ts#L88) (clearing the token etc.). Because this catch we need to manually call the `user/me` endpoint outside this module. So right now we want to prevent the `getSession` getting called so we still have the token etc. and call it manually.

Another solution could also be to allow the API error(s) from `getSession` bubble through (and not clear the token etc. immediately) or create some kind of hook so we can intercept on special errors like a 428. This is more work and need more design to be able to create this for local and refresh provider without drifting to far from the `authjs` provider. 

### Provider

- [ ] AuthJS
- [X] Local
- [X] Refresh
- [ ] New Provider

**Comment by bitfactory-frank-spee** [comment]
@zoey-kaiser Thanks for releasing this! 🚀

**Comment by zoey-kaiser** [comment]
Thank you for pushing this and being so patient ❤️ Happy holidays and have a great start into your new year!
