### ISSUE TITLE
Add a configuration option for refreshToken and accessToken names in auth requests

### ISSUE THREAD

**Issue by MelvinIdema** [sidebase/nuxt-auth#703]
### Describe the feature

Add a configuration option to rename refresh_token and access_token to what a backend expects. Right now whenever the refresh provider asks for a new refresh token it'll include the refresh token in to body of the request as "refreshToken" but our back-end expects the naming to be in snake case like this: "refresh_token".

### How would you implement this?

An extra option in the provider configuration:

```
{
      token: {
        signInResponseTokenPointer: "/data/access_token",
        requestName: "access_token",
        headerName: "Authorization",
        maxAgeInSeconds: 60 * 60,
      },
      refreshToken: {
        signInResponseRefreshTokenPointer: "/data/refresh_token",
        requestName: "refresh_token",
        maxAge: 60 * 60 * 24 * 30,
      },
}
```

### Additional information

- [X] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [ ] Local
- [X] Refresh
- [ ] New Provider

**Comment by emrecanmuslu** [comment]
Hello,

I also request this update to be made.

**Comment by phoenix-ru** [comment]
Duplicates #635
