### ISSUE TITLE
0.70 Resolved a Big Issue (NEXTAUTH_URL) - Thank You!

### ISSUE THREAD

**Issue by lspellman-opsguru** [sidebase/nuxt-auth#708]
### Environment

Just wanted to give a quick shoutout for something 0.70 fixed. 

I've been using 0.67 with a Nuxt 3 app and been banging my head against the wall for a few days where deployment to AWS Amplify was blocked by the NEXTAUTH_URL environment variable problem.  For others who are researching this kind of problem, the issue is that you do not have control (i.e. can't set) any runtime environment variables for the "server" Amplify deploys with your app.  

Buried within next-auth library is a call to process.env.NEXTAUTH_URL, that it can never retrieve. When it can't it sets the redirect_uri for Auth callbacks to http://localhost:3000 -- entirely blocking your production deployment! 

I haven't dug into the internals to see what got changed with 0.70, but a vanilla deployment with whatever next-auth dependency it wants, works great.  redirect_uri now picks up the domain host and callbacks from SignIn work.

Got lucky as I just happened to notice the release had been out there for 10 hours and decided to give it a whirl.  

Many thanks!  Close this ticket as soon as you'd like!

### Reproduction

No repo needed

### Describe the bug

No more bug :-)  Joining as sponsor for solving my problem before you even knew I was having it, lol.

**Comment by zoey-kaiser** [comment]
Hi @lspellman-opsguru 👋 

Thank you so much for your kind words! This issue completely went under, as you already had closed it, therefore I just noticed it ❤️
