### ISSUE TITLE
custom cookie name for `local` provider

### ISSUE THREAD

**Issue by GamerGirlandCo** [sidebase/nuxt-auth#717]
### Describe the feature

I'd like the ability to change the name of the cookie that stores the `local` provider's token.

### How would you implement this?

through an option in the nuxt config

### Additional information

- [X] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [X] Local
- [ ] Refresh
- [ ] New Provider

**Comment by zoey-kaiser** [comment]
Hi @GamerGirlandCo 👋 

Thanks for the suggestion. I think configuring it via the Nuxt Config makes sense. Would you like to open a PR yourself?

**Comment by GamerGirlandCo** [comment]
> Hi @GamerGirlandCo 👋
> 
> Thanks for the suggestion. I think configuring it via the Nuxt Config makes sense. Would you like to open a PR yourself?

I was going to, but looking at the code, it appears that it's already been done here 😅
https://github.com/sidebase/nuxt-auth/blob/5d713aa419bcefc342f6a6e14899db6cc3d05d7f/src/runtime/types.ts#L64-L179

**Comment by phoenix-ru** [comment]
Was already closed by https://github.com/sidebase/nuxt-auth/pull/654
