### ISSUE TITLE
Token (cookie) is lost on refresh using Docker

### ISSUE THREAD

**Issue by julian-dueck** [sidebase/nuxt-auth#718]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.1
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      runtimeConfig, devtools, modules, auth, colorMode, tailwindcss
- Runtime Modules:  @sidebase/nuxt-auth@0.6.7, @nuxt/ui@2.14.2
- Build Modules:    -

### Reproduction

No reproduction, sorry. I think it's pretty straight forward.

### Describe the bug

My app runs fine with `npm run dev` and `npm run build` until I dockerize it for production. I use the Dockerfile template provided by sidebase. I execute `npm run build` in the Dockerfile and run it with `node /app/.output/server/index.mjs`. I use `local` provider. When I log in with credentials, everything works fine, until I refresh the page and the token (cookie) is gone and the user is sent back to the login page. Is the vueApp being unmounted on refresh? Is the session data lost on refresh?

### Additional context

Dockerfile
```Dockerfile
ARG NODE_VERSION=node:20.11.1

FROM $NODE_VERSION AS dependency-base

# create destination directory
RUN mkdir -p /app
WORKDIR /app

# copy the app, note .dockerignore
COPY package.json .
COPY package-lock.json .
RUN npm ci

FROM dependency-base AS production-base

# build will also take care of building
# if necessary
COPY . .
RUN npm run build

FROM $NODE_VERSION AS production

COPY --from=production-base /app/.output /app/.output

# Run in production mode
ENV NODE_ENV=production
```

Docker Compose
```docker-compose
version: '3.9'

services:
  web:
    build: 
      context: .
    env_file:
      - .env
    ports:
      - "80:3000"
    command: node /app/.output/server/index.mjs
```

Is this a Docker issue? Did I do something wrong?

**Comment by sandrinjoy** [comment]
I have also faced similar issue, the cookie gets removed on certain scenario.
So on refreshing & since there is no auth cookie , we take them to login page.
Weird part is that, after waiting for a few seconds, the cookie got restored, probably the authtoken api got hit.
After refreshing again, the user is logged in back.
@julian-dueck can you share your auth config ?

**Comment by julian-dueck** [comment]
This is my auth config:
```
auth: {
  isEnabled: true,
  provider: {
    type: 'local',
    sessionDataType: {status: 'string', created: 'string', userInfo: {id: 'string', fullName: 'string', username: 'string'}},
  },
  session: {
    enableRefreshPeriodically: 10000,
    enableRefreshOnWindowFocus: true,
  },
  globalAppMiddleware: true,
}
```
In my case, the cookie does not get restored after waiting for a few minutes.
