### ISSUE TITLE
Investigate whether we can drop the requirement of setting an `origin` for production

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#72]
### Describe the feature

At the moment we require an origin for production and fallback to defaults for development.

This was based on the deployment guide of next auth: https://next-auth.js.org/deployment

In a recent PR @JoaoPedroAS51 raised that we may be able to drop it: https://github.com/sidebase/nuxt-auth/pull/69#discussion_r1037297982

I found no convincing reasons to not drop it, however this should be investigated first as it may be security related (e.g.: for oauth callbacks).

**Comment by manniL** [comment]
Do you *need* to provide it in Next Auth? 🤔
That could be a good indicator.

**Comment by JoaoPedroAS51** [comment]
What I meant is that we can create a single func that uses the `origin` and fallback to `requrl`. So `origin` still required for production, but optional for development. Then in production we check if the `origin` is defined in build time.
