### ISSUE TITLE
Set the secure attribute of the token cookies.

### ISSUE THREAD

**Issue by matteioo** [sidebase/nuxt-auth#728]
### Describe the feature

I would appreciate it if there is a possibility to set the `Secure` attribute on both `token` and `refresh` cookies. Thus resulting in the cookies only being sent through HTTPS. 

I will link the PR where I already made changes which worked in both relevant playgrounds. For now, the `secureCookieAttribute` defaults to `false`, even though I am open for discussions about a more secure default by switching it to `true` if not defined otherwise.

### How would you implement this?

How about adding a new attribute in `nuxt.config.ts` in both `ProviderLocal` and `ProviderRefresh`? Nonetheless, open for other ways on how to implement the Secure attribute of the token and refresh cookies.

### Additional information

- [X] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [X] Local
- [X] Refresh
- [ ] New Provider

**Comment by FerhatCengz** [comment]
I think not, you can configure it with auth js instead.

**Comment by phoenix-ru** [comment]
Closed via #729
