### ISSUE TITLE
Nuxt-auth + nuxt/i18n wipes out all types from the config file

### ISSUE THREAD

**Issue by TheDutchCoder** [sidebase/nuxt-auth#737]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, auth, modules, runtimeConfig
- Runtime Modules:  @sidebase/nuxt-auth@0.7.1, @nuxtjs/i18n@8.3.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-js6xqk?file=composables%2FuseThing.ts

### Describe the bug

Bear with me for this one, I'm not sure which module is to blame here, but the combo of these two modules removes all type definitions from the runtime config.

You can see, in the composable, that `.foo` is no longer typed when both modules are enabled.
When I disable either of these modules, types generate correctly.

Bug report on nuxt/i18n repo: https://github.com/nuxt-modules/i18n/issues/2915

**Comment by TheDutchCoder** [comment]
This looks like an i18n bug, as downgrading it makes it work again.
I'll close this once they confirm

**Comment by phoenix-ru** [comment]
#738 was merged, this needs re-checking after 0.7.3 is out

**Comment by TheDutchCoder** [comment]
There's no 0.7.3 release though?

**Comment by TheDutchCoder** [comment]
Oh it's an alpha release.
Not sure I want to move that to production
