### ISSUE TITLE
Redirect back to login page after logged in and reload the page [Local provider - Static files]

### ISSUE THREAD

**Issue by prabodhana** [sidebase/nuxt-auth#743]
### Environment

- Operating System: Linux
- Node Version:     v20.12.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      modules, typescript, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.7.2
- Build Modules:    -

### Reproduction

[stackblitz](https://stackblitz.com/edit/github-y43qrn?file=pages%2Findex.vue)

Login - 1000
password  - 123456

### Describe the bug

I use sidebase nuxt auth local provide for my project. On the local development env its works without issue but after I complied it to static files using nuxt generate command. and after its have strange behavior. After I logged in to the system and if I refresh the browser window its logged out me and redirect me to login page.

### Logs

There's a warning after run nuxt generate command

>  WARN  [plugin:vite:reporter] [plugin vite:reporter]                                         
> (!) project_path..../node_modules/@sidebase/nuxt-auth/dist/runtime/middleware/auth.mjs is dynamically imported by virtual:nuxt:/project_path..../.nuxt/middleware.mjs but also statically imported by /project_path..../node_modules/@sidebase/nuxt-auth/dist/runtime/plugin.mjs, dynamic import will not move module into another chunk.

**Comment by ThorsAngerVaNeT** [comment]
Have the same issue

**Comment by zoey-kaiser** [comment]
Closed in favour of #754
