### ISSUE TITLE
cannot start the module playground

### ISSUE THREAD

**Issue by wingchiutong** [sidebase/nuxt-auth#753]
### Environment

MacOS

### Reproduction

> git clone https://github.com/sidebase/nuxt-auth

> cd nuxt-auth

> pnpm i

> pnpm dev:prepare

> pnpm dev

### Describe the bug

I've followed the instruction from this page - https://nuxt.com/modules/sidebase-auth

After configuring the Github clientId, and clientSecret in the server/api/auth/[...].ts, then executing `pnpm dev`, I get this error 

ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "dev" not found

Please help.

Thanks!
Gary

**Comment by phoenix-ru** [comment]
What module playground are you trying to open? I think the instruction is outdated and you need to `cd` into it, e.g.
```sh
cd playground-local
pnpm dev
```

**Comment by wingchiutong** [comment]
> What module playground are you trying to open? I think the instruction is outdated and you need to `cd` into it, e.g.
> 
> ```shell
> cd playground-local
> pnpm dev
> ```

You are a star. It works now. Thank you so much. I am able to login with Github. Cheers
