### ISSUE TITLE
Issue with Keycloak Provider

### ISSUE THREAD

**Issue by sregdorr** [sidebase/nuxt-auth#760]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.8.0
- Builder:          -
- User Config:      devtools, build, modules, vite, auth, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.5.1, @sidebase/nuxt-auth@0.7.2, ()
- Build Modules:    -
------------------------------

### Reproduction

You'll have to forgive me, I've not used an online IDE like this before, and I can't figure how to securely use secrets, but I actually don't think you need them. It's already throwing the first error that is blocking me with [just this](https://stackblitz.com/edit/github-1mjsqw?file=server%2Fapi%2Fauth%2F%5B...%5D.ts).

### Describe the bug

When I use the Keycloak provider as described [here](https://next-auth.js.org/providers/keycloak) and run the app I get this error on startup:

```
[nitro] [uncaughtException] KeycloakProvider is not a function

  at <anonymous> (server\api\auth\[...].ts:59:1)
  at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
  at async loadESM (node:internal/process/esm_loader:28:7)
  at async handleMainPromise (node:internal/modules/run_main:113:12)
```

If I create my own provider with something like this:
```
import {NuxtAuthHandler} from "#auth"
import KeycloakProvider from "next-auth/providers/keycloak";
import type {Provider} from 'next-auth/providers/index'


const { keycloak, authSecret } = useRuntimeConfig()

console.log(JSON.stringify(keycloak))

function KeycloakProvider1() {
  const { keycloak } = useRuntimeConfig()
  console.log(`${keycloak.issuer}/.well-known/openid-configuration`)

  return {
    id: "keycloak",
    name: "Keycloak",
    clientId: keycloak.clientId,
    clientSecret: keycloak.clientSecret,
    wellKnown: `${keycloak.issuer}/.well-known/openid-configuration`,
    type: "oauth",
    version: "2.0",
    authorization: {
      params: {
        scope: "openid email profile",
        code_challenge_method: "S256"
      }
    },
    checks: ["pkce", "state"],
    idToken: true,

    profile(profile: any) {
      var _profile$name;

      return {
        id: profile.sub,
        name: (_profile$name = profile.name) !== null && _profile$name !== void 0 ? _profile$name : profile.preferred_username,
        email: profile.email,
        image: profile.picture
      };
    },

    style: {
      logo: "/keycloak.svg",
      logoDark: "/keycloak.svg",
      bg: "#fff",
      text: "#000",
      bgDark: "#fff",
      textDark: "#000"
    },
  } as Provider
}

export default NuxtAuthHandler({
  secret: authSecret,
  providers: [
    // GithubProvider.default({}),
    KeycloakProvider1()
    //   KeycloakProvider({
    //     id: "keycloak",
    //     clientId: keycloak.clientId,
    //     clientSecret: keycloak.clientSecret,
    //     issuer: keycloak.issuer,
    //   })
  ],
})

```

It works beautifully ...locally. I can `npm run dev` and auth works. I can `npm run build`, source my .env variables, and then `node .output/server/index.mjs` and auth works.

But, when I build the image with this Dockerfile:
```
FROM node:lts as builder
WORKDIR /build

COPY ./package.json /
COPY ./package-lock.json /

RUN npm ci

COPY . .

ARG GIT_COMMIT
ARG APP_VERSION

ENV NUXT_GIT_COMMIT_HASH=$GIT_COMMIT
ENV NUXT_APP_VERSION=$APP_VERSION

RUN npm run build

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
```

And then try to `docker-compose up` this file:
```
version: "3"

services:
  sales2:
    container_name: sales2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "1.2.3"
        GIT_COMMIT: xx.test
    environment:
      - NUXT_AUTH_SECRET=****
      - AUTH_ORIGIN=http://localhost:3000
      - NUXT_KEYCLOAK_CLIENT_ID=****
      - NUXT_KEYCLOAK_CLIENT_SECRET=****
      - NUXT_KEYCLOAK_ISSUER=https://****.com/realms/****
    ports:
      - "3000:3000"

```

The application will start and I can navigate to the index page, but when I call `await signIn("keycloak")` I get the following error:
```
[nuxt] [request error] [unhandled] [500] (0 , _preactRenderToString.default) is not a function
sales2  |   at send (./.output/server/chunks/routes/api/auth/_..._.mjs:13671:512)
sales2  |   at Object.signin (./.output/server/chunks/routes/api/auth/_..._.mjs:13677:15)
sales2  |   at AuthHandler (./.output/server/chunks/routes/api/auth/_..._.mjs:14766:23)
sales2  |   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sales2  |   at async Object.handler (./.output/server/chunks/routes/api/auth/_..._.mjs:15012:24)
sales2  |   at async Object.handler (./.output/server/chunks/runtime.mjs:3059:19)
sales2  |   at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3325:7)
```

**Comment by phoenix-ru** [comment]
Please notice that you need to use `KeycloakProvider.default(` due to a known Vite bug, same as here:
https://github.com/sidebase/nuxt-auth/blob/faa039b72da2c64d9c214f0502dea053c7a4ff84/playground-authjs/server/api/auth/%5B...%5D.ts#L9-L15

**Comment by sregdorr** [comment]
Awesome! Thank you @phoenix-ru. I will give that a try!

**Comment by zoey-kaiser** [comment]
Hi @sregdorr 👋 

I also used the Keyclock provider a while back and had no problems! The code for this is open source, feel free to have a look at how I did it and copy some code: https://github.com/pixeltranslate/app/blob/0.1.0-alpha.1/server/api/auth/%5B...%5D.ts

I will close this issue now, if you need any further help, feel free to reopen!

**Comment by sregdorr** [comment]
Much appreciated, @zoey-kaiser!
