### ISSUE TITLE
Refresh provider on tab refocus calls `getSession` instead of `refresh`

### ISSUE THREAD

**Issue by mbellamyy** [sidebase/nuxt-auth#765]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.15.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      nitro, auth, components, imports, runtimeConfig, modules, pinia, security, build, css, app, robots, devtools
- Runtime Modules:  nuxt-security@1.4.3, @nuxtjs/tailwindcss@6.12.0, @pinia/nuxt@0.5.1, @vueuse/nuxt@10.9.0, @nuxtjs/robots@3.0.0, @nuxt/image@1.7.0, @sidebase/nuxt-auth@0.7.2
- Build Modules:    -
------------------------------

### Reproduction

not needed, code is obvious

### Describe the bug

This is actually two issues. 

First issue is here. Let's assume `refresh` provider is chosen.

https://github.com/sidebase/nuxt-auth/blob/faa039b72da2c64d9c214f0502dea053c7a4ff84/src/runtime/utils/refreshHandler.ts#L43-L62

We're creating two intervals. One of them is calling `getSession` and the other is calling `refresh`. But the `refresh` implementation calls `getSession` at the end itself... So the first interval might be redundant for refresh? I know the interval times are different. So this is not a hugely imporant part of this issue. 

## Now the second (and more important) part of the issue: 

https://github.com/sidebase/nuxt-auth/blob/faa039b72da2c64d9c214f0502dea053c7a4ff84/src/runtime/utils/refreshHandler.ts#L22-L29

This function is the tab refocus refresher. It is calling `getSession` which is acceptable in the `local` provider, but for `refresh` I think it should call `refresh`, which in turn calls `getSession` later. 
If the token is expired (but can be refreshed), this method is missing it and logging the user out.

**Comment by ThomasSimonsen20** [comment]
@phoenix-ru Hey Phoenix sorry to ping, I see you started working on a PR regarding this, is this something you are still working on? I am facing a similar issue as above and I believe your PR would fix that issue :)

I am sadly not experienced enough to figure out if I could help with anything in your PR, as I can barely understand what's going on :D

**Comment by phoenix-ru** [comment]
Hi @ThomasSimonsen20 , I was on a vacation :slightly_smiling_face: 
I will possibly come back to this in 2 days or next week, as it's awaiting review from @zoey-kaiser

**Comment by ThomasSimonsen20** [comment]
Thank you for the update, hope you had a nice vacation :)

**Comment by zoey-kaiser** [comment]
Hi @mbellamyy and @ThomasSimonsen20 👋 

Sorry for the ping, but I wanted to quickly let you know that we have just released https://github.com/sidebase/nuxt-auth/releases/tag/0.8.0-alpha.3 in which you can now define your own custom refresh logic! Feel free to check out the release notes for more information!
