### ISSUE TITLE
baseURL is not working

### ISSUE THREAD

**Issue by zecar** [sidebase/nuxt-auth#772]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      future, srcDir, devtools, components, modules, colorMode, ignore, appConfig, css, extensions, ssr, routeRules, vue, nitro, runtimeConfig, auth, router, vite, i18n, csurf, content
- Runtime Modules:  @nuxt/eslint@0.3.13, @nuxt/test-utils/module@3.13.1, @unocss/nuxt@0.61.0, @sidebase/nuxt-auth@0.7.2, @pinia/nuxt@0.5.1, @nuxt/content@2.12.1, nuxt-csurf@1.5.2, @nuxtjs/i18n@8.3.1, @nuxtjs/tailwindcss@6.12.0, @nuxtjs/color-mode@3.4.1
- Build Modules:    -
------------------------------

### Reproduction

setup auth module option inside nuxt.config.ts to 

baseURL: 'http://project.local:3001',

### Describe the bug

the `<form>` element from the default signin page keeps pointing to "localhost" instead of what was set in nuxtConfig.auth.baseURL

![image](https://github.com/sidebase/nuxt-auth/assets/8117818/ca7cef18-865c-455e-be9f-6ef87b64c60c)

**Comment by zoey-kaiser** [comment]
Hi @zecar 👋 

What other environment variables do you pass? Also, how do you overwrite `nuxtConfig.auth.baseURL`? If you are using an environment variable in your Nuxt Config, you will need to set it at built time.

**Comment by zecar** [comment]
@zoey-kaiser, sorry for not updating

I got this working by passing `AUTH_ORIGIN` and `NEXTAUTH_URL`

please update the docs of the project with this usecase
