### ISSUE TITLE
Need to set NEXTAUTH_URL and it's undocumented

### ISSUE THREAD

**Issue by dword-design** [sidebase/nuxt-auth#773]
### Describe the feature

I need to set `NEXTAUTH_URL`, otherwise I get a warning in the console that it's not set and all callback urls are set to localhost. Here is what seems to work for me:

```
NEXTAUTH_URL=http://domain.local:port
baseURL or AUTH_ORIGIN=http://domain.local:port
```

See also [this comment](https://github.com/sidebase/nuxt-auth/issues/735#issuecomment-2104513928).

I couldn't get it to work with paths other than the default `/api/auth`.

### Provider

- [X] AuthJS
- [ ] Local
- [ ] Refresh
- [ ] New Provider

**Comment by basarozcan** [comment]
Thank you for your comment @dword-design . I also faced with that issue and solved with using 'NEXTAUTH_URL' as you described

**Comment by zoey-kaiser** [comment]
Hi @dword-design 👋 

We are currently working on a rewrite of our documentation to better explain and outline all the nuances such as required environment variables! Thank you for opening an issue to raise more awareness of this!

I will ensure that this information is properly included and outlined in the new documentation 🥳

**Comment by zoey-kaiser** [comment]
Hi @dword-design 👋 

We just released the new docs. Please have a look at:

- https://auth.sidebase.io/guide/advanced/deployment/self-hosted
- https://auth.sidebase.io/guide/application-side/configuration#baseurl

That both go into more details about the usage of `baseURL` and `AUTH_ORIGIN`. I hope they give you a better overview of what environment secrets are needed!
