### ISSUE TITLE
Error: Navigating to an external URL is not allowed by default. Use `navigateTo(url, { external: true })`.

### ISSUE THREAD

**Issue by kaboume** [sidebase/nuxt-auth#775]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      runtimeConfig, devtools, build, modules, vite, auth
- Runtime Modules:  (), @pinia/nuxt@0.5.1, @sidebase/nuxt-auth@0.7.2
- Build Modules:    -
------------------------------

### Reproduction

nuxt.config.ts : 
```

auth: {
    baseURL: "http://localhost:8081/v1/",
    provider: {
      type: "local",
      endpoints: {
        signIn: { path: "/auth/login", method: "post" },
        signOut: { path: "auth/logout", method: "post" },
        signUp: { path: "auth/register", method: "post" },
        getSession: { path: "auth/user", method: "get" },
      },
      token: { signInResponseTokenPointer: "/tokens/access/token" },
    },
  },
```

### Describe the bug

Hi,

When the signin method is executed, this message is thrown : 

**MyLogin.vue:59 Error: Navigating to an external URL is not allowed by default. Use `navigateTo(url, { external: true })`.
    at navigateTo (router.js?v=07f3b5e0:74:13)
    at signIn (useAuth.mjs?v=07f3b5e0:33:12)
    at async Proxy.login (MyLogin.vue:50:5)**

```
await signIn({
      email: email.value,
      password: password.value,
      recaptchatoken,
    });
    loading.value = false;
    ....
}
```

**Comment by zoey-kaiser** [comment]
For anyone stumbling on this issue: If you need to redirect to an external URL you can pass the flag `external` into the method to ensure this error does not occur and the redirect is handled properly:

```ts
// Trigger a sign-in with a redirect afterwards to an external page (if set, this will cause a hard refresh of the page)await signIn(credentials, { callbackUrl: 'https://sidebase.io', external: true })
```

Source: https://sidebase.io/nuxt-auth/application-side/session-access-and-management

**Comment by Suniron** [comment]
I got the same error with a simple `signIn` without any redirect:

```ts
const handleSubmit = async (e: Event) => {
  e.preventDefault()
  const credentials = {
    password: password.value,
    username: login.value,
  }

  isLoading.value = true
  await signIn(credentials)
  isLoading.value = false
}
```

So, the `isLoading.value = false` is never reached.

Any idea?
