### ISSUE TITLE
Update documentation on endpoint paths starting with `/`

### ISSUE THREAD

**Issue by spras** [sidebase/nuxt-auth#782]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.12.2`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `yarn@1.22.22`
- Builder:          `-`
- User Config:      `debug`, `ssr`, `devtools`, `runtimeConfig`, `modules`, `css`, `vuetify`, `auth`, `features`, `app`, `components`, `hooks`, `build`
- Runtime Modules:  `vuetify-nuxt-module@0.14.1`, `@nuxt/test-utils/module@3.13.1`, `@nuxtjs/device@3.1.1`, `@sidebase/nuxt-auth@0.8.0-rc.1`, `@vueuse/nuxt@10.11.0`
- Build Modules:    `-`

### Reproduction

here is my nuxt.config.ts 
```
  auth: {
    baseURL: process.env.CUSTOM_API_URL + "/",
    globalAppMiddleware: {
      isEnabled: true,
    },
    session: {
      enableRefreshPeriodically: false,
      enableRefreshOnWindowFocus: true,
    },
    provider: {
      type: "local",
      token: {
        maxAgeInSeconds: 18000,
        sameSiteAttribute: "strict",
        secureCookieAttribute: true,
      },
      endpoints: {
        getSession: { path: "/api/session", method: "get" },
      },
      pages: {
        login: "/connexion",
      },
    },
  },
```
### Describe the bug

I'm currently testing upgrade from 0.7.2 to 0.8.0-rc

This break my config : local provider and auth.baseURL defined to a custom base url ex : https://example.com/

Login is posted to the nuxt base URL , not to my custom base url

As a workaround I had to redefine all the endpoints and removing the / prefix .

```
endpoints: { 
       signIn: { path: 'login', method: 'post' },        
       signOut: { path: 'logout', method: 'post' },        
       signUp: { path: 'register', method: 'post' },        
       getSession: { path: 'session', method: 'get' }    
}
```
Perhaps it has to become the default values ?

It seems to be linked to the modifications for this issue https://github.com/sidebase/nuxt-auth/issues/742 , 
https://github.com/sidebase/nuxt-auth/pull/750/files ,  joinPathToApiURL function

**Comment by phoenix-ru** [comment]
Hi @spras, it looks correct to me that you redefine your endpoints because of the custom base url.
Using `/` prefix for endpoints always means to use Nuxt's internal routing - this is intended.

This behaviour was mostly inspired by how URL's are resolved in the browser. For example, assuming you are on https://example.com/subpage and you have `<a href="/another">`, you will be navigated to https://example.com/another.
I wanted to replicate it, but in the context of Nuxt. Our module assumes that URLs starting with `/` are local to Nuxt, therefore it avoids extra overhead of crossing the domain boundary.

The fact that using `{ path: 'login' }` satisfies your usecase should be considered a bug rather than a desired result. Similar to browser navigation analogy, I would expect the navigation to be same-level (e.g. `{ path: 'three' }` switching from `/one/two` to `/one/three`). But since I don't foresee anyone ever wanting same-level navigation, it is how it is.

I would suggest you to use fully-specified URLs in path configs, because your usecase (I assume) involves going away from Nuxt to an external custom URL.

**Comment by Ray0907** [comment]
I faced the similar issue. Here is my nuxt.config file. Ensure that the origin ends with a ‘/’. This worked for me.
```
auth: {
		provider: {
			type: 'authjs',
		},
		origin: '/prefix/',
	},
```

**Comment by spras** [comment]
@phoenix-ru your explaination make sense , it'OK for me. I think documentation should be more detailed and explicit on it.

**Comment by phoenix-ru** [comment]
Thank you for the feedback @spras, we will adjust the documentation accordingly

**Comment by coreyshuman** [comment]
I've been struggling with this as well when using an external auth server on `@sidebase/nuxt-auth@0.8.0`. Here are some of the configurations I've tried and their unexpected outcomes:

### Example 1 - Incorrect URL

```js
auth: {
  baseURL: 'http://base-url',
  provider: {
    endpoints: {
      signIn: {path: 'http://api-url/login'},
    },
}
```

The sign in path becomes: `http://base-url/api/auth/http://api-url/login`

### Example 2 - Incorrect URL

Add the ending slash on baseURL.
```js
auth: {
  baseURL: 'http://base-url/',
  provider: {
    endpoints: {
      signIn: {path: 'http://api-url/login'},
    },
}
```

The sign in path becomes: `http://base-url/http://api-url/login`

### Example 3 - Incorrect URL

Delete baseURL.
```js
auth: {
  baseURL: '',
  provider: {
    endpoints: {
      signIn: {path: 'http://api-url/login'},
    },
}
```

The sign in path becomes: `http://localhost:3000/api/auth/http://api-url/login`


The only solution which works is to define baseURL as my external URL with ending slash, and then use no leading slash on the path config, as seen below. This is the configuration which @phoenix-ru said should be considered a bug.

### Example 4 - Correct URL

```js
auth: {
  baseURL: 'http://api-url/',
  provider: {
    endpoints: {
      signIn: {path: 'login'},
    },
}
```

The sign in path becomes: `http://api-url/login`, allowing me to use my external endpoint.

I think a more sophisticated solution may be required. Perhaps checking if the endpoint path begins with a scheme (https://) in which case the baseURL is dropped, allowing a fully-specified URL to override the baseURL.

**Comment by zoey-kaiser** [comment]
Hi everyone 👋 

I took the following steps to address this issue:
- Adjusted the documentation to explain the current behaviour in #796 
- Opened a new RFC issue to discuss potential improvements in #797 

I hope that these steps address this issue for now and that we can find a better solution in #797 to improve the module in the long run! 🥳

**Comment by alfredomtzrmz** [comment]
@phoenix-ru @zoey-kaiser I tried everything but doesn't work for me, still using the default baseURL
https://github.com/sidebase/nuxt-auth/issues/802#issue-2407232743
