### ISSUE TITLE
Provider refresh causes Infinite redirect at sign-in page

### ISSUE THREAD

**Issue by hiroki-otaka** [sidebase/nuxt-auth#792]
### Environment

- Operating System: Linux
- Node Version:     v22.3.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      modules, build, auth, routeRules
- Runtime Modules:  ../src/module.ts
- Build Modules:    -

### Reproduction

1. Clone the repo
2. `cd nuxt-auth/playground-refresh`
3. Edit pages/index.vue to comment `definePageMeta({ auth: false })` out
4. Run dev server and open local pages

### Describe the bug

Error "500 Infinite redirect in navigation guard" is shown.

The same procedure in playground-local has no problem.
The documentation states that the local provider and the refresh provider is the same except refreshing tokens.
The refresh provider should treat the login path as special as the local provider does.

**Comment by hiroki-otaka** [comment]
https://stackblitz.com/edit/github-4rxvta?file=pages%2Findex.vue,app.vue,nuxt.config.ts

Key points are:
- enable globalAppMiddleware
- not disable auth locally (by defining page meta)

The local provider seems to prevent this error.
https://github.com/sidebase/nuxt-auth/blob/8e6519f90f00c7b4478ed34088d69e5bcb0ba5dc/src/runtime/middleware/auth.ts#L70-L75

**Comment by zoey-kaiser** [comment]
Hi @hiroki-otaka 👋 

This makes sense. The expectation for the `local` provider was added wayyyy back in 2023 #543, before the refresh provider was added. I assume it slipped through when we created it, however the fix should be very easy. Would you like to push a PR and include the `refresh` provider in the same check?

**Comment by hiroki-otaka** [comment]
Thank you for explaining backgrounds.
And sure, I'll make a PR.
