### ISSUE TITLE
[nuxt] Could not access nitro. The only available runtime config keys on the client side are public and app

### ISSUE THREAD

**Issue by victorlmneves** [sidebase/nuxt-auth#793]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.12.1`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.1.0`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `typescript`, `runtimeConfig`, `auth`
- Runtime Modules:  `@sidebase/nuxt-auth@0.8.0`, `@nuxtjs/tailwindcss@6.12.0`, `nuxt-icon@0.5.0`
- Build Modules:    `-`

### Reproduction

This is a fork from the https://github.com/sidebase/nuxt-auth-example where it uses Auth0 as provider

https://github.com/victorlmneves/nuxt-auth-sidebase

### Describe the bug

After updating from v0.7.2 I start getting this warning on the browser console when running on dev mode
```
[nuxt] Could not access `nitro`. The only available runtime config keys on the client side are `public` and `app`. See `https://nuxt.com/docs/guide/going-further/runtime-config` for more information.
```

### Additional context

The warning is visible when running dev mode
Looking to logs from the update I have the feeling that it comes from here
https://github.com/sidebase/nuxt-auth/blob/b2ad71a9d572fb3237a4c5fb32475773437d1c9f/src/runtime/utils/kit.ts#L21

**Comment by zoey-kaiser** [comment]
Hi @victorlmneves 👋 

Thanks for reporting this issue! We have also encountered it already in some of our internal projects, as it causes some tests to fail. @phoenix-ru will look into this issue on Thursday and we will prioritize releasing a patch for this!
