### ISSUE TITLE
Custom Error Handling for Access Denied Scenarios

### ISSUE THREAD

**Issue by mussingtonr** [sidebase/nuxt-auth#801]
### Environment

I'm encountering challenges in handling access control errors with custom messages within the `authjs` provider of `nuxt-auth`. While the documentation provides guidance for redirecting based on error codes, I'd like to display user-friendly, custom error messages without exposing the error code in the URL parameters. I've tried using nuxt's built in useError but the error messages never reach the error page for them to be used.

Currently using Nuxt 3 with Nuxt UI. DB is supabase (credentials aren't being saved from Oauth within db) 

**Desired Behavior:**

- Implement custom error handling within the `authjs` provider or related callbacks.
- Throw a JavaScript error with a user-friendly message upon access denial (e.g., "Access Denied: User not authorized for this project").
- Capture this error and redirect the user to a custom error page (`/auth/error`).
- Display the custom error message from the error object on the error page, without relying on the URL parameter.

`// server/api/auth/[...].ts`

```
import GithubProvider from 'next-auth/providers/github'
import { StartggProvider } from './providers/startgg'
import { NuxtAuthHandler } from '#auth'

const config = useRuntimeConfig()

async function checkUserAccess(discriminator: string, sgg_userid: string) {
  try {
    const response = await $fetch('/api/getUserAccessStatus', {
      method: 'GET',
      params: { discriminator, sgg_userid },
    })

    if (!response.access) {
      console.error('Error checking user access:', response)
      return false
    }

    return response.access
  }
  catch (error) {
    console.error('Error checking user access:', error)
    return false
  }
}

export default NuxtAuthHandler({
  secret: config.authJsSecret,
  pages: {
    signIn: '/auth/login',
    error: '/auth/error',
  },
  providers: [
    // @ts-expect-error You need to use .default here for it to work during SSR. May be fixed via Vite at some point
    GithubProvider.default({
      clientId: config.github.clientId,
      clientSecret: config.github.clientSecret,
    }),
    StartggProvider({
      callbackUrl: config.public.startggCallbackUrl as string,
      clientId: config.public.startggClientId as string,
      clientSecret: config.startggClientSecret,
    }),
  ],
  callbacks: {
    signIn: async ({ user }) => {
      console.log('I made it to the signIn callback!') //

      const discriminator = user?.discriminator
      const sgg_userid = user?.id

      const canAccess = await checkUserAccess(discriminator, sgg_userid)
      console.log('canAccess:', canAccess) // Logging

      if (!canAccess) {
        // return false
        // Throw error with message for redirection
        throw createError({
          statusCode: 403,
          statusMessage: 'AccessDenied',
          data: 'Access Denied: User not found in allow list',
        })
      }

      return true
    },
    jwt: async ({ token, user }) => {
      console.log('I made it to the jwt callback!') // Logging
      // Pass all user fields into the token
      if (user)
        token = { ...token, ...user }
      return token
    },
    session: async ({ session, token }) => {
      console.log('I made it to the session callback!') // Logging
      // Assign user data from the token to the session
      session.user = { ...session.user, ...token }
      return session
    },
  },
})
```

### Reproduction

**Steps to Reproduce:**

1. Configure `nuxt-auth` with the `authjs` provider and an authentication provider.
2. Implement access control logic within the `signIn` callback or a custom callback specific to your provider.
3. Throw a custom JavaScript error with the desired message when access is denied based on access control check (e.g., `checkUserAccess`).

### Describe the bug

Currently, any error message created that's custom isn't being sent to the error page. I would like to display a user-friendly, custom error messages without exposing the error code in the URL parameters while using a custom or built in provider.

**Comment by zoey-kaiser** [comment]
Hi @mussingtonr 👋 

This should be possible, however you need to use the "normal" JS errors. In your example you are currently throwing an h3 error, which cannot be handled by NextAuth (as it does not have any integration with Nuxt).

Please try and throw a normal error using `throw new Error()` and see if this resolves your issue!

However, using this will also limit you to the predefined error messages from NextAuth. If you would to add more context, you can also return additional error data or write your own handler using the `redirect` callback. There are a couple of nice guides on this online like https://medium.com/@mangergeorgepraise/displaying-custom-error-messages-with-nextauth-js-cdcdda4e49bc, feel free to search around using NextAuth over NuxtAuth, as this package is used under the hood.

As of now, this is not a bug or even something that is being handled from our side. However, due to the extendability of NextAuth, I am very confident you can find a solution online that fulfills your use case (like the example I linked).
