### ISSUE TITLE
custom baseURL is not working

### ISSUE THREAD

**Issue by alfredomtzrmz** [sidebase/nuxt-auth#802]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `experimental`, `components`, `modules`, `colorMode`, `fonts`, `auth`
- Runtime Modules:  `@nuxt/ui@2.17.0`, `@nuxt/fonts@0.7.1`, `@vueuse/nuxt@10.11.0`, `@sidebase/nuxt-auth@0.8.0`
- Build Modules:    `-`

### Reproduction

I set the following config:
```ts
  auth: {
    provider: {
      baseURL: 'https://tx8_api.test/',
      type: 'refresh',
      endpoints: {
        signIn: { path: 'login', method: 'post' },
        signOut: { path: 'logout', method: 'post' },
        signUp: false,
        getSession: { path: 'me', method: 'get' },
        refresh: { path: 'refresh', method: 'post' },
      },
      token: {
        signInResponseTokenPointer: 'data/access_token',
        cookieName: 'access_token',
        type: 'Bearer',
        maxAgeInSeconds: 60 * 60,
        sameSiteAttribute: 'strict',
      },
      refreshToken: {
        signInResponseRefreshTokenPointer: 'data/access_token',
        cookieName: 'access_token',
        refreshRequestTokenPointer: 'access_token',
        maxAgeInSeconds: 20160 * 60,
      },
      pages: {
        login: '/login',
      },
    },
  },
  ```
  
My backend is running in Valet  (Laravel app) exposed in https://tx8_api.test/api and my Nuxt app is exposed in port 3000

### Describe the bug

When I try to login, happens this
![Screenshot 2024-07-13@2x](https://github.com/user-attachments/assets/4053da31-780c-47d8-b58c-19ac0be1a83d)
The baseURL still the default one.
On Postman the request is successfully
![Screenshot 2024-07-13@2x](https://github.com/user-attachments/assets/749b540b-ee05-4d32-9dd0-129ae6e948ac)

### Additional context
I'm following the steps to [use an external backend](https://auth.sidebase.io/guide/local/quick-start#using-an-external-backend) but doesn't work for me 

_No response_

**Comment by zoey-kaiser** [comment]
Hi @alfredomtzrmz 👋 

Sadly its pretty hard for me to identify what could be going wrong. Your configuration looks correct to me. However, I am surprised that the requests are still being made to `localhost` and not your external backend. 

Could you try and reproduce this issue in a small reproduction?

**Comment by alfredomtzrmz** [comment]
@zoey-kaiser Thanks! But now i got this error `net::ERR_CERT_COMMON_NAME_INVALID` and my config:

```ts
  auth: {
    baseURL: 'https://tx8_api.test/api/auth/',
    provider: {
      type: 'refresh',
      endpoints: {
        signIn: { path: 'login', method: 'post' },
        signOut: { path: 'logout', method: 'post' },
        signUp: false,
        getSession: { path: 'me', method: 'get' },
        refresh: { path: 'refresh', method: 'post' },
      },
      token: {
        signInResponseTokenPointer: 'data/access_token',
        cookieName: 'access_token',
        type: 'Bearer',
        maxAgeInSeconds: 60 * 60,
        sameSiteAttribute: 'strict',
      },
      refreshOnlyToken: false,
      refreshToken: {
        signInResponseRefreshTokenPointer: 'data/access_token',
        cookieName: 'access_token',
        refreshRequestTokenPointer: 'access_token',
        maxAgeInSeconds: 20160 * 60,
      },
      pages: {
        login: '/login',
      },
    },
  },

```

**Comment by alfredomtzrmz** [comment]
@zoey-kaiser nevermind, I forgot to set my virtual domain to secure 😅. Now works fine!
