### ISSUE TITLE
Add Discussions space

### ISSUE THREAD

**Issue by victorlmneves** [sidebase/nuxt-auth#803]
### Describe the feature

To have a dedicated place to ask for tips/support would be nice to have the "Discussions" space available

### Additional information

- [ ] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [ ] Local
- [ ] Refresh
- [ ] New Provider

**Comment by zoey-kaiser** [comment]
Hi @victorlmneves 👋 

We have previously tried out using the GitHub discussions section, however, found that it was not used a lot and added a lot more overhead in tracking communication in multiple places. For this reason we had removed the discussions section, as the interest did not warrant the maintenance. 

For now, I think we will continue to focus on using issues over discussions. I can also recommend joining our Discord server, as there is more activity in there when it comes to the topics you mentioned above: https://discord.gg/VzABbVsqAc

If we do notice that the need for a discussions space increases, we would be happy to reopen it, however during our last check-in on this (3 months ago) it was not worth adding.

**Comment by victorlmneves** [comment]
Thanks
I wasn't aware of the Discord channel
