### ISSUE TITLE
Refreshing a page removes the cookie using the refresh provider

### ISSUE THREAD

**Issue by alfredomtzrmz** [sidebase/nuxt-auth#806]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@1.22.21`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `experimental`, `components`, `modules`, `colorMode`, `fonts`, `auth`
- Runtime Modules:  `@nuxt/ui@2.17.0`, `@nuxt/fonts@0.7.1`, `@vueuse/nuxt@10.11.0`, `@sidebase/nuxt-auth@0.8.0`
- Build Modules:    `-`

### Reproduction

I'm using an external backend with refresh provider with the following config:
```ts
  auth: {
    baseURL: 'http://external_backend.com/api/auth/',
    globalAppMiddleware: true,
    provider: {
      type: 'refresh',
      endpoints: {
        signIn: { path: 'login', method: 'post' },
        signOut: { path: 'logout', method: 'post' },
        signUp: false,
        getSession: { path: 'me', method: 'get' },
        refresh: { path: 'refresh', method: 'post' },
      },
      token: {
        sameSiteAttribute: 'strict',
        signInResponseTokenPointer: '/data/access_token',
        cookieName: 'access_token',
        maxAgeInSeconds: 60 * 60,
      },
      refreshToken: {
        signInResponseRefreshTokenPointer: '/data/access_token',
        cookieName: 'access_token',
        refreshRequestTokenPointer: 'access_token',
        maxAgeInSeconds: 20160 * 60,
      },
      pages: {
        login: '/login',
      },
    },
  },
```

### Describe the bug

After logging in a cookie is set under access_token and I have an authenticated state redirecting to index page.
![Screenshot 2024-07-15@2x](https://github.com/user-attachments/assets/b36a44e3-85ab-48d0-9b50-1a45dcca1d0e)

If I refresh the page, the cookie gets removed and redirects me to /login.
![Screenshot 2024-07-15@2x](https://github.com/user-attachments/assets/0e2fc503-adda-4b23-a5d3-40cbc37e61d4)

### Additional context

- I tried setting `sameSiteAttribute` either **lax** or **strict** and doesn't work either.
- I'm not using secure connection, just HTTP

Also I noticed that the cookie is sets as lax event when i'm setting to strict

**Comment by zoey-kaiser** [comment]
Hi @alfredomtzrmz 👋 

Sadly debugging issue in the `local` and `refresh` provider are always a bit tricky, as it is hard to reproduce your setup with your backend. However do you think you could maybe replicate the issue in a Nuxt3 app, with a mocked backend? 

You could use the [`refresh-playground`](https://github.com/sidebase/nuxt-auth/tree/main/playground-refresh) as a base for this!

**Comment by alfredomtzrmz** [comment]
@zoey-kaiser Thanks! I realized is and issue with my Laravel backend refresh token flow. Tried with local provider and works!
