### ISSUE TITLE
Docs custom sign in page: Note that `auth: false` needs to be set to avoid redirect loop

### ISSUE THREAD

**Issue by BracketJohn** [sidebase/nuxt-auth#81]
### Describe the feature

When a user wants to create a custom sign in page while having the global auth-middleware enabled, they need to add `auth: false` as a `definePageMeta` attribute to that page.

### Additional information

Another idea: allow path matching / specification that is ignored by global middleware.

related discord thread of affected user: https://discord.com/channels/1024643779711483944/1024705710455533598/1049160681489956874
![image](https://user-images.githubusercontent.com/25911230/205700056-ec0f37e5-a386-4b43-94c7-5f884598e5c0.png)

**Comment by JoaoPedroAS51** [comment]
Yeah, I also thought about having path matching. But we can't import the auth options as they are defined by the user in `[...].ts`, so we would need to add the `auth.pages` to `nuxt.config` and merge them into `NuxtAuthHandler`.

**Comment by BracketJohn** [comment]
As much as I would like this, I don't think that we should rip apart the `NuxtAuthHandler` config -> from that point onwards the advantage of having many guides, tutorials, ... from NextAuth that also apply to `nuxt-auth` vanishes. 

If we could import from the server side from our client-code it may be something different. Our middleware could import the auth handler and try to read the configuration from it. But ofc. that's also super dangerous because the nuxt auth handler could also contain secrets.

**Comment by JoaoPedroAS51** [comment]
> As much as I would like this, I don't think that we should rip apart the NuxtAuthHandler config -> from that point onwards the advantage of having many guides, tutorials, ... from NextAuth that also apply to nuxt-auth vanishes.

Yeah, that's exactly my point.

**Comment by JoaoPedroAS51** [comment]
So your idea is something like `ignorePaths: ['/foo', '/bar']`, right?

**Comment by BracketJohn** [comment]
Yes, that's it! I haven't looked into it, but it would be nice to follow the same patterns that nitro uses for `routeRules`: https://nitro.unjs.io/config/#routerules

Maybe the naming can be `publicPaths` instead of `ignorePaths`? This naming would be more independent of the global-middleware context. Or maybe even better, restructure the global middleware settings to allow:
```
enableGlobalAppMiddleware: boolean | {
  enabled: boolean
  ignoresPaths: ['/foo', '/bar']
}
```

**Comment by BracketJohn** [comment]
I've added this note to the new docs, see #90 and soon https://sidebase.io/nuxt-auth/application-side/custom-sign-in-page

I've moved my proposal to allow ignore Paths into #91.

Closing this via #90

**Comment by BracketJohn** [comment]
This was added with #90
