### ISSUE TITLE
How to exclude login page when enableGlobalAppMiddlware is true

### ISSUE THREAD

**Issue by masoudei** [sidebase/nuxt-auth#82]
Hi , my nuxt.config.ts is :
` auth: {
        isEnabled: true,
        enableGlobalAppMiddleware: true,
    }
`
I am using custom pages , so I need to implement credentials and providers on my own login page , used this config in my server/api/[...].ts  : 
`
    pages: {
        signIn: '/login',
    },
`
Now it will be on redirect loop , how to exclude my pages/login.vue from global middleware ?
I need no auth for some pages or some layouts!

**Comment by JoaoPedroAS51** [comment]
Hi @masoudei ! See https://github.com/sidebase/nuxt-auth/issues/81

**Comment by masoudei** [comment]
thanks perfect.
