### ISSUE TITLE
Redirect route after signing in

### ISSUE THREAD

**Issue by NyllRE** [sidebase/nuxt-auth#827]
### Environment

- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.21

### Reproduction

no reproduction since this is a question rather than a bug

### Describe the bug

There doesn't seem to be clear documentation on how to redirect a user to a specific route (eg: `/profile`) after a user has signed in. The closest thing to my situation is the [callbacks](https://auth.sidebase.io/guide/authjs/nuxt-auth-handler#callbacks) in nuxt-auth-handler but it's still not very clear where I can redirect to a specific link after a certain action like signing out or in

**Comment by zoey-kaiser** [comment]
Have a look at the docs section here on the signIn function 😊 
https://auth.sidebase.io/guide/application-side/session-access#signin
