### ISSUE TITLE
Runtime types do not match documentation

### ISSUE THREAD

**Issue by dc-shackle** [sidebase/nuxt-auth#830]
### Describe the feature

Wasn't sure if this counts as a bug report or enhancement as it touches on both documentation and code.

https://github.com/sidebase/nuxt-auth/blob/9295d1fe4f27d42c879862a48202f5b215fc0048/src/runtime/types.ts#L84-L96 

The `signIn` and `signUp` endpoints do not allow for a value of `false` to be provided, though the documentation implies that  it should be possible to do so (https://auth.sidebase.io/guide/local/quick-start#api-endpoints).

### How would you implement this?

Update the runtime types mentioned to allow for a value of `false`.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [X] Local
- [X] Refresh
- [ ] New Provider

**Comment by zoey-kaiser** [comment]
Hi @dc-shackle 👋 

We resolved this issue in the rewrite of the documentation. Thank you very much for brining it up 😊
