### ISSUE TITLE
Token and Session null when called from cachedEventHandler

### ISSUE THREAD

**Issue by flim** [sidebase/nuxt-auth#845]
### Environment

- Operating System: Darwin
- Node Version:     v20.12.2
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

When authenticated.
Call internal server api (eg. `/api/test`) from page with
```vue
// /pages/home.vue
<script setup lang="ts">
// [...]
const { data, status } = await useFetch('/api/test')
// [...]
</script>
```

On server side

```javascript
// /server/api/test.ts
import {getToken} from "#auth";

export default cachedEventHandler(async (event) => {
    const token = await getToken({event})

    console.log(token) // null
}, {
    swr: true,
    maxAge: 60
});
```

```javascript
// /server/api/test2.ts
import {getToken} from "#auth";

export default eventHandler(async (event) => {
    const token = await getToken({event})

    console.log(token) // not null
});
```

### Describe the bug

As an authenticated user,
when I call the internal server api that implementing `cachedEventHandler`, the value returned by `getToken` and `getServerSession` are `null`.

But works when using classical `eventHandler`.

**Comment by phoenix-ru** [comment]
@flim 
I believe you are doing something conceptually wrong - why would you want to cache authenticated requests? This is a security vulnerability. `h3` is correctly protecting you from shooting your own legs.

> [!CAUTION]
> I highly advise you against caching any user-specific data - it IS a vulnerability regardless of your usecase.

In case you still want to cache this - you need to provide header names (`authorization` and `cookie`) to `varies`: https://nitro.unjs.io/guide/cache#options
