### ISSUE TITLE
Is there anyway to enforce refresh session?

### ISSUE THREAD

**Issue by ncperng** [sidebase/nuxt-auth#85]
### Ask your question

While in development (npm run dev), my useSession() works perfectly without any problem. But, while production (npm run build) and use node .output/server/index.mjs, the { data } from useSession is null. 

The issue can be solved after a browser tab switch (switch to another tab, and then switch back). Guess it triggered tab-refocus (enableSessionRefreshOnWindowFocus: true). Is there anything to enforce SessionRefresh from javascript?

**Comment by ncperng** [comment]
I tried to call the function getSession() in the onMounted() callback, which solves my problem. Any better solution is appreciated, otherwise I will close this problem. Many thanks in advance.

**Comment by BracketJohn** [comment]
Heya!

The session should also be initialized on the initial page load! Can you share your code / a reproduction with me so that I can look into it?

> I tried to call the function getSession() in the onMounted() callback, which solves my problem. Any better solution is appreciated, otherwise I will close this problem. Many thanks in advance.

As per this question:
- you can enable periodic refresh by setting `enableSessionRefreshPeriodically` in the nuxt-config, it will then auto refresh. See docs here https://github.com/sidebase/nuxt-auth#nuxtconfigts
- you can add an application middleware that calls `getSession`

**Comment by BracketJohn** [comment]
closing this now as there's no more activity + q was answered.

**Comment by ncperng** [comment]
@BracketJohn Thanks for your kind suggestions, but in my case, adding **enableSessionRefreshPeriodically** still have the same problem.

I tried to build an empty project to reproduce this problem, however it works perfectly and the problem is gone. I will try more cases with **layout** and **vue-router** to see if the problem comes from them or not.

Many thanks for your kind response.

**Comment by BracketJohn** [comment]
Sure thing, thanks for looking into it further + good luck. Would be interesting to get a repro and see if this is somethign `nuxt-auth` related or not!

Have a good day 💯
