### ISSUE TITLE
engines field change in package.json a few days ago was a breaking change

### ISSUE THREAD

**Issue by dword-design** [sidebase/nuxt-auth#860]
### Describe the feature

FYI, see title. Adding an engines field will automatically make the package incompatible with previous versions and [version 20 is still maintained](https://nodejs.org/en/about/previous-releases).

### Additional information

- [ ] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [ ] Local
- [ ] Refresh
- [ ] New Provider

**Comment by phoenix-ru** [comment]
Agree with you - it was an oversight from our side. Will change to a less strict version
