### ISSUE TITLE
Load `baseURL` from runtime config

### ISSUE THREAD

**Issue by cngJo** [sidebase/nuxt-auth#878]
### Describe the feature

I usually have my API base URL for external APIs in:

```ts
  runtimeConfig: {
    public: {
      apiBaseUrl: 'https://my-awesome-backend.local'
    }
  },
```

and replicate it in `nuxt-auth` config

```ts
baseURL: process.env.NUXT_PUBLIC_API_BASE_URL ?? "https://my-awesome-backend.local",
```

But then I need the `NUXT_PUBLIC_API_BASE_URL` variable on build and runtime, which is a bit annoying. 

Therefore, it would be awesome to specify a JSON pointer to runtime config like it's done for the access / refresh tokens.

### Additional information

- [X] Would you be willing to help implement this feature?

### Provider

- [X] AuthJS
- [X] Local
- [X] Refresh
- [ ] New Provider

**Comment by cngJo** [comment]
Maybe related to #797

**Comment by phoenix-ru** [comment]
You can now set `baseURL` using

```ts
runtimeConfig: {
  public: {
    auth: {
      baseURL: 'https://example.com/your/base/url'
    }
  }
}
```

**Comment by phoenix-ru** [comment]
Done in #913
