### ISSUE TITLE
503 Server Unavailable

### ISSUE THREAD

**Issue by kurashina-design** [sidebase/nuxt-auth#89]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

yarn add --dev @sidebase/nuxt-auth
yarn dev

### Describe the bug

The App cannnot start with below messages.

### Logs

```shell
file:///siteroot/nuxt3.merkmal/httpdocs/.nuxt/dev/index.mjs:13
import { NextAuthHandler } from 'file:///siteroot/nuxt3.merkmal/httpdocs/node_modules/next-auth/core/index.js';

SyntaxError: Named export 'NextAuthHandler' not found. The requested module 'file:///siteroot/nuxt3.merkmal/httpdocs/node_modules/next-auth/core/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file:///siteroot/nuxt3.merkmal/httpdocs/node_modules/next-auth/core/index.js';
const { NextAuthHandler } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by kurashina-design** [comment]
Perhaps the next-auth's version causes this issue.

`yarn add next-auth@4.14'

It works!

**Comment by BracketJohn** [comment]
> The App cannnot start with below messages.

Did you also follow the rest of the getting started guide? E.g., add the module to the `nuxt.config.ts`, add the auth handler, ...?

**Comment by awais-afoxtech** [comment]
Hello, I am having the same issue, installed as configured as described in the getting started guide. 

![Screenshot 2022-12-08 160522](https://user-images.githubusercontent.com/62846118/206431216-81b09620-8023-498b-90eb-f1760bf29934.png)

**Comment by BracketJohn** [comment]
Hey @awais-afoxtech, thanks for sharing! ❤️ 

Is there any way you coyuld give me access to the repo where the problem occurs / can you share a reproduction, e.g., via stackblitz? 

see here for somne pointers on how to do it:> https://nuxt.com/docs/community/reporting-bugs#create-a-minimal-reproduction

**Comment by pauljanns** [comment]
I have the same issue. Did nothing more except following the guide and installing  "@sidebase/nuxt-auth": "^0.3.0-alpha.3"

**Comment by JoaoPedroAS51** [comment]
Yeah, me too. I can reproduce locally.

@BracketJohn The [next-auth v4.18.1](https://github.com/nextauthjs/next-auth/releases/tag/next-auth%40v4.18.1) caused this issue.

**Comment by kurashina-design** [comment]
I followed the rest of the getting started guide.

The error message says:

`SyntaxError: Named export 'NextAuthHandler' not found. The requested module 'file:///siteroot/nuxt3.merkmal/httpdocs/node_modules/next-auth/core/index.js' is a CommonJS module`

So I tried to find 'NextAuthHandler' in the index.js, but I couldn't. I thought the next-auth on which @sidebase/nuxt-auth depends has experienced some breaking changes unintentionallly. So I installed (downgraded) next-auth@4.14 and found 'NextAuthHandler' three times in the index.js. The error has disappeared in the nuxt app. Simply NextAuthHandler has disappeared in the latest next-auth, I think.

**Comment by BracketJohn** [comment]
Thanks to y'all, this will be fixed via #94 and I'll do a release afterwards.

Thanks @JoaoPedroAS51 for the research + last working version, using exactly `4.18.0` now.

**Comment by BracketJohn** [comment]
Release is out: `npm i -D @sidebase/nuxt-auth@0.3.0` -> release notes for `0.3.0` will follow shortly.

**Comment by pauljanns** [comment]
thanks for the quick fix
