### ISSUE TITLE
[nitro] [uncaughtException] DiscordProvider is not a function

### ISSUE THREAD

**Issue by diifark** [sidebase/nuxt-auth#897]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.1.0
- Nuxt Version:     3.13.0
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, css, i18n, auth, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, @nuxtjs/i18n@8.5.1, @sidebase/nuxt-auth@0.9.1
- Build Modules:    -
------------------------------

### Reproduction

-

### Describe the bug

server just not launching but should be, there is my [...].ts config

import { NuxtAuthHandler } from '#auth'
import DiscordProvider from 'next-auth/providers/discord';

export default NuxtAuthHandler({
    secret: useRuntimeConfig().authSecret,
    providers: [
    DiscordProvider({
        clientId: '',
        clientSecret: ''
  })
],
})

### Logs

```shell-script
ERROR  [nitro] [uncaughtException] DiscordProvider is not a function

  at <anonymous> (server\api\auth\[...].ts:7:1)
  at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:474:24)
  at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:119:5)
```

**Comment by phoenix-ru** [comment]
Please, make sure that you use `.default` in your configuration like so:
https://github.com/sidebase/nuxt-auth/blob/ab772fdc8bed645e5f8ee518adc25f087c08dfe0/playground-authjs/server/api/auth/%5B...%5D.ts#L9-L10

It is a bug with `next-auth` with Vite which forces such a workaround. This won't be needed with `authjs` in the future.
