### ISSUE TITLE
Documentation refers to wrong environment variable for AUTH_NO_ORIGIN error

### ISSUE THREAD

**Issue by ronaldtb** [sidebase/nuxt-auth#906]
### Environment

not applicable

### Reproduction

Start Nuxt using the `NUXT_AUTH_ORIGIN` value set in production.
The `Error: AUTH_NO_ORIGIN: No `origin` - this is an error in production` error will be thrown.

### Describe the bug

The documentation at https://auth.sidebase.io/resources/error-reference#auth-no-origin refers to the `NUXT_AUTH_ORIGIN` environment variable, but according to https://github.com/sidebase/nuxt-auth/blob/main/docs/guide/application-side/configuration.md?plain=1#L11 the environment variable needs to be `AUTH_ORIGIN`.

Changing the environment variable to `AUTH_ORIGIN` works with version `0.9.2`.

**Comment by phoenix-ru** [comment]
Reopening after some consideration as it's apparently a legitimate bug. Nuxt filters out environment variables which are not defined on `runtimeConfig`. See "key requirements" here: https://nuxt.com/docs/guide/going-further/runtime-config#environment-variables

**Comment by dingdangdog** [comment]
I thought `originEnvKey` was an optional config, but it looks like it's required even when using the `runtimeconfig.authOrigin` environment variable, I must use `originEnvKey: "NUXT_AUTH_ORIGIN"` to avoid errors ! ! !

Now it seems that my code is not wrong, but it took me a long time, so I record it here.

Am I missing something? Can anyone tell me what's going on?

## my config

> @sidebase/nuxt-auth:^0.10.0
> node version: v20.12.0
> npm version: 9.8.1

- package.json

```json
{
  "name": "modulename",
  "private": true,
  "type": "module",
  "license": "MIT",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --host 0.0.0.0",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@mdi/font": "^7.4.47",
    "@nuxtjs/i18n": "^8.3.1",
    "@nuxtjs/tailwindcss": "^6.12.2",
    "@prisma/client": "^6.2.1",
    "@prisma/nuxt": "^0.2.0",
    "@sidebase/nuxt-auth": "^0.10.0",
    "echarts": "^5.6.0",
    "next-auth": "~4.21.1",
    "nuxt": "^3.12.4",
    "nuxt-echarts": "^0.2.4",
    "vue": "latest",
    "vuetify-nuxt-module": "^0.18.3",
    "xlsx": "^0.18.5"
  }
}
```

- nuxt.config.ts
```ts
  runtimeConfig: {
    public: {},
    appVersion: "",
    appUrl: "",
    dataPath: "",
    authSecret: "",
    authOrigin: "", // NUXT_AUTH_ORIGIN
  },

  modules: [
    "@nuxtjs/i18n",
    "vuetify-nuxt-module",
    "@nuxtjs/tailwindcss",
    "nuxt-echarts",
    "@sidebase/nuxt-auth",
    "@prisma/nuxt",
  ],

  auth: {
    // baseURL: process.env.NUXT_AUTH_ORIGIN,
    // globalAppMiddleware: false,
    // originEnvKey: "NUXT_AUTH_ORIGIN",
    provider: {
      type: "authjs",
      trustHost: false,
      addDefaultCallbackUrl: true,
    },
    sessionRefresh: {
      enablePeriodically: false,
      enableOnWindowFocus: true,
    },
  },
```

- .env
```sh
NUXT_AUTH_ORIGIN="http://localhost:9090/api/auth"
```

**Based on the above configuration, running `npm run dev` will still prompt**:
```console
ℹ AUTH_NO_ORIGIN: No origin - this is an error in production, see https://sidebase.io/nuxt-auth/resources/errors. You can ignore this during development
```

This error is so annoying.

**Comment by VasiliyRusin** [comment]
Hi! I understand that the issue is already closed, but I believe the types in the `nuxt.config.ts` file cause significant confusion regarding this problem.

According to the types, origin is not allowed in auth under `runtimeConfig`, which adds to the misunderstanding.

<img width="676" alt="Image" src="https://github.com/user-attachments/assets/783951ac-5c62-49bd-8937-f71e3ddf2b66" />
