### ISSUE TITLE
Doesn't Refresh Token When Expired and Tab is Closed

### ISSUE THREAD

**Issue by luthfihizb** [sidebase/nuxt-auth#914]
### Environment

- Operating System: Windows_NT    
- Node Version:     v20.17.0      
- Nuxt Version:     3.12.4        
- CLI Version:      3.12.0        
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22  
- Builder:          -
- User Config:     -
- Runtime Modules:  @sidebase/nuxt-auth@0.9.2
- Build Modules:    -

### Reproduction

Here is my auth config

```
auth: {
    isEnabled: true,
    disableServerSideAuth: false,
    globalAppMiddleware: true,
    baseURL: `${process.env.API_HOST}/v1/auth/`,
    provider: {
      type: "local",
      endpoints: {
        signIn: { path: "login", method: "post" },
        getSession: { path: "session", method: "get" },
      },
      token: {
        signInResponseTokenPointer: "/data/token",
        cookieName: "_auth_t",
        maxAgeInSeconds: 10,
        cookieDomain: "localhost",
      },
      refresh: {
        isEnabled: true,
        refreshOnlyToken: true,
        endpoint: {
          path: "refresh",
          method: "post",
        },
        token: {
          signInResponseRefreshTokenPointer: "/data/refreshToken",
          cookieName: "_auth_r",
          maxAgeInSeconds: 3600 * 24 * 7,
          cookieDomain: "localhost",
        },
      },
      session: {
        dataType: {
          id: "number",
          username: "string",
          name: "string",
        },
      },
    },
  },
```

### Describe the bug

Currently, I'm testing what happens when the access token expires by simulating a very short expiration time (10 seconds). If the access token expires while the tab is still open (but I switch to another tab), when I refocus the tab, the access token refreshes fine..

![image](https://github.com/user-attachments/assets/9d426b74-194f-4117-8d74-0e8ca2e79031)

But if the tab is closed when the access token is expired, the refresh mechanism is somehow ignored, and the user is redirected to the login page even though the refresh token still exists in the cookies. Reloading the tab also does not trigger the refresh.

![image](https://github.com/user-attachments/assets/382b0c23-5e51-4585-862d-ef87ea202789)

Is this behavior expected? What I expect is that refocusing existing tab, reloading the tab, or opening a new tab should have the same behavior, right?

**Comment by andychukse** [comment]
`enableOnWindowFocus` is true by default. Maybe for your use case enabling period refresh will work.

```
sessionRefresh: {
        enablePeriodically: 1000 * 10,
        enableOnWindowFocus: true,
    }
```

**Comment by luthfihizb** [comment]
> Maybe for your use case enabling period refresh will work

enabling period refresh only works if the tab is open.. meanwhile the issue still occurs if the token expires while the tab is closed
