### ISSUE TITLE
Ability to render during initial session refresh API call

### ISSUE THREAD

**Issue by PaulCombal** [sidebase/nuxt-auth#919]
### Describe the feature

My project uses the local provider. On every page load, even before app.vue is rendered, a call to my authentication endpoint is made, presumably to get the authentication data.

I wouldn't have an issue with this if I could display a loading screen while the request is being made. I apologize if I missed the way to get around it.

![image](https://github.com/user-attachments/assets/2f8a5d30-5949-4ed2-92f4-6571d2c99a23)

This screenshot shows that the trace of the call, and I do not know if I can render anything before it finishes. The call seems to be run before the refreshHandler's `init` method is called.

### How would you implement this?

The topic is open to discussion. Maybe the initial session refresh call can be disabled in the configuration, just like we can for `enableOnWindowFocus`.
`useAuth().refresh()` would have to be called manually in the app.

### Additional information

- [ ] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [X] Local
- [ ] Refresh
- [ ] New Provider

**Comment by zoey-kaiser** [comment]
You can disable the server-side fetching either:

- Globally: https://auth.sidebase.io/guide/application-side/configuration#disableserversideauth
- On a page basis: https://auth.sidebase.io/guide/advanced/caching#page-specific-cache-rules

The session will then only be fetched client side and the status will be loading until the session is fetched on the client!
