### ISSUE TITLE
Can I use the same identity across multiple subdomains?

### ISSUE THREAD

**Issue by MilesWuCode** [sidebase/nuxt-auth#920]
### Describe the feature

I have two subdomains:

p1.domain.com
p2.domain.com
Both are using Nuxt Auth.

I want to maintain the authenticated state on p2.domain.com after logging in on p1.domain.com.

I've consulted the following documentation:https://next-auth.js.org/configuration/options#cookies

However, it's not working as expected. Am I missing something?

**Comment by zoey-kaiser** [comment]
Have a look at this discussion from NextAuth: https://github.com/nextauthjs/next-auth/discussions/1299#discussioncomment-362054

**Comment by manuel-84** [comment]
How do you do this if the provider type is authjs and not local?
