### ISSUE TITLE
Throw exception inside getSession to outsite treatments

### ISSUE THREAD

**Issue by Mucaccino** [sidebase/nuxt-auth#933]
### Describe the feature

I need to perform external error handling when calling getSession from a signIn call.

It turns out that in my project signIn works, returning the access token, but when calling nextTick(getSession) and the api responds with an error when recovering the session, the error just comes out in the console, and I can't perform the treatment.

### How would you implement this?

The suggestion is within the try, which has console.error, to also trigger an error to be handled externally.

### Additional information

- [X] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [X] Local
- [ ] Refresh
- [ ] New Provider

### Reference line

https://github.com/sidebase/nuxt-auth/blob/a4b2b2e0cbf9a2bc9cd76988972672d3e85f429a/src/runtime/composables/local/useAuth.ts#L133

**Comment by phoenix-ru** [comment]
Let's move to #952, if you don't mind @Mucaccino
