### ISSUE TITLE
Allow external login page

### ISSUE THREAD

**Issue by Thomas-Philippot** [sidebase/nuxt-auth#935]
### Describe the feature

It would be great t allow external login page on local provider.

```js
provider: {
  type: 'local',
  pages: {
    login: 'http://my-external-login-page',
  },
},
  ```
  
  Currently this triggers an error :  ``Navigating to an external URL is not allowed by default. Use `navigateTo(url, { external: true })``

### How would you implement this?

Changing the `auth.js` middleware to check if `authConfig.provider.pages.login` is an external link

```js
const external = /^https?:\/\/\S+/.test(authConfig.provider.pages.login)
return navigateTo(authConfig.provider.pages.login.path, { external });
```

### Additional information

- [X] Would you be willing to help implement this feature?

### Provider

- [ ] AuthJS
- [X] Local
- [ ] Refresh
- [ ] New Provider

**Comment by jordi-tomas** [comment]
Hi, that solves my problem too. It would be interesting to have that check.
