### ISSUE TITLE
next-auth authorization-url.js file not found during build

### ISSUE THREAD

**Issue by shadowmimosa** [sidebase/nuxt-auth#941]
### Environment

Nuxt project info:                                                                                                                                15:38:38

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.4.0
- Nuxt Version:     3.14.159
- CLI Version:      3.11.1
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.9.0
- Builder:          -
- User Config:      compatibilityDate, devServer, devtools, modules, extends, css, auth, imports, build, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.5.5, @nuxt/ui@2.19.2, @sidebase/nuxt-auth@0.9.4
- Build Modules:    -
------------------------------

### Reproduction

Not yet

### Describe the bug

When building the Nuxt 3 project with @sidebase/nuxt-auth and next-auth@4.21.1, encountering a file not found error for the authorization-url.js file.

```
ERROR  ENOENT: no such file or directory, realpath '/Users/Phoenix/Documents/Repos/DDCloud/sales-lead-management/node_modules/.pnpm/next-auth@4.21.1_next@13.5.7_@babel+core@7.26.0_react-dom@18.3.1_react@18.3.1__react@18.3.1___ko5kluscrg5ldlgwp7mzwyhtjm/node_modules/next-auth/core/lib/oauth/authorization-url.js'
```

Current Configuration
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  modules: ['@sidebase/nuxt-auth'],
  auth: {
    provider: {
      type: 'authjs',
      addDefaultCallbackUrl: true
    },
    globalAppMiddleware: true
  }
})
```

Steps to Reproduce
Install dependencies with pnpm
Run pnpm build
Error occurs during the build process
Expected Behavior
The build should complete successfully without any file not found errors.
Additional Context
Using pnpm as package manager
The error seems to be related to the next-auth oauth file path resolution
This issue occurs consistently on build
Attempted Solutions
Cleaned node_modules and reinstalled dependencies
Cleared Nuxt cache
Reinstalled next-auth with specific version 4.21.1
Would appreciate any guidance on resolving this issue.

**Comment by phoenix-ru** [comment]
You are probably getting an error due to `pnpm`:
https://github.com/nuxt/nuxt/issues/14146

Can you show your `.npmrc` (only interested in `shamefully-hoist` option)?

**Comment by shadowmimosa** [comment]
Thank you for your response!

I don't have an .npmrc file locally, so I just created one and added the following setting:

```ini
shamefully-hoist=true
```
However, this did not resolve the issue. The command still does not produce any output or create the project.

Is there anything else I can try to troubleshoot this, or any other configurations I may need to set in the .npmrc file?

**Comment by shadowmimosa** [comment]
Thank you for your response!

I don't have an .npmrc file locally, so I just created one and added the following setting:

```ini
shamefully-hoist=true
```
However, this did not resolve the issue. The command still does not produce any output or create the project.

Is there anything else I can try to troubleshoot this, or any other configurations I may need to set in the .npmrc file?

**Comment by shadowmimosa** [comment]
it seems that the issue I encountered might be due to **the file path being too long**. Some systems have limitations on the maximum allowed file path length, and exceeding that can cause issues. If you're working in an environment with such restrictions (like Windows with default settings), I suggest trying to shorten the file path or moving the project to a directory with a shorter path.

I hope this helps! I will go ahead and close the issue now.
