### ISSUE TITLE
baseURL domain gets swaped to http://localhost:3000 always

### ISSUE THREAD

**Issue by Vijayabhaskar96** [sidebase/nuxt-auth#954]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      compatibilityDate, modules, build, auth, routeRules
- Runtime Modules:  ../src/module.ts
- Build Modules:    -
------------------------------

### Reproduction

Run the [How to test static Nuxt 3 apps?](https://github.com/sidebase/nuxt-auth?tab=readme-ov-file#how-to-test-static-nuxt-3-apps example to test) section.

### Describe the bug

baseURL despite what you set the domain part is replaced with `http://localhost:3000`

You can set baseURL: "http://example.com/login" and it will become "http://localhost:3000/login"

**Comment by Vijayabhaskar96** [comment]
If the endpoint paths start with `/` the baseURL is ignored for some reason.

https://github.com/sidebase/nuxt-auth/blob/9852116a7d3f3be56f6fdc1cba8bdff747c4cbb8/src/runtime/utils/url.ts#L13C3-L15C32

Overriding what the user has defined for `baseURL` is undesirable. The defined `baseURL` should always be respected.

**Comment by phoenix-ru** [comment]
Hi @Vijayabhaskar96, we are currently finishing up the PR #913 which completely revamps the way Nuxt Auth deals with urls and pathing. Please follow it instead :)
